>Synechococcus_7942_ClpS1
M-----------------AVETIQKPETTTKRKIAP---------RYRVLLHNDDFNPM-
-EYVVMVLMQTVPSLT-----QPQAVDIMME-----------------------------
---------AHTNGTG---------LVITCDIE--------PA------------EFYCE
Q----------------------LKSHG--------------------------------
----------LEQQ----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------H
>gnl|BL_ORD_ID|2177 @Agrobacterium_tumefaciens_C58@ gi|15889508|ref|NP_355189.1| ATP-dependent Clp protease adaptor [Agrobacterium tumefaciens str. C58]
MSD--------------------SPVDLKP--------------------------K---
------------PKVKPKLERPKLYKVML-------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------LNDDYT---------------------------------------
--------------------PREFVTVVL-KAVFRMSEDTGRRVMMTAHR-------FGS
AV--------------VVVCERDIAETKAK------------------------------
--------------------------------------------EATDLGKEAGFPLMFT
TEP------------------------------------EE
>gnl|BL_ORD_ID|1337 @Agrobacterium_tumefaciens_C58@ gi|15888689|ref|NP_354370.1| ATP-dependent Clp protease adaptor protein ClpS [Agrobacterium tumefaciens str. C58]
MIA--------------------KPIYMQG--------------------------EGDG
EDGGTNRGTSVITRVKPKTKRPNLYRVLL-------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------LNDDYT---------------------------------------
--------------------PMEFVIHIL-ERFFQKDREAATRIMLHVHQ-------HGV
GE--------------CGVFTYEVAETKVS------------------------------
--------------------------------------------QVMDFARQHQHPLQCV
ME-------------------------------------KK
>gnl|BL_ORD_ID|1418 @Agrobacterium_tumefaciens_C58@ gi|15888770|ref|NP_354451.1| two component sensor kinase [Agrobacterium tumefaciens str. C58]
MSADKHSPADANQLAMAVLNAVQNPVILVDGEGFISFANWEAEAFFGASASHLARYRVST
FIPFGSPLLALIDQVRERRAPVNEYRVDLSSPR------LGQDKLVDLYVAPVVS---EP
GSVVVVFQERSMADKIDRQLTHRAAARSVTGLASM------------LAHEIKNPLSGIR
GAAQLLEMSVPDEDRALTRLICDETDRIV---SLVDRMEIFSDERPVDRVPVNIHS-VLD
HVKAIAKAGFARNIKISENYDPSLPAVYANRDQLVQVFLNLVKNAAEAVANQPDGEVVLT
TAYRPGIRLSVAGSRERISLPLEFCVHDNGPGVPSDLLPHLFDPFITTKT-------NGS
GLGLALVAKLIGAHGGIVECDSQNHRTTFR------------------------------
--------------------------------------------VLMPVSPEVALDDSSL
PNTTG-----N----------------------------DR
>gnl|BL_ORD_ID|832 @Anaeromyxobacter_dehalogenans_2CP_1@ gi|220915956|ref|YP_002491260.1| ATP-dependent Clp protease adaptor protein ClpS [Anaeromyxobacter dehalogenans 2CP-1]
M-----------------------------------------------------------
---------------------------------------------------AERTRPGGD
TEVVVPKTRAERE--------TKRPPL--------YR-----VLLHNDHYTTQEFVDFVL
M-TVFNHDPESAHRIMLHVHMHGVGVAGIYPYEIAE------------------------
-----------------------------------TKARKTMDLAREAEY----------
-PLLVTIEPE--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>gnl|BL_ORD_ID|798 @Aquifex_aeolicus_VF5@ gi|15606404|ref|NP_213784.1| hypothetical protein aq_1151 [Aquifex aeolicus VF5]
MEGRNYDLNSLRKLADFIEKDVEHVELIRQVLKDEELKEVARRFAEYLKSYRDFKGKEKE
VEEVVYKHLRGLIDLKEGLKEREELANFISKFNVTPEEVVAEHGKLFELIREKLKDKFSP
EQLNEICLSLAKITLIHISLLIDQMRKKGTETLRLLLDNLPDVVVVLDSNFKINFINKTG
EEKLKFKREEVVGKPFTELLPERYRGVYRLLCELCKMKGSGTLPEVVYLGNPKLAILKPF
EVSYQTLSVNGETFFIIDLRDVSEEVKKERERQRISRLYSLFTHLIKIIFEETEKEEIFR
KIADFLVDEENFTYAEITLDGHTIIKKGKMGEYSVCFKLKSKEKYYLTLSKEEEFYPAEV
QLIINFLEELSTAIDAITAHEKLEKIEFFDKLTRLPTRIFFVKALSDRLSIAAQERKKVV
VVVLDIDNFTAINTLYGTEVGDKVLIEVADSLRDSVRIGDILARLGADTFGVALTCADVP
VAVNSFLARLNKLFSKPVIVNGKEIQVTFSIGISVFPDDGNEAEKLLGYALQAMFEAKKL
GGNRVVYYSSKEFPKIEEIITKKKELLEAIKKDEFILFYQPKIDLKEKKIVGCEALIRWK
KGDKLVPPYEFIPLLEETGLMNEVGLIVLEKACRQLKE------------WHKKGIEIEI
AINISPAQFRSGEFLQSFLKDLEGYTELLYYLGVEVTETALVENVSVATLFLKSLSELGI
RVYIDDFGTGYSSILHLKQLPVSALKIDVEFVKDMDVNERDYEIVKGVINLAHSLGLKTV
AEGVEKEIHEKMLMELSCDYAQGYYYSPPLPPEEFEEFFRKFNGLK
>gnl|BL_ORD_ID|129 @Aquifex_aeolicus_VF5@ gi|15605738|ref|NP_213115.1| hypothetical protein aq_168 [Aquifex aeolicus VF5]
MD----------------------------------------------SIYRDAGYDVLK
VSAKTGEGIDELVDYLEGF-----------------------------------------
------------------------------------------------------------
---------------------------------ICILAGPSGVGKSSILSRLTGEELRTQ
EVSE----------------------KTERGRH---------------------------
-----------------TTTGVRLIPFGK-------------------------------
-----------------------------------------------------------G
SFVGDTPGFS--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------KVEATMFV-------------KPREVRNYFREFLRYQCKYPDCTHTNEPGCAV
KEAVKNGEI---------------------------------------------------
------------------------------------------------------------
----------------SCERYKSYLKIIKVYLEEIKELCRE----D
>Synechococcus_7942_ClpS1
MAVE------------------------------------------------TIQKP--E
TTT-----------KRKIAPRYRVLLHNDDFNPM-EYVVMVLMQTVPSLTQPQAVDIMME
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------HTNGTGLVITCDIEPAEFYC--------EQLKSHGLEQQH---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|1161 @Bdellovibrio_bacteriovorus_HD100@ gi|42522812|ref|NP_968192.1| hypothetical protein Bd1289 [Bdellovibrio bacteriovorus HD100]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------GNNKK--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------DSNSNYP
FAS----------PE-------------------------------------GEAGVQLV
PKLDTPKMY----------KVILLNDDYTPMDFVV--LVLRRF-----FAK-TEEQATEI
MLDVH-------------------------------------------------------
---------------------------------------------KKGAGVAGVFSLEIA
-------EMKVMQVN---------------------------------------------
-----------------------------------QFAQLNQYPLKSTLEEEA-------
-----------------------------
>gnl|BL_ORD_ID|1427 @Bdellovibrio_bacteriovorus_HD100@ gi|42523078|ref|NP_968458.1| L-lysine 6-monooxygenase [Bdellovibrio bacteriovorus HD100]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------SDNKHYDLIGI--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GIGLFNLSLAALLSK
TPDVKFRFFDRKHRFDWHSEIMFADSEMQTSYMKDLVTAADPTNPFSFMNFLVQKGLFYA
FLNTGRQTITRREFEMYCQWVSQNL-PEYLSFD------------SDIESVTYDGSKFIL
TINGEIFTAQNICIGTGLVPHLPEFAQALEGPEVF-HAKSSYLKLLDATNKDVVVVGGGQ
TGLEIFRNCLQGKWGHPKSLKLIASRQNLEPLDNSPFVNEYFTPSYVKEFLQLDQDQKDP
IVKYQKLASDGNTPEYLETLYRDLY--------QLKHVWGDKRQIEILPYRRVTEMVKIG
DR------Y----------KMHIHNGFSNQSETTTADTVVLSTGFRVNIPSLIEP--LRP
MINFD-------------------------------------------------------
---------------------------------------------ENGR-FQMNQDFQVS
WNGSENNKIFALNFS---------------------------------------------
-----------------------------------RHGHGISEPQTSLMAWRSARIINNL
TKKSIFPIDKA----------VPNFITYI
>gnl|BL_ORD_ID|2667 @Bordetella_petrii_DSM_12804@ gi|163856974|ref|YP_001631272.1| clpS gene product [Bordetella petrii DSM 12804]
MSSTL-------------------------------------------------------
-----------------------------------------------------DTQHDVA
VE--------------------------KAPARTAP---PPMYQVVLLNDDYTPMEFVVK
VL-QKFFGKNQEDATRI-------------------------------------------
------------------------------------------------------------
-MLQVHHEGRG---TCGVYPRDVAATRIAQ---------------VAQYARARQHPLQC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VMEPV
>gnl|BL_ORD_ID|2228 @Bordetella_petrii_DSM_12804@ gi|163856535|ref|YP_001630833.1| unnamed protein product [Bordetella petrii DSM 12804]
MTQPA-------------------------------------------------------
-----------------------------------------------------ARRALIV
VD--------------------------------------------VQNEYF----GGKL
PIEYPDPQQSLANIGRA-------------------------------------------
------------------------------------------------------------
-MDAAHAAGVPIVLVQDIEP---AESPLFARGSHGAE--------LHESVVSRPHDHHVV
KGMPSAFAG-----TGLEAWLAE-RGIDTITVVGY---MTHNCDDSTVKHAVHAGLRVEV
LNDATGSV---------------------------PYANSAGQASAEEIHRVLTVVMQSR
FA--AVMSTAQWI------------------AGLNGAPMPTRDNIYASNQR---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ARGLA
>gnl|BL_ORD_ID|542 @Borrelia_garinii_PBi@ gi|51598707|ref|YP_072895.1| hypothetical protein BG0460 [Borrelia garinii PBi]
MKKKKQ------------------------------------------------------
------------------------------------------------------------
---------------------KKLYEILNLFLLVFKT-----------------------
--TTLTIGGG--------------------------------------------------
--LIIISEL---KKILVKKRKIISEDDFNKI-------LATSNVIPGVTAINFV------
---------------FLVGRRFGGF-----------------------------------
-------PCALLLVVAGILPSIIV-----IIMVFFYLKLVPNSIHVEKFLEGAKISSIII
MLT-------VVLKFSKKMLNNSI---------IKWTICFLVIFAIFKLKIR-------I
SYVLLIFFLIYTLKYITIKK-----------------ILTKEKKDID
>gnl|BL_ORD_ID|932 @Campylobacter_concisus_13826@ gi|157164897|ref|YP_001466798.1| hypothetical protein CCC13826_1206 [Campylobacter concisus 13826]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------KFLVSAKSKVLAGVAAVSALSSNA
L-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------AAGLTMGTNGTVT-------------
GDIDPAPFTSMAIAV-----------------VTFVALVYAIKAGIRLLG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------R
>gnl|BL_ORD_ID|998 @Campylobacter_concisus_13826@ gi|157165154|ref|YP_001466864.1| thiamine biosynthesis protein ThiH [Campylobacter concisus 13826]
M-----------------------------------------------------------
------------------------------------------------------------
--------------KFTRNDHMKLLPHMQDVGSDIMDEILKECASYKPEIYSEADVKAAL
-------------------------NAKHCSLENLKALLSPAAAPFLEPIAQLAQAKTRA
NFGSNITLFTPLYIANYCDNLCVYCGFNAKNNIKRAKLSDEEITRELREISKSGLEEILI
LTGESETNSSVAYIANACALAKKFFKVVGVEIYPLNSEGYALLHKSGADYVTVFQETYNP
TKYEKIH------LGGNKRIFPYRLNAQERALLGGMRGVGFAALLGIDDFRLDAFATALH
ASLVQ---------------------------KKYPHAEIAFSCPRLRPI-INNDR----
---INPRDVGERELLQ--------VICAYRIFMPTASITISTR-----------------
---EKAKFRDNAVKI-----AANKISAGVKVSIGAHGEEKKGD----------------E
QF---------------EISDSRSVDEIKAMIKANGLEPLMSEYVY--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------V
>gnl|BL_ORD_ID|1332 @Candidatus_Protochlamydia_amoebophila_UWE25@ gi|46446967|ref|YP_008332.1| unnamed protein product [Candidatus Protochlamydia amoebophila UWE25]
M------------------P-----------QATLPKTFPAFFWF-----FLKKQWKWLL
F--AQIFSFA----WS---------LDHTLWPYVIMTLIDTITNFAGPQAEVWHALAKPI
IMGISLWLGVEISFRLAGFIIAYIVPKIEADIRMSMFQYVMHHSHQYFSSHMAGSIANKI
ADLPQSL-------TRLLTLIVQLFLPACLALMISTTMFAFINPFFALILISWV---IIH
MGICLAFSKKCDDYSNTHAESRTLLSGKIIDSLSNNANIRLFSRSQFEA-SYLSFFQEDE
LNKHWRSLFYMEKMKIALGIACFLGACIALNWYMLYSWQQGELSAGEVVFIFNTTWNITI
MAWLAGLELPQVFKEIG-------------ICKQALTVIQDTHDIIDSPFAEQLTIHQGK
IIFDNVTFRYQKQQSLFQNM---NITIEAGQKVGLVGFSGSGKTTFINLILRNYDIESGR
ILIDNQDISKVTQTSLREQISIIPQDPTLFHRSLIDNIRYARPDATDEEVIEASKQAHCH
EFILKLPDKYQTLVGERGSKLSGGQRQRIAIARAILKNAPILILDEATSALDSVTERNIQ
EGLEFLMKDHTSLVIAHRLSTLSGMDRILVFKEGKIIEDGTHEELIQADQHYANMWEMQV
GGFLIDNYDELEDEESEIDSSVY
>gnl|BL_ORD_ID|1252 @Candidatus_Protochlamydia_amoebophila_UWE25@ gi|46446887|ref|YP_008252.1| murF gene product [Candidatus Protochlamydia amoebophila UWE25]
M------------------RIMTLKQIAKILNSSLPEVEGVVKGFCVDSRLTKKNEVFVA
LRGEHVDGHAYLNEVKQKGALAAIVDQNYQGPVFGMHLFRTENPLLALQMLAQKCLEKT-
-------------SRVVAVTGSIGKTTTKEFIKT-----LLEQRYVTAASQGN---SNSQ
VGLPLTVLNHTTGTEDILVLEMGMTEPGQLS-----TLVNIAHPEVSVLTTAALVHACRF
ETLKDIALTKAEIFSHSHT--RLGVVDREIEAYETIAQIGECKKISFSTVSSRADYHLET
VNEEVR--LKTEGQSISLGKMCLPGKHNLHNL----------LAAIAVARYFELTWN-EI
KQAIPFLKLPERRLQF--------------VQKEGVYFLNDSYN------ASELSVKSAL
ETLPNATGKGYKIAVLGSMMELGHFSDECHQRVGEFALNYVDKMYCLG------------
------------------------------------------------------------
-------------------------AECLPIVEVWKKANRPVELFMERSELISTLKKNLK
PADVVLLKGSRSKE----------------------------------------LWKI--
----------LEE---------L
>gnl|BL_ORD_ID|1190 @Candidatus_Solibacter_usitatus_Ellin6076@ gi|116620336|ref|YP_822492.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
MRRHAAQMANPAIAPDTEILERE---REQHVPL------------------YRVVLL---
------------------DDNDHTYDYVIEMLQKIFIFTLDQAYRHAEEVDRAGRTVLIT
CELREA------------------------------------------------------
-------------------------------------EYARDQIQAYGPDWRLPRSKGSM
SAVVEPAQ-----------------
>gnl|BL_ORD_ID|7252 @Candidatus_Solibacter_usitatus_Ellin6076@ gi|116626398|ref|YP_828554.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
MNIEIAHEGPIAI---VTLNRPE---RRNALSLELMLDLIAALDEIGRNRELRAVILAAA
GKVFSSGHDLSEMTGRDINDYRRIFDVCCDLMQKIQSIPQPVIAEVQGIATAAGCQLVAT
CDLAIAADTARFATPGVRIGLFCTTPMVALTRAIGRKRAMQMLLTGDFVDAPTAADWGLV
NQVVPAADLQSAARALAQKVAAASSLVVAIGKQAFYTQIDLDQPKAYA----YAKEVMSM
NALAADAQEGISSFLGKRAPCWSGK
>Synechococcus_7942_ClpS1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------AVETIQKPETTTKRK------------------------IAP---RYR
---------------------------------------VLLHNDDFNPMEYVVMVLMQT
------------------------------------------------------------
------------------------------------------------------------
VPSLTQPQAVDIMMEAHTNGTGLVITCDIEPAEFYCEQLKS-------------------
--------------------------------HGLE------------------------
--------------------------------QQH
>gnl|BL_ORD_ID|893 @Chlamydophila_abortus_S26_3@ gi|62185541|ref|YP_220326.1| unnamed protein product [Chlamydophila abortus S26/3]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------LQFTQNPIIQAYTEA-----------------
------------------DLFGRGIFFSLLI--------------LSLCTWTVLHQKLAI
QKKFLKSGKSLKDFLIK-----NRHAPLSLEIHPELNPFADLYFTIKRGTLELLDKNRQQ
APDHGPV----------------------LSVEDIQ------------------------
---SLET-------------------LLG-AVMPKYRALMHENNFIPATTISLA------
----------------------------PFLG----------------------------
----------LLGTVWGILTAFSHISSGEVG-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------GTAMMEGLATALGTTIVGLFVAI
PSLIGFN------YLKAHS-------------------------------------SRLI
LEIEQTAYLLLNSIEVKYRQ-----------------------------TNL
>gnl|BL_ORD_ID|723 @Chlamydophila_abortus_S26_3@ gi|62185371|ref|YP_220156.1| lpxB gene product [Chlamydophila abortus S26/3]
M-----------------------------------------------------------
------------------------------------------------------------
----------------FPLYLVRLLYPIGLIANLFFGFAFTLQWFLSERH----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------KRACVPKAFWIFSSIG
AILMIAHGFIQSQFPIALLHGANLVIYFRNLNIS--------------------------
------------------------------------------------------------
-------------------------SSRKLSLKTTLIILAVTLLLTALPFALEAYYHPNM
QWMASPNIFHLPLPPPNMYWHMIGCLGLFTFSCRFFIQWCHLEMNNQSTLPVLFWQVGFV
GGFLAFLYFIRTGDPVNILSYGCGLFPSIAN--------------LRIIYKKSRLSEFHN
PSYFISAGEASGDTLG------SDLLRHIKALHPDKRCFGVGGPLMRQEGLEPL------
-----------------------------IHMEEFQVS------------------GFLE
ILTSIFT-------------------LIK-KYRKLYKAILKENPEIVF------------
----------CIDFPDFHFFLIKKLRKCGYTGKIVH------------------------
---------YVCPSIWAWRPKRKKILEKYLDTLLLILPF---------------------
------------------------------------------------------------
---------------------------ENELFINSPLKTIYLGHPLVKTISNFQHCPSWK
QALAISDQ-------PIVALFPGSRPGDILRNLQVHIRAFLASSLAESHQLLVSSYNLKH
DQTILDLLEKEGCCGKTVPAMYRYHLMRDCDCALAKCGTIALE--AALNQTPTIVTCLLR
PFDIFLAKYIFKIFMSAYSLPNIITKSIIFPEFIGGKSDFTPEEVAAAIDILANPKSREK
QKRACQTLLETMETNVVTVQECLQTIHSLKSRFHTENDCLGNYVQKNVRPSF
>gnl|BL_ORD_ID|2204 @Chlorobium_tepidum_TLS@ CT2237 hypothetical protein
M---------------------------IRLTASNNPD----------------------
------------------------------------------------------------
---------------TRTE-----------------------------------------
---------ELIADVDTLDAW---------------------------------------
-------------RVVLFND----------------------------------------
-DDHTFDEVIFQIIKAVRCTRSIAEKHTW-------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------EVHTRGRA
IVYAGEMSNCIRVS---------------------------AILEEIALKTEI-------
-----------------------------------------QTG
>gnl|BL_ORD_ID|1487 @Chlorobium_tepidum_TLS@ CT1509 CAAX prenyl protease 1, putative
MMMNLFGQIILFTLIGTWLIKLAADLLNLRAASPTLPEAFRDVYDPADYRRSQEYLRANT
KFSLISSTFDLALLLVFWFAGGFNALDQLIRAWGFDPVINGVLYIGALLLLQSVADLPFS
IYHTFVLEERFGFNQTTPKVFVIDLIKTLLLAVLIGTPVLAAILWFFQSAGPLGWLWAWG
GVTAFSLLLQYVAPTWIMPMFNKFEPLEDGELRKSIMDYAAEVRFPLTGIYVMDGSKRSA
KGNAFFTGFGKNKRIVLFDTLIKNHSTGELVA------------------------VLAH
EIGHFKKKHIFMSMGLSMLNLGVVFYLLSLFMNNRMLFDAFAMQETSVYASLLFFML---
--------------LYNPVEFII-----SIL--------------------MQMLSRRNE
FEADNY------------------------------------------------------
--------------------------------------------AV------KTYRNGAL
LADALKKLSRQNLSNLTPHPF-----------NVFLNYSHPPVLQRVERIEAA-------
-----------------------------------------ARH
>gnl|BL_ORD_ID|2556 @Chloroflexus_aurantiacus_J_10_fl@ gi|163848160|ref|YP_001636204.1| ATP-dependent Clp protease adaptor protein ClpS [Chloroflexus aurantiacus J-10-fl]
MS----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------TEQPAVTV
RPAV-------SFAVASDEELERPYRVIV-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------QNDDV----------------
---------------------------------------------TPMDFVVIVL-----
------------------------------------------------------------
-----------------------RVFFGL------------DLARAEQVMLTAHYEGRAL
-VTVLPLQEA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------QERVYQAHH
------------------------------------------------------------
------------------------------------------------------------
------------------AAREAGYPLTFYLEPDEQ------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>gnl|BL_ORD_ID|568 @Chloroflexus_aurantiacus_J_10_fl@ gi|163846172|ref|YP_001634216.1| aldehyde dehydrogenase [Chloroflexus aurantiacus J-10-fl]
MSK-------------------------IIAPECEWSHLLAQLRSVVPEAFNSEGHVLNL
IEGTWGWPGHGKHYSTPIDGTELGRMPMIDLETAKRAVRFAAREHETWARTDLDERRRRV
RETVDGLRQHRDLIAYLLMWEIGKPYHLACDDVDRCLDGVEWYIDQIEWMLSNRQPLGLI
SNIA-------SW--------NYPYSVLVHAVLVQALAGNAVIAKTPSDGGLFALTLGFA
IARRAGLPVSLVS----GSGGALSDALVRNADVACLAFVGGKTNGRDIAASLYDRNKRYM
LEMEGVNCYGIWDFSDWASLAQQIKKGFAYGKQRCTAYIRYVVQRRLFPKFLDVYLPVLK
SLQIGNPVLVDRAGDPLPRLDFGPLINARKVEELRVLYSEALGAGAVCLYEGEL------
--------NPELFLPDQDISAYMAPIALLNVPRNCRLH-HNEPF----------------
---------------------------------------------GPIDTIVIVD-----
------------------------------------------------------------
-----------------------------------------SIEELISEMNISNGNLVSS
-IATDDLRLG--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------QMIASELRA
------------------------------------------------------------
-------------------FKVGINRMRSRGDRDEVFGGMGA-------SWKGCFVGGKY
LVEAVTVGAP--------GERLYGNFPDYTLLPEQR------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>Synechococcus_7942_ClpS1
MAV---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMV------
------------------LMQTVPSLTQ---PQAVDIMMEAHTNGT--------------
--------GLVITCDIEPAEFYCEQLKSH-------------------------------
---------------GLEQQ----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------H
>gnl|BL_ORD_ID|1028 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637456|ref|YP_677663.1| hypothetical protein CHU_1046 [Cytophaga hutchinsonii ATCC 33406]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------IRIQS------------------------
------------------------------------------------------------
------------------------------------------------------------
--------HSFPFQQEEDVALMEEVQTSDMN-----------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------DLVVYNDDVNTFEHVIQVL
MSVC-GHSPEQAEQCTLLIHYKGKC-------TVKMGSLNELKPMRQGICDK--------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------GISAE-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------IL
>gnl|BL_ORD_ID|1117 @Dehalococcoides_ethenogenes_195@ gi|57234119|ref|YP_181873.1| molybdenum ABC transporter, ATP-binding protein [Dehalococcoides ethenogenes 195]
MLEVN--------IKKKLP-----------------------------------------
--------------------GFDLEVAFSADS--GIMAMLG------PSGSGKTMTLQCV
AGLT--------QVDEGYINLNGEV---LLDT-----SRKIDIRPQVRRVGF----VFQN
YALFPHLTVRDNIAYGIRHLEKA---------------ESDGIITRLMEN----------
-----MHIASLGHRF-------PSQLSAGQQ-----------------------------
---------------------------------------------------QRVALARAI
APEPRVLLLDEPFSA-----------------LDAVVKE---------------------
------------------SLEIELLSLQQF------YKGIIILVTHNFAEGYRMSSKMAI
YES--------G--------------------------------RIAQCGDKGKIVGSPA
NLT----------VAG------------------------------LMGFKNLLVGTVSQ
IIGQDLYLEVPGLSLFKIRLPEQMQLAVGMRLTLG-------------------------
------------------------------IRSEF-----------------VRVSAAAE
ENSLPGVVSGVINEVASTRCFFSAGAN--------LQYTFEAFLPPPA------------
------------------------------------------------------------
------------------------------------------------------------
-----------DASLKVGSRLNFCF------------------------PTEHL------
-------------------------------------VVVGQAGETAQTGSLAG------
--------------------------
>gnl|BL_ORD_ID|1269 @Dehalococcoides_ethenogenes_195@ gi|57233975|ref|YP_182025.1| hypothetical protein DET1313 [Dehalococcoides ethenogenes 195]
MLRPASAAGRYYPASKE-------------------KIRSVIAPMEVKGVAKERYLGAVM
PHAGYPYSG-----------GVAMAVASRLDLP-ETVIILG------PSHTGIGAEYAIM
ASGI-------WQTPMGEVEIDSTLAHSIMKY-----CRHIKADPSAHQY---EHSIEVQ
LPILQYFKPDIKIVPLTVSFGKA-------------------------------------
-----ETLAEIGHGI-------ASALRETGR-----------------------------
------------------------------------------------------------
------EAIIIASSDMTHYESQADAHQKDSLALDAIIKL---------------------
------------------DAAQMLERIQQNHITMCGFAPVAAMLTAVKEMGAKRARVVAY
QTS--------G--------------------------------DVTHHLDQ--------
----------------------------------------------VVGYAGLVVEQTEE
---------SPQVALARAAVETFVREKKVITPSAE-------------------------
------------------------------ISAELTGEAGVFVSLK--KLGELRGCIGTF
EPRFDNIADEIVSNAVSSSSKDPRFEPVSEWELPFLSYSVDVLTPPQAVEDMGSLDAKKY
GVIVES------------------------------------------------------
------------------------------------------------------------
---------------------------------GHLRGLLLPDLEGVDTPSEQI------
-------------------------------------AICRQKAGIAPDAPVRLYRFEVQ
-----------------------RYY
>gnl|BL_ORD_ID|752 @Deinococcus_radiodurans_R1@ gi|15805613|ref|NP_294309.1| ATP-dependent Clp protease adaptor protein ClpS [Deinococcus radiodurans R1]
MA-----------------------------------------------------RRGAL
PVLKSAAPLGGGARPILGAMTRPTI-----------------PPGPPGAEG---------
----------------------------------------------------------RT
QTLE--------------------------------------------------------
--------------------------------------------------------RTET
KKPR----LWRVLLLNDDYTPM--------DYVVQVLEQFFR------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------KTEQEAELIMLAVHHKGQGVAGVYTRDVAETKVAQV
TA----------------------------------------------------------
------------------------------------------------------------
-----------------------------------HAQREGHPLRVVAEP----------
------------------------------------------------------------
-----------------------ESEGE
>gnl|BL_ORD_ID|1231 @Deinococcus_radiodurans_R1@ gi|15806084|ref|NP_294788.1| hypothetical protein DR_1064 [Deinococcus radiodurans R1]
MN-----------------TTDHATPLTEGHPYRVERAVLAGVPCLLELPPKDSDVRGVC
LVYHGAWAAKEGKLGVYSALTTHGIAVVIPDAALHGERQGDTPPGLNAREY---------
----------------------------------------------------------VW
DSVR--------------------------------------------------------
--------------------------------------------------------RTVV
EAPA----LLDALAGRFGAGPVLAVGSSMGGYVVQTLLQTEP------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------RLTRARCAHHLGCLAGTAGAGAGAAGVSGSAPAPDPRL
AR----------------------------------------------------------
------------------------------------------------------------
-----------------------------GPHATADRERGGRPGVFARRAPSADGGGLPR
SLRGRDGRFRGTEFSRRRPLHQRGPARRGA------------------------------
-----------GVLVGEIGCWRNRLLRE
>gnl|BL_ORD_ID|3490 @Delftia_acidovorans_SPH_1@ gi|160898941|ref|YP_001564523.1| ATP-dependent Clp protease adaptor protein ClpS [Delftia acidovorans SPH-1]
M-----------------------------------------------------------
ARMIFM--ATQPPS------------------------IPPAIPTVRPVSDDDGAVVLE-
------------------------------------------------------------
---------------------------------------------------RRRQRVQP-
-------PQMYQVVMLNDDFTPMEFVIIVL-QELFGKDR-ETATQIML------------
------------------------------------------------------------
------------------------------------KIHL----DGRGVCGVYSR-----
-----------------------DVAATKVEQV---------------------------
------------------------------------------------------------
----LQAAQKAG--------------------------------HPLQAMFEP-VE
>gnl|BL_ORD_ID|2111 @Delftia_acidovorans_SPH_1@ gi|160897562|ref|YP_001563144.1| 2-hydroxy-3-oxopropionate reductase [Delftia acidovorans SPH-1]
MNASSLKLGFVGLGIMGAPMAGHLLTAGHQLFVNTLGKIPAQIAESSATQCTTARGVAER
ADIIFL--ML--PDTPDVEKVLFGEDGVAAGLKGSSGKVVVDMSSISPVATKDFARRIEA
IGAQYLDAPVSGGEVGAKNATLSIMVGGPEDVFARVKPLFERMGKNITLVGGNGDGQTAK
VANQIIVALNIEAVAEALLFASRAGADPARVREALLGGFASSKILEVHAERMIKRTFDP-
---------GFRISLHQKDLNLALSSARQLGVSLPNTAQ-AQELFNSC------------
------------------------------------------------------------
------------------------------------VAHGGANWDHSGMVRALEI-----
-----------------------Q-ANFEVGQK---------------------------
------------------------------------------------------------
----VQA-------------------------------------------------
>gnl|BL_ORD_ID|1675 @Desulfovibrio_vulgaris_DP4@ gi|120602577|ref|YP_966977.1| ATP-dependent Clp protease adaptor protein ClpS [Desulfovibrio vulgaris DP4]
M-----------------------------SNGPLAPGYDSDILVED------DVRLPRM
YRVLLHNDDYTTM-----------------------------------------------
------------------------------------------------------------
--------------------------EFVVS-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------ILVE-VFRKTAEQATAIMLAVHRDGVGECGVYTFEV---
--------AETKAAIVHARARREGYPLRCSTEEV------------
>gnl|BL_ORD_ID|2474 @Desulfovibrio_vulgaris_DP4@ gi|120603376|ref|YP_967776.1| nitrite reductase [Desulfovibrio vulgaris DP4]
MNNQKTFKGLRLAALGLVAVAAFTAGCSDVSTELKTPVYKTKLTAEEIRNSAFKPEFPKQ
YASYERNDETTVMTEYKGSVPFNKNDNVNPLPEGYRHAQPYLKNLWLGYPFMYEYREARG
HTYAIQDFLHIDRINRYAEKGGLPATCWNCKTPKMMEWVKENGDGFWSKDVNEFRDKIDM
KDHTIGCATCHDPQTMELRITSVPLTDYLVSQGKDPKKLPRNEMRALVCGQCHVEYYFNG
PTMGVNKKPVFPWAEGFDPADMYRYYDKHGDLQVKGFEGKFADWTHPASKTPMLKAQHPE
YETWINGTHGAAGVTCADCHMSYTRSDDKKKISSHWWTSPMKDPEMRACRQCHSDKTPDY
LKSRVLFTQKRTFDLLLAAQEVSVKAHEAVRLANEYQGAKAAGYDDLMIQAREMVRKGQF
FWDYVSAENSVGFHNPAKALDTLAQS--QQFSQKAIDLAMEATQYGIGKDLTGDIKTIVP
PILKMNRKLQQDPEFMKTHKWFQYLPVLPKADQVWDGQKRLVSAKQ
>gnl|BL_ORD_ID|187 @Ehrlichia_canis_Jake@ gi|73666821|ref|YP_302837.1| 3-phosphoshikimate 1-carboxyvinyltransferase [Ehrlichia canis str. Jake]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------VLISE-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------KIYHM---------------
------------------------------------------------------------
--------------------CGHVDILK-----------DN-------------------
------------------------LMSHATLVLAS----QVIGVTKIYDLVFNDDIMLTI
KALDLLGVKI---KYNKSSKVCTVEG-------MGVGGFLCPKDALYLNNPAIYMMI---
------GCLASCPFTSFLYGNSNISISKVMKPL---------LLMGARFIANDNKFPAAL
VGYIDMLPIRYVAKDDETKMAMIFAALNTFGTTTIISTTGKDSIVPILQYLNVGIECFIN
KNYVINISGQRELYSKDMCIPNDFFCMLSFIAVALVLKESEITILNVLLTDRIKSFCKVL
IEMGGNLFFVNHRNNAIGEKVADLLIKGS-VLQGMKCLHNNDF--------DIDEYLFIV
IIAAYAD------------------GITVLSNVLDHILMDKRLKTVINELVKAGIRIDIE
GNRLIIYGCSDNILDWNLVDACYDFKMTILFLVIGMISKNVIKIKNIRKTRDLLTIIELF
NKHGAGIKII
>gnl|BL_ORD_ID|186 @Ehrlichia_canis_Jake@ gi|73666820|ref|YP_302836.1| DNA polymerase III subunit alpha [Ehrlichia canis str. Jake]
MSQIFVHLRSHSDYSLLHGMVKIESLVNLCVQHNMPALALTDSGNLFGSLEFSDCASNSG
IQPIIGCNIMISYNGDNIGELILLVKNQVGYSNIVNLVSNSFRNDQSGKINRIDLNTLIS
LKDGIIVLTGGHDGFLAQLLLGNVIDYGIIDKLLLAFKGNLYVELQRHNIEEEKLIERTL
IKFAYEKDVPLVATNDILFARREDFLAHDVLSCISDGNYIAQEDRKMFTEEHYFKSSNEM
HELFVDIPEAISNTVLIAQRCSFMPEIRKPMLPHFPCSSGRNESQELISQAIDGLNSRLK
DSNLSKEQTSKYYERLHYELDIIISMDYAGYFLIVSDFICWSKRNDIMVGPGRGSGAGSL
VAWSLQITDLDPIEFGLIFERFLNPDRISMPDFDIDFCQEGRDHVIEYVRKKYGYVAHII
TFGKLQAKAVLRDVGRVMQMPYFQVDRICKMIPHNPVRPVTLSEAIEMDKNLQKERDDDE
TVAKLLEISLKLEGLYRHVSIHAAGIVICDRRLEELLPLYYDNVSFLPITQYNMKYTEKA
GLVKFDFLGLRTLTVINQICHLVNNGGQNVDISRIPLNDKKTYEMLSAGDSVGVFQLESS
GMREVISKLKPDNINDIIALISLYRPGPMDNISIYIARKHGFEKPDYIHPILEGVLKETF
GVIIYQEQVMEIAKIMAGYSLGEADLLRRAMGKKIKEEMDNQRRAFISGAINNGIEEEKA
SYIFDLVAKFAGYGFNKSHAAAYALISYQTAYLKANYTLEFFTASMNLDITDKDKLEMLC
HQAKLHGIKILPPDINTSKVFFTIEGSSSIRYALGALKNVGQHSAKEIVDDIAYKDIWDF
IDRVSTKCVHKRILESIIKAGVLDSIHSNRKQLFESVFLFLDIIEYNKYNANFNQFSL--
--FTDRAHYKLSETDDWTKEEKLDNEFSSIG--FYLNHHPMENYKCLLEKLNIG---FIN
YD-------DRSAYNNR---------IVGIISSVKVRSASRDKFAVVTLSDPY-------
-----NIHEIAFYNGSVIEDNKDLFTSGAPVIIEM----DNDFYSTAARLLGKNIYSFES
KISSIIK------------------SMVIYISVEDSVII-KELSSLLKD-----------
------NGSTVVLINVLLPDDHVTIQLPNSFLITPLIFMQIFKLSWVRD----IEINSIT
NEH------I
>gnl|BL_ORD_ID|1000 Escherichia_coli_UTI89 gi|91209918|ref|YP_539904.1| ATP-dependent Clp protease adaptor protein ClpS [Escherichia coli UTI89]
M-----------------------------------------------------------
------------GKTNDWLDFDQLAE----------------------------------
------------------------------------------------------------
-----------EKVRDALKPPSMYKVILVNDDY-------------TPMEFVIDVLQK--
----------------FFSYDVERATQL--------------------------------
--------------------------MLAVHYQGKAICG---------------------
------------VFTAEVAETKV----------AMVNKYARENEHPLLCTLEKA------
--------------------------------------------------------
>gnl|BL_ORD_ID|3362 Escherichia_coli_UTI89 gi|91212298|ref|YP_542284.1| hypothetical protein UTI89_C3305 [Escherichia coli UTI89]
M---KFKVIALAALMGISGMAAQANELPDGPHIVTSGTASVDAVPDIATLAIEVNVAAKD
AATAKKQADERVAQYISFLELNQIAK--KDISSANLRTQPDYDYQDGKSILKGYRAVRTV
EVTLRQLDK-----LNSLLDGALKAGLNEIRS--------VSLGVAQPDAYKDKARKAAI
DNAIHQAQELANGFHRKLGP--VYSVRYHVSNY-------------QPSPMVRMMKAD--
------------------------------------------------------------
------------------------------------------------------------
------------AAPVSAQETYEQAAIQFDDQVDVIFQLE-PVDQPPAKTPAAH------
--------------------------------------------------------
>Synechococcus_7942_ClpS1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------AVETIQKPETTTKRKIAPRYRVLLHNDDFNPMEY
VVMVLMQTVPSLTQPQAVDIMME-------------------------------------
-------------AHTNGTGLVIT------------------------------------
------------------------------------------------------------
------CDIE--------------------------------------------------
------------------------------------------------PAEFYCEQLKSH
GLEQQH------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|3483 @Flavobacterium_johnsoniae_UW101@ gi|146301250|ref|YP_001195841.1| unnamed protein product [Flavobacterium johnsoniae UW101]
M----------------------------------------------------------S
TKEKVREKVREKEAAVFNNEIIMYNDDVNTFDHVIDTLMRV---------------CDHT
AEQA--------------------EQCSLIVHYNGKCTVKTGPIEKLK------------
--------------------------------------PQCTQLLEAGLSAEIV------
--------------------------------------
>gnl|BL_ORD_ID|1424 @Flavobacterium_johnsoniae_UW101@ gi|146299191|ref|YP_001193782.1| unnamed protein product [Flavobacterium johnsoniae UW101]
MKNALICFLAAFMAFSCKKENNVIHTDDKEEIGQKQSSFVSDQSNNTGSLYSVSYEPTST
TNQIVKHKYY----------TLSYNEKFEQAEWVAYELKKEYLKNGNFKRPYFIEDPKVT
TGSADWRNYKKSGYDKGHLCPAGDMEFSEEAYND---TFYTSNISPQKHDFNSGIWNRIE
QKTRYWAGKYNDIYVVTGGVLKDTDKKIGTEKVSVPKYFYKIVLAKSGKEHKAIAFLVPN
KDSDKSIYDFVVPIETVEKMTGIDFFPNLKNLKNSKDF
>gnl|BL_ORD_ID|3268 @Geobacter_metallireducens_GS_15@ gi|78224482|ref|YP_386229.1| unnamed protein product [Geobacter metallireducens GS-15]
M---------------------------------------------------------TT
ETILTQIDDR--------------------------------------------------
------------------------------------------------------------
----------------------------------GVATLTMNRPELHNAFDDLLIAALTA
ELRRLEAD----------------DSVRVVILAASGRSFSAGADLS--WMRRMADYTREE
NLTD-------------AQVLAELMRTLATLKKPTIAQVQGAAF---GGGVGLVACC---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----DVAIAS---------------------------------RRATFCLSEVKLGLIPA
VISPYVVEALGPRAARRYFQ----------------------------------------
------------------SAEIFDAAEA------RGLGLVHEV-------------TTEE
ELPAAVERLAATLLLNGPRAM---------------------------------------
----------------------------A-AAKELVARVASGPIDEAMIRDTAERIADTR
ASAEGKEGLSA--------------FLEKRKPRWVKG-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|3141 @Geobacter_metallireducens_GS_15@ gi|78224355|ref|YP_386102.1| unnamed protein product [Geobacter metallireducens GS-15]
M-------------ETQDEKSERERSVPPIVAIDGTAIKRIREAKKLTQLYVASVVGVTT
DTISRWENNRYPTIKRDNAEKVATALEVSLEEILKPEPVSE--------PEPEPEAVPV-
--------------LLSPRKQRLAPLVL-------------AVGLGTLLVALIVGAVLSR
RGAAELVATRVLPPFG--APGQLVPVQVKVDRRDGEKSGFIVKERI----PAGWR-FVAS
NPPVAGEAGEREVKWLIPPGGTGPVTISYTLT-APR------------------------
----TLLLGSQADFGG-EVILSHGKATRRGIIGGPARIVVNGRHWADTNGDGRIDDN---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----EIMPAYYLCE--------------------EM------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------RGLGLDWKTIETIWSGAGYTWNDKL
KVFEVVK-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|1467 @Haemophilus_somnus_129PT@ gi|113461597|ref|YP_719666.1| ATP-dependent DNA helicase RecG [Haemophilus somnus 129PT]
MGGQFLDAIPL-----------------------------TSLSGVGAAIAEKLGRIGLF
SLQDLLFHLPIRYEDRTRI------------------TPI------IDLRIDQHATIEGI
VQTCDIQFGRRPVLVVTLSDGTAKIALRFFNFNAGMKNGFQLGARVKAFGEIKRGRFMAE
IHHPEYEIIRDNRPLQLAETLTPIYATTEGLKQNTLRKLTEQALALLEKMPLAELLPRAF
NPHDF-SLKQAIYVLHRPPPDISLELLEQGKHPAQLRLIFEELLAHNLAMQKVRCGSQHF
SALPLRYQTALKQNFLDLLPYQPTNAQQRVVAEIEYDLGRSFPMMRL---------VQGD
VGSGKT-LVVALAALTAIDNGKQV-------ALMVPTEI------LAEQHTANFQHWFEP
LGIKVGCLTGK-----------------------VKGKSRQATLEEISQGSIQMVVGTHA
LFQDDVKFAELVLVVIDEQHRFGVHQRLMLREKGKYAGIYPHQLIMTATPIPRTLAMVAY
ADLDISIIDELPPGRTPIQTIAVSEERRTEIVARVYNACVNEKRQAYWVCTLIDESEVLE
AQAAESIAEDLQKALPVLRIGLIHGRMKASEKQEVMRQFKNAELNLLVATTVIEVGVDVP
NASLMIIENAERLGLAQLHQLRGRVGRGSTASYCVLMYKSPLSKVSRKRLEVMRSSQDGF
FISEQDLEIRGPGEVLGTKQTGVAEFKVADLIRDRKMLPTVQHYARLLITRSPKLADDLI
QRWLKNKEIYTNA
>gnl|BL_ORD_ID|58 @Haemophilus_somnus_129PT@ gi|113460200|ref|YP_718257.1| ABC transporter ATP-binding, sugar transport [Haemophilus somnus 129PT]
MKETESNPTPLLEACDVSKAFSGVEVLKSINFSLYSGQVHTLLGGNGAGKSTLMKIIAGI
QLQD-TGTLKIHGKVRTNL------------------TPSKAHQLGIYLVPQEPLLFSNL
SVKENILFG-LPRTMDLQSKLTALLTELNSHLNLDMQAGL-LDVADQQLVEIMRG-----
-------LMRDAQILILDE---PTASLTPVETENLFGQINSLLVKGVGIVFISHKLSEVW
QIADWVSVMRDGYIALSEPID---------------------KINHDDVIQAITPRAKNA
SL------TESQQLWLDLPGHKRVKSTEFPLLTVENFTGEGFRDINFEIYPGEILGLAGV
VGSGRTELAETLYGLRKAKSGKVIFCDELINSLSVKQRLKRGLVYLPEDRQASGLHLDSP
LSWNTCGLTYHDMGFWIDESKEKAILERYYHAIGIKFNHVEQSVRTLSGGNQQKILIAKC
LEADP------RLLIVDEPTR-GV-------DIGARADIY--QLIKS---IAKQNVAVLF
ISSDLEEIEQMSSRVLVMHDGKLSQSLKGE------------------------------
---------------------------------------------------------DIN
TDNIM------RLAFS--------------------------------------------
------------------------------------------------------------
------------S
>gnl|BL_ORD_ID|1340 @Heliobacterium_modesticaldum_Ice1@ gi|167629478|ref|YP_001679977.1| rplX gene product [Heliobacterium modesticaldum Ice1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------A-----------
------------------------------------------------------------
--------------------------------------------------------NPKV
HVRKGDLVQVITGK-------------------------------DAGKKGKIIEV----
------------------------------------------------------------
------------------------------------------IPAKNRVV----------
-----------------------------------------------VEKVNIVKRHSKP
SKTNPQGGIIEKEAPIDASNVMIFCPKCDRPVRSGHKFLENGDKARICRKCGDVLDK---
------------------------------------------------------------
------------------------------DK
>gnl|BL_ORD_ID|3187 @Herpetosiphon_aurantiacus_DSM_785@ gi|159899721|ref|YP_001545968.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
M-----------------------------------------------------------
------------------------------------------------------------
-----NTRRDVAT-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
AEPQTTTDVE--LDFITLSDEELEKPYRVILQ----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------ND------DI
TP----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MEVVVWVL-EKVFEQSFEQ-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---AKRIMIEAHVK----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GHA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----LVTILPFKEASAR-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------VYSAQSRARDMGFPLVLFLEPDF--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|1367 @Herpetosiphon_aurantiacus_DSM_785@ gi|159897901|ref|YP_001544148.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
M-----------------------------------------------------------
------------------------------------------------LPMRPNEFTVMQ
ATHTDAMRDHCVL-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
MEPQTSA------------GRNNKP---VITY----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TDAGSAVCGF
NPSTANGVASEEVLDSTAVVITKPTLRLPTGTVI--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------RASWRVRITHRNGQALTSPL-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---AFDIVGDPSTV----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GTA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----IVV-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------ELATVTREEV--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>gnl|BL_ORD_ID|900 @Legionella_pneumophila_2300_99_Alcoy@ gi|296106398|ref|YP_003618098.1| ATP-dependent Clp protease adaptor protein ClpS [Legionella pneumophila 2300/99 Alcoy]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-SRQNLEEIIQTGIADTELSTEIST-----------------------------------
-----AIKRPRKYKV------------------------LL---LNDDYTPMDF------
----------------------------------VVEVLKHFF-HLNE------------
--------EVAIQ--VMLQVHFQGKGVCGVFTRDI-------------------------
-------------------------AETKVALVNEYARMNQHP-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------LLSSM-----------------------
-------------------------------------------------------EPE
>gnl|BL_ORD_ID|2833 @Legionella_pneumophila_2300_99_Alcoy@ gi|296108331|ref|YP_003620032.1| dienelactone hydrolase family protein [Legionella pneumophila 2300/99 Alcoy]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------LVTKEVEYEDGDTVCKG
FIAYHSSVSKPLPCVMVAHDWGGRGEGVCNKAIQLAGMGYIGFAIDMYGNAKLGKDKVE-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------KRALMTPFR
ENRGKLITRINAAFSKVVQLPEVDSDKVAAIGYCFGGLCVLDLIRSGAPLRGVVSFHGVL
LPLEGESNKPLHAKV------------------------LILHGYDDPLVPIEQ------
--------------VNQFAIEMTERK-----VDWQVHVYGQTAHSFTD------------
--------PNAND--DEMGLHYN-------------------------------------
------------------------------KLADQRSWQSTQL-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------FLQDLF-----------------------
---------------------------------------------------------A
>gnl|BL_ORD_ID|1666 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116331466|ref|YP_801184.1| hypothetical protein LBJ_1906 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M-----------------------------------------------------------
------SDIFRFDTEEQTLTKEKVKLKRPSKYR---------------------------
------------------------------------------------------------
--------------------------------VIILND----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DFTPMEFVVWIL-----
--------------------------------------QFVFHRSRAQS-----------
---------------------------------------QQIMLKAHITGKALCGVYSHD
V-----------------------------------------------------------
---------------ARTKV----IQV--------------------------QQLAEQH
GYPLHCTME-----------------VEEES
>gnl|BL_ORD_ID|1440 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116331240|ref|YP_800958.1| hypothetical protein LBJ_1643 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M-----------------------------------------------------------
------AST-QTPDLDEITSTKST----GGPWR---------------------------
------------------------------------------------------------
--------------------------------VVLWDD----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------NEHTYEYVIEML-----
--------------------------------------VEICMMTVEKA-----------
---------------------------------------FLHAVQVDQEKRTI--VFSGE
F-----------------------------------------------------------
---------------EHAEHVQERILT--------------------------YGADPRM
-SNSKGSMS-----------------ATLEK
>gnl|BL_ORD_ID|2385 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116332185|ref|YP_801903.1| receiver component of a response regulator [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M-----------------------------------------------------------
----------------------KV----APTYS---------------------------
------------------------------------------------------------
--------------------------------ILLAED----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------DENNAELLIRYLERYNF
DVDHVIDGVAAEIRLRKTRYDLILTDNRMPKFDGIDLLERIPEMNEATP-----------
------------------------------IIFLTVSNEKETIIQAAHNKKLV--AY---
LLKPIDMRVLIEKICQALKIGAGSLIDKKEYPFEIILLNHTQQGVEIELKGCPYG-----
---------------KNIEKLVQEISLFLKELSKPNSILIKVNPEFFYFKNGTQVL----
-YALKVRLA------TKYEIGKEDVIIQTEH
>gnl|BL_ORD_ID|2454 @Methylibium_petroleiphilum_PM1@ gi|124267648|ref|YP_001021652.1| hypothetical protein Mpe_A2462 [Methylibium petroleiphilum PM1]
MPDDTVPP-------------------------------TPPKRPVTKPDDGQGAVVAER
QSARVEPPRMYQVVLLNDDYTPMEFVV---------------------------------
------------------------------------------------------------
-------------------------------------------------------MVLQE
FFQRDIE-TATQI----------------MLKIHHEGRGV---CGVYTKDVAST------
---------KVESVLAAA--------------------------------------KRSG
HPLQCTME----------------------------------------------------
----------------AA
>gnl|BL_ORD_ID|5870 @Mycobacterium_smegmatis_MC2_155@ gi|118470020|ref|YP_890293.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------RLKPGRP--------------
------------------------------------------------------------
------------------------DLADHARFFD--------------------------
------------------------------------------------------------
----------------------------------APTATPDSPVTVTWAGVTTLLVDDGT
SALLTDGFFSRPGLLTVGLRPLAPNVPRIDGCLARLGVDRLAAV---LPVHTHFDHAMDS
AVVAERTGAALVGGSSAAQIGIGGGLPDDRIVTVTPGEPVAMEAYDVTLFVSEHCPPDRF
PGVITEPVVPPAKAS-AYKCGEAWSTLVHHRPSDRRVLIVGSAGAVPGALAGQRADVVYL
GVGQLGRQPERYLTDYWTQTVRTVGARRVVLIHWDDFFRPLHRPLRALP------YVADD
LDATMRVLTT--------------------------------------------------
-------LAAH-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------DG-----------------------------------
----------------------VALHLPTLWQR---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------SDPWIET-------------------------------------------
-----------------------------------GS-----------------------
------------------------------------------------------------
---------------------------------------------------GPWR-----
----------------------
>gnl|BL_ORD_ID|4359 @Mycobacterium_smegmatis_MC2_155@ gi|118470694|ref|YP_888782.1| unnamed protein product [Mycobacterium smegmatis str. MC2 155]
MTATGTPPGIEDVLALSPLQQGLYSLAGLTEEDTGADPYVIAMAADIEGAVDPALLRSCA
EAMLVRHPNLRASFFQGNLTRPVAVVPTAVDLPWRHVTAPTAEAAAAIEAEERTRRFDLG
RGPLIRFLLIEMPAQRWRLVVTAHHIAIDGWSLPVFVGEYITLYAADGDTAVFPAAPRPY
RDYIGWLAGRDHDASRARWRAHLDGLDGPTLLAPALSGREAEPGLPARTEVTLDEQASAE
IFDGARARGVTVNTLFQMAWAAILSAFTDRTDVVYGVTVSGRPDELSGVESMVGLFINTV
PLRIRLDPAGSVGEQCLAVQREAADLRDHSYLSHTEIRALGGIGELFDTLLVYENFPPGG
LVGSDEFPLGSDGDGAVLRPSALESLSHFPVTIAAHPTHGRLTVLVETLDGALGMLDPHA
LGRRVLTVVQRLLRSWDRPVRDVAVTLDDEVATVAPTDTAVRPGGFHTAFTEAAAQRLGS
IALTWDG-----GELT--YRQLDEAADRVAAELRRRGVGTETPVPIRLPRGPEYVVAMLG
VLKA-------------------GGL-------IVPLDP-AMPDERVDEIIRQTHPDGRQ
PAIVDDAFVAAVRAADAELPADYRPAHVHPGQGAYIVFTSGTTGKPKGVIGTHQALLAY-
--------AADHARNVLRPAAQRVGHPLRVAHAWSFTFDAAWQPLVALLDGHANHIVGDD
VQRDAEALVETIGRHAIDMIDTTPSMFTQLRAAGLLSTVPLAVLALGGEAIDTALWQAIQ
AECERTWMSAHNCYGPTEATVEAVVAAIADHRDPCIGKPTDPTAAYVLDSWLRPVPAGVA
GELYLAGGQLTRGYVGRPGETAARFVADPFTLGARMYRTGDVVRRTPDGALQFLGRSDDQ
VKIRGFRVEPGEVAAALHRHPQVRHAHVALRRHRSGPRLVAYVVTDASLADAAGELRRML
AATLPRYLVPHHILLVDEIPLTTNGKVDDARLAALDSGRQSGGFQGPATDTERVVAEVLA
EVLDTRAVDVTAEFLDLGLDSIVALTVVQAVRRRGLALRARLMLECANVRELAAAIDADA
HHAAVDHTPEDSGPIPLLPNGSWLYQYGEPRRLAQTEAFRLPEGTTAAQLRTLLRTVVDG
HEVLRTRLDRVTRTLVPHGPRDVLTEAVGVGTLADAVAEQAALSVDRIDPQQGSMLDAVW
LRHPDAPGGVFILTAHVLALDPASWRIVVGELETAWHALASGREPTPVREHTSLRRWSRM
LSERALKLDTVDFWHRQFDGADPDIGARRVDPATDRMRDIAVEMTFADADLTARLLTGGV
PVTEVLAAATARTVTAWRRERGQPTPAPLLALETHGRADAVVSADLGEDPHQVDTGDTAG
LLSMIYPLRVTAGDARGVAELVAAIPGDPIDYGLLRHLREDTAESLGVHRDPQLLLNYLG
RIELDSADHALLQDRSLLSGVTPIPEPDVAVRHELTIMAAVIDRDGSAVLGAQWRTLPDI
LSAAEVGTLQTMWLDALREVVE
>Synechococcus_7942_ClpS1
M------------------------------------------------AVETIQKPETT
TKRKIAPRYRVLLHND--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------DFNPMEYVVMVLMQTVP-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SLTQPQAVDIMMEAHTNGT-------------------GLVITCD----------
------------------------------------------------------------
-----------------------------------IEPAEFYCEQLK-------------
---------------------------------SHGLEQQH
>gnl|BL_ORD_ID|378 @Neisseria_gonorrhoeae_FA_1090@ gi|59800852|ref|YP_207564.1| ATP-dependent Clp protease adaptor protein ClpS [Neisseria gonorrhoeae FA 1090]
MTAQ-------HQSDTLLHRLNTLPPKRY-------------------------GVFLLN
DDYTTMEF-----------------------------------------------VVEIL
---------TE-IFM------LGQEQAVAVMLSVHH------------------------
---------------------------------------EGKGLCGTYT-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------RDIAQTKQQ----
--------------------------QVMQRA----------------------------
------------------------------------------------------------
--------------------------KAEGHPLQCIVEEI
>gnl|BL_ORD_ID|1111 @Neisseria_gonorrhoeae_FA_1090@ gi|59801585|ref|YP_208297.1| DNA polymerase III chi subunit [Neisseria gonorrhoeae FA 1090]
MPKVTFYTHVDQIPLFTCRLIARAIRDGG-------------------------RILVWS
DSFGRLQE-----------------------------------------------LDKML
---------WQYEAE------SFIPHEIWETEEAMP------------------------
---------------------------------------SDTSVLLACD-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--GNLPRIPEGMAVLNLSDGFWNTASVLPA-------RVLEIVGNSLEDLADARERFTAY
RRSG---------------------FAIEHHG----------------------------
------------------------------------------------------------
--------------------------MEGKA---------
>gnl|BL_ORD_ID|374 @Nitratiruptor_SB155_2@ gi|152990128|ref|YP_001355850.1| ATP-dependent Clp protease, adaptor protein ClpS [Nitratiruptor sp. SB155-2]
MG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------EKVETK----EVVKLEEP--
--------KKYK------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----VFLLNDDYTTMDFVVDI--------------------------------------
-------------------LCDIFDKS-YEEAV-----NIMLTIHRQ-------------
------------------------------------GKGLCGIYTYEIAETKIDQVHR--
------------------------------------------------------------
------------------------------------------------------------
----------------LA------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------RAHEFP
LKAVMEEE
>gnl|BL_ORD_ID|1448 @Nitratiruptor_SB155_2@ gi|152991202|ref|YP_001356924.1| fumarylacetoacetate hydrolase family protein [Nitratiruptor sp. SB155-2]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
KIVCVGR-----------------------------------------------------
----------------------------------------NYVEHI----EELNNEMPTE
PVYFLKPQSAITETIHYQEDLHYEGEICFLIGNPIKVGVGLDLTKRALQSRL--------
----------KEKGLPWERAKAFRGSALFSDFVPVKSFEGLRIELFKNG-----------
------------------------------------------------------------
------------------------------------------------------------
-----TLVQSGGVDLMIYKPEF--------------------------------------
-------------------LLQDIEAIFGLEEG-----DILMSGTPK-------------
--------------------------------------GVGAIKTGDIFEAKLWQGDR--
------------------------------------------------------------
------------------------------------------------------------
--------KLIQKIWRTV------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>gnl|BL_ORD_ID|42 @Pelodictyon_phaeoclathratiforme_BU_1@ gi|194335225|ref|YP_002017019.1| ATP-dependent Clp protease adaptor protein ClpS [Pelodictyon phaeoclathratiforme BU-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------NSSLANRWTASLTTPVTKQREQGSGPDLLDAY--
---------------------RVVLFNDEEHTFEEVIEQIIKAVRC-SRQKAEKHTWEVH
TRGRSIVFA----GAMLLCLRVSSILEE--------------------------------
--------------------------------------------------------IALK
TEIQTS------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>gnl|BL_ORD_ID|862 @Pelodictyon_phaeoclathratiforme_BU_1@ gi|194336045|ref|YP_002017839.1| DNA repair protein RadC [Pelodictyon phaeoclathratiforme BU-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------RIHDFDPDNRPRE---RLLRSGAASLSPAELLAIILRTG
TKNLNIVDTCNELIARYSLEKLANITLEELKKVKGIGDAKAMQIVAIFELNKRLHYSRNL
NKKIQAARDVFEYMAGRVPDETKEHLFVLHLNTKNQIIKTELVSVGTLNAALIHPREVFK
SAIKESSHAIILVHNH--------------------------------------------
------------------------------------------------------------
---------------------PSGDVEPSNADKQVTDLLKQASTVIQ-------------
-----------------IDLLDHIIIGKT-GCFSFRESGLL-------------------
------------------------------------------------------------
---------------------------------------------------
>gnl|BL_ORD_ID|1082 @Petrotoga_mobilis_SJ95@ gi|160902574|ref|YP_001568155.1| threonyl/alanyl tRNA synthetase SAD [Petrotoga mobilis SJ95]
MS----EK-----------------------------------------------VKIIN
VIKQG-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------DNYFATIENNPFYPDGKGGQLGDRGKIDIAEVLGTTE-----------------
-TGVILNKHLNPGEYFYEIDKKRRFDIAQQHTGQHILSAAFERIGSLKTVSFKMGEEYST
IDLDGQNIEE--ELLNKAQELSNDIISKCIEVEEIYTDKERAQKYNLRKPLSDKISGEVR
LIKIDDFDISACGGFHVKNTGNI-----NLLKITNTEKVKGNLTRVYFLA----------
-----GLRAINDYSQK--------DSILKNISSILTSGLYDLENKVESLLNENKDYKNRM
K------KLAEKNAYYLAKDLIEKALVVNKNKIVYYKKEDETADFLHKYVDLKDYTLIVE
DEKDKTFSIFSKNINCKELIEKLKTNNNIKGGGSEVRGNISGDIKLEDILKILEK
>gnl|BL_ORD_ID|1577 @Petrotoga_mobilis_SJ95@ gi|160903069|ref|YP_001568650.1| methyl-accepting chemotaxis sensory transducer [Petrotoga mobilis SJ95]
MKGMIVETWMETWKNTYGEDYVNQLLTEIGIPKDKHFSPFEDLEDSKVFKLLDLMSKTTN
KSKEELMKELGKKNIYTFKKYYPNFFRKKGLLSFLSTMNDVHKSLTRRIKGAKPPAIEFE
IIDSNSAYITYRSFRDMRYYFLGLLEGSAEVFGEKIEYEIIDQGNTDQGSFLKIKLKSEK
PYAKIKKARFFTAMSLSLMKMFFTSLTFYTIIIVFLLSWLFTWILGNHWYTFLITGILSG
AFILSMGNYFKRL----FSSSSEGLQNLNNLEYDKPVLLKGEKMLEKHSLEIDNLRSNFN
GIFIQLTGDIEEIETFTE--------------------KVGERAEEMKEISDSIGELVEQ
VAISSEQIAQDAESISNVVEVNVNTIQSIISREDQMVDSLE----NAVKRINDS-SSKVE
ASSKEIENMSERFNNLVKESDKLEEDTKEILKVVDT--VKGIADQTNLLALNAAIEASRA
GEAGRGFAVVADEIRKLAEESKIAASQIDNILSRISSGIQLLTETVEKEFKAMREGANNL
RISSLNNKESATNIKNISKEIHE---ILNELSSEGVKLEDLTKN-TQNLLAISEEGSATA
EEISSSVKTFVNNI--KEILQNIKEVDRFISSLKESLSN--------------KN
>gnl|BL_ORD_ID|2249 @Pseudomonas_stutzeri_A1501@ gi|146282647|ref|YP_001172800.1| ATP-dependent Clp protease adaptor protein ClpS [Pseudomonas stutzeri A1501]
M-----------------------------------------------------------
------------------------------------------------------------
-------------LRNPFALVGTYCLYHRFADSQGD----------------SSAGCEAV
HIYLAPAPRPRTVMRMHAFAQIRLTFNQDRPLEDGDDASGLAVEEAKPQL----------
------------------------------------------------------------
------------------------------------------------------------
---------------------KAPPM--YKVVMFNDDYTPMDFVVEV-------------
--------------------------LEGIFNHSREQ-------ATKIMLAVHT------
------------------------------------------------------------
-----EGQAVCGV-----------------------------------------------
------------------------------------------------------------
--------------------------------------YTRDVAETKAMQVNQYAR--EC
QHPL-------------------------------LCEIEKD------------------
--------G
>gnl|BL_ORD_ID|3141 @Pseudomonas_stutzeri_A1501@ gi|146283540|ref|YP_001173693.1| gamma-carboxygeranoyl-CoA hydratase [Pseudomonas stutzeri A1501]
MT----------------------------------------------------------
------------------------------------------------------------
------DFQTIELNKDARGVA-TLWLNRADKNNAFDAQVIGELN--------AA--LAQV
Q------DDAGIRFLILR-GRGK-HFSAGADLGWMRESAKL-------------------
-DYQANLADAHELGELMQRLYQLPQPTLAVVQGAAFGGALGLIACCDMAIGARDALFCLS
EVRIGLAPAVISPYVVKAIGE---------------------------------------
---------------------R-ATR--RYALTAERFDGTRARELGL------------L
ADTYPASELDAALEQWVA-----NLLLNSPQALKACKDLL--------------------
------------------------------------------------------------
-----------------LEVGDGD------------------------------------
------------------------------------------------------------
--------------------------------------FSADLRQTTEQAIARLRTSPEG
QEGL-------------------------------SAFLEKRTPAWQEK-----------
--------K
>gnl|BL_ORD_ID|6674 @Rhodopirellula_baltica_SH_1@ gi|32477341|ref|NP_870335.1| hypothetical protein RB12137 [Rhodopirellula baltica SH 1]
M-------------------------------------------S---------------
------------------------------------------------------------
--------DHSAA-----------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VAEP
DV-VTEEEQRSDRKPKRQPPYHVILWDDTD------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------HSYDYVI-SMMKRLFRMP--IEKGYQVAKE-----
---------------VDKSGRAICMTTTLELAELKRDQIHAFGK----------------
-----------------------DERLDRCKGS---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------MSATIEPARG
>gnl|BL_ORD_ID|3127 @Rhodopseudomonas_palustris_CGA009@ RPA3148 DUF174
M-----------------------------------------------------------
-------------------------------LQPSLSHSAAGQAGDRINRPLAMAGDGGR
SGPSTPSTSVITKTKP--------------------------------------------
------------------------------------------------------------
----------RTKRPNLYRVLIL-------------------------------------
------------------------------------------------------------
------------------------------------------NDD---------------
------------------------------------------------------------
----------------------------------------------------YTPMEFVV
HVLEKFF-------QMDVEAATKVMLHVHHHGIGECGVFTYEIAETK-------------
-----------------------------------------VTQVMDFARKHQHPLQCVM
EKK---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>gnl|BL_ORD_ID|1197 @Rhodopseudomonas_palustris_CGA009@ RPA1203 conserved hypothetical protein
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------ILV-------------------------------------
------------------------------------------------------------
------------------------------------------NDD---------------
------------------------------------------------------------
----------------------------------------------------YTPREFVV
SVLKGEF-------RMTEDQATKVMLTAHQRGVCVVGVFTKDVAETK-------------
-----------------------------------------ATRATDAGRAKGYPLLFTT
EPEE--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>gnl|BL_ORD_ID|3359 @Rhodopseudomonas_palustris_CGA009@ RPA3380 putative chemotaxis protein cheY3
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------YRIDF-NKLRFLIC-------------------------------------
------------------------------------------------------------
------------------------------------------DDN---------------
------------------------------------------------------------
----PHMRRILRTLLHSFGTREVYEAEDGATALEMYSHYSPDILITDWEMPIFDGLELAQ
MIRQPEA-------KGN-PYAPIIMLTAHSEKRRVTLARDAGVTEFL-------------
-----------------------------------------AKPISSKGLYQR-------
------ILNVVASPRPFIRTRNYFGPDRRRNTTAGYIGP---------------------
------------------------------------------------------------
------------------------------------------------------------
ERRHGGEADIIQQPSLLDKARVNT------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>gnl|BL_ORD_ID|2151 @Rhodospirillum_rubrum_ATCC_11170@ gi|83593445|ref|YP_427197.1| ATP-dependent Clp protease adaptor protein ClpS [Rhodospirillum rubrum ATCC 11170]
M--------NTESQSAKMTTRDHDMAPRLGQGGDDQNDDDRGGQGPGQP-----------
------------------------------------------------------------
-----------------------------GTGVVVKAKPKTKKPSMYRVLM---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------LNDDYTPMEFVVHVLERFFGK-THEEATNIMLHVHQRG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------VGLC
GVYTYEVAE---------------------------------------------------
------------------------------------------------------------
--------------TKVSQVMDLAR-----------------------------------
---RSQHPLQCTLEK-----------------------------------------E
>gnl|BL_ORD_ID|1983 @Rhodospirillum_rubrum_ATCC_11170@ gi|83593277|ref|YP_427029.1| methylglutaconyl-CoA hydratase [Rhodospirillum rubrum ATCC 11170]
M------DLLVET---------------------------------VEPRGV--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------VRLTLNRP-------------------------------
----------------EVRN----------------------------------------
-------------------------------------AFDDRLIAELTEAVLRHGRDPAV
RVIVLAAQGRAFSAGADLGWMRRMADFSRS----------------ENLIDALELARMLQ
VIDLCPKPTVALVQGVA------------------------YGGG-----------VGLV
AACDIALAAEPALFCLSEVRLG----------LIPAV-------------------ISPY
VIRAIGP--RACRRLFLTAETFG-----AQRALGLGLVSDVVAADA-LEGVAAAVIAALL
----AGAP------EAQSEVKDLIRLVENS------------VMDEALLRESAVRIADRR
SSDEAREGMAAFLEKRSPVWMTPDPEGEEARACFH-D-------------------C
>gnl|BL_ORD_ID|3949 @Roseiflexus_castenholzii_DSM_13941@ gi|156743978|ref|YP_001434107.1| ATP-dependent Clp protease adaptor protein ClpS [Roseiflexus castenholzii DSM 13941]
MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------AEVSVPLTTTIPTTEYV-----------------------
------------------------------------------------------------
------------------------------------------------VVTEEEL-----
------------------------------------------------------------
------------------------------------ERPYRVIIENDDV-----------
-----TPM----------DFVVLVLL-TIFELGFEQSVAIMLEAHHNGRAHV--VTLPYE
EAQRRVYEAHHA--------------------------------------AREAGYPLSF
Y--------LEPDA
>gnl|BL_ORD_ID|2854 @Roseiflexus_castenholzii_DSM_13941@ gi|156742883|ref|YP_001433012.1| aldehyde dehydrogenase [Roseiflexus castenholzii DSM 13941]
MKHTMIAPGLEWSSLLERAKALVPEAFDEDGNPLNLIHGEWGFPGHPKPFLSPVDGTMLG
NYPMIDLDT---------------------------------------------------
----------------ARHAVAAAASEFGAWSTTDLSERQQRVDACVHLLRQHRELIGRL
LMWEIGKPYAQAM----------------TDVDRCISGVEWYVEQIPSMMEG--------
--RKPLGLISNIASWNYPLSVLVHAMLVQMLAGNPVI------------AKTPSD-----
-GGLFALTVAIALARRCGLPVSLVSGSGGRLSEALVRGSEVACLAFVGGKTNGRDIAASL
YDREKRYMLEMEGINAYGIWQFSRWDALATQLRRGFDYGKQRCTAYVRLVVQRQLFPQ--
----------FLDMYLPVLKSLRIGNPTLVDHPDAPPPTLDFGPLINGRKVDELQVWISE
AIGGGAVSLYQGTLRDEDFLPHQDISAYMAPVALLNVPRNARLYHNEPF-----------
-----GPV----------DTIVVV----------DSVEELITEMNISNGCLVASVACDNE
HLAQQIAAEVRAFKVGINTIRSRGDRDEVFGGIGQSWKGCFVGGKYLVQAVTIGPPGERL
YGNFPDYTLLPEER
>gnl|BL_ORD_ID|999 @Rubrobacter_xylanophilus_DSM_9941@ gi|108803856|ref|YP_643793.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-VGSLTRDIRCSAAT----KTAPARKTRRAPS-----------REPRYRVI---------
-----------LHNDDWTPMDHVVAA---LMKVVPRLSLRRAVSIMLEAHTKGQAVVTRC
HREL----------------------------------------------AELYREGL--
------------------------------------------------------------
-----------------KAEG-----------LISTIEPD--------------G
>gnl|BL_ORD_ID|2018 @Rubrobacter_xylanophilus_DSM_9941@ gi|108804875|ref|YP_644812.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------GAAT------RPKRRSREKSG-----------GLPPYNVV---------
-----------LLDDDDHSYEYVIFM---LRKLF-GYPVRKGYELAREVDTTGRAVVATT
HLEE----------------------------------------------AELKRDQI--
------------------------------------------------------------
-----------------QSFGPDPLIPRCKGSMRAVVEPAP-------------G
>gnl|BL_ORD_ID|414 Streptococcus_thermophilus_CNRZ1066 gi|55822408|ref|YP_140849.1| ABC transporter ATP binding protein [Streptococcus thermophilus CNRZ1066]
MFKIFKRLTAKELSM---------------------------------IVLAVIFVCLNV
YLNLKIPDYMSDIITLLSTKGTKASDIFAWNTDAPGMRMLLMSFAGFMASVVVSFLAART
ASSFTTR-----------------------------------------------------
-----------------LRDDIFHQVLDFSDAEIKKFSIPSLLTRTTNDITQLQMALTMG
LQVITQGPIMAIWAITKIADKNGNWLLALLVAVAVIAILMLFLLIMVMPKQRLIQTLTDK
LNSVTRESLTGIRVVRAYNAESYQEDKFEKANTDLTQNNLFIGRSFALLTPVMTAVSSGL
TLAIYWIGAHLIEDVKIPTDPTKIAGAMEDKVHLFSDMVVYSSYAMQVVMGFMMMMVVFF
LLPRAVVAAGRINEVLDTQSSVSYPEYSSEKPKEV------------GTVEFEDVSFRYS
ETSEPVLEHVSFKAKKGDTVALIGSTG---SGKSTLVNLIPRFYDATQGTIKVDGVDVRY
YDHETLHNIVGYIPQK--AVLFSGDITSNMTMGTS----------------------NNS
PLDDAKIWEALELAQGKDFVENKEGQLKAEVAQAGSNFSGGQKQRLAIARALARKPEILI
FDDSFSALDYKTDRKLRQELAEKTQDMTKLIVAQRISTIMDA--D---------------
--QILVLDKGKVVGQGTHEELLANNEV-----YQEIAYSQL------S----------KE
ELED----------------------------GK--------------------------
------------------------------------------------------------
-----------------------------------------------------------
>gnl|BL_ORD_ID|5165 Streptomyces_avermitilis_MA_4680 gi|29831702|ref|NP_826336.1| ATP-dependent Clp protease adaptor protein ClpS [Streptomyces avermitilis MA-4680]
MGR---------------------------------------------------------
------------------------------------------------------------
-----------------------------VTAPAPLEIEKTESAEEVFAVPEPDVPWVTI
VHNDPVNLMSY-------------------------------------------------
------------------------------------------------------------
------------------------------------------------VTYVFQT-----
------------------------------------------------------------
------------------------------YFGYSKDKAT--------------------
------------------------------------------------------------
------------------------------------------------------------
---KLMLDVHHKGRAVVSSGTREEMERDVQAMHGYGLWATL-------------------
------------------------------------------------------------
---------QQDR------K
>gnl|BL_ORD_ID|886 Streptomyces_avermitilis_MA_4680 gi|29827424|ref|NP_822058.1| hypothetical protein SAV_883 [Streptomyces avermitilis MA-4680]
MIIVTG------------------------------------------------------
------------------------------------------------------------
--------ATGKLGRRIVERLLERV-------PADRVGVSVRDPRKAQDLADRGVR-VRQ
GSFDDPASLVHAFEGAEQLLLVSLDRTGQECVSGHRAAIDAAVKAGVGRILYTSQMGAAH
------------------------------------------------------------
----------DSRFQACRDHAQTEDLLRATGLPW---TALRNGFYASSALQFLESARHTG
DIALPADG-----------------------PVAWTGHDDL---------AEATAAILAE
EHRFEGP-----------------------TPPLTGPAAL--------------------
------------------------------------------------------------
------------------------------------------------------------
-DFDTVAEIASQTTGRPFTRTVVPDDAFREQVLAHGAPAPI-------------------
---------------------------------GNLMLSIFAAARNGEFTAVDSTLAELI
GREPATFRTQLEH---AWAE
>gnl|BL_ORD_ID|457 @Sulfurimonas_denitrificans_DSM_1251@ gi|78776659|ref|YP_392974.1| ATP-dependent Clp protease adaptor protein ClpS [Sulfurimonas denitrificans DSM 1251]
MA--------------------------------------------------TNIDLET-
------------------------KEKVKIKYPKKYKVLLLNDDYTSMEFV---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------ID
ILITIF----------------------------------------------------HK
NYEQAHQIMLEIHKKTKGIC----------------------------------------
----------------------------GIYTYEIAETKVMQVHKKAR------------
----------------------------------------------DNGFALRATMEEE-
------------------------------------------------------------
---------------------------------------------
>gnl|BL_ORD_ID|417 @Sulfurimonas_denitrificans_DSM_1251@ gi|78776619|ref|YP_392934.1| excinuclease ABC subunit C [Sulfurimonas denitrificans DSM 1251]
MTLRECIKQLPDSAGVYQYFDKDGHLLYIGKAKSLAKRVKSYFNFAPKFKPNSNLSSRIS
KMISQTHTLQYIVVNS-EHDALILENSLIKQLMPKYNILLRDDKTYPYIYIDNSQKYPRF
EMTRKIIKSSNIKYYGPFSVGARDILDSIYELCALVQKKGSLTSKKLCLYHQINRCLGPC
ELHVSDEDYQRELDLAKELILNKKILIKKLQEKMFYYADNLRFEEATALR----------
--------------DRCERISRSEIKSEIDFASSENYDIFVIASSQSRAVVVRIFMREGK
IISSSHDYIQLHEGYDEDE-------LYQRAIMGFYSHGKPPIIAPILVASEFEGKDSIE
EFLSTLFEKKADIKVPKTAKRKQLIDLA--LLNAAELLKNETKENQSGILDEIKKLFSLQ
RVPSRVETFDNSHMSGVATVGAMSVYENGAFDKKSYRIYHLEARDEYAQMREMLLRRVES
FLKNPPPDLWILDGGSTLLNLALSILESSGVNIDVIAIAKEKVDAKAH------------
------------------------RAKGKAKDIIYSREDIFKLLDSDKRLHFVQKLRDEA
HRCAINFHKKTKLKSDNESKLLTLKGISQAKIIKLLKHFTTFDAIKEASVEELSTVLNLK
DANIIKSSY-----------------------------------I
>Synechococcus_7942_ClpS1
MAV---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMV------
------------------LMQTVPSLTQ---PQAVDIMMEAHTNGT--------------
--------GLVITCDIEPAEFYCEQLKSH-------------------------------
---------------GLEQQ----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------H
>Synechococcus_7942_ClpS1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------AVETIQKPETTT
KRKIAPRYRVLL------------------------------------------------
--------------------------------------------------------HNDD
FNPMEYVVMVLMQTVPSLTQ--PQAVDIMM------------------------------
-----------------------EAHTNGTGLVITCDIEPAEFYC---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------EQLKSHGLEQQ--------------------------------------
----------------------------------------H
>Synechococcus_7942_ClpS1
M----------------AVETIQKPE----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
TTKRKIAPRYRVLLHNDDFNPM--------------------------------------
------------------------------------------------------------
--------------------------------------------------EYVVMVLMQT
VP------------SLTQPQAVDIMMEAHTNGTGLVITCDIEPAEFYCEQ----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------LKSHG-------------------------------------------------
-------LEQQH------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>Synechococcus_7942_ClpS1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------AVETIQKPETTT
KRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSL------TQPQAVDIMMEAHTNGTGLV
ITCDIEPAEFYCEQLKSH------------------------------------------
------------------------------------------------------------
-----------------------------------GLEQQH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|2106 @Treponema_denticola_ATCC_35405@ gi|42527626|ref|NP_972724.1| hypothetical protein TDE2123 [Treponema denticola ATCC 35405]
ME----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------LKKQAQKGTIISEKFI--EPEN
YRVILLNDDFTPMDF------------------------------VVAVLI---------
-SIFNKSQEEAETL-MFKVHKTGQASV--GIY----------------------------
---------------------------VYDIAT-----------TKCFQV----------
--------LTAAKNNN--------FPLQCKVE----KV
>Synechococcus_7942_ClpS1
M-------------------------AVETIQKPETTTKRKIAP--------RYRVLLHN
DDFNPMEYVVMVLMQT--------------------------------------------
-------------------------------VPSLTQPQAVDIMMEAHT-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------NGTGLVITCDIEPAEFY---------CEQ
LKSH---------GLEQQH-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-
