>gnl|BL_ORD_ID|11271 @Ciona_intestinalis@ jgi|Cioin2|293833|estExt_fgenesh3_pg.C_chr_14p0166
MSID--------------------------------AGSHQILAKVYYSGHAFSLHLEHT
IQMEELFTMVRLNCNFPDAQVFTLKWMDDEGDPCTISSQLELSEALRLYRHNNETVLLFH
IFLGIPVEPGLLCPGEH-------------------------------------------
-----------------------------KLYRHGARRWYKLKRILRQI-----------
------------------------------------------------------------
--KKPKHPRIPIESGPILDSGDSQDSKASSDQASPNAPGFGLKDF---EMLKVIGRGSYA
KVLLVKLKSTDKMYAM---KVIKKELVTDEEDIDWVQTEKH----------VFETASNYP
FLVGL----HSCFQTPERLF---FVIEYVNGGDLMFHMQRQRKLPEEHARFYAAEIVLAL
H-------FLHEKG-------IIYRDLKLDNVLLDSDGHIKLTDYGMCKEGIRKGVNTST
FCGTPNYIAPEILRGEDYDFSVDWWALGVLMFEMMAGRSPFDIVGMTDNPEQNTEDYLFQ
VILEKVIRIPRSLSVKASS----VL---KGFLNKIPVDRLGCN-----------------
-------------HESGFQDILDHQFFRTIDWD---------------------------
------LLQSRQVVP---PYKPNIEDDLGLDNFDKQ--FTQEPV-QLTP--TEATVI---
-----------------GKIDQADFE-------GFEYI-----------------NPLLM
TSDV---AV
