>gnl|BL_ORD_ID|8679 @Drosophila_melanogaster@ gi|21358013|ref|NP_651658.1| cleavage and polyadenylation specificity factor 100, isoform A [Drosophila melanogaster]
MTSIIKLHTISGAMDESPPCYILQIDDVRILLDCGWDEKFDANFIKELKRQVHTLDAVLL
SHPDAYHLGALPYLVGKLGLNCPIYATIPVFKMGQMFMYDLYMSHFNMGDFDLFSLDDVD
TAFEKITQLKYNQTVSLKDKGYGISITPLNAGHMIGGTIWKIVKVGEEDIVYATDFNHKK
ERHLSGCELDRLQRPSLLITDAYNAQYQQARRRARDEKLMTNILQTVRNNGNVLIAVDTA
GRVLELAHMLDQLWKNKESGLMAYSLALLNNVSYNVIEFAKSQIEWMSDKLT-KAFEGAR
NNPFQFKHIQLCHSLADVYKLPAGPKVVLASTPDLESGFT---------RDLFV------
---QWASNANNSIILTTRTSP------GTLAMEL--VENCAPG-----KQIELDVRR---
-----RVDLEGAEL--EEYLRTQGEKLNPLIVKP----------------------DVEE
ESSSESEDDIEMS------------VITGKHDIVVRPE---GRHHSGFFKSNKRHHVMFP
YH--------EEKVKCDE-------------------YGEIINLDDYRIADATGYEFVPM
EEQNKENVKKEEPGIGAEQQANGGIVDNDVQLLEKPTKLISQ-RKTIEVNAQVQRIDFEG
RSDGESMLKILSQLRPRRVI--VIHGTAEG--------------TQVVARHCEQNVGARV
----FTPQKGEIIDVTS---EIHIYQVRLTEGLVSQLQFQKGKD--AEVAWVDGRLGMRV
KAIEAPMDVTVEQDASVQEGKTLTLETLADD-EIPIHNSVLINELKLSDFKQTLMRNNIN
SEFSGGVLWCSNGTLALRRVDAGKVAMEGCLSEEYYKI----------------------
--RELLYEQYAIV
