>gnl|BL_ORD_ID|1223 @Saccharomyces_cerevisae@ gi|6320546|ref|NP_010626.1| Fcf1p [Saccharomyces cerevisiae S288c]
MGKAKKTRKFGLVKRTLNTKKDQRLKKNQENIKTK-------------------EDPELT
RNIPQVSSALFFQYNQAIKPPYQVLIDTNFIN---FSIQKKVDIVRGMMDCLLAKCNPLI
TDCVMAELEKLGPKYRIALKLARDPRIKRLSCSHKGTYADDCLVHRVLQHKCYIVATND-
-----------------AGLKQRIRKIPGIPLMSVGGHAYVIEKLPDVF
