>Escherichia_coli_UTI89_gnl|BL_ORD_ID|1000 Escherichia_coli_UTI89 gi|91209918|ref|YP_539904.1| ATP-dependent Clp protease adaptor protein ClpS [Escherichia coli UTI89]
M-----------------------------------------------------------
------------GKTNDWLDFDQLAE----------------------------------
------------------------------------------------------------
-----------EKVRDALKPPSMYKVILVNDDY-------------TPMEFVIDVLQK--
----------------FFSYDVERATQL--------------------------------
--------------------------MLAVHYQGKAICG---------------------
------------VFTAEVAETKV----------AMVNKYARENEHPLLCTLEKA------
--------------------------------------------------------
>Escherichia_coli_UTI89_gnl|BL_ORD_ID|3362 Escherichia_coli_UTI89 gi|91212298|ref|YP_542284.1| hypothetical protein UTI89_C3305 [Escherichia coli UTI89]
M---KFKVIALAALMGISGMAAQANELPDGPHIVTSGTASVDAVPDIATLAIEVNVAAKD
AATAKKQADERVAQYISFLELNQIAK--KDISSANLRTQPDYDYQDGKSILKGYRAVRTV
EVTLRQLDK-----LNSLLDGALKAGLNEIRS--------VSLGVAQPDAYKDKARKAAI
DNAIHQAQELANGFHRKLGP--VYSVRYHVSNY-------------QPSPMVRMMKAD--
------------------------------------------------------------
------------------------------------------------------------
------------AAPVSAQETYEQAAIQFDDQVDVIFQLE-PVDQPPAKTPAAH------
--------------------------------------------------------
>Streptococcus_thermophilus_CNRZ1066_gnl|BL_ORD_ID|414 Streptococcus_thermophilus_CNRZ1066 gi|55822408|ref|YP_140849.1| ABC transporter ATP binding protein [Streptococcus thermophilus CNRZ1066]
MFKIFKRLTAKELSMIVLAVIFVCLNVYLNLKIPDYMSDIITLLSTKGTKASDIFAWNTD
APGMRMLLMSFAGFMASVVVSFLAARTASSFTTRLRDDIFHQVLDFSDAE----------
------------------------------------------------------------
------------------------------------------------------------
------IKKFSIPSLLTRTTNDITQLQMALTMGLQ---VITQGPIMAIWAITKI------
-ADKNGNWLLALLVAVAVIAILMLFLLIMVMPKQRLIQTLTDKLNSVTRESLTGIRVVRA
YNAESYQEDKFEKANTDLTQNNLFIGRSFALLTPVMTAVSSGLTLAIYWIGAH-------
----------------LIEDVKIPTDPTKIAGAMEDKVHLFSDMVVYSS------YAMQV
VMGFMMMMVVFFLLPRAV----VAAGRINEVLDTQSSVSYPEYSSEKPKEVGTVEFED--
----------VSFRYSETSEPVLEHVSFKAKKGDTVALIGSTGSGKSTLVNLIPRFYDAT
QGTIKVDGVDVRYYDHETLHNIVGYIPQKAVLFSGDITSNMTMGTSNNSPLDDAKIWEAL
ELAQGKDFVENKEGQLKAEVAQAGSNFSGGQKQRLAIARALARKPEILIF-----DDSFS
ALDYKTDRKLRQELAEKTQDMTKLIVAQRISTIMDADQILVLDKGKVVGQGTH--EEL--
-----------------------------LANNEVYQEIAY-------------------
-------------SQLSKEELED-------------------------------------
----------------------GK
>Streptococcus_thermophilus_CNRZ1066_gnl|BL_ORD_ID|1263 Streptococcus_thermophilus_CNRZ1066 gi|55823257|ref|YP_141698.1| bifunctional methionine sulfoxide reductase A/B protein [Streptococcus thermophilus CNRZ1066]
MRNIPKSVTLKAWRCKYLVKG---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VLKMSNPNNHVIYLAGGCFW---GVEEYFSRVPGVLDAVSGYANG
SSETTRYELISQTGHAETV-------------------------QVTYDAGKVTLREILL
HFFRIINPLSKNKQGNDV---------GTQYRTGVYYTDVNDLPIIEKVFQEMSEQYGQP
LAVELLPLQHFIPAEEYHQDYLKKNPNGYCHINVNQAVNPVIDSSSYHKPSQEELKVSLS
PEAYA----------------------VTQENRTERAFTSPLWNHFEPGIYVDVVTGE--
----------PLFSSRDKFYSACGWPSFSRPI----------------------------
------------------------------------------------------------
-------------------------------------------SPEVANY-----KEDHS
---------------------HNMDRIEVRSRVGDSHLGHVFPDGPSDKGGLRYCING--
-----------------------------VATRFVPKADME-------------------
-------------KEGYAYLLDQ-------------------------------------
----------------------VD
>Streptomyces_avermitilis_MA_4680_gnl|BL_ORD_ID|5165 Streptomyces_avermitilis_MA_4680 gi|29831702|ref|NP_826336.1| ATP-dependent Clp protease adaptor protein ClpS [Streptomyces avermitilis MA-4680]
MGR---------------------------------------------------------
------------------------------------------------------------
-----------------------------VTAPAPLEIEKTESAEEVFAVPEPDVPWVTI
VHNDPVNLMSY-------------------------------------------------
------------------------------------------------------------
------------------------------------------------VTYVFQT-----
------------------------------------------------------------
------------------------------YFGYSKDKAT--------------------
------------------------------------------------------------
------------------------------------------------------------
---KLMLDVHHKGRAVVSSGTREEMERDVQAMHGYGLWATL-------------------
------------------------------------------------------------
---------QQDR------K
>Escherichia_coli_UTI89_gnl|BL_ORD_ID|2943 Escherichia_coli_UTI89 gi|91211873|ref|YP_541859.1| hypothetical protein UTI89_C2868 [Escherichia coli UTI89]
MRDYSAKTLPDCSIHCHKSFNSVCLVNIEGTMTPVKVWQERVEIPTYETGPQDIHPMFLE
NRVYQGSSGAVYPYGVTDTLSEQKTLKSWQAVWLENDYIKVMILPELGGRVHRAWDKVKQ
RDFVYHNEVIKPALVGLLGPWISGGIEFNWPQHHRP-----------TTFMPV-------
----------DFTLEAHDDGAQTVWVG---ETEPMHGLQVMTGFTLRPDRAALEIASRVY
NGNATPRHFLWWANPAVKGGEGHQSVFPPDVTAVFDHGKRAVSAFPIATGTYYKVDYSAG
VDISRYKNVPVPTSYMAEKSQYDFVGAWCHDEDGGLLHVANHHIAPGKKQWSWGHSEFGQ
AWDKSLTDNNGPYIELMTGIFADNQPDFTWLDAYEEKRFEQYFLPYHSLGMVQNASRDAV
IKLQRSERGIEWGLYAISPLNGYRLAIREIGKCNALLDDAVALTPATAIQGVLHGINPER
LTIELSDADGNIVLSYHEHQSQALPLPDVAKAPLAAQDITSTDEAWFIGQHLEQYHHASR
SPFDYYLRGVALDPLDYRCNLALAMLEYNRADFPQAVAYATQALKRAHALNKNPQCGQAS
LIRASAYERQGQYQQAEEDFWRAVWSGNSKAGGYYGLARLAARNGNFDAGLDFCQQSLRA
CPTNQEVLCLHNLLLVLSGRQDNARLQREKLLRDYPLNATLWWLNWFDGRSESALVQWRG
LCQGRDVNALMTAGQLINWGMPALAADMLNALDCQRTLPLYLQASLLPKAERGELVVKAI
DAFPQFVRFPNTLEEVAALESIEECWFARHLLACFYYNKRSYGKAIALWQRCVEMSPEFA
DGWRGLAIHAWNKQHDYELAARYLDNAYQLAPQDARLLFERDLLDKLSGVTPEKRLARLE
NNLEIALKRDDMTAELLNLWHLTGQADKAADILATRKFHPWEGGEGKVTSQFILNQLLRA
WQHLDAREPQQASELLHAALHYPENLSEGRLPGQTDNDIWFWQAVCANAQGDETEAMRCL
RLAATGDRTINIHSYYNDQPVDYLFWQGMALRLLGEQHTAQQLFSEMKQWAKEMAKTSIE
ADFFAVSQPDLLSLYSDLQQQHKEKCLMVAMLAAAGLGEVAHYESARAELMAINPAWPKA
ALFTTVMPFIFSYVH
>Streptococcus_thermophilus_CNRZ1066_gnl|BL_ORD_ID|351 Streptococcus_thermophilus_CNRZ1066 gi|55822345|ref|YP_140786.1| late competence protein required for DNA uptake [Streptococcus thermophilus CNRZ1066]
MIPKE--------------------------YYG--------------------------
------------------------------------------------------------
------------------------------------------------------------
RLFTKEQLPV---DYLSEAVKLESMI--KVDKKLRCKRC--------YSRIEEDWQLPNG
QYYCRACIVFGRNQEGKELYYFPSEKSEVDFPVLKWSGKLTPYQ--NEVSEKLLKTYK-N
QKHSLVHAV-TGAGKTEMIYNIVAYVLENKNRVVIASPRVDVCRELFLRMQKD-------
----FTCSISLL--------HADSEPYDGSPLVIATTHQLLKFYHSFDLIIVDEVDAFPF
VGNVMLNHAVKQAKTETGRYIYLTA-----------------TSTLALEEQVRLGAIEKY
HLASRFHGNPLVLPRFFWQGRLQKSLTSEKLPRPLIHQIKKQ-----RKSNFPLLIFFPN
IALGEKFSITLKKYLPTENIAFVSSKSEERSTIVEKFRKKELSILVTTTILERGVTFPQV
DVFVCMAN--------HYLYTSSSLIQIGGRVGRSPERPTGKLYFFHEGLSK--------
----------------SMLQCREEINAM--------------NKKGGFENEVSTM
>Streptomyces_avermitilis_MA_4680_gnl|BL_ORD_ID|5165 Streptomyces_avermitilis_MA_4680 gi|29831702|ref|NP_826336.1| ATP-dependent Clp protease adaptor protein ClpS [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GRVTAPAPLE--------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------IEKTESAEEVFAV-PEPDV
PW----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VTIV----------HNDPVNLMS-----
YVTYVFQ-----TYF-GYSKDKATKLMLDVHHKGRAVVSSGTR-----------------
-------EEMERDVQAMHGYG-LWATLQQD-----------------RK
>Streptomyces_avermitilis_MA_4680_gnl|BL_ORD_ID|7507 Streptomyces_avermitilis_MA_4680 gi|29834043|ref|NP_828677.1| ABC transporter ATP-binding protein [Streptomyces avermitilis MA-4680]
MRGHS----RMKTPSGHGAAPDGTGAAD-----EAAARTLLR---SAARHSRSRCVALCL
TTAAASG----------------ASLLLPAALGRALDLLLTRPGDAAGTHWVLWCTGLVL
LIALLDACHT----VLAGTTDARATAWLRQRLVGHVLAVGPRAGERFG-----PGELVAR
L------VGN-----AAQAGTAPATAATLLAA-----LAGPVGAVVALGLIDPLL-----
------------AAVFLGGAPVLTLLLRAFARDSSQCVARYQDVQGRIAGALAEAIGGAR
TIAAGGTADKEVARILRPLPELSREGRRMWRVQGRAAAQAVAVA-PLLQL-------GVV
AVGGVLLVHHRLSVGELLAASRYA-VLATGVGVLVGQLSGLIRARAAARRLGEVLTEPAP
VYGTRQLPPGEG-----RLELRSVTV-RRGGRTVLDGVDLVVPAGRTVAV----------
--VGRSGSGKSLLAALAGRLADPDDGHVLLDGV--PLRDLDRTALRRAVGHAFERPALLG
DTIEDTIAFGIP------------------------SPPPDRVRQAAATARADSFVRRLP
DGYATPCAEA--PLSGGECQRLGLARAFAHDSRLLV----------LDDALSSLDTVTER
HITEALL-----RHTPGSSRLIIAHRVSTAARADAVVWLAAGR-----------------
-------VRAVGTH----------AELWRSAAYREVFGSSGTERNGGAG
