>gnl|BL_ORD_ID|33124 @Aquilegia_coerulea@_026_00244.1|PACid:22056235
METAICGRVSLSPNHVF---NNHKPGDKHAIYRGPCTNRGILMTISAAGP--GKGGGLLD
RPTIEK----TTPGRESGFDV-----RKSRKMSPPYRVMLHNDNYNKREYVVQVLMKVIP
GMTVDNAVNIMQEAHINDLAVVIICAQADAEEHCTQLRGNGLLSSIEPASG-GC
