>gnl|BL_ORD_ID|27119 @Cyanophora_paradoxa@_ConsensusfromContig53754-maker-ConsensusfromContig53754-snap-gene-0.1-mRNA-1:cds:10842/945-1043:2:-
MAFCSAVPLRA-------------------------------------------------
-----------------------------GRVVGSVL---------------------QA
-----------------------------------------------------TPSACFQ
PAEPAPV-----------------------------------------------------
------------------SSVSSRRSTFFAGE----------------------------
-------------------------------------------------IDVGVHVDARS
TA-----------DSSPATRRFVAATVVP-P--------TSAV-----------------
--------------VLKPAP----------------------------------------
-KIAKTGLQTDTASAKPEVETGGDG-----------------------AKSKERENEEEF
MGKW----KVLLHNDEANTMEYVIKAIRTVVPNISHQEAVNIMLEAHTTG-VVVIVCEKE
HA--------EYYCEGLKGYQLWSSIEPED-----V
>gnl|BL_ORD_ID|11994 @Cyanophora_paradoxa@_ConsensusfromContig55759-snap_masked-ConsensusfromContig55759-abinit-gene-0.0-mRNA-1:cds:11871/189-261:0:+
MP----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------QSSLLRSAVRTDSEHA
SAFLRNLLASP-------------------------------------------------
------------------APAAAGGG----------------------------------
------------------------------------------------------------
-------------TVASRLRQALERGLPPAA--------ESLA-----------------
--------------AFLSDA----------------------------------------
-AFDAAQRQT-----AREEEEGGSG-----------------------------------
-------------------------------ADAAAQRAADRLLYDAARAAVLELL----
-----------------------------------I
>gnl|BL_ORD_ID|9183 @Cyanophora_paradoxa@_ConsensusfromContig43066-snap_masked-ConsensusfromContig43066-abinit-gene-0.0-mRNA-1:cds:9624/33-108:0:+
AS----------------------------------------------------------
SEPIAVVELATGAVLFANSAWLPFEVLGTGRGGAALHARC--------------------
-----------------------------------------------------RAEFTGE
TLFLVLEDVRALR-----------------------------------------------
------------------SAEEESRS----------------------------------
------------------------------------------------------------
--------KSRFLSISHEIRTPLWGIL------------SSAG-----------------
--------------LLLERP----------------------------------------
-ALDEEARDL-----AETIQTSGDA-----------------------------------
----------------------------------LLALVNDVLDYSRAEADALALDPRPF
DLLELLDASATLVASRLGPRHRARIIGNLL-----A
>gnl|BL_ORD_ID|31414 @Cyanophora_paradoxa@_ConsensusfromContig9027-snap_masked-ConsensusfromContig9027-abinit-gene-0.1-mRNA-1:cds:2416/10656-10815:0:-
HS--------------------------------------ATERCTADPGKAGLLLDLYV
DGSLKVSRRLFQAEGIPFGTWHHVAITLTDTLVVAYLDGVETTPVSDSLAASAFPKLQRA
KHWLGHGRLEDLFFRAVGGASSLFFWGNGWSDYVSITPFILGTPFSSFWIKPRKQQAVWA
SVFPSTL-----------------------------------------------------
------------------STAKASRS----------------------------------
---------------------------------------------------DVLSVDRRI
FE-----------FGSEADQSKIAVGFLPPG-----------------------------
--------------AVVSDPTTNSQITG--------------------------------
-SASAGKMSL-----VVVAYDGGTAV----------------------TSFEAFGGANS-
----------LPVNDFVSG------------ADIPCELAVDCAL----------------
-----------------------------------L
>gnl|BL_ORD_ID|9176 @Cyanophora_paradoxa@_ConsensusfromContig43027-snap_masked-ConsensusfromContig43027-abinit-gene-0.0-mRNA-1:cds:9903/446-551:0:+
MG----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------S
LLSPAAS-----------------------------------------------------
------------------GPVPEGRG----------------------------------
-----------------------------------------------------VLVAQR-
--------------LEAVDEAAVGQLFVPYAVRVRLEQFSSNG-----------------
--------------FLLKRG----------------------------------------
-TWDQANYLM--------------G-----------------------------------
------------------------------------------------------------
-----------------------------------E
