>gnl|BL_ORD_ID|27381 @Mimulus_guttatus@_mgv1a012902m|PACid:17696785
METAAPFQSSFTHPPLNGSTRPNPSRVGSNSILSGAWLQQRLSISGVNLGNSRVGF---T
STKKLSIRVRIAEVKANERRKTLEEILYALVVQKFMDADVALVPNIASGEDRYRVDNQWA
IIGGVGKGGGVLDKPV---IEKT-------NQNPGRESEFDLRKSRKMSPPYRVMLHNDN
FNKREYVVQVLMKVI-------PGMTVDNAVNIMQEAHINGLAVVIICAQPDAEEHCTQL
RGNGLLSS-------------------------IEPA-------------SG-G------
---------------------------C
>gnl|BL_ORD_ID|23053 @Mimulus_guttatus@_mgv1a025350m|PACid:17692454
ITIYY--------------------------------------------------F----
-----------AKEETNRRV-------------------VPLFPETYV------------
--------------PIKVPFRKG------LHQE--------FRQPSGTGIDFRFFPMEDL
SHSPSRYE-VFPIVVSADTCPTPYIIDERSYLLSHTFRQMQITQVIVGKNHEAQFTAK-V
IRQLLWTGDVCYELREIYGLGKSGPGKDCVVCMTEPKDIALLPCRHMCMCSGCAKALRLQ
SNKCPICRETIEAVLEIKIDTMDFSHKP
