>gnl|BL_ORD_ID|29390 @Phaseolus_vulgaris@_091014468m|PACid:23560356
M----EAALSTALALSPNQVFNAVNPGDKNFGLKYCK----DRTVVVTMAATGILGKGGG
LAERPTIEKT---------TPGRESEFDLRKSRKTSPPFRVLLHNDNFNKREYVVQVLMK
VIPGMTIDNAVNIMQEAHHNGLAVVIICAQVDAEDHCMQLRGSGLLSSIEPADGGGC
>gnl|BL_ORD_ID|27534 @Phaseolus_vulgaris@_091022870m|PACid:23558459
M----KSAICGRI-LSPNHVF---KPGDTP---SFCKGPYSNLCVPMAVVATG-PGKGGG
LLEKPVIERV---------TPGRESEFDLKKSRKTAPPYRVILHNDNYNKREYVVQVLMK
VIPGMTLDNAVNIMQEAHHNGLSVVIICAQSDAEDHCMQLRGNGLLSSIEPADGG-C
>Oryza_sativa_gnl_BL_ORD_ID_22109
MAISSRAAACGAL-IFPTTASAAPVSRSVSVDQRVSH----RRRKAVAVAAVPHASSGGA
LLERPAFDQSQLDTLPVTQEGGDTGRMRDRRGSGSGDSYKVLLIDDARHTEKLVEKALPQ
VVPSVTAEAARQLFHASRQKGAALVIVAVKEHAEFYAQMMVRQGLRSAIEPESDLAS
