>gnl|BL_ORD_ID|14527 @Selaginella_moellendorffii@_69252|PACid:15415805
GL----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GGGVLD--------------------------------
---------KPAI--------ETAPTPGRESEFDLRKKKKM-------------------
-----------------APPYRVILHN---------DNFNRREYVVQ-------------
----------------------------------------------------VLMKVIPG
MTLDNAVNIMQEAHHN------------GLSVVIVCSQEDA-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
EEHCTQLRANGLLSSI--EPAS--GG----------------------------------
------------------------------------------------------------
-------------
>gnl|BL_ORD_ID|7580 @Selaginella_moellendorffii@_403693|PACid:15408858
MR----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------RIMDKTHNIRNLSVIAHVDHGKSTLTDSLVAAAGFISLDNA
GNVRMTDTRKDEVD-RGITIKSTGISLLYTMPDAALKDFRGSRDGNEYLINL--------
----------VDSPGHVDFSSEVTAALRITDGALVVVDCVEGVCVQTETVLRQALGERIK
PV----LVVNKMDRCFLELQLDGEEAYQTFQRV--------IENANVILSTYED-----K
LLGDVQVYPERGTVGFGAG------LHGWGFTLTTFAKMYASKFKVDEKKMVEKLWGEN-
-------------------------------------------YFDPATKKWTTRNTGSP
TCTRGFVQFIYNPIKQIIDIAVNDQMDKLLPMLQKLNVTLKGEDKQKSGKALMKRVMQLW
LPASDALLEMIIYHLPSPVVAQKYRVENLYEGPLDD---KYAAAIRNCDPKGPLMVYVSK
MIPANDNGRFYAFGRVFSGTVATGMKVRIMGPA---------------------------
-----------------------------------YVPGGKTDLYVRSVQRTHIW-----
----------------------------MGKKQETVDDVPCGNNAAMVGLDQFIVKNATL
TNESEVDAHPIRAM--------KFSVSPVVRVAVQCENAADLPKLAEGLKRLAKSDPMVQ
CSIDESGE-------------HIVAGAGELHLEICLKDLQS-------------------
----EFMQTAIKVSDPVVSFRETVLERSRQVMSKSPNKHNRLYFEARPLEDGLADAIDEG
RIGPRDDPKLRSKIMAEEFSWDKDQARKIWSFGPETSGPNLVVDACKGVQ--YLNEIKDS
VV--AAFQIV----SKEGAIAGESMRGIGFEVCDVVLHSDAIHR----GGGQIMPTARRV
MYAAQLCANPRLL------------------EPVYLVEIQAPEAALGGIYSVLNQKRGHV
FE-----------------------------------------ELRRPGTPLYSI-KAYL
PVIESFGFSTQLRAATSGQAFPQSVFD---------------------------------
------------------------------------------------------------
--HWEMVASDPLDPAS--QAGVIVAG----------------------------------
---------------------IRKRKGIKEAVPPLIEYEDHL------------------
-------------
