>gnl|BL_ORD_ID|43912 @Zea_mays@_GRMZM2G459391_T02|PACid:20863728
M-------------------------------------------------EAAV------
-----PSRVALSAASRLPNPHAVTGDRSFIYKGRCQ------------------------
------SLAIPMAL----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------SAAAPGKGG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------GVLDRPVEK-----TTPGRQ
SEFDVKKSRK-----MSPPYRVILHNDNYNRREYVVKVL---------------------
------------------------------------------------------------
------------------------MKVIPGM-----------------------------
------------------------------------------------------------
--------------------------------------------------------TVDN
AVNIMQEAHVNGLSV---------------VIVCSQSEA--------------EEHCTSL
RGNGLRSSIE--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------GG
C
>gnl|BL_ORD_ID|41210 @Zea_mays@_GRMZM2G002756_T01|PACid:20861026
M-------------------------------------------------MASV------
-----PSRVALSAASRLPNLHAVAGDRSFIYKRRCP------------------------
------SLSIPMAL----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------SAAAPGKGG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------GVLDRPVEK-----ITPGRQ
SEFDVKKSRK-----MTPPFRVILHNDNHNRREYVVQVL---------------------
------------------------------------------------------------
------------------------MKVIPGM-----------------------------
------------------------------------------------------------
--------------------------------------------------------TVDN
ALNIMQEAHVNGLSV---------------VIVCSQSEA--------------EEHCTSL
RGNGLRSSIE--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PAS-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------GG
C
>Oryza_sativa_gnl_BL_ORD_ID_22109
MAISSR--------------------------------------------AAAC------
-----GALIFPTTASAAPVSRSVSVDQRVSHRRRK-------------------------
------AVAVAAVP----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------HASSGG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ALLERPAFDQSQLDTLPVTQ
EGGDTGRMRDRRGSGSGDSYKVLLIDDARHTEKLVEKAL---------------------
------------------------------------------------------------
------------------------PQVVPSV-----------------------------
------------------------------------------------------------
--------------------------------------------------------TAEA
ARQLFHASRQKGAAL---------------VIVAVKEHA--------------EFYAQMM
VRQGLRSAIE--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PESD----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------LA
S
>gnl|BL_ORD_ID|5868 @Zea_mays@_GRMZM2G118243_T02|PACid:20825594
MWAAEAAFSRSGSWREAEDEREALRWAALQRLPTVTRARRGLLRSPAPDGAAAVEGDDVL
CEVDVAGLSSGDRTALVDRLVADSGDSEHFFRRIRS--RFDAVQIEFPKIEVRYEDVTVD
AYVHVGSRALPTIPNFICNMTEAFLRHLRIYRGGRVKLPILDNISGVIRPSRMTLLLGPP
SSGKTTLLLALAGRLGPGLKMSGNITYNGHHLNEFVPQRTSAYVSQQDWHASEMTVRETL
EFAGRCQGVGIKYDMLVELLRREKNAGIKPDEDLDVFMKALALEGKQTSLVAEYIMKILG
LDVCADTIVGDEMIKGISGGQKKRLTTGELLVGSARVLFMDEISTGLDSATTYQIIKYLR
NSTHALDGTTIISLLQPAPETYELFDDVILIAEGQIVYQGPREYAVDFFGAMGFRC----
-PERKNVADFLQEVLSKKDQQQY---WCHYDYPYQFVSVSKFAEAFKTFIIGKRLHQELT
VPYNRHHNHPAALCTSSYGVKRLELLKSNYQWQRLLMKRNSFIYVFKFIQLLLVALITMT
VFFRSTMHHDSVDDGIIYLG--------ALYFAIVMILFNGFTEVSMLVTKLPVLYKHRD
LHFYPPWAYTLPSWLLSIPTSLYESGMWVLVTYYVVGYDPQFTRFLGQFLLLFFLHQTSL
ALFRVMASLGRNMIVANTFGSFALLVVMILGGFIITKESIPVW---WIW--GYWVSPMMY
AQNAISVNEF-----HGHSWNKQFANQNITMGEAILTGYGLFKEKYWFWIGVGALFGYAI
ILNILFTMFLTLLNPIGNLQAVVA-----------KDQVRHRDSRRKNDRVA--------
--LELRSYLHSNS-----------LSVLPPAGNLKE--QKGMVLPFQPLSMCFRNINYYV
DVPVELKKQGVAEDRLQLLVDVTGAFRPGILTALVGVSGAGKTTLMDVLAGRKTGGLIEG
SITISGYPKNQETFTRISGYCEQNDVHSPCLTVIESLLYSACLRLPSHVDADTQRAFVEE
VMELVELNPLSGALVGLPGVNGLSTEQRKRLTIAVELVANPSIVFMDEPTSGLDARSAAI
VMRTVRNIVNTGRTIVCTIHQPSIDIFESFDELLFMKRGGQLIYAGPLGAKSRNLVDFFE
AIPGVPKIRDGYNPAAWMLEVT------------STQMEQIL-------GVDFAEYYRQ-
------------------------------------------------------------
----------SKLFQQTREI--------VEALSRPSSESKELTFATK-------------
---------YAQPFCAQYM---------------ACLWKHNLS-----------YWRNPQ
YTAVRFFYTVIISLMFGTIC----------------------------------------
-----WKFGSRRGTQHDIFNAMGA-----MYAAVLFIGITNATSVQPVISIERFVSYRE-
---------RAAGMYSALPFAFSL------------VTVEFPY------ILVQSLIYGSI
FYSLGSFEWTAAKFLWYLFFMYFTLLYFTFYGMMTTAITPNHTIAPI----IAAPF----
--YTLWNLFCGFMIPRKRIPVWWRWYYWANPVSWTLYGLLTSQFGDLD------------
QPLLMADGVTSTTVVAFLEEHFGFRHDFLGAVAAMVAGFCVLFAVVFALAI--KYLNFQR
R
>gnl|BL_ORD_ID|895 @Zea_mays@_GRMZM2G368448_T01|PACid:20820621
M-------------------------------------------------AGSVVTDD--
--------SAASTTGMRDDENSLSGES---FSEWRSCDRAD-------------------
------SDTPSTSP------------------------PFWDSDGDDDDPGRV-------
------------------------------------------------WHLP--------
-------------------------AGVKEDEKVQV------------------------
-----------ETWKKGDGG----------------------------------------
------DG----------PKPSELFGHHTWRIE-NFSKEKKREMKSEPFEAGGYKWYILV
YPQGCDVSNHLSLFLCVANHDKLLPGWSHF---AQFTIAVANIDPKKM------------
-------KYSGELNLVCFLLGRFWKKEHDWGWKK-------FMELSKIQDGFLVDDV-LE
IIAQVQVIREKVDRPFRCLDRPYRRELIRIYMTNVEQIYRRFVEERRSKLSKLIEDKMKW
SSFRAFWSAIDPNTRHHMSREKTETILKILVKQFFVEKEVTST------LVMDSLYTSLK
ALEYRMKSKKCKTKLADLEELPAPMVHVDMDMFVLADDVIALLERAALE--PLPCQPVAP
KDDKTSQSRMKDGS-SGEVYKVSMEREERRLTELAQKILETFVLSHIF-SGIEVAYQEAV
ALKRQEELIREEEEEAGLLEHQMKGKRGGGANEKDKRAKKKQTKQKKNNRKAKDKERDVK
CEVKILERLHDETVIDNSDGLPAKVEVIAKVDALEEGSSDGSDMPNRGKNQCNKGLS---
---ISLAKEGDGLPSTSSVTGGSGRNSSGCCTAPKLDQDTVLLTLRDKL--RKLGQRLQ-
-------EKNIEGQKLLKAHFEARDTK---VKVEESSDSSNSLDRPPDVPESSMHSSEDT
VDLKVNGTPNKDASV----VNPVLEESVSGIPVTAKNESLPSARTKEGPVSNKD-NASSL
KMKTMASCLK--------LHPADVD-----KDAPFPSKSPRINRAAPVPSK---LPSADK
ATPVLPKSSLSVNKAALVRPKSPAVDKATPVCPESPAVDKVTPVRPRSPAVDKATPVRSQ
SPAVDKATHVCPQSPSVDKATPSIDKATPVRPKSPAIDKVTPIPPKSPPVDKASPAPPKS
LSGAKDVPVPSRSLQIDRFIPAPPRLSQVDKAALPSSEQPHISPATNSEAQGATTSRKVT
ASSVLEVAAASRPSSAPVLPTPRSTAPVASHIQTSTLLSRSMSEAAGRRSVNDPSFSAPS
YTPQTYRNAIIGKTGLATTSANLAYQSYSLGQDTAPSQPLSAYASSTAVMMPPAGRSDQS
SARHGFKSGSGKLEAHDSWQQWKGDNNVDMHLWRDHTTYQQMTRGQAYDQSRRDDTYQQT
CSRGTEKFSRHAGL-QARQFQTETPASHVWHQQQGQVAEEFPHLDIINDLLEEDQINGSI
PES-----------------------FHQDYNVFGLPFSPRGNVSDMGMASVRSPARFNS
TKYEYDGGFSG--------------AYDINAVN----GLRERQFPSLDSYSNGLSDVSAS
KPWL--NGSPSPSVMSLGVNTNGYH--------PQVADYPSLGNGVNGVSLWRRHAN-GR
W
