>Acaryochloris_marina_MBIC11017_gnl_BL_ORD_ID_3792
QTPVTRP-----EEKQAQKTVRKP---YPNFKVIVVNDDVNTFEHVAKTLMTYIPHMTSD
KAWELTNQIHFEGQAIVWVGPQEQAELYHMQLQRAG------LTMAPLEA---A
>Anabaena_variabilis_ATCC_29413_gnl_BL_ORD_ID_3450
TAPTVTP-------ERSNQTVRKS---YPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGD
LAWDLTNQVHYEGQAIVWVGPQEPAELYHQQLRRAG------LTMAPLEA---A
>Nostoc_punctiforme_ATCC_29133_gnl_BL_ORD_ID_3650
TAPTITP-------ERSSQVTRKT---YPNYKVIVLNDDFNTFQHVAECLMKYIPGMSGD
RAWDLTNQVHYEGQAIVWVGPQEPAELYHQQLRRAG------LTMAPLEA---A
>Nodularia_spumigena_CCY9414_gnl_BL_ORD_ID_1770
TAPTVTP-------GKTTEVVRKT---YPNYKVIVLNDDFNTFQHVSECLMKYIPGMTGD
RAWDLTNQIHYEGQAIVWVGPQEMAELYHQQLRRAG------LTMAPLEA---A
>Arthrospira_platensis_NIES_39_gnl_BL_ORD_ID_1627
ASPTTTP-------SRSSQTVRKP---YPNYKVIVLNDDFNTFQHVANCLMKYLPGMTSD
QAWELTNRVHYEGQATVWVGPLEQAELYHTQLSREG------LTMAPLEK---A
>ClpS2_Synechococcus_7942_ClpS2
AAPATAP-------GTTTTRVRQP---YPHFRVIVLDDDVNTFQHVAECLLKYIPGMTGD
RAWDLTNQVHYEGAATVWSGPQEQAELYHEQLRREG------LTMAPLEA---A
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_2237
SSATVTP-------TKPETSVKAL---KP-WKVIVLNDDFNTFQHVANCLVKYIPHMHPD
RAWKLTQQVHSEGRAIVWVGPLEQAELYHEQLSREG------LTMAPLEQ---A
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_2530
PLPTKTP-------LDPVKTPEKTPLRWRDWVVRLFNDPVNKFEHVVESLCKHVPGMSQD
MAWSVAWQAHREGVAATYQGPREVAELVCEKLVRDG------LISDCCES----
>Acaryochloris_marina_MBIC11017_gnl_BL_ORD_ID_5473
SVETLEK----------RSTSRKL---APKYRVLLHNDDFNSMEHVVQVLIQTVPNLTQP
QAVSVMMEAHTNGIALVITCAFEHAEFYCETLKMHG------LTSTIEPD---E
>Anabaena_variabilis_ATCC_29413_gnl_BL_ORD_ID_1891
SVETIEK----------RSTSRKL---APRYRVLLHNDDYNSMEYVVQVLITTVPSLTQP
QAVSIMMEAHTNGLALVITCAQEHAEFYCETLKDHG------LSSTIEPD---E
>Nodularia_spumigena_CCY9414_gnl_BL_ORD_ID_2031
------------------------------------------MEHVVQSLITTVPSLTQP
QAVSIMMEAHTNGMALVITCAQEHAEFYCETLKSHG------LSSTIEPD---E
>Nostoc_punctiforme_ATCC_29133_gnl_BL_ORD_ID_3476
SVETIQK----------PSTTRKL---APRYRVLLHNDDYNSMEHVVQSLIATVPSLTQP
QAVSIMMEAHTNGLALVITCALEHAEFYCETLISHG------LSSTIEPD---E
>Arthrospira_platensis_NIES_39_gnl_BL_ORD_ID_6367
STQTVEK----------TSTNRKL---APRYRVLLHNDDHNPMEYVVQVLMSTVPGLTQP
QAVSIMMEAHTNGLALVITCALEHAEFYCETLKNHG------LTSTIEPD---E
>ClpS1_Synechococcus_7942_ClpS1
AVETIQK--------PETTTKRKI---APRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQP
QAVDIMMEAHTNGTGLVITCDIEPAEFYCEQLKSHG------LEQQ-------H
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_745
STETLER----------KSVQRKP---MPLYKVLLHNDDHTPMNYVIEVLMKTIPKMQPS
KARKIMLEAHNGGVAVVIVCALEHAEFYSESLNRHN------LTSTYEPD---C
>Brassica_rapa_gnl_BL_ORD_ID_16356
DKPIIEKTTPGRESEFDLRKSKKM---APPYRVILHNDNFNKREYVVQVLMKVIPGMTVD
NAVNIMQEAHINGMAVVIVCAQADAEQHCMQLRGNG------LLSSVEPDGGGC
>Medicago_truncatula_gnl_BL_ORD_ID_34263
EKPVIEKATPGRESEFDLKKSRKT---APPYRVILHNDNFNKREYVVQVLMKVIPGMTLD
NAVNIMQEAHHNGMSVVIICAQADAEDHCMQLRGNG------LLSSIEPAGDGC
>Zea_mays_gnl_BL_ORD_ID_43912
DRP-VEKTTPGRQSEFDVKKSRKM---SPPYRVILHNDNYNRREYVVKVLMKVIPGMTVD
NAVNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNG------LRSSIEPASGGC
>Oryza_sativa_gnl_BL_ORD_ID_6727
DRP-IEKVTPGRQSEFDVRKSRKM---TPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVD
NAVNIMQEAHVNGLSVVIICSQSEAEEHCTSLRGNG------LRSSIEPASGGC
>Physcomitrella_patens_gnl_BL_ORD_ID_33457
DRPTIDKPTPGRESEFDLKKKKKM---SPPYRVMLHNDNFNKREYVVQVLLKAIPGMTVD
IAVNVMNEAHINGIAVVIVCPQEDAEDYCMQLRTNG------LLSSIEPDT--C
>Physcomitrella_patens_gnl_BL_ORD_ID_6354
DRPTIDKPTPGRESEFDLKKKKKM---SPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVD
IAVNVMNEAHINGLAVVIVCPQEDAEDYCMQLRTNG------LLSSIEPAS--C
>Cyanophora_paradoxa_gnl_BL_ORD_ID_27119
AKPEVETGGDGAKSK-ERENEEEF---MGKWKVLLHNDEANTMEYVIKAIRTVVPNISHQ
EAVNIMLEAHTTGV-VVIVCEKEHAEYYCEGLKGYQ------LWSSIEPED--V
>Volvox_carteri_gnl_BL_ORD_ID_608
DSPTITS-----EPQQGTDRAYKR---PPIYKVFLHNDNYNKREYVVKVLLKVVEEITVD
DAVTVMQEAHETGVALVVACPQENAERYCEGLRLNG------LTSTIEPAG--R
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_9005
DAPTTTQ-----QPASGVERSQKR---PPIYKVLLHNDNYNKREYVVKVLLKVVEQITVD
DAVTCMQEAHETGVALVVACPQDNAERYCEGLRLNG------LTSTIEPGG--C
>Cyanidioschyzon_merolae_gnl_BL_ORD_ID_2238
EREAVRE-------KTTATKGVDP---GKKYKLLLFNDEKNTRERVVEVLLKCIPGLSKL
DAQSIMQKAHTTGMALVGVWVFELAEAYCDLLRSEG------LVSDIEPA---E
>Cyanophora_paradoxa_gnl_BL_ORD_ID_23599
ERPSVIGDVDVTAWATFMARRKAQ---APKYRVLLFNDPFNKREHVV------IDGLTTA
DAVEIMSKAHNEGFAVAAVVVQEVAELYVEGLRSCG------LTATCEPD---E
>Rhodopseudomonas_palustris_CGA009_gnl_BL_ORD_ID_1197
--------------------------------MILVNDDYTPREFVVSVLKGEF-RMTED
QATKVMLTAHQRGVCVVGVFTKDVAETKATRATDAGRAKGYPLLFTTEPE---E
>Rhodopseudomonas_palustris_CGA009_gnl_BL_ORD_ID_3127
STPSTSV-------ITKTKPRTKR---PNLYRVLILNDDYTPMEFVVHVLEKFF-QMDVE
AATKVMLHVHHHGIGECGVFTYEIAETKVTQVMDFARKHQHPLQCVMEKK----
>Escherichia_coli_UTI89_gnl_BL_ORD_ID_1000
MGKTNDWLDFDQLAEEKVRDALKP---PSMYKVILVNDDYTPMEFVIDVLQKFF-SYDVE
RATQLMLAVHYQGKAICGVFTAEVAETKVAMVNKYARENEHPLLCTLEKA----
>Streptomyces_avermitilis_MA_4680_gnl_BL_ORD_ID_5165
TAPAPLE-IEKTESAEEVFAVPEP---DVPWVTIVHNDPVNLMSYVTYVFQTYF-GYSKD
KATKLMLDVHHKGRAVVSSGTREEMERDVQAMHGYG------LWATLQQDR--K
>Chlorobium_tepidum_TLS_gnl_BL_ORD_ID_2204
NNPDTRT--------EELIADVDT---LDAWRVVLFNDDDHTFDEVIFQIIKAV-RCTRS
IAEKHTWEVHTRGRAIVYAGEMSNCIRVSAILEEIA------LKTEIQTG----
>Synechococcus_7942_ClpS1
M-----------------------------------------------------------
------------------------------------------------------AVETIQ
KPETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLV
ITCDIEPAEFYCEQLKSHGLEQQH----------------
>Rubrobacter_xylanophilus_DSM_9941_gnl|BL_ORD_ID|999 gi|108803856|ref|YP_643793.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
------------------------------------------VGSLTRDIRCSAATKTAP
ARKTRRAPSREPRYRVILHNDDWTPMDHVVAALMKVVPRLSLRRAVSIMLEAHTKGQAVV
TRCHRELAELYREGLKAEGLISTIEPDG------------
>gnl|BL_ORD_ID|16002 Arabidopsis_thaliana AT1G68660.1|PACid:19653949
M------------ETAICGRLALAPSSLFNSKSGDKHLVSKGPCVNR-------------
---------------------------SILMTLSTSAALGKGGGVLDKPIIEKTTPGRES
EFDLRKSKKIAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVV
IVCAQADAEQHCMQLRGNGLLSSVEPDGGGC---------
>Synechococcus_7942_ClpS2
MLPSPFRPQTTIASENVKTASKAAQPKVNSSMSPQPDESVLSILGVP-------------
----------------------------RPCVKKRSRDDAFVLTVLTCSLQAIAAPATAP
GTTTTRVRQPYPHFRVIVLDDDVNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAATV
WSGPQEQAELYHEQLRREGLTMAPLEAA------------
>Agrobacterium_tumefaciens_C58_gnl|BL_ORD_ID|2177 gi|15889508|ref|NP_355189.1| ATP-dependent Clp protease adaptor [Agrobacterium tumefaciens str. C58]
M-----------------------------------------------------------
---------------------------------------------------SDSPVDLKP
KPKVKPKLERPKLYKVMLLNDDYTPREFVTVVLKAVF-RMSEDTGRRVMMTAHRFGSAVV
VVCERDIAETKAKEATDLGKEAGFPLMFTTEPEE------
>Rhodopseudomonas_palustris_CGA009_gnl|BL_ORD_ID|1197 RPA1203 conserved hypothetical protein
M-----------------------------------------------------------
------------------------------------------------------------
----------------ILVNDDYTPREFVVSVLKGEF-RMTEDQATKVMLTAHQRGVCVV
GVFTKDVAETKATRATDAGRAKGYPLLFTTEPEE------
>Deinococcus_radiodurans_R1_gnl|BL_ORD_ID|752 gi|15805613|ref|NP_294309.1| ATP-dependent Clp protease adaptor protein ClpS [Deinococcus radiodurans R1]
M-----------------------------------------------------------
------------------ARRGALPVLKSAAPLGGGARPILGAMTRPTIPPGPPGAEGRT
QTLERTETKKPRLWRVLLLNDDYTPMDYVVQVLEQFF-RKTEQEAELIMLAVHHKGQGVA
GVYTRDVAETKVAQVTAHAQREGHPLRVVAEPESEGE---
>Agrobacterium_tumefaciens_C58_gnl|BL_ORD_ID|1337 gi|15888689|ref|NP_354370.1| ATP-dependent Clp protease adaptor protein ClpS [Agrobacterium tumefaciens str. C58]
M-----------------------------------------------------------
------------------------------------IAKPIYMQGEGDGEDGGTNRGTSV
ITRVKPKTKRPNLYRVLLLNDDYTPMEFVIHILERFF-QKDREAATRIMLHVHQHGVGEC
GVFTYEVAETKVSQVMDFARQHQHPLQCVMEKK-------
>Rhodopseudomonas_palustris_CGA009_gnl|BL_ORD_ID|3127 RPA3148 DUF174
M-----------------------------------------------------------
--------------------LQPSLSHSAAGQAGDRINRPLAMAGDG-GRSGPSTPSTSV
ITKTKPRTKRPNLYRVLILNDDYTPMEFVVHVLEKFF-QMDVEAATKVMLHVHHHGIGEC
GVFTYEIAETKVTQVMDFARKHQHPLQCVMEKK-------
>Rhodospirillum_rubrum_ATCC_11170_gnl|BL_ORD_ID|2151 gi|83593445|ref|YP_427197.1| ATP-dependent Clp protease adaptor protein ClpS [Rhodospirillum rubrum ATCC 11170]
M-----------------------------------------------------------
----------------NTESQSAKMTTRDHDMAPRLGQGGDDQNDDDRGGQGPGQPGTGV
VVKAKPKTKKPSMYRVLMLNDDYTPMEFVVHVLERFF-GKTHEEATNIMLHVHQRGVGLC
GVYTYEVAETKVSQVMDLARRSQHPLQCTLEKE-------
>Nitratiruptor_SB155_2_gnl|BL_ORD_ID|374 gi|152990128|ref|YP_001355850.1| ATP-dependent Clp protease, adaptor protein ClpS [Nitratiruptor sp. SB155-2]
M-----------------------------------------------------------
--------------------------------------------------------GEKV
ETKEVVKLEEPKKYKVFLLNDDYTTMDFVVDILCDIF-DKSYEEAVNIMLTIHRQGKGLC
GIYTYEIAETKIDQVHRLARAHEFPLKAVMEEE-------
>Sulfurimonas_denitrificans_DSM_1251_gnl|BL_ORD_ID|457 gi|78776659|ref|YP_392974.1| ATP-dependent Clp protease adaptor protein ClpS [Sulfurimonas denitrificans DSM 1251]
M-----------------------------------------------------------
------------------------------------------------------ATNIDL
ETKEKVKIKYPKKYKVLLLNDDYTSMEFVIDILITIF-HKNYEQAHQIMLEIHKKTKGIC
GIYTYEIAETKVMQVHKKARDNGFALRATMEEE-------
>Bordetella_petrii_DSM_12804_gnl|BL_ORD_ID|2667 gi|163856974|ref|YP_001631272.1| clpS gene product [Bordetella petrii DSM 12804]
M-----------------------------------------------------------
-------------------------------------------------SSTLDTQHDVA
VEKAPARTAPPPMYQVVLLNDDYTPMEFVVKVLQKFF-GKNQEDATRIMLQVHHEGRGTC
GVYPRDVAATRIAQVAQYARARQHPLQCVMEPV-------
>Delftia_acidovorans_SPH_1_gnl|BL_ORD_ID|3490 gi|160898941|ref|YP_001564523.1| ATP-dependent Clp protease adaptor protein ClpS [Delftia acidovorans SPH-1]
M-----------------------------------------------------------
-----------------------------ARMIFMATQPPSIPPAIPTVRPVSDDDGAVV
LERRRQRVQPPQMYQVVMLNDDFTPMEFVIIVLQELF-GKDRETATQIMLKIHLDGRGVC
GVYSRDVAATKVEQVLQAAQKAGHPLQAMFEPVE------
>Methylibium_petroleiphilum_PM1_gnl|BL_ORD_ID|2454 gi|124267648|ref|YP_001021652.1| hypothetical protein Mpe_A2462 [Methylibium petroleiphilum PM1]
M-----------------------------------------------------------
-----------------------------------PDDTVPPTPPKRPVTKPDDGQGAVV
AERQSARVEPPRMYQVVLLNDDYTPMEFVVMVLQEFF-QRDIETATQIMLKIHHEGRGVC
GVYTKDVASTKVESVLAAAKRSGHPLQCTMEAA-------
>Neisseria_gonorrhoeae_FA_1090_gnl|BL_ORD_ID|378 gi|59800852|ref|YP_207564.1| ATP-dependent Clp protease adaptor protein ClpS [Neisseria gonorrhoeae FA 1090]
M-----------------------------------------------------------
-----------------------------------------------------TAQHQSD
TLLHRLNTLPPKRYGVFLLNDDYTTMEFVVEILTEIF-MLGQEQAVAVMLSVHHEGKGLC
GTYTRDIAQTKQQQVMQRAKAEGHPLQCIVEEI-------
>gnl|BL_ORD_ID|1000 Escherichia_coli_UTI89 gi|91209918|ref|YP_539904.1| ATP-dependent Clp protease adaptor protein ClpS [Escherichia coli UTI89]
M-----------------------------------------------------------
-----------------------------------------------GKTNDWLDFDQLA
EEKVRDALKPPSMYKVILVNDDYTPMEFVIDVLQKFF-SYDVERATQLMLAVHYQGKAIC
GVFTAEVAETKVAMVNKYARENEHPLLCTLEKA-------
>Legionella_pneumophila_2300_99_Alcoy_gnl|BL_ORD_ID|900 gi|296106398|ref|YP_003618098.1| ATP-dependent Clp protease adaptor protein ClpS [Legionella pneumophila 2300/99 Alcoy]
M-----------------------------------------------------------
------------------------------------------SRQNLEEIIQTGIADTEL
STEISTAIKRPRKYKVLLLNDDYTPMDFVVEVLKHFF-HLNEEVAIQVMLQVHFQGKGVC
GVFTRDIAETKVALVNEYARMNQHPLLSSMEPE-------
>Pseudomonas_stutzeri_A1501_gnl|BL_ORD_ID|2249 gi|146282647|ref|YP_001172800.1| ATP-dependent Clp protease adaptor protein ClpS [Pseudomonas stutzeri A1501]
M----------------------------------------------LRNPFALVGTYCL
YHRFADSQGDSSAGCEAVHIYLAPAPRPRTVMRMHAFAQIRLTFNQDRPLEDGDDASGLA
VEEAKPQLKAPPMYKVVMFNDDYTPMDFVVEVLEGIF-NHSREQATKIMLAVHTEGQAVC
GVYTRDVAETKAMQVNQYARECQHPLLCEIEKDG------
>Desulfovibrio_vulgaris_DP4_gnl|BL_ORD_ID|1675 gi|120602577|ref|YP_966977.1| ATP-dependent Clp protease adaptor protein ClpS [Desulfovibrio vulgaris DP4]
M-----------------------------------------------------------
-------------------------------------------------SNGPLAPGYDS
DILVEDDVRLPRMYRVLLHNDDYTTMEFVVSILVEVF-RKTAEQATAIMLAVHRDGVGEC
GVYTFEVAETKAAIVHARARREGYPLRCSTEEV-------
>Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197_gnl|BL_ORD_ID|1666 gi|116331466|ref|YP_801184.1| hypothetical protein LBJ_1906 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M-----------------------------------------------------------
------------------------------------------------SDIFRFDTEEQT
LTKEKVKLKRPSKYRVIILNDDFTPMEFVVWILQFVF-HRSRAQSQQIMLKAHITGKALC
GVYSHDVARTKVIQVQQLAEQHGYPLHCTMEVEEES----
>Bdellovibrio_bacteriovorus_HD100_gnl|BL_ORD_ID|1161 gi|42522812|ref|NP_968192.1| hypothetical protein Bd1289 [Bdellovibrio bacteriovorus HD100]
M-----------------------------------------------------------
----------------------------------------GNNKKDSNSNYPFASPEGEA
GVQLVPKLDTPKMYKVILLNDDYTPMDFVVLVLRRFF-AKTEEQATEIMLDVHKKGAGVA
GVFSLEIAEMKVMQVNQFAQLNQYPLKSTLEEEA------
>Treponema_denticola_ATCC_35405_gnl|BL_ORD_ID|2106 gi|42527626|ref|NP_972724.1| hypothetical protein TDE2123 [Treponema denticola ATCC 35405]
M-----------------------------------------------------------
----------------------------------------------------ELKKQAQK
GTIISEKFIEPENYRVILLNDDFTPMDFVVAVLISIF-NKSQEEAETLMFKVHKTGQASV
GIYVYDIATTKCFQVLTAAKNNNFPLQCKVEKV-------
>Anaeromyxobacter_dehalogenans_2CP_1_gnl|BL_ORD_ID|832 gi|220915956|ref|YP_002491260.1| ATP-dependent Clp protease adaptor protein ClpS [Anaeromyxobacter dehalogenans 2CP-1]
M-----------------------------------------------------------
---------------------------------------------AERTRPGGDTEVVVP
KTRAERETKRPPLYRVLLHNDHYTTQEFVDFVLMTVF-NHDPESAHRIMLHVHMHGVGVA
GIYPYEIAETKARKTMDLAREAEYPLLVTIEPE-------
>Chloroflexus_aurantiacus_J_10_fl_gnl|BL_ORD_ID|2556 gi|163848160|ref|YP_001636204.1| ATP-dependent Clp protease adaptor protein ClpS [Chloroflexus aurantiacus J-10-fl]
M-----------------------------------------------------------
-----------------------------------------------STEQPAVTVRPAV
SFAVASDEELERPYRVIVQNDDVTPMDFVVIVLRVFF-GLDLARAEQVMLTAHYEGRALV
TVLPLQEAQERVYQAHHAAREAGYPLTFYLEPDEQ-----
>Roseiflexus_castenholzii_DSM_13941_gnl|BL_ORD_ID|3949 gi|156743978|ref|YP_001434107.1| ATP-dependent Clp protease adaptor protein ClpS [Roseiflexus castenholzii DSM 13941]
M-----------------------------------------------------------
---------------------------------------------SAEVSVPLTTTIPTT
EYVVVTEEELERPYRVIIENDDVTPMDFVVLVLLTIF-ELGFEQSVAIMLEAHHNGRAHV
VTLPYEEAQRRVYEAHHAAREAGYPLSFYLEPDA------
>Herpetosiphon_aurantiacus_DSM_785_gnl|BL_ORD_ID|3187 gi|159899721|ref|YP_001545968.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
M-----------------------------------------------------------
-----------------------------------------NTRRDVATAEPQTTTDVEL
DFITLSDEELEKPYRVILQNDDITPMEVVVWVLEKVF-EQSFEQAKRIMIEAHVKGHALV
TILPFKEASARVYSAQSRARDMGFPLVLFLEPDF------
>gnl|BL_ORD_ID|5165 Streptomyces_avermitilis_MA_4680 gi|29831702|ref|NP_826336.1| ATP-dependent Clp protease adaptor protein ClpS [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
--------------------------------------------GRVTAPAPLEIEKTES
AEEVFAVPEPDVPWVTIVHNDPVNLMSYVTYVFQTYF-GYSKDKATKLMLDVHHKGRAVV
SSGTREEMERDVQAMHGYGLWATLQQDRK-----------
>Cytophaga_hutchinsonii_ATCC_33406_gnl|BL_ORD_ID|1028 gi|110637456|ref|YP_677663.1| hypothetical protein CHU_1046 [Cytophaga hutchinsonii ATCC 33406]
M-----------------------------------------------------------
----------------------------------------------IRIQSHSFPFQQEE
DVALMEEVQTSDMNDLVVYNDDVNTFEHVIQVLMSVC-GHSPEQAEQCTLLIHYKGKCTV
KMGSLNELKPMRQGICDKGISAEIL---------------
>Flavobacterium_johnsoniae_UW101_gnl|BL_ORD_ID|3483 gi|146301250|ref|YP_001195841.1| unnamed protein product [Flavobacterium johnsoniae UW101]
M-----------------------------------------------------------
------------------------------------------------------STKEKV
REKVREKEAAVFNNEIIMYNDDVNTFDHVIDTLMRVC-DHTAEQAEQCSLIVHYNGKCTV
KTGPIEKLKPQCTQLLEAGLSAEIV---------------
>Chlorobium_tepidum_TLS_gnl|BL_ORD_ID|2204 CT2237 hypothetical protein
M-----------------------------------------------------------
------------------------------------------------IRLTASNNPDTR
TEELIADVDTLDAWRVVLFNDDDHTFDEVIFQIIKAV-RCTRSIAEKHTWEVHTRGRAIV
YAGEMSNCIRVSAILEEIALKTEIQTG-------------
>Pelodictyon_phaeoclathratiforme_BU_1_gnl|BL_ORD_ID|42 gi|194335225|ref|YP_002017019.1| ATP-dependent Clp protease adaptor protein ClpS [Pelodictyon phaeoclathratiforme BU-1]
M-----------------------------------------------------------
------------------------------------------NSSLANRWTASLTTPVTK
QREQGSGPDLLDAYRVVLFNDEEHTFEEVIEQIIKAV-RCSRQKAEKHTWEVHTRGRSIV
FAGAMLLCLRVSSILEEIALKTEIQTS-------------
>Candidatus_Solibacter_usitatus_Ellin6076_gnl|BL_ORD_ID|1190 gi|116620336|ref|YP_822492.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
M-----------------------------------------------------------
--------------------------------------------RRHAAQMANPAIAPDT
EILEREREQHVPLYRVVLLDDNDHTYDYVIEMLQKIF-IFTLDQAYRHAEEVDRAGRTVL
ITCELREAEYARDQIQAYGPDWRLPRSKGSMSAVVEPAQ-
>Rhodopirellula_baltica_SH_1_gnl|BL_ORD_ID|6674 gi|32477341|ref|NP_870335.1| hypothetical protein RB12137 [Rhodopirellula baltica SH 1]
M-----------------------------------------------------------
--------------------------------------------SDHSAAVAEPDVVTEE
EQRSDRKPKRQPPYHVILWDDTDHSYDYVISMMKRLF-RMPIEKGYQVAKEVDKSGRAIC
MTTTLELAELKRDQIHAFGKDERLDRCKGSMSATIEPARG
>Rubrobacter_xylanophilus_DSM_9941_gnl|BL_ORD_ID|2018 gi|108804875|ref|YP_644812.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
------------------------------------------------------GAATRP
KRRSREKSGGLPPYNVVLLDDDDHSYEYVIFMLRKLF-GYPVRKGYELAREVDTTGRAVV
ATTHLEEAELKRDQIQSFGPDPLIPRCKGSMRAVVEPAPG
>Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197_gnl|BL_ORD_ID|1440 gi|116331240|ref|YP_800958.1| hypothetical protein LBJ_1643 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M-----------------------------------------------------------
-----------------------------------------------------ASTQTPD
LDEITSTKSTGGPWRVVLWDDNEHTYEYVIEMLVEIC-MMTVEKAFLHAVQVDQEKRTIV
FSGEFEHAEHVQERILTYGADPRMSNSKGSMSATLEK---
