>Rubrobacter_xylanophilus_DSM_9941_gi_108803856_ref_YP_643793.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Rubrobacter_xylanophilus_DSM_9941_
MVGSLTRDIRC-------------------------------------------------
------------------------------------------------------------
----------------------SAATKTAP---------------ARKTRRAPSREP---
---RYRVILHNDDWTPMDHVVAALMKVVPRLSLRRAVSIMLEAHTKGQAVVTRCHRELAE
LYREGLKAEGLIST-IEPDG----------
>Trichodesmium_erythraeum_IMS101_gi_113474895_ref_YP_720956.1__clpS_gene_product__Trichodesmium_erythraeum_IMS101_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSIETIEKP-----------------TTSTVRKTAP---
---HYRVLLHNDDFNSMEYVVQTLMKTVPSLTQPQAVNIMMEAHSNGIALVIICALEPAE
FYCENLKNHGLTST-IEPDE----------
>Cyanothece_sp._CCY0110_gi_126657545_ref_ZP_01728701.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._CCY0110_
------------------------------------------------------------
------------------------------------------------------------
---------------------MTTEVIEKR---------------SSSTSTVRKPAP---
---RYRVLLHNDDFNSMEYVVQTLMQTVSGMTQPQAVDIMMEAHTNGTALVITCALEPAE
FYCETLKNHGLTST-IEPDE----------
>Cyanothece_sp._PCC_8801_gi_218246012_ref_YP_002371383.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_8801_
------------------------------------------------------------
------------------------------------------------------------
---------------------MTTEVIEKR---------------STSSATVRKPAP---
---RYRVLLHNDDFNSMEYVVQTLMQTVAGMTQPQAVDIMMEAHTNGTALVITCALEHAE
FYCETLKNHGLTSS-IEPDE----------
>Crocosphaera_watsonii_WH_0003_gi_357263411_gb_EHJ12427.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_0003_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MEYVVQTLMQIVPSITQPQAVDIMMEAHSNGTALVITCALEPAE
FYSETLKNHGLTST-IEPDE----------
>Crocosphaera_watsonii_WH_8501_gi_67924069_ref_ZP_00517517.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_8501_
------------------------------------------------------------
------------------------------------------------------------
---------------------MTTDVIEKP---------------SSSTSTVRKPAP---
---RYRVLLHNDDFNSMEYVVQTLMQTVPSITQPQAVDIMMEAHSNGTALVITCALEPAE
FYSETLKNHGLTST-IEPDE----------
>Microcystis_aeruginosa_PCC_7806_gi_159029424_emb_CAO90801.1__unnamed_protein_product__Microcystis_aeruginosa_PCC_7806_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSTEVIEKR-----------------STATIRKPAP---
---RYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITCIQEHAE
FYCETLKNKGLTSS-IEPDE----------
>Microcystis_aeruginosa_NIES-843_gi_166367986_ref_YP_001660259.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Microcystis_aeruginosa_NIES-843_
------------------------------------------------------------
------------------------------------------------------------
-------------------------MIEKR-----------------STATIRKPAP---
---RYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITCIQEHAE
FYCETLKNKGLTSS-IEPDE----------
>Synechococcus_sp._PCC_7002_gi_170078877_ref_YP_001735515.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._PCC_7002_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSTGVIEQR-----------------STSTIRKPAP---
---RYRVLLHNDDFNSMEHVVQTLMQTVAGLTQPQAVSIMMEAHTNGIALVITCVQEHAE
FYCETLKMHGLTST-IEPDE----------
>Cyanothece_sp._PCC_7424_gi_218438615_ref_YP_002376944.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7424_
------------------------------------------------------------
------------------------------------------------------------
-------------------MSTSTQVIEKS-----------------TTSTVRKPAP---
---RYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGTALVITCTLEHAE
FYCETLKNHGLTST-IEPDE----------
>Cyanothece_sp._PCC_7822_gi_307150896_ref_YP_003886280.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7822_
------------------------------------------------------------
------------------------------------------------------------
-----------------MSTSTSTQVIEKS-----------------STSTVRKPAP---
---RYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGMALVITCTLEHAE
FYCETLKAHGLTST-IEPDE----------
>Lyngbya_sp._PCC_8106_gi_119489795_ref_ZP_01622553.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Lyngbya_sp._PCC_8106_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MEYVVQVLLQTVPSLTQPQAVSIMMEAHTNGLALVITCAQEHAE
FYCETLKNNGLTST-IEPDE----------
>Nodularia_spumigena_CCY9414_gi_119510879_ref_ZP_01630003.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nodularia_spumigena_CCY9414_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MEHVVQSLITTVPSLTQPQAVSIMMEAHTNGMALVITCAQEHAE
FYCETLKSHGLSST-IEPDE----------
>Nostoc_sp._PCC_7120_gi_17231817_ref_NP_488365.1__clpS_gene_product__Nostoc_sp._PCC_7120_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKR-------------------STSRKLAP---
---RYRVLLHNDDHNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLALVITCAQEHAE
FYCETLKDHGLSST-IEPDE----------
>Anabaena_variabilis_ATCC_29413_gi_75907498_ref_YP_321794.1__clpS_gene_product__Anabaena_variabilis_ATCC_29413_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKR-------------------STSRKLAP---
---RYRVLLHNDDYNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLALVITCAQEHAE
FYCETLKDHGLSST-IEPDE----------
>Fischerella_sp._JSC-11_gi_354566131_ref_ZP_08985304.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Fischerella_sp._JSC-11_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETQQKR-------------------STSRKLAP---
---QYRVLLHNDDYNTMEYVVQVLLTTVPSLTQPQAVSIMMEAHSNGLALVITCAQEPAE
FYCETLKNHGLTST-IEPEE----------
>Arthrospira_maxima_CS-328_gi_209523998_ref_ZP_03272550.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_maxima_CS-328_
----------------------------------------MALVCFGIDKFPDHCNFVN-
------------------------------------------------------------
----------------GGDGSVSTQTVEKT-------------------STNRKLAP---
---RYRVLLHNDDYNPMEYVVQVLMSTVPGLTQPQAVSIMMEAHTNGLALVITCALEHAE
FYCETLKNHGLTST-IEPDE----------
>Arthrospira_platensis_NIES-39_gi_291571937_dbj_BAI94209.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_platensis_NIES-39_
----------------------------------------MALVCFGIDKFPYHCTFVN-
------------------------------------------------------------
----------------GGDGSVSTQTVEKT-------------------STNRKLAP---
---RYRVLLHNDDHNPMEYVVQVLMSTVPGLTQPQAVSIMMEAHTNGLALVITCALEHAE
FYCETLKNHGLTST-IEPDE----------
>Arthrospira_platensis_str._Paraca_gi_284052626_ref_ZP_06382836.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_platensis_str._Paraca_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSTQTVEKT-------------------STNRKLAP---
---RYRVLLHNDDHNPMEYVVQVLMSTVPGLTQPQAVSIMMEAHTNGLALVITCALEHAE
FYCETLKNHGLTST-IEPDE----------
>Microcoleus_chthonoplastes_PCC_7420_gi_254414360_ref_ZP_05028127.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Microcoleus_chthonoplastes_PCC_7420_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MEYVVQALIQTVPSLTQPQAVNIMMEAHNSGIALVITCALEHAE
FYCETLKNHGLTST-IEPDE----------
>Nostoc_punctiforme_PCC_73102_gi_186684027_ref_YP_001867223.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nostoc_punctiforme_PCC_73102_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIQKP-------------------STTRKLAP---
---RYRVLLHNDDYNSMEHVVQSLIATVPSLTQPQAVSIMMEAHTNGLALVITCALEHAE
FYCETLISHGLSST-IEPDE----------
>Raphidiopsis_brookii_D9_gi_282897015_ref_ZP_06305017.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Raphidiopsis_brookii_D9_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKP-------------------STTRKLAP---
---RYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVTIMMEAHSNGLALVISCALEHAE
FYCESLNNHGLTST-IEPDD----------
>Cylindrospermopsis_raciborskii_CS-505_gi_282899028_ref_ZP_06307010.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cylindrospermopsis_raciborskii_CS-505_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKP-------------------STTRKLAP---
---RYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVSIMMEAHSHGLALVISCALEHAE
FYCESLNNYGLTST-IEPDD----------
>Acaryochloris_marina_MBIC11017_gi_158338702_ref_YP_001519879.1__clpS_gene_product__Acaryochloris_marina_MBIC11017_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETLEKR-------------------STSRKLAP---
---KYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIALVITCAFEHAE
FYCETLKMHGLTST-IEPDE----------
>Acaryochloris_sp._CCMEE_5410_gi_359457944_ref_ZP_09246507.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Acaryochloris_sp._CCMEE_5410_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETLEKR-------------------STGRKLAP---
---KYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIALVITCAFEHAE
FYCETLKMHGLTST-IEPDE----------
>Leptolyngbya_valderiana_BDU_20041_gi_148972604_ref_ZP_01811408.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Leptolyngbya_valderiana_BDU_20041_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKR-------------------STVRKHAP---
---RYRVLLHNDDFNTMEYVVQTLVKTVPGLTQPQAVSIMMEAHTNGMALVITCAQEHAE
FYCETLRRHGLSSS-IEPDD----------
>Nostoc_azollae_0708_gi_298490087_ref_YP_003720264.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nostoc_azollae_0708_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKR-------------------STTRKLAP---
---QYRVLLHNDDYNSMEYVVQVLMTSVPSITQPQAVNIMMEAHNSGLALVITCAQEHAE
FYCETLKGHGLSST-IEPD-----------
>Cyanothece_sp._PCC_7425_gi_220908775_ref_YP_002484086.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7425_
------------------------------------------------------------
------------------------------------------------------------
---------------------MAVETIEQR-------------------STVRKLAP---
---RYRVLLHNDDVNSMEHVVEVLLKTVPSLTQPQAVDIMMEAHVNGIALVITCALEHAE
FYCESLKLGGLTST-IEPDE----------
>Lyngbya_majuscula_3L_gi_332711797_ref_ZP_08431728.1__hypothetical_protein_LYNGBM3L_67610__Lyngbya_majuscula_3L_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MEYVVKTLMETVASLTQPQAVNIMMEAHQSGLALVITCAQEHAE
FYCETLKNRGLTST-IEPDE----------
>Oscillatoria_sp._PCC_6506_gi_300868553_ref_ZP_07113170.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Oscillatoria_sp._PCC_6506_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVETIEKR-------------------STVRKIAP---
---RYRVLLHNDDFNSMEYVVQTLMHTVPSLTQPQAVNIMMEAHTNGLAVVIICAQEHAE
FYSETLNNHGLIST-IEPDE----------
>Microcoleus_vaginatus_FGP-2_gi_334120716_ref_ZP_08494794.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Microcoleus_vaginatus_FGP-2_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSVEIIQKA-------------------STVRKLAP---
---RYRVLLHNDDFNPMEYVVQTLMATVPSLTQPQAVNVMMEAHTNGMGLVIVCALEHAE
FYAETLNNHGLSSS-IEPDD----------
>Thermosynechococcus_elongatus_BP-1_gi_22297755_ref_NP_681002.1__clpS_gene_product__Thermosynechococcus_elongatus_BP-1_
----------------------------------------------------------M-
------------------------------------------------------------
----------------EAWPTMSVQTIEKP-------------------ATVRKLAP---
---RYRVLLHNDNVNSMEYVVEVLLKTVPSLTQPQAVDIMMEAHLTGVALVITCALEHAE
FYCEGLKMAGLTST-IEPTE----------
>Synechocystis_sp._PCC_6803_gi_16331021_ref_NP_441749.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechocystis_sp._PCC_6803_
------------------------------------------------------------
------------------------------------------------------------
--------------------MMATEVLNKP-----------------SNSTIRKHAP---
---RYRVLLHNDDFNSMEHVVQTLIQTVAGMTQPQAVDIMMEAHFNGMSLVITCELEHAE
FYCETLRSHGLSST-IEPDE----------
>Synechococcus_elongatus_PCC_6301_gi_56750848_ref_YP_171549.1__clpS_gene_product__Synechococcus_elongatus_PCC_6301_
------------------------------------------------------------
------------------------------------------------------------
---------------------MAVETIQKP-----------------ETTTKRKIAP---
---RYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITCDIEPAE
FYCEQLKSHGLEQQ-----H----------
>Synechococcus_elongatus_PCC_7942_gi_81299501_ref_YP_399709.1__clpS_gene_product__Synechococcus_elongatus_PCC_7942_
------------------------------------------------------------
------------------------------------------------------------
---------------------MAVETIQKP-----------------ETTTKRKIAP---
---RYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITCDIEPAE
FYCEQLKSHGLSSS-IEPDD----------
>cyanobacterium_UCYN-A_gi_284929541_ref_YP_003422063.1__hypothetical_protein_UCYN_10070__cyanobacterium_UCYN-A_
------------------------------------------------------------
------------------------------------------------------------
---------------------MVTDVIEKI---------------SLNTSTTKKPVP---
---RYKVLLHNDDFNPMDYVVQILMQTISGMTRPQAAEIMMEAHISGTALVITCAFEPAE
FYRETLKNHGLSSS-IEPDE----------
>Synechococcus_sp._PCC_7335_gi_254423912_ref_ZP_05037630.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._PCC_7335_
------------------------------------------------------------
------------------------------------------------------------
-------------------MSTSISTIEKP-----------------SVSTVRKIAP---
---RYRVLLHNDDFNSMEYVVEALIETVPSLTAPQAIDIMMQTHNTGIGLVIVCEMEHAE
FYCEGLKGKGLTST-IEPEE----------
>Synechococcus_sp._JA-3-3Ab_gi_86607127_ref_YP_475890.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._JA-3-3Ab_
------------------------------------------------------------
------------------------------------------------------------
---------------------MATETLVKP-------------------SVTPKHMP---
---MYRVLLHNDDVNTMEYVVQVLVKVIPSMLPPQATEIMLEAHNNGVAVVIVVPREHAE
FYCEQLRQHGLTSS-IEPER----------
>Synechococcus_sp._JA-2-3Ba_2-13__gi_86608169_ref_YP_476931.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._JA-2-3Ba_2-13__
------------------------------------------------------------
------------------------------------------------------------
---------------------MATETLVKP-------------------SVTPKHMP---
---MYRVLLHNDDVNTMEYVVQVLVKVIPAMMPPQATEIMLEAHHNGVAVVIVVPREHAE
FYCEQLRQHGLTSS-IEPER----------
>Synechococcus_sp._CC9311_gi_113954242_ref_YP_729603.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._CC9311_
------------------------------------------------------MVDTP-
------------------------------------------------------------
----------------SRSP-GGAAVLDKQ------------------TERVRKTSP---
---RYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNTGIGLVIVCDIEPAE
FYCETLKNKGLTST-IEPES----------
>Synechococcus_sp._WH_8016_gi_352096458_ref_ZP_08957285.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Synechococcus_sp._WH_8016_
------------------------------------------------------MVDTP-
------------------------------------------------------------
----------------SRSP-GGAAVLDKQ------------------TERVRKTSP---
---RYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNTGVGLVIVCDIEPAE
FYCETLKNKGLTST-IEPED----------
>Synechococcus_sp._BL107_gi_116072120_ref_ZP_01469388.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._BL107_
-----------------------------------------------------MAEETP-
------------------------------------------------------------
----------------TRSP-GGAAVLDKA------------------PERVRKRSP---
---RYKVLLHNDPVNSMEYVMATLRQVVPQLSEQDAMAVMLEAHNTGIGLVIVCDIEPAE
FYCETLKSKGLTST-IEPED----------
>Synechococcus_sp._CC9902_gi_78185599_ref_YP_378033.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._CC9902_
-----------------------------------------------------MAEETP-
------------------------------------------------------------
----------------TRSP-GGAAVLDKA------------------PERVRKRSP---
---RYKVLLHNDPVNSMEYVMTTLRQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDIEPAE
FYCETLKSKGLTSS-IEPED----------
>Synechococcus_sp._WH_5701_gi_87303756_ref_ZP_01086507.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_5701_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------MLLHNDPVNSMEYVMATLRQVVPQLSEQDAMAVMLEAHNTGIGLVIVCDIEPAE
FYCETLKSKGLTST-IEPED----------
>Synechococcus_sp._WH_7803_gi_148238705_ref_YP_001224092.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_7803_
---------------------------------------------------MVMAVETP-
------------------------------------------------------------
----------------SRTP-GGAAVLEKA------------------PERVRKQSP---
---RYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAE
FYCETLKGKGLTST-IEPEN----------
>Synechococcus_sp._WH_8102_gi_161353432_ref_NP_898239.2__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_8102_
---------------------------------------------------MAMAVDTP-
------------------------------------------------------------
----------------TRSP-GGAAVMEKA------------------PERVRKQSP---
---RYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEAHNTGVGLVIVCDLEPAE
FYCETLKAKGLTST-IEPET----------
>Synechococcus_sp._WH_8102_gi_33633458_emb_CAE08663.1__conserved_hypothetical_protein__Synechococcus_sp._WH_8102_
MASAPQVRATSDCPPSTAAPTW---MLLWPESRPSEQVVQRFPLDLNLPNTMAMAVDTP-
------------------------------------------------------------
----------------TRSP-GGAAVMEKA------------------PERVRKQSP---
---RYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEAHNTGVGLVIVCDLEPAE
FYCETLKAKGLTST-IEPET----------
>Synechococcus_sp._WH_7805_gi_88807954_ref_ZP_01123465.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_7805_
-----------------------------------------------------MAVETP-
------------------------------------------------------------
----------------SLTP-GGAAVLDKA------------------PERVRKQSP---
---RYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAE
FYCETLKGKGLTST-LEPDT----------
>Synechococcus_sp._WH_8109_gi_260434316_ref_ZP_05788286.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_8109_
----------------------------------MSRSISLFPLNLKVFGSMVMAVDSP-
------------------------------------------------------------
----------------SQKP-GGAAVLDKA------------------PERVRKRSP---
---RYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAE
FYCEMLKSKGLTSS-IEPEE----------
>Synechococcus_sp._CC9605_gi_78211862_ref_YP_380641.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._CC9605_
---------------------------------------------------MVMAVESP-
------------------------------------------------------------
----------------SQKP-GGAAVLDKA------------------PEKVRKRSP---
---RYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAE
FYCETLKSKGLTSS-IEPEN----------
>Synechococcus_sp._RS9916_gi_116075699_ref_ZP_01472958.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._RS9916_
-----------------------------------------------------MAVNTT-
------------------------------------------------------------
----------------SPGP-GGAAVLDKQ------------------TERVRKRSP---
---RYKVLLHNDPVNSMEYVVSTLQQVVPQLSEQDAMAVMLEAHNSGVGLVIVCDLEPAE
FYCETLKAKGLTST-LEPES----------
>Prochlorococcus_marinus_str._MIT_9303_gi_124024066_ref_YP_001018373.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9303_
-------------------------------------MGERPTYIGALPIVLAMAVNAP-
------------------------------------------------------------
----------------SPSP-GGAAVLEKQ------------------TERIRKQSP---
---HYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAE
FYCETLKAKGLTST-LEQES----------
>Prochlorococcus_marinus_str._MIT_9313_gi_33864059_ref_NP_895619.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9313_
---------------------------MKLGLPTICTMGERPTYIGAVPIVLAMAVNAP-
------------------------------------------------------------
----------------SPTP-GGAAVLEKQ------------------TERIRKQSP---
---HYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAE
FYCETLKAKGLTST-LEQES----------
>Synechococcus_sp._RS9917_gi_87125032_ref_ZP_01080879.1__hypothetical_protein_RS9917_03483__Synechococcus_sp._RS9917_
----------------------------------------------MHRSDLAMVGSTS-
------------------------------------------------------------
----------------STSP-GGAAVLDKQ------------------TERVRKHSP---
---RYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAE
FYCETLKAKGLTST-LEPET----------
>Prochlorococcus_marinus_subsp._marinus_str._CCMP1375_gi_33241103_ref_NP_876045.1__clpS_gene_product__Prochlorococcus_marinus_subsp._marinus_str._CCMP1375_
------------------------------------------------------MVGNP-
------------------------------------------------------------
----------------GRGP-GGAAVVDKQ------------------TERVRKTSP---
---RYKVLLHNDPVNTMDYVVTTLRQVVPQLSEQDAMAVMLETHNTGIGLVITCDLEPAE
FYSESLKGKGLTST-IEPES----------
>Cyanobium_sp._PCC_7001_gi_254430350_ref_ZP_05044053.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanobium_sp._PCC_7001_
-------------------------------------------MTAAAMTTVPQATQTP-
------------------------------------------------------------
----------------SRE--SGAAVMEKA------------------PERVRKPSP---
---RYKVLLHNDPVNSMEYVVTTLRQVVPSLSEQDAIAVMLEAHNTGVGLVIVCDLEPAE
FYCETLKAKGLTST-LEPDD----------
>Synechococcus_sp._CB0205_gi_317968680_ref_ZP_07970070.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._CB0205_
---------------------------------------------------MIRSTQAP-
------------------------------------------------------------
----------------GRES-GGAAVMEKA------------------PERVRKPSP---
---RYKVLLHNDPVNTMEYVVSTLRQVVPSLSEQDAIAVMMEAHNTGVGLVIVCDIEPAE
FYSETLKAKGLSST-IEPED----------
>Synechococcus_sp._CB0101_gi_318042663_ref_ZP_07974619.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._CB0101_
------------------------------------MPELDWMPRSTPCTAAFTATQTP-
------------------------------------------------------------
----------------GRES-GGGAVMEKA------------------PERVRKPSP---
---RYKVLLHNDPVNTMEYVVGTLRQVVPSLSEQDAIAVMLEAHNTGVGLVIVCDIEPAE
FYSETLKAKGLTST-IEPES----------
>Synechococcus_sp._WH_5701_gi_87301880_ref_ZP_01084714.1__hypothetical_protein_WH5701_01105__Synechococcus_sp._WH_5701_
------------------------------------------------MSDTIRATETP-
------------------------------------------------------------
----------------TRSP-GGAAVIEKE------------------VQRVRKPSP---
---RYRVLLHNDPVNSMEYVVTTLRQVVPSLSEQDAIAVMLEAHNTGVGLVIVCDLEPAE
FYSETLKAKGLSST-IEPES----------
>Synechococcus_sp._RCC307_gi_148243279_ref_YP_001228436.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._RCC307_
---------------------------------------------------MTHASETP-
------------------------------------------------------------
----------------VSSPGGGAAVMERQ------------------PETVRKPSP---
---RYRVLLHNDPVNSMEYVVTSLREVVPSLSEQDAMAVMLEAHNSGVGLVIVCDIEPAE
FYCESLKAKGLTST-IEPEE----------
>Prochlorococcus_marinus_str._MIT_9515_gi_123966912_ref_YP_001011993.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9515_
----------------------------------------------------MSIIKLE-
------------------------------------------------------------
----------------KGDN-NNAAVLEKK------------------TAALKNKSP---
---KYKVLLHNDPVNSMEYITIALREVVPQLSEQDAIAIMLEAHNNGVGLVIVCDLEPAE
FYSESLKSKGISSS-IEKDE----------
>Prochlorococcus_marinus_str._AS9601_gi_123969234_ref_YP_001010092.1__clpS_gene_product__Prochlorococcus_marinus_str._AS9601_
----------------------------------------------------MLSIKLE-
------------------------------------------------------------
----------------QSGS-NNSAVIEKK------------------PAELKNKSP---
---KYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTGIGLVIVCDLEPAE
FYSESLKSKGISSS-IEKED----------
>Prochlorococcus_marinus_str._MIT_9202_gi_254526054_ref_ZP_05138106.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9202_
----------------------------------------------------MLSIKLE-
------------------------------------------------------------
----------------QSVS-NGSAVIEKK------------------PAELKNKSP---
---KYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTGIGLVIICDLEPAE
FYSESLKSKGISSS-IEKED----------
>Prochlorococcus_marinus_str._MIT_9312_gi_78779975_ref_YP_398087.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9312_
----------------------------------------------------MLSIKLE-
------------------------------------------------------------
----------------QSVS-NNSAVIEKK------------------PAELKNKSP---
---KYRVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTGVGLVIVCDLEPAE
FYSESLKSKGISSS-IEKED----------
>Prochlorococcus_marinus_str._MIT_9215_gi_157414100_ref_YP_001484966.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9215_
----------------------------------------------------MSSIKLE-
------------------------------------------------------------
----------------QRVS-NSSAVIEKK------------------PAELKNKSP---
---KYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTGIGLVIICDLEPAE
FYSESLKSKGISSS-IEKED----------
>Prochlorococcus_marinus_str._MIT_9301_gi_126697028_ref_YP_001091914.1__hypothetical_protein_P9301_16901__Prochlorococcus_marinus_str._MIT_9301_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MEYVTISLREVVPQLSEQDAIAIMLEAHNTGVGLVIVCDLEPAE
FYSESLKSKGISSS-IEKED----------
>Prochlorococcus_marinus_subsp._pastoris_str._CCMP1986_gi_33862055_ref_NP_893616.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_subsp._pastoris_str._CCMP1986_
---------------------------------------MINRFSCNYNQKVMSNIKFE-
------------------------------------------------------------
----------------KGEN-NNAAVLEKK------------------TAPLKNKSP---
---KYKVLLHNDPVNSMEYVTNALREVVPQLSEQDAISIMLEAHNTGVGLVIVCDLEPAE
FYSESLKSKGISSS-IEKED----------
>Prochlorococcus_marinus_str._MIT_9211_gi_159904162_ref_YP_001551506.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9211_
-----------------------------------------MSLVDWNYLPTGIMVEAT-
------------------------------------------------------------
----------------GSSP-GGATVIEKQ------------------SELVRKRSP---
---RYKVLLHNDPVNSMDYVVTTLRQVVPQLSEQDALAVMLEAHNTGVGLVIVCDLEPAE
FYSESLKAKGLSST-IEKET----------
>Prochlorococcus_marinus_str._NATL1A_gi_124026645_ref_YP_001015760.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._NATL1A_
----------------------------------MSNIMVSSLLKSAIHLDSLIMVDSA-
------------------------------------------------------------
----------------NQTD-GDTAVIDRE------------------VQRVRKISP---
---KYKVLLHNDPVNTMDYVVDTLRQVVPQLSEQDALNIMLETHNNGVGLVITCDLEPAE
FYSESLKAKGLTST-IELES----------
>Prochlorococcus_marinus_str._NATL2A_gi_72382903_ref_YP_292258.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._NATL2A_
----------------------------------MSNIMVNSLSKSAIHLESLIMVDSA-
------------------------------------------------------------
----------------NQTD-GDTAVIDRE------------------VQRVRKISP---
---KYKVLLHNDPVNTMDYVVEILRQVVPQLSEQDALNIMLETHNNGVGLVITCDLEPAE
FYSESLKAKGLTST-IELES----------
>Gloeobacter_violaceus_PCC_7421_gi_37520315_ref_NP_923692.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Gloeobacter_violaceus_PCC_7421_
------------------------------------------------------------
------------------------------------------------------------
---------------------MSTETLERK-------------------SVQRKPMP---
---LYKVLLHNDDHTPMNYVIEVLMKTIPKMQPSKARKIMLEAHNGGVAVVIVCALEHAE
FYSESLNRHNLTST-YEPDC----------
>Oryza_sativa_Japonica_Group_gi_115476544_ref_NP_001061868.1__Os08g0432500__Oryza_sativa_Japonica_Group_
MEAAVPSRVALS-ASRLSNHHHHA-VGGER----------YAIYRGRCPNPAIPMALAA-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-IEKV-TPGRQS---EFDVRKSRKMTP---
---PYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIICSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_195652021_gb_ACG45478.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS_containing_protein__Zea_mays_
MMASVPSRVALSAASRLPN--LHA-VAGDR----------SFIYKRRCPSLSIPMAL-S-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-VEKI-TPGRQS---EFDVKKSRKMTP---
---PFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALSIMQEAHVNGLSVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_226493842_ref_NP_001148322.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS_containing_protein__Zea_mays_
MMASVPSRVALSAASRLPN--LHA-VAGDR----------SFIYKRRCPSLSIPMAL-S-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-VEKI-TPGRQS---EFDVKKSRKMTP---
---PFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALNIMQEAHVNGLSVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_223948869_gb_ACN28518.1__unknown__Zea_mays_
------------------------------------------------------MAL-S-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-VEKI-TPGRQS---EFDVKKSRKMTP---
---PFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALNIMQEAHVNGLSVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_223943781_gb_ACN25974.1__unknown__Zea_mays_
------------------------------------------------------MAL-S-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-VEKT-TPGRQS---EFDVKKSRKMSP---
---PYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_226506038_ref_NP_001150373.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS_containing_protein__Zea_mays_
MEAAVPSRVALSAASRLPN--PHA-VTGDR----------SFIYKGRCQSLAIPMAL-S-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-VEKT-TPGRQS---EFDVKKSRKMSP---
---PYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Sorghum_bicolor_gi_242081547_ref_XP_002445542.1__hypothetical_protein_SORBIDRAFT_07g021160__Sorghum_bicolor_
MEAAVPSRVALSAASRLPN--RHA-VAGDR----------SFVYKGRCQSLAIPMAL-S-
------------------------------------------------------------
----------------AAAPGK-GGVLDRP-VEKT-TPGRQS---EFDVKKSRKMSP---
---PYRVILHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Oryza_sativa_Japonica_Group_gi_125603506_gb_EAZ42831.1__hypothetical_protein_OsJ_27419__Oryza_sativa_Japonica_Group_
MEAAVPSRCG---ALREPALQPPP-PRGER----------YAIYRGRCPNPAIPMALAA-
------------------------------------------------------------
----------------AAAPGKGGGVLDRP-IEKV-TPGRQS---EFDVRKSRKMTP---
---PYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIICSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Brachypodium_distachyon_gi_357147864_ref_XP_003574520.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS-like__Brachypodium_distachyon_
MEAAVPSRIALS--ARIMN-HHVV-AAGGR----------SSIYRGRYPNIAIPIVV---
------------------------------------------------------------
-----------------TAAGKGGGVLDRP-AEKI-SPGRQS---EFDVKKSRKMSP---
---PYRVVLHNDNENRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLAVVIVCSQSEAE
EHCTSLRGNGLRSS-IEPASGG-------C
>Arabidopsis_thaliana_gi_145326694_ref_NP_001077794.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arabidopsis_thaliana_
METAICGRLALA-----PSSLFNS-KSGDK----------HLVSKGPCVNRSILMTLST-
------------------------------------------------------------
----------------SAALGKGGGVLDKPIIEKT-TPGRES---EFDLRKSKKIAP---
---PYRVILHNDNFNKREYVVQVLMK------------------------------ADAE
QHCMQLRGNGLLSS-VEPDGGG-------C
>Arabidopsis_thaliana_gi_18409086_ref_NP_564937.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arabidopsis_thaliana_
METAICGRLALA-----PSSLFNS-KSGDK----------HLVSKGPCVNRSILMTLST-
------------------------------------------------------------
----------------SAALGKGGGVLDKPIIEKT-TPGRES---EFDLRKSKKIAP---
---PYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAE
QHCMQLRGNGLLSS-VEPDGGG-------C
>Arabidopsis_lyrata_subsp._lyrata_gi_297841589_ref_XP_002888676.1__hypothetical_protein_ARALYDRAFT_894639__Arabidopsis_lyrata_subsp._lyrata_
METAICGRLALA-----PSSLFNS-KSGDK----------HLVSKGPCVNRGVLMTLST-
------------------------------------------------------------
----------------YAALGKGGGVLDKPIIEKT-TPGRES---EFDLRKSKKMAP---
---PYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAE
QHCMQLRGNGLLSS-VEPDGGG-------C
>Vitis_vinifera_gi_147805878_emb_CAN78258.1__hypothetical_protein_VITISV_026645__Vitis_vinifera_
METAICGRVPLS-----PNXFFTS-KS---------------------------------
------------------------------------------------------------
------------------APGKGSGVLERPTIERI-MPGRES---EFDLRKSRKMSP---
---PYRVLLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQVDAE
XHCMQLRGNGLLSS-IEPASGG-------C
>Vitis_vinifera_gi_225455872_ref_XP_002274839.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS__Vitis_vinifera_
METAICGRVPLS-----PNHFFTS-KSGDK----------HSLSK-QWTHRTMLMTVSA-
------------------------------------------------------------
-----------------AAPGKGSGVLERPTIERI-MPGRES---EFDLRKSRKMSP---
---PYRVLLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQVDAE
DHCMQLRGNGLLSS-IEPASGG-------C
>Populus_trichocarpa_gi_224099343_ref_XP_002311446.1__predicted_protein__Populus_trichocarpa_
METAICGRIALS-----PNHVFNP-KPGDK----------NSVCRGPCANRGILMAIST-
------------------------------------------------------------
-----------------TCSGKGGGLLEKPVIERT-TPGRES---EFDLRKSKKMAP---
---PYRVMLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAE
EHCMQLRGNGLLSS-IEPASGG-------C
>Populus_trichocarpa_gi_224111728_ref_XP_002315955.1__predicted_protein__Populus_trichocarpa_
METAICGRIALS-----PNHVFNP-KPGDK----------NSVCRGPCASRGILMSISAT
VS----------------------------------------------------------
----------------GKGGGGGGGILEKPVIERT-TPGRES---EFDLRKSKKMAP---
---PYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICTQADAE
EHCMQLRGNGLLSS-IEPASGG-------C
>Ricinus_communis_gi_255576515_ref_XP_002529149.1__ATP-dependent_Clp_protease_adaptor_protein_clpS__putative__Ricinus_communis_
------------------------------------------------------MALSA-
------------------------------------------------------------
-----------------TGAGKGGGLLEKPVIEKT-TPGRES---EFDLRKSRKTAP---
---PYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAE
DHCMQLRGNGLLSS-IEPASGG-------C
>Glycine_max_gi_351721328_ref_NP_001235414.1__uncharacterized_protein_LOC100500511__Glycine_max_
MKSAICGRI-LS-----PNHVF---KPGDT----------HSICKGPYSNLCVPMVVLA-
------------------------------------------------------------
-----------------TGPGIGGGVLEKPVIEKV-TPGRES---EFDLKKSRKSAP---
---PYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAE
DHCMQLRGNGLLSS-IEPANGG-------C
>Glycine_max_gi_351723283_ref_NP_001234970.1__uncharacterized_protein_LOC100527361__Glycine_max_
MKSAICGRI-LS-----PNHVF---KPGDT----------HSICKGPYSNLCVPMAVLA-
------------------------------------------------------------
-----------------TGPGKGGGVLEKPVIEKV-TPGRES---EFDLKKSRKSAP---
---PYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAE
DHCTQLRGNGLLSS-IEPASGG-------C
>Vitis_vinifera_gi_225423913_ref_XP_002281884.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS__Vitis_vinifera_
MENAICGRLALS-----PNHVFNS-KSGDK----------HSLLKGPCTNRSFLMAISA-
------------------------------------------------------------
-----------------SGPGK-GGLLERPVIEKV-TPGRES---EFDLRKSRKIAP---
---PYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAE
DHCMQLRGNGLLSS-IEPASGG-------C
>Vitis_vinifera_gi_297737852_emb_CBI27053.3__unnamed_protein_product__Vitis_vinifera_
MENAICGRLALS-----PNHVFNS-KSGDK----------HSLLKGPCTNRSFLMAISA-
------------------------------------------------------------
-----------------SGPGK-GGLLERPVIEKV-TPGRES---EFDLRKSRKIAP---
---PYRVILHNDNYNKREYVVQVLMK------------------------------ADAE
DHCMQLRGNGLLSS-IEPASGG-------C
>Medicago_truncatula_gi_357488429_ref_XP_003614502.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Medicago_truncatula_
MKSAICRSMGLS-----PNHLF---ISGDR----------YSFCKGPYSNLCVPMAVLT-
------------------------------------------------------------
-----------------KGSGKGGGILEKPVIEKA-TPGRES---EFDLKKSRKTAP---
---PYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQADAE
DHCMQLRGNGLLSS-IEPAGDG-------C
>Picea_sitchensis_gi_294460817_gb_ADE75982.1__unknown__Picea_sitchensis_
MASVIYSRLILP-----QPQLYQQ-KSGEK----------ISQSKGACMNRVFSAIRST-
------------------------------------------------------------
-----------------SPGGKGGGLLERPTIEKT-TPGRES---EFDLRKSRKTSP---
---PYRVLLHNDNYNKREYVVQVLMKVIPGMTLDTAVNIMQEAHYNGLAVVIICAQVDAE
EHCTQLRGNGLLSS-IEPASDG-------C
>Glycine_max_gi_351724025_ref_NP_001237811.1__uncharacterized_protein_LOC100306117__Glycine_max_
MEAALCSALAPS-----PNQVFNAANPGDK-----------NVPLKYSKDRSVVMTVAA-
------------------------------------------------------------
----------------TGILGKGGGLLERPTIETT-SPGRES---EFDLRKSRKTSP---
---PYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAE
DHCMQLRGNGLLSS-IEPADGGG------C
>Glycine_max_gi_356531226_ref_XP_003534179.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS-like__Glycine_max_
MEAALCSALALS-----PNQVFNAANPGDK-----------NVPLKYSKDRSVVMTVAA-
------------------------------------------------------------
----------------TGILGKGGGLLERPTIETT-SPGRES---EFDLRKSRKTSP---
---PYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAE
DHCMQLRGNGLLSS-IEPADGGG------C
>Physcomitrella_patens_gi_121489819_emb_CAK19331.1__putative_adaptor_protein_ClpS__Physcomitrella_patens_
MAGSLRLFVSIPATARH--------FGING----------VEKAQRVHNRVNGRYKINA-
------------------------------------------------------------
----------------ASGPSQGGGVLDRPTIDKP-TPGRES---EFDLKKKKKISP---
---PYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLAVVIVCPQEDAE
DYCMQLRTNGLLSS-IEPAS---------C
>Physcomitrella_patens_subsp._patens_gi_168011584_ref_XP_001758483.1__predicted_protein__Physcomitrella_patens_subsp._patens_
------------------------------------------------------------
------------------------------------------------------------
---------------------QGGGVLDRPTIDKP-TPGRES---EFDLKKKKKMSP---
---PYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLAVVIVCPQEDAE
DYCMQLRTNGLLSS-IEP------------
>Physcomitrella_patens_subsp._patens_gi_168014848_ref_XP_001759963.1__predicted_protein__Physcomitrella_patens_subsp._patens_
------------------------------------------------------------
------------------------------------------------------------
----------------AAAPGQGGGVMDRPTIDKP-TPGRES---EFDLKKKKKMSP---
---PYRVMLHNDNFNKREYVVQVLLKAIPGMTVDIAVNVMNEAHINGIAVVIVCPQEDAE
DYCMQLRTNGLLSS-IEPD-----------
>Selaginella_moellendorffii_gi_302761288_ref_XP_002964066.1__hypothetical_protein_SELMODRAFT_142341__Selaginella_moellendorffii_
MACTLTQVAHLWPSTSQVSRFNTIFAEADK-------------CHKCFTRIIASHAVRA-
------------------------------------------------------------
----------------ALPGGLGGGVLDKPAIETAPTPGRES---EFDLRKKKKMAP---
---PYRVILHNDNFNRREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGLSVVIVCSQEDAE
EHCTQLRANGLLSS-IEPASGGS------C
>Chlorella_variabilis_gi_307105846_gb_EFN54094.1__hypothetical_protein_CHLNCDRAFT_31972__Chlorella_variabilis_
MTICVGQRLGGQAVAGKAGDKPPTRGAWLVPAGATRRSAQRRARLHVA------------
------------------------------------------------------------
----------------ARSAGKGGGVLDRP----GVLPGQ-----QRGRETRRRRPP---
---SYRVLLHNDNYNRREYVVQVLMKVVEGTTVDDAVNIMQEAHINGLAMVTQCAQDKAE
LYCESLRLNGLIAT-IEPAGTGGSDGTSSS
>Chlamydomonas_reinhardtii_gi_159467236_ref_XP_001691804.1__clp_protease_adaptor_protein__Chlamydomonas_reinhardtii_
M------------MTRSPVAGLPRPCSALQRSGCT--LQGAFG--TFAPQTTRTFVVTW-
------------------------------------------------------------
----------------AK-----GGVMDAP------TTTQQP---ASGVERSQKRPP---
---IYKVLLHNDNYNKREYVVKVLLKVVEQITVDDAVTCMQEAHETGVALVVACPQDNAE
RYCEGLRLNGLTST-IEPGG---------C
>Volvox_carteri_f._nagariensis_gi_302834902_ref_XP_002949013.1__hypothetical_protein_VOLCADRAFT_73976__Volvox_carteri_f._nagariensis_
MAASVLRPPPVSVASRAPTAAL----AVLPGSACLGWRRANFGTSTLLSQTTRTCVQMR-
------------------------------------------------------------
----------------AG----VPGLLDSP------TITSEP---QQGTDRAYKRPP---
---IYKVFLHNDNYNKREYVVKVLLKVVEEITVDDAVTVMQEAHETGVALVVACPQENAE
RYCEGLRLNGLTST-IEPAG---------R
>Ktedonobacter_racemifer_DSM_44963_gi_298245523_ref_ZP_06969329.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Ktedonobacter_racemifer_DSM_44963_
M-----------------------------------------------------------
------------------------------------------------------------
----------------AQRQCQPSRLEIRP---------------EEVVRQRSSLLP---
---LYKVILFNDDYNDMLHVVAALLETVNTLTMQEATHIMLTAHLNGNAIVIVCPHELAE
HYQERLLGYALTVT-IEPE-----------
>Guillardia_theta_gi_57335897_emb_CAH25350.1__hypothetical_protein__Guillardia_theta_
RICACVRSAWSFPVAFPAHLHHPLLRAVCFFIKWISSILWFMMGRQVLAALALLPLAWCF
QAPTSFLPGTRGITQQTCATLRPAVLGKMQLEAPERIKIPDTFNPAEWGVGGGKGGFGDG
LGGFKVPDSFNPAEMEKERQGGRTAVMDRP-------------------SDKTDPGK---
---KYKVLLFNDDKNTRQYVIDTLMKYIPGMTADKAKEITVAAHNTGMAIVGVWMYEMAE
AYSDVLRSAGLRSD-IDPE-----------
>Trichodesmium_erythraeum_IMS101_gi_113477268_ref_YP_723329.1__clpS_gene_product__Trichodesmium_erythraeum_IMS101_
MSLGISII----------------------------------------------------
------------------------------------------------------------
----------------------GIIENIAVRGGASSPTTLAP---KKDSQVVNKPYP---
---NYKVIVLNDDVNTFKHVAECLQKYIPGMTSDRAWELTYQVHNEGQAIVWVGPLEQAE
LYHQQLSRAGLTMAPLEKA-----------
>Lyngbya_sp._PCC_8106_gi_119490026_ref_ZP_01622650.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Lyngbya_sp._PCC_8106_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MTSSPTVAP---SRSSQVTQQPYP---
---NYKVIVLNDDFNTFEHVSSCLMKYIPGMNSDLAWKLTNQVHFEGQATVWVGPLEQAE
LYHTQLSREGLTMAPLEKA-----------
>Oscillatoria_sp._PCC_6506_gi_300864591_ref_ZP_07109450.1__ATP-dependent_Clp_protease_adaptor__Oscillatoria_sp._PCC_6506_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MTSSPTIAP---DRSSQVTRKPYP---
---NYKVIVLNDDFNTFQHVSECLVKYIPGMTSDRAWKLTNQVHYEGQATVWVGPQEQAE
LYHMQLSRAGLTMAPLEQA-----------
>Microcoleus_vaginatus_FGP-2_gi_334119600_ref_ZP_08493685.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Microcoleus_vaginatus_FGP-2_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MTSSPTIAP---VRSSQVTRKPYP---
---NYRVIVLNDDFNTFQHVVECLTKYIPGMTSDQAWKLANQIHHEGQATVWVGPQEQAE
LYHMQLSRAGLTMAPLEST-----------
>Arthrospira_maxima_CS-328_gi_209526864_ref_ZP_03275384.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_maxima_CS-328_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MIASPTTTP---SRSSQTVRKPYP---
---NYKVIVLNDDFNTFQHVANCLMKYLPGMTSDQAWELTNRVHYEGQATVWVGPLEQAE
LYHTQLSREGLTMAPLEKA-----------
>Arthrospira_platensis_NIES-39_gi_291567197_dbj_BAI89469.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_platensis_NIES-39_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MVASPTTTP---SRSSQTVRKPYP---
---NYKVIVLNDDFNTFQHVANCLMKYLPGMTSDQAWELTNRVHYEGQATVWVGPLEQAE
LYHTQLSREGLTMAPLEKA-----------
>Arthrospira_platensis_str._Paraca_gi_284051855_ref_ZP_06382065.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_platensis_str._Paraca_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MTSDQAWELTNRVHYEGQATVWVGPLEQAE
LYHTQLSREGLTMAPLEKA-----------
>Nodularia_spumigena_CCY9414_gi_119510612_ref_ZP_01629742.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nodularia_spumigena_CCY9414_
MVTRLS------------------------------------------------------
------------------------------------------------------------
----------------------------AAVYGAGTAPTVTP---GKTTEVVRKTYP---
---NYKVIVLNDDFNTFQHVSECLMKYIPGMTGDRAWDLTNQIHYEGQAIVWVGPQEMAE
LYHQQLRRAGLTMAPLEAA-----------
>Nostoc_sp._PCC_7120_gi_17227900_ref_NP_484448.1__clpS_gene_product__Nostoc_sp._PCC_7120_
MVTKLS------------------------------------------------------
------------------------------------------------------------
----------------------------IDVYAMSTAPTVTP---ERSNQTVRKTYP---
---NYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTNQVHYEGQAIVWVGPQEPAE
LYHQQLRRAGLTMAPLEAA-----------
>Anabaena_variabilis_ATCC_29413_gi_75909055_ref_YP_323351.1__clpS_gene_product__Anabaena_variabilis_ATCC_29413_
MVTKLS------------------------------------------------------
------------------------------------------------------------
----------------------------IDVYAMSTAPTVTP---ERSNQTVRKSYP---
---NYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTNQVHYEGQAIVWVGPQEPAE
LYHQQLRRAGLTMAPLEAA-----------
>>gi_21542305_sp_Q8YZQ3.2_CLPS_NOSS1_RecName__Full_ATP-dependent_Clp_protease_adapter_protein_ClpS_gi_21542305_sp_Q8YZQ3.2_CLPS_NOSS1_RecName__Full_ATP-dependent_Clp_protease_adapter_protein_ClpS
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSTAPTVTP---ERSNQTVRKTYP---
---NYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTNQVHYEGQAIVWVGPQEPAE
LYHQQLRRAGLTMAPLEAA-----------
>Nostoc_punctiforme_PCC_73102_gi_186684201_ref_YP_001867397.1__ATP-dependent_Clp_protease_adaptor__Nostoc_punctiforme_PCC_73102_
MVRNLS------------------------------------------------------
------------------------------------------------------------
----------------------------ADVYGMTTAPTITP---ERSSQVTRKTYP---
---NYKVIVLNDDFNTFQHVAECLMKYIPGMSGDRAWDLTNQVHYEGQAIVWVGPQEPAE
LYHQQLRRAGLTMAPLEAA-----------
>Nostoc_azollae_0708_gi_298491120_ref_YP_003721297.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nostoc_azollae_0708_
METRLA------------------------------------------------------
------------------------------------------------------------
----------------------------AVYYDMATAPTVTP---DRVNQVTRKTYP---
---NYKVIVLNDDFNTFQYVAECLMKYIPGMSGDLAWDLTNQVHYEGQAIVWVGPQEPAE
LYHQQLRRAGLTMAPLEGA-----------
>Fischerella_sp._JSC-11_gi_354566811_ref_ZP_08985982.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Fischerella_sp._JSC-11_
MITKLS------------------------------------------------------
------------------------------------------------------------
----------------------------AAVYAMAATPTIAP---ERSTQVTRKPYP---
---NYKVIVLNDDFNTFQHVAECLVKYIPGMTSDRAWELTNQVHYEGQAIVWTGPQEPAE
LYHQQLRRAGLTMAPLEAA-----------
>Cyanothece_sp._CCY0110_gi_126656780_ref_ZP_01727994.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._CCY0110_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MATSTSTAP---KGSTVIDRKPYP---
---NYKVIVLNDDFNTFNHVANCLMKYIPGMSSDRAWELTEQVHFEGLAIVWTGPQEQAE
LYHQQLRREGLTMAPLEEA-----------
>Cyanothece_sp._ATCC_51142_gi_172038476_ref_YP_001804977.1__putative_ATP-dependent_Clp_protease_adaptor_protein__Cyanothece_sp._ATCC_51142_
MSKRLS------------------------------------------------------
------------------------------------------------------------
----------------------------TGIQGMATSTSTAP---KGSTVIDRKPYP---
---NYKVIVLNDDFNTFNHVANCLMKYIPGMSSDRAWELTEQVHFEGLAIVWTGPQEQAE
LYHQQLRREGLTMAPLEEA-----------
>Crocosphaera_watsonii_WH_0003_gi_357261617_gb_EHJ10864.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_0003_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MATSTSTAP---KGATVVERKHYP---
---NYKVIVLNDDFNTFDHVAKCLLKYIPGMSSDRAWELTEQVHFEGLATVWTGPQEQAE
LYHQQLRREGLTMAPLEEA-----------
>Crocosphaera_watsonii_WH_8501_gi_67924463_ref_ZP_00517887.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_8501_
MSKRLS------------------------------------------------------
------------------------------------------------------------
----------------------------IGIRGMATSTSTAP---KGATVVERKRYP---
---NYKVIVLNDDFNTFDHVAKCLLKYIPGMSSDRAWELTEQVHFEGLATVWTGPQEQAE
LYHQQLRREGLTMAPLEEA-----------
>Microcystis_aeruginosa_PCC_7806_gi_159031002_emb_CAO88704.1__clpS__Microcystis_aeruginosa_PCC_7806_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MASAPSTTL---DKSTQGVKKTYP---
---NYKVIVLNDDFNTFDHVANCLIKYIPDMTTDRAWELTNQVHYQGQAIVWTGPQEPAE
LYHQQLRREGLTMAPLEAV-----------
>Microcystis_aeruginosa_NIES-843_gi_166363445_ref_YP_001655718.1__ATP-dependent_Clp_protease_adaptor__Microcystis_aeruginosa_NIES-843_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MSSAPSTTL---DKSTQVVKKTYP---
---NYKVIVLNDDFNTFDHVANCLIKYIPDMTTDRAWELTNQVHYQGQAIVWTGPQEQAE
LYHQQLRREGLTMAPLEAA-----------
>Cyanothece_sp._PCC_8801_gi_218246561_ref_YP_002371932.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_8801_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MATAPSVAP---KGSTAVVNKPYP---
---NYKVIVLNDDFNSFEHVAKCLMTYIPGMTSDRAWELTNQVHFEGQATVWVGPQEQAE
LYHQQLRREGLTMAPLEKA-----------
>Cyanothece_sp._PCC_7424_gi_218441397_ref_YP_002379726.1__ATP-dependent_Clp_protease_adaptor__Cyanothece_sp._PCC_7424_
MSTNVA------------------------------------------------------
------------------------------------------------------------
----------------------------AVVTAMTTAPTIAP---DKTTQVVKKTYP---
---NYKVIVLNDDFNTFQHVANCLMKYIPGMTSDRAWELTNQVHYEGQATVWVGPQEQAE
LYHQQLRREGLTMAPLEAA-----------
>Cyanothece_sp._PCC_7822_gi_307150152_ref_YP_003885536.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7822_
MSTNVA------------------------------------------------------
------------------------------------------------------------
----------------------------AVVKAMATAPTVAP---DKTTQVVKKTYP---
---NYKVIVLNDDFNTFEHVAKCLMKYIPGMTSDRAWELTNQVHFEGQAIVWVGPQEQAE
LYHQQLRREGLTLAPLEAA-----------
>Microcoleus_chthonoplastes_PCC_7420_gi_254412762_ref_ZP_05026535.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Microcoleus_chthonoplastes_PCC_7420_
MTVVIS------------------------------------------------------
------------------------------------------------------------
----------------------------AARSATSAAPTQAP---EKSRQVTRKPYP---
---NYKVIVLDDDFNTFQHVHDCLVKYIPGMSSDYAWKLTNQVHFEGQAIVWVGPQEQAE
LYHQQLSRAGLTMAPLEAA-----------
>Lyngbya_majuscula_3L_gi_332708950_ref_ZP_08428921.1__hypothetical_protein_LYNGBM3L_32060__Lyngbya_majuscula_3L_
--MVRS------------------------------------------------------
------------------------------------------------------------
----------------------------AAYKATFAAPVKAP---ERSGQVTRKPYP---
---KYKVIVLDDDFNTFQHVHDCLVKYIPGMTNDHAWELTHQVHNEGQAIVWVGPQEQAE
LYHQQLSRAGLTMAPLEAT-----------
>Raphidiopsis_brookii_D9_gi_282895992_ref_ZP_06304023.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Raphidiopsis_brookii_D9_
M-KTRP------------------------------------------------------
------------------------------------------------------------
----------------------------SPIYAMAPAPTVTP---DQGTQVIRKPYP---
---NYKIIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWELTNQVHYEGQAIVWVGPQEQAE
LYHQQLRRAGLTMAPLEAA-----------
>Cylindrospermopsis_raciborskii_CS-505_gi_282901708_ref_ZP_06309624.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cylindrospermopsis_raciborskii_CS-505_
M-KTRP------------------------------------------------------
------------------------------------------------------------
----------------------------SPVYAMASAPTVTP---DQGTQVVRKPYP---
---NYKVIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWELTNQVHYEGQAIVWVGPQEQAE
LYHQQLRRAGLTMAPLEAA-----------
>Thermosynechococcus_elongatus_BP-1_gi_22298631_ref_NP_681878.1__clpS_gene_product__Thermosynechococcus_elongatus_BP-1_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MPSVVP---QERQQVTRKHYP---
---NYKVIVLNDDFNTFQHVAACLMKYIPNMTSDRAWELTNQVHYEGQAIVWVGPQEQAE
LYHEQLLRAGLTMAPLEPE-----------
>Synechocystis_sp._PCC_6803_gi_16330271_ref_NP_440999.1__ATP-dependent_Clp_protease_adaptor__Synechocystis_sp._PCC_6803_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MISNAATSTP---DRLTSTVRKTYP---
---NFKVIVLNDDFNTFQHVSDCLLKYIPGMTGDRAWELTNQVHFDGLAIVWVGPQEQAE
LYHQQLRREGLTMAPLEKA-----------
>Synechococcus_sp._PCC_7002_gi_170078679_ref_YP_001735317.1__putative_ATP-dependent_Clp_protease_adaptor_protein__Synechococcus_sp._PCC_7002_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MAPAPGILK---ESDRQTVRKPYP---
---NFKVIVLNDDFNTFEHVAHCLMTYIPNMTADQAWNLTNQVHFDGQAIVWVGPQEPAE
LYHQQLRREGLTMAPLEAA-----------
>Synechococcus_sp._PCC_7335_gi_254421403_ref_ZP_05035121.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._PCC_7335_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------MLNDDFNTFEHVVKTLTTYIPGMNSDQAWELADQIHNEGQAIVWTGPLEQAE
LYHSQLIRAGLTVAPLEKA-----------
>Acaryochloris_marina_MBIC11017_gi_158337023_ref_YP_001518198.1__clpS_gene_product__Acaryochloris_marina_MBIC11017_
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MQTPVTRP-EEKQAQKTVRKPYP---
---NFKVIVVNDDVNTFEHVAKTLMTYIPHMTSDKAWELTNQIHFEGQAIVWVGPQEQAE
LYHMQLQRAGLTMAPLEAA-----------
>Acaryochloris_sp._CCMEE_5410_gi_359459224_ref_ZP_09247787.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Acaryochloris_sp._CCMEE_5410_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MAITAVQTPVTRP-EEKQAQKTVRKPYP---
---NFKVIVVNDDVNTFEHVAKTLMTYIPHMTSDKAWELTNQIHFEGQAIVWVGPQEQAE
LYHMQLQRAGLTMAPLEAA-----------
>Synechococcus_elongatus_PCC_6301_gi_56751052_ref_YP_171753.1__clpS_gene_product__Synechococcus_elongatus_PCC_6301_
MSPQPDESVLSILGVPRPCVKKRSRNDA--------------------------------
------------------------------------------------------------
----------------------FVLTVLTCSLQAIAAPATAP---GTTTTRVRQPYP---
---HFRVIVLDDDVNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAE
LYHEQLRREGLTMAPLEAA-----------
>Synechococcus_elongatus_PCC_7942_gi_81299287_ref_YP_399495.1__clpS_gene_product__Synechococcus_elongatus_PCC_7942_
MSPQPDESVLSILGVPRPCVKKRSRDDA--------------------------------
------------------------------------------------------------
----------------------FVLTVLTCSLQAIAAPATAP---GTTTTRVRQPYP---
---HFRVIVLDDDVNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAE
LYHEQLRREGLTMAPLEAA-----------
>Cyanothece_sp._PCC_7425_gi_220909224_ref_YP_002484535.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7425_
MVRPIQTS----------------------------------------------------
------------------------------------------------------------
----------------------------SLSPLAVATPRQSP-TPVQDRQTIRQPYP---
---HYKVIVLNDDFNTFEHVAKCLMKYIPNMTSDRAWELTYQVDREGQAIVWVGPQEQAE
LYHLQLGQAGLTMAPLELA-----------
>Gloeobacter_violaceus_PCC_7421_gi_37521807_ref_NP_925184.1__ATP-dependent_Clp_protease_adaptor__Gloeobacter_violaceus_PCC_7421_
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MSSATVTP---TKPETSVKALKP---
----WKVIVLNDDFNTFQHVANCLVKYIPHMHPDRAWKLTQQVHSEGRAIVWVGPLEQAE
LYHEQLSREGLTMAPLEQA-----------
>Synechococcus_sp._JA-3-3Ab_gi_86606056_ref_YP_474819.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._JA-3-3Ab_
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------TTEAPTRPAQQS---SPSRTRVRQPYP---
---HFKVIVLDDDFNTFQHVTECLLKYIPGMTLPLARQLTVQVDAEGQAVVWVGPQEQAE
LYHQQLLREGLTMAPLEPA-----------
>Synechococcus_sp._JA-2-3Ba_2-13__gi_86610000_ref_YP_478762.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._JA-2-3Ba_2-13__
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------TTEAPTRPAQQF---SPSRTQVRQPYP---
---HFKVIVLDDDFNTFQHVTECLLKYIPGMTLPLARQLTVQVDAEGQAVVWVGPQEQAE
LYHQQLLREGLTMAPLEPA-----------
>Synechococcus_sp._CC9311_gi_113955042_ref_YP_730629.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CC9311_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTMATPGTAS---VLQPERTTLRYP---
---NARVIVLNDDVNTFEHVVECLCKIIPGMNSDKAWTLAHQIDGEGAAEVWAGPLEPAE
LYHQQLSSEGLTMAPLERN-----------
>Synechococcus_sp._WH_8016_gi_352093981_ref_ZP_08955152.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_8016_
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MATPGTAS---VLQPERTTLRYP---
---NARVIVLNDDVNTFEHVVECLCKIIPGMNSDKAWTLAHQIDGEGSAEVWAGPLEPAE
LYHQQLSSEGLTMAPLERN-----------
>Synechococcus_sp._BL107_gi_116070493_ref_ZP_01467762.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._BL107_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTSSSPSSST---LLERQKTTQRYP---
---EAKVIVLDDDVNTFQHVVDCLRKIIPGMDEDKAWGLAHRIDGEGSAEVWRGPLEQAE
LYHQQLQTEGLTMAPLDRC-----------
>Synechococcus_sp._CC9902_gi_78184628_ref_YP_377063.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CC9902_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTSSSPSSST---LLERQKTTQRYP---
---EAKVIVLDDDVNTFQHVVDCLRKIIPGMDEEKAWGLAHRIDGQGSAEVWRGPLEQAE
LYHLQLQTEGLTMAPLDRC-----------
>Synechococcus_sp._WH_8109_gi_260434286_ref_ZP_05788256.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_8109_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTSSSPGSSA---VLERQGTTQRYP---
---QARVIVLDDDVNTFQHVVDCLRKIIPGMSEDNAWNLANRIDGHGAAEVWCGPLEQAE
LYHQQLQSEGLTMAPLERC-----------
>Synechococcus_sp._CC9605_gi_78212974_ref_YP_381753.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CC9605_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTSSSPGSSA---VLERQGTTQRYP---
---QARVIVLDDDVNTFQHVVDCLRKIIPGMSEDNAWNLANRIDGQGSAEVWCGPLEQAE
LYHQQLQAEGLTMAPLERC-----------
>Synechococcus_sp._WH_8102_gi_33865838_ref_NP_897397.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._WH_8102_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MSSSSPGSAS---LLERQTITQRYP---
---QARVIVLDDDVNTFQHVVDCLRKIIPGMSEEKAWSLANRIDGQGSAEVWCGPLEQAE
LYHQQLAAEGLTMAPLERC-----------
>Prochlorococcus_marinus_str._MIT_9303_gi_124023254_ref_YP_001017561.1__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._MIT_9303_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTFATPGSTP---LLERAKQTQRYP---
---QARVIVLNDDVNTFQHVVDCLRRIIPGMSEERAWNLAHQIDGQGSAEVWCGPLEQAE
LYHQQLSGEGLTMAPLERC-----------
>Prochlorococcus_marinus_str._MIT_9313_gi_33862944_ref_NP_894504.1__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._MIT_9313_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTFATPGTTP---LLERAKQTQRYP---
---QARVIVLNDDVNTFQHVVDCLRRIIPGMSEERAWNLAHQIDGQGSAEVWCGPLEQAE
LYHQQLSGEGLTMAPLERC-----------
>Synechococcus_sp._RS9916_gi_116074794_ref_ZP_01472055.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._RS9916_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTGSSGAQST---LLERSRTTQGYP---
---EARVIVLNDDVNTFQHVVDCLCKIIPGMGTERAWDLAHQVDGQGSAEVWCGPLEQAE
LYHQQLTGEGLTMAPIERC-----------
>Synechococcus_sp._WH_7803_gi_148239546_ref_YP_001224933.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._WH_7803_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTSSSPGVST---VLERDRQAQRYP---
---QARVIVLNDDFNTFEHVVESLCRIIPGMNTEKAWSLAHRIDGEGAAEVWCGPLEQAE
LYHQQLGAEGLTMAPIERC-----------
>Synechococcus_sp._WH_7805_gi_88808607_ref_ZP_01124117.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_7805_
MYLLVQASCSRAL-----------------------------------------------
------------------------------------------------------------
--------------------------------MTSSSPGVST---VLERDRQALRYP---
---QARVIVLNDDVNTFEHVVESLCRIIPGMNTDKAWALARRVDGEGSAEVWCGPLEQAE
LYHQQLGADGLTMAPIERC-----------
>Synechococcus_sp._RS9917_gi_87124406_ref_ZP_01080255.1__hypothetical_protein_RS9917_12370__Synechococcus_sp._RS9917_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTVTPTGTAT---VLDRATSRSDYP---
---QARVIVLDDDVNTFQHVVDCLCRIIPGMGSERAWDLAHRIDSEGAADVWSGPLEQAE
LYHQQLSAEGLTMAPLERC-----------
>Synechococcus_sp._RCC307_gi_148242507_ref_YP_001227664.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._RCC307_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MTSSAPSRQT---AGSTLLERAPYP---
---NFKVVVLNDEVNTFQHVVDCLVKYIPAMDPDRAWSLAQQIDSDGQAVVWVGPQEQAE
LYHMQLGAEGLTMAPLERA-----------
>Synechococcus_sp._WH_5701_gi_87302745_ref_ZP_01085556.1__hypothetical_protein_WH5701_13370__Synechococcus_sp._WH_5701_
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MAAPGVQT---IPAGIRQRQRYP---
---HLRVVVLDDDVNTFQHVVNCLVRYLPGMGPDRAWELAHQIDSQGSAVVWSGPQEQAE
LYHQQLSQEGLTMAPLERE-----------
>Synechococcus_sp._CB0205_gi_317970016_ref_ZP_07971406.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CB0205_
M-----------------------------------------------------------
------------------------------------------------------------
----------------------------QPIRSISSSPGGQA---VMERQRVRAPYP---
---TGRVIVLDDDHNTFQHVVEVLVKHIPAMVSDRAWELAHQIDSQGSAVVWSGPLEQAE
LYHQLLAGEGLTMAPVERG-----------
>Synechococcus_sp._CB0101_gi_318041538_ref_ZP_07973494.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CB0101_
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------AQQA---VRDKQRVDAPYP---
---TGRVIVLDDDHNTFQHVVEVLVRYIPAMTSDRAWELAHQIDGQGSALVWSGPLEQAE
LYHQQLGAEGLTMAPLERG-----------
>Prochlorococcus_marinus_str._AS9601_gi_123968534_ref_YP_001009392.1__clpS_gene_product__Prochlorococcus_marinus_str._AS9601_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MVNSLGT---VLEPKKSKAKYP---
---EARVIVLDDNFNTFQHVANCLLTIIPSMSEQRAWDLTIKVDKTGSAEVWRGNLEQAE
LYHEQLFSKGLTMAPIEKT-----------
>Prochlorococcus_marinus_str._MIT_9301_gi_126696337_ref_YP_001091223.1__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._MIT_9301_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MFNSLGT---VLDPKKSKAKYP---
---EARVIVLDDNFNTFQHVANCLLTIIPSMSEQRAWDLTIKVDKTGSAEVWRGNLEQAE
LYHEQLFSKGLTMAPIEKT-----------
>Prochlorococcus_marinus_str._MIT_9215_gi_157413367_ref_YP_001484233.1__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._MIT_9215_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MLNSLST---VLDQKKSKAKYP---
---EARVIVLDDSFNTFQYVANCLLTIIPSMSERRARDLTIKVDKTGSAEVWRGNLEQAE
LYHEQLLSKGLTMAPIEKT-----------
>Prochlorococcus_marinus_str._MIT_9202_gi_254526218_ref_ZP_05138270.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9202_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MFNSLSI---VLDQKKSKAKYP---
---EARVIVLDDSSNTFQHVAYCFLTIIPSMSERRAWNLTIKVDKTGSAEVWRGNLEQAE
LYHEQLLSKGLTMAPIEKT-----------
>Prochlorococcus_marinus_str._MIT_9312_gi_78779324_ref_YP_397436.1__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._MIT_9312_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MYNSPLT---VLDNKKSKVKYP---
---EARVIVLDDSFNTFQHVANCLLIIIPGMSENRAWDLTIKVDNTGSAEVWRGNLEQAE
LYHEQLVSKGLTMAPIDKT-----------
>Prochlorococcus_marinus_str._MIT_9211_gi_159904055_ref_YP_001551399.1__hypothetical_protein_P9211_15141__Prochlorococcus_marinus_str._MIT_9211_
----------------------------MRETKRRNQCSRRAHQKDASRNGRPLLLMMD-
------------------------------------------------------------
----------------KKIMTRHTKDFVATTAMKFSANSTTT---VLDPKTTKKKYP---
---EARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWVLAVEVDREGLAEVWRGPLEQAE
LYHQQLISKGLTMAPIEKT-----------
>Prochlorococcus_marinus_subsp._marinus_str._CCMP1375_gi_33241004_ref_NP_875946.1__clpS_gene_product__Prochlorococcus_marinus_subsp._marinus_str._CCMP1375_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MKFSANSTTT---VLDPKTTKKKYP---
---EARIIVLDDNFNTFEHVANCLATIIPGMSEKRSWVLAVEVDREGLAEIWRGPLEQAE
LYHQQLISKGLTMAPIEQT-----------
>Prochlorococcus_marinus_str._NATL2A_gi_161347556_ref_YP_291789.2__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._NATL2A_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MKFSTNSTTT---VLDPKTTKIKYP---
---EARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWELAVEVDREGLAEVWRGPFEQAE
LYHQQLISKGLTMAPIEKT-----------
>Prochlorococcus_marinus_str._NATL2A_gi_72002284_gb_AAZ58086.1__conserved_hypothetical_protein__Prochlorococcus_marinus_str._NATL2A_
------------------------------------------------------------
------------------------------------------------------------
-------------------MLKDVLQLTAATAMKFSTNSTTT---VLDPKTTKIKYP---
---EARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWELAVEVDREGLAEVWRGPFEQAE
LYHQQLISKGLTMAPIEKT-----------
>cyanobacterium_UCYN-A_gi_284928874_ref_YP_003421396.1__hypothetical_protein_UCYN_02930__cyanobacterium_UCYN-A_
MFKRL-------------------------------------------------------
------------------------------------------------------------
-----------------------------SITIPETSISTNI---KHSAVIDYKPYP---
---NCKIIVLNDDFNTFDHVANCLIRYIPAMTKSHAWELTQKIHFNGFATVWMGPLEQAE
LYHQQLRREGLTMAPLEGI-----------
>Conexibacter_woesei_DSM_14684_gi_284045641_ref_YP_003395981.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Conexibacter_woesei_DSM_14684_
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GQTIEKQRVQGPGSG
LGGNWRVIVKNDDHNTFDHVARTLARYIPGVTIAVGYDYADRIHNSGQAIVWSGQREVAE
LYWEQLQGAGLTMAPLEQG-----------
>Patulibacter_sp._I11_gi_367468593_ref_ZP_09468447.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Patulibacter_sp._I11_
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------SQTIEQTRAADPGTG
LGGAWNVIVRNDDHNTFDHVATTLARVIPGVNVDAGFRLADRIHQAGLAVVWTGHKELAE
HYWEQLRDAGLTMAPLEQA-----------
>Gloeobacter_violaceus_PCC_7421_gi_37522100_ref_NP_925477.1__hypothetical_protein_gll2531__Gloeobacter_violaceus_PCC_7421_
MLSSAEAPSPGTVQWAPNGQKAQDRQHRVASVHVTGLAASGYLAVASYPASRQPGDVQKR
LRWGAIVVSFGYTGTQDD------------------------------------------
----------------YPHASMERMVLAPAAVSAPPLPTKTPLDPVKTPEKTPLRWR---
---DWVVRLFNDPVNKFEHVVESLCKHVPGMSQDMAWSVAWQAHREGVAATYQGPREVAE
LVCEKLVRDGLISDCCES------------
