>gi|18409086|ref|NP_564937.1| ATP-dependent Clp protease adaptor protein ClpS [Arabidopsis thaliana]
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRSILMTLSTSAALGKGGGVLDKPIIEKTTPGRESEF
DLRKSKKIAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAEQHC
MQLRGNGLLSSVEPDGGGC

>gi|297841589|ref|XP_002888676.1| hypothetical protein ARALYDRAFT_894639 [Arabidopsis lyrata subsp. lyrata]
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRGVLMTLSTYAALGKGGGVLDKPIIEKTTPGRESEF
DLRKSKKMAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAEQHC
MQLRGNGLLSSVEPDGGGC

>gi|224099343|ref|XP_002311446.1| predicted protein [Populus trichocarpa]
METAICGRIALSPNHVFNPKPGDKNSVCRGPCANRGILMAISTTCSGKGGGLLEKPVIERTTPGRESEFD
LRKSKKMAPPYRVMLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAEEHCM
QLRGNGLLSSIEPASGGC

>gi|225423913|ref|XP_002281884.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS [Vitis vinifera]
MENAICGRLALSPNHVFNSKSGDKHSLLKGPCTNRSFLMAISASGPGKGGLLERPVIEKVTPGRESEFDL
RKSRKIAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAEDHCMQ
LRGNGLLSSIEPASGGC

>gi|224111728|ref|XP_002315955.1| predicted protein [Populus trichocarpa]
METAICGRIALSPNHVFNPKPGDKNSVCRGPCASRGILMSISATVSGKGGGGGGGILEKPVIERTTPGRE
SEFDLRKSKKMAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICTQADAE
EHCMQLRGNGLLSSIEPASGGC

>gi|145326694|ref|NP_001077794.1| ATP-dependent Clp protease adaptor protein ClpS [Arabidopsis thaliana]
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRSILMTLSTSAALGKGGGVLDKPIIEKTTPGRESEF
DLRKSKKIAPPYRVILHNDNFNKREYVVQVLMKADAEQHCMQLRGNGLLSSVEPDGGGC

>gi|225455872|ref|XP_002274839.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS [Vitis vinifera]
METAICGRVPLSPNHFFTSKSGDKHSLSKQWTHRTMLMTVSAAAPGKGSGVLERPTIERIMPGRESEFDL
RKSRKMSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQVDAEDHCMQ
LRGNGLLSSIEPASGGC

>gi|357488429|ref|XP_003614502.1| ATP-dependent Clp protease adapter protein clpS [Medicago truncatula]
MKSAICRSMGLSPNHLFISGDRYSFCKGPYSNLCVPMAVLTKGSGKGGGILEKPVIEKATPGRESEFDLK
KSRKTAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQADAEDHCMQL
RGNGLLSSIEPAGDGC

>gi|351723283|ref|NP_001234970.1| uncharacterized protein LOC100527361 [Glycine max]
MKSAICGRILSPNHVFKPGDTHSICKGPYSNLCVPMAVLATGPGKGGGVLEKPVIEKVTPGRESEFDLKK
SRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAEDHCTQLR
GNGLLSSIEPASGGC

>gi|351721328|ref|NP_001235414.1| uncharacterized protein LOC100500511 [Glycine max]
MKSAICGRILSPNHVFKPGDTHSICKGPYSNLCVPMVVLATGPGIGGGVLEKPVIEKVTPGRESEFDLKK
SRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAEDHCMQLR
GNGLLSSIEPANGGC

>gi|294460817|gb|ADE75982.1| unknown [Picea sitchensis]
MASVIYSRLILPQPQLYQQKSGEKISQSKGACMNRVFSAIRSTSPGGKGGGLLERPTIEKTTPGRESEFD
LRKSRKTSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDTAVNIMQEAHYNGLAVVIICAQVDAEEHCT
QLRGNGLLSSIEPASDGC

>gi|356531226|ref|XP_003534179.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS-like [Glycine max]
MEAALCSALALSPNQVFNAANPGDKNVPLKYSKDRSVVMTVAATGILGKGGGLLERPTIETTSPGRESEF
DLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAEDHC
MQLRGNGLLSSIEPADGGGC

>gi|351724025|ref|NP_001237811.1| uncharacterized protein LOC100306117 [Glycine max]
MEAALCSALAPSPNQVFNAANPGDKNVPLKYSKDRSVVMTVAATGILGKGGGLLERPTIETTSPGRESEF
DLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAEDHC
MQLRGNGLLSSIEPADGGGC

>gi|226506038|ref|NP_001150373.1| ATP-dependent Clp protease adaptor protein ClpS containing protein [Zea mays]
MEAAVPSRVALSAASRLPNPHAVTGDRSFIYKGRCQSLAIPMALSAAAPGKGGGVLDRPVEKTTPGRQSE
FDVKKSRKMSPPYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|255576515|ref|XP_002529149.1| ATP-dependent Clp protease adaptor protein clpS, putative [Ricinus communis]
MALSATGAGKGGGLLEKPVIEKTTPGRESEFDLRKSRKTAPPYRVILHNDNYNKREYVVQVLMKVIPGMT
LDNAVNIMQEAHYNGLSVVIICAQADAEDHCMQLRGNGLLSSIEPASGGC

>gi|147805878|emb|CAN78258.1| hypothetical protein VITISV_026645 [Vitis vinifera]
METAICGRVPLSPNXFFTSKSAPGKGSGVLERPTIERIMPGRESEFDLRKSRKMSPPYRVLLHNDNYNKR
EYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQVDAEXHCMQLRGNGLLSSIEPASGGC

>gi|242081547|ref|XP_002445542.1| hypothetical protein SORBIDRAFT_07g021160 [Sorghum bicolor]
MEAAVPSRVALSAASRLPNRHAVAGDRSFVYKGRCQSLAIPMALSAAAPGKGGVLDRPVEKTTPGRQSEF
DVKKSRKMSPPYRVILHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAEEHC
TSLRGNGLRSSIEPASGGC

>gi|226493842|ref|NP_001148322.1| ATP-dependent Clp protease adaptor protein ClpS containing protein [Zea mays]
MMASVPSRVALSAASRLPNLHAVAGDRSFIYKRRCPSLSIPMALSAAAPGKGGGVLDRPVEKITPGRQSE
FDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALNIMQEAHVNGLSVVIVCSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|195652021|gb|ACG45478.1| ATP-dependent Clp protease adaptor protein ClpS containing protein [Zea mays]
MMASVPSRVALSAASRLPNLHAVAGDRSFIYKRRCPSLSIPMALSAAAPGKGGGVLDRPVEKITPGRQSE
FDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALSIMQEAHVNGLSVVIVCSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|223943781|gb|ACN25974.1| unknown [Zea mays]
MALSAAAPGKGGGVLDRPVEKTTPGRQSEFDVKKSRKMSPPYRVILHNDNYNRREYVVKVLMKVIPGMTV
DNAVNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNGLRSSIEPASGGC

>gi|115476544|ref|NP_001061868.1| Os08g0432500 [Oryza sativa Japonica Group]
MEAAVPSRVALSASRLSNHHHHAVGGERYAIYRGRCPNPAIPMALAAAAAPGKGGGVLDRPIEKVTPGRQ
SEFDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIICSQSEAE
EHCTSLRGNGLRSSIEPASGGC

>gi|357147864|ref|XP_003574520.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS-like [Brachypodium distachyon]
MEAAVPSRIALSARIMNHHVVAAGGRSSIYRGRYPNIAIPIVVTAAGKGGGVLDRPAEKISPGRQSEFDV
KKSRKMSPPYRVVLHNDNENRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLAVVIVCSQSEAEEHCTS
LRGNGLRSSIEPASGGC

>gi|297737852|emb|CBI27053.3| unnamed protein product [Vitis vinifera]
MENAICGRLALSPNHVFNSKSGDKHSLLKGPCTNRSFLMAISASGPGKGGLLERPVIEKVTPGRESEFDL
RKSRKIAPPYRVILHNDNYNKREYVVQVLMKADAEDHCMQLRGNGLLSSIEPASGGC

>gi|223948869|gb|ACN28518.1| unknown [Zea mays]
MALSAAAPGKGGGVLDRPVEKITPGRQSEFDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTV
DNALNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNGLRSSIEPASGGC

>gi|168014848|ref|XP_001759963.1| predicted protein [Physcomitrella patens subsp. patens]
AAAPGQGGGVMDRPTIDKPTPGRESEFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLLKAIPGMTVDIA
VNVMNEAHINGIAVVIVCPQEDAEDYCMQLRTNGLLSSIEPD

>gi|125603506|gb|EAZ42831.1| hypothetical protein OsJ_27419 [Oryza sativa Japonica Group]
MEAAVPSRCGALREPALQPPPPRGERYAIYRGRCPNPAIPMALAAAAAPGKGGGVLDRPIEKVTPGRQSE
FDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIICSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|121489819|emb|CAK19331.1| putative adaptor protein ClpS [Physcomitrella patens]
MAGSLRLFVSIPATARHFGINGVEKAQRVHNRVNGRYKINAASGPSQGGGVLDRPTIDKPTPGRESEFDL
KKKKKISPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLAVVIVCPQEDAEDYCMQ
LRTNGLLSSIEPASC

>gi|168011584|ref|XP_001758483.1| predicted protein [Physcomitrella patens subsp. patens]
QGGGVLDRPTIDKPTPGRESEFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMN
EAHINGLAVVIVCPQEDAEDYCMQLRTNGLLSSIEP

>gi|302761288|ref|XP_002964066.1| hypothetical protein SELMODRAFT_142341 [Selaginella moellendorffii]
MACTLTQVAHLWPSTSQVSRFNTIFAEADKCHKCFTRIIASHAVRAALPGGLGGGVLDKPAIETAPTPGR
ESEFDLRKKKKMAPPYRVILHNDNFNRREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGLSVVIVCSQEDA
EEHCTQLRANGLLSSIEPASGGSC

>gi|307105846|gb|EFN54094.1| hypothetical protein CHLNCDRAFT_31972 [Chlorella variabilis]
MTICVGQRLGGQAVAGKAGDKPPTRGAWLVPAGATRRSAQRRARLHVAARSAGKGGGVLDRPGVLPGQQR
GRETRRRRPPSYRVLLHNDNYNRREYVVQVLMKVVEGTTVDDAVNIMQEAHINGLAMVTQCAQDKAELYC
ESLRLNGLIATIEPAGTGGSDGTSSS

>gi|300868553|ref|ZP_07113170.1| ATP-dependent Clp protease adaptor protein ClpS [Oscillatoria sp. PCC 6506]
MSVETIEKRSTVRKIAPRYRVLLHNDDFNSMEYVVQTLMHTVPSLTQPQAVNIMMEAHTNGLAVVIICAQ
EHAEFYSETLNNHGLISTIEPDE

>gi|148972604|ref|ZP_01811408.1| ATP-dependent Clp protease adaptor protein ClpS [Leptolyngbya valderiana BDU 20041]
MSVETIEKRSTVRKHAPRYRVLLHNDDFNTMEYVVQTLVKTVPGLTQPQAVSIMMEAHTNGMALVITCAQ
EHAEFYCETLRRHGLSSSIEPDD

>gi|298490087|ref|YP_003720264.1| ATP-dependent Clp protease adaptor protein ClpS ['Nostoc azollae' 0708]
MSVETIEKRSTTRKLAPQYRVLLHNDDYNSMEYVVQVLMTSVPSITQPQAVNIMMEAHNSGLALVITCAQ
EHAEFYCETLKGHGLSSTIEPD

>gi|75907498|ref|YP_321794.1| clpS gene product [Anabaena variabilis ATCC 29413]
MSVETIEKRSTSRKLAPRYRVLLHNDDYNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLALVITCAQ
EHAEFYCETLKDHGLSSTIEPDE

>gi|209523998|ref|ZP_03272550.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira maxima CS-328]
MALVCFGIDKFPDHCNFVNGGDGSVSTQTVEKTSTNRKLAPRYRVLLHNDDYNPMEYVVQVLMSTVPGLT
QPQAVSIMMEAHTNGLALVITCALEHAEFYCETLKNHGLTSTIEPDE

>gi|113474895|ref|YP_720956.1| clpS gene product [Trichodesmium erythraeum IMS101]
MSIETIEKPTTSTVRKTAPHYRVLLHNDDFNSMEYVVQTLMKTVPSLTQPQAVNIMMEAHSNGIALVIIC
ALEPAEFYCENLKNHGLTSTIEPDE

>gi|354566131|ref|ZP_08985304.1| ATP-dependent Clp protease adapter protein clpS [Fischerella sp. JSC-11]
MSVETQQKRSTSRKLAPQYRVLLHNDDYNTMEYVVQVLLTTVPSLTQPQAVSIMMEAHSNGLALVITCAQ
EPAEFYCETLKNHGLTSTIEPEE

>gi|307150896|ref|YP_003886280.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7822]
MSTSTSTQVIEKSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGMAL
VITCTLEHAEFYCETLKAHGLTSTIEPDE

>gi|291571937|dbj|BAI94209.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira platensis NIES-39]
MALVCFGIDKFPYHCTFVNGGDGSVSTQTVEKTSTNRKLAPRYRVLLHNDDHNPMEYVVQVLMSTVPGLT
QPQAVSIMMEAHTNGLALVITCALEHAEFYCETLKNHGLTSTIEPDE

>gi|17231817|ref|NP_488365.1| clpS gene product [Nostoc sp. PCC 7120]
MSVETIEKRSTSRKLAPRYRVLLHNDDHNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLALVITCAQ
EHAEFYCETLKDHGLSSTIEPDE

>gi|284052626|ref|ZP_06382836.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira platensis str. Paraca]
MSTQTVEKTSTNRKLAPRYRVLLHNDDHNPMEYVVQVLMSTVPGLTQPQAVSIMMEAHTNGLALVITCAL
EHAEFYCETLKNHGLTSTIEPDE

>gi|218438615|ref|YP_002376944.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7424]
MSTSTQVIEKSTTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGTALVI
TCTLEHAEFYCETLKNHGLTSTIEPDE

>gi|159029424|emb|CAO90801.1| unnamed protein product [Microcystis aeruginosa PCC 7806]
MSTEVIEKRSTATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITC
IQEHAEFYCETLKNKGLTSSIEPDE

>gi|218246012|ref|YP_002371383.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 8801]
MTTEVIEKRSTSSATVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVAGMTQPQAVDIMMEAHTNGTALVI
TCALEHAEFYCETLKNHGLTSSIEPDE

>gi|166367986|ref|YP_001660259.1| ATP-dependent Clp protease adaptor protein ClpS [Microcystis aeruginosa NIES-843]
MIEKRSTATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITCIQEH
AEFYCETLKNKGLTSSIEPDE

>gi|126657545|ref|ZP_01728701.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. CCY0110]
MTTEVIEKRSSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVSGMTQPQAVDIMMEAHTNGTALVI
TCALEPAEFYCETLKNHGLTSTIEPDE

>gi|158338702|ref|YP_001519879.1| clpS gene product [Acaryochloris marina MBIC11017]
MSVETLEKRSTSRKLAPKYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIALVITCAF
EHAEFYCETLKMHGLTSTIEPDE

>gi|282897015|ref|ZP_06305017.1| ATP-dependent Clp protease adaptor protein ClpS [Raphidiopsis brookii D9]
MSVETIEKPSTTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVTIMMEAHSNGLALVISCAL
EHAEFYCESLNNHGLTSTIEPDD

>gi|81299501|ref|YP_399709.1| clpS gene product [Synechococcus elongatus PCC 7942]
MAVETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITC
DIEPAEFYCEQLKSHGLSSSIEPDD

>gi|359457944|ref|ZP_09246507.1| ATP-dependent Clp protease adaptor protein ClpS [Acaryochloris sp. CCMEE 5410]
MSVETLEKRSTGRKLAPKYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIALVITCAF
EHAEFYCETLKMHGLTSTIEPDE

>gi|282899028|ref|ZP_06307010.1| ATP-dependent Clp protease adaptor protein ClpS [Cylindrospermopsis raciborskii CS-505]
MSVETIEKPSTTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVSIMMEAHSHGLALVISCAL
EHAEFYCESLNNYGLTSTIEPDD

>gi|170078877|ref|YP_001735515.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7002]
MSTGVIEQRSTSTIRKPAPRYRVLLHNDDFNSMEHVVQTLMQTVAGLTQPQAVSIMMEAHTNGIALVITC
VQEHAEFYCETLKMHGLTSTIEPDE

>gi|334120716|ref|ZP_08494794.1| ATP-dependent Clp protease adapter protein clpS [Microcoleus vaginatus FGP-2]
MSVEIIQKASTVRKLAPRYRVLLHNDDFNPMEYVVQTLMATVPSLTQPQAVNVMMEAHTNGMGLVIVCAL
EHAEFYAETLNNHGLSSSIEPDD

>gi|220908775|ref|YP_002484086.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7425]
MAVETIEQRSTVRKLAPRYRVLLHNDDVNSMEHVVEVLLKTVPSLTQPQAVDIMMEAHVNGIALVITCAL
EHAEFYCESLKLGGLTSTIEPDE

>gi|159467236|ref|XP_001691804.1| clp protease adaptor protein [Chlamydomonas reinhardtii]
MMTRSPVAGLPRPCSALQRSGCTLQGAFGTFAPQTTRTFVVTWAKGGVMDAPTTTQQPASGVERSQKRPP
IYKVLLHNDNYNKREYVVKVLLKVVEQITVDDAVTCMQEAHETGVALVVACPQDNAERYCEGLRLNGLTS
TIEPGGC

>gi|67924069|ref|ZP_00517517.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 8501]
MTTDVIEKPSSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVPSITQPQAVDIMMEAHSNGTALVI
TCALEPAEFYSETLKNHGLTSTIEPDE

>gi|16331021|ref|NP_441749.1| ATP-dependent Clp protease adaptor protein ClpS [Synechocystis sp. PCC 6803]
MMATEVLNKPSNSTIRKHAPRYRVLLHNDDFNSMEHVVQTLIQTVAGMTQPQAVDIMMEAHFNGMSLVIT
CELEHAEFYCETLRSHGLSSTIEPDE

>gi|186684027|ref|YP_001867223.1| ATP-dependent Clp protease adaptor protein ClpS [Nostoc punctiforme PCC 73102]
MSVETIQKPSTTRKLAPRYRVLLHNDDYNSMEHVVQSLIATVPSLTQPQAVSIMMEAHTNGLALVITCAL
EHAEFYCETLISHGLSSTIEPDE

>gi|22297755|ref|NP_681002.1| clpS gene product [Thermosynechococcus elongatus BP-1]
MEAWPTMSVQTIEKPATVRKLAPRYRVLLHNDNVNSMEYVVEVLLKTVPSLTQPQAVDIMMEAHLTGVAL
VITCALEHAEFYCEGLKMAGLTSTIEPTE

>gi|302834902|ref|XP_002949013.1| hypothetical protein VOLCADRAFT_73976 [Volvox carteri f. nagariensis]
MAASVLRPPPVSVASRAPTAALAVLPGSACLGWRRANFGTSTLLSQTTRTCVQMRAGVPGLLDSPTITSE
PQQGTDRAYKRPPIYKVFLHNDNYNKREYVVKVLLKVVEEITVDDAVTVMQEAHETGVALVVACPQENAE
RYCEGLRLNGLTSTIEPAGR

>gi|86608169|ref|YP_476931.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. JA-2-3B'a(2-13)]
MATETLVKPSVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPAMMPPQATEIMLEAHHNGVAVVIVVPR
EHAEFYCEQLRQHGLTSSIEPER

>gi|86607127|ref|YP_475890.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. JA-3-3Ab]
MATETLVKPSVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPSMLPPQATEIMLEAHNNGVAVVIVVPR
EHAEFYCEQLRQHGLTSSIEPER

>gi|254423912|ref|ZP_05037630.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7335]
MSTSISTIEKPSVSTVRKIAPRYRVLLHNDDFNSMEYVVEALIETVPSLTAPQAIDIMMQTHNTGIGLVI
VCEMEHAEFYCEGLKGKGLTSTIEPEE

>gi|284929541|ref|YP_003422063.1| hypothetical protein UCYN_10070 [cyanobacterium UCYN-A]
MVTDVIEKISLNTSTTKKPVPRYKVLLHNDDFNPMDYVVQILMQTISGMTRPQAAEIMMEAHISGTALVI
TCAFEPAEFYRETLKNHGLSSSIEPDE

>gi|56750848|ref|YP_171549.1| clpS gene product [Synechococcus elongatus PCC 6301]
MAVETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITC
DIEPAEFYCEQLKSHGLEQQH

>gi|108803856|ref|YP_643793.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
MVGSLTRDIRCSAATKTAPARKTRRAPSREPRYRVILHNDDWTPMDHVVAALMKVVPRLSLRRAVSIMLE
AHTKGQAVVTRCHRELAELYREGLKAEGLISTIEPDG

>gi|254430350|ref|ZP_05044053.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanobium sp. PCC 7001]
MTAAAMTTVPQATQTPSRESGAAVMEKAPERVRKPSPRYKVLLHNDPVNSMEYVVTTLRQVVPSLSEQDA
IAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPDD

>gi|88807954|ref|ZP_01123465.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 7805]
MAVETPSLTPGGAAVLDKAPERVRKQSPRYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEAHN
TGVGLVIVCDLEPAEFYCETLKGKGLTSTLEPDT

>gi|119489795|ref|ZP_01622553.1| ATP-dependent Clp protease adaptor protein ClpS [Lyngbya sp. PCC 8106]
MEYVVQVLLQTVPSLTQPQAVSIMMEAHTNGLALVITCAQEHAEFYCETLKNNGLTSTIEPDE

>gi|148238705|ref|YP_001224092.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 7803]
MVMAVETPSRTPGGAAVLEKAPERVRKQSPRYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEA
HNTGVGLVIVCDLEPAEFYCETLKGKGLTSTIEPEN

>gi|87125032|ref|ZP_01080879.1| hypothetical protein RS9917_03483 [Synechococcus sp. RS9917]
MHRSDLAMVGSTSSTSPGGAAVLDKQTERVRKHSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMA
VMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPET

>gi|318042663|ref|ZP_07974619.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CB0101]
MPELDWMPRSTPCTAAFTATQTPGRESGGGAVMEKAPERVRKPSPRYKVLLHNDPVNTMEYVVGTLRQVV
PSLSEQDAIAVMLEAHNTGVGLVIVCDIEPAEFYSETLKAKGLTSTIEPES

>gi|87301880|ref|ZP_01084714.1| hypothetical protein WH5701_01105 [Synechococcus sp. WH 5701]
MSDTIRATETPTRSPGGAAVIEKEVQRVRKPSPRYRVLLHNDPVNSMEYVVTTLRQVVPSLSEQDAIAVM
LEAHNTGVGLVIVCDLEPAEFYSETLKAKGLSSTIEPES

>gi|116075699|ref|ZP_01472958.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. RS9916]
MAVNTTSPGPGGAAVLDKQTERVRKRSPRYKVLLHNDPVNSMEYVVSTLQQVVPQLSEQDAMAVMLEAHN
SGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPES

>gi|148243279|ref|YP_001228436.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. RCC307]
MTHASETPVSSPGGGAAVMERQPETVRKPSPRYRVLLHNDPVNSMEYVVTSLREVVPSLSEQDAMAVMLE
AHNSGVGLVIVCDIEPAEFYCESLKAKGLTSTIEPEE

>gi|317968680|ref|ZP_07970070.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CB0205]
MIRSTQAPGRESGGAAVMEKAPERVRKPSPRYKVLLHNDPVNTMEYVVSTLRQVVPSLSEQDAIAVMMEA
HNTGVGLVIVCDIEPAEFYSETLKAKGLSSTIEPED

>gi|260434316|ref|ZP_05788286.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 8109]
MSRSISLFPLNLKVFGSMVMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCEMLKSKGLTSSIEPEE

>gi|161353432|ref|NP_898239.2| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 8102]
MAMAVDTPTRSPGGAAVMEKAPERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEA
HNTGVGLVIVCDLEPAEFYCETLKAKGLTSTIEPET

>gi|72382903|ref|YP_292258.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. NATL2A]
MSNIMVNSLSKSAIHLESLIMVDSANQTDGDTAVIDREVQRVRKISPKYKVLLHNDPVNTMDYVVEILRQ
VVPQLSEQDALNIMLETHNNGVGLVITCDLEPAEFYSESLKAKGLTSTIELES

>gi|78185599|ref|YP_378033.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CC9902]
MAEETPTRSPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVMTTLRQVVPQLSEQDAMAVMLEAHN
TGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPED

>gi|78211862|ref|YP_380641.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CC9605]
MVMAVESPSQKPGGAAVLDKAPEKVRKRSPRYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEA
HNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|113954242|ref|YP_729603.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CC9311]
MVDTPSRSPGGAAVLDKQTERVRKTSPRYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNT
GIGLVIVCDIEPAEFYCETLKNKGLTSTIEPES

>gi|33633458|emb|CAE08663.1| conserved hypothetical protein [Synechococcus sp. WH 8102]
MASAPQVRATSDCPPSTAAPTWMLLWPESRPSEQVVQRFPLDLNLPNTMAMAVDTPTRSPGGAAVMEKAP
ERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEAHNTGVGLVIVCDLEPAEFYCET
LKAKGLTSTIEPET

>gi|37520315|ref|NP_923692.1| ATP-dependent Clp protease adaptor protein ClpS [Gloeobacter violaceus PCC 7421]
MSTETLERKSVQRKPMPLYKVLLHNDDHTPMNYVIEVLMKTIPKMQPSKARKIMLEAHNGGVAVVIVCAL
EHAEFYSESLNRHNLTSTYEPDC

>gi|116072120|ref|ZP_01469388.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. BL107]
MAEETPTRSPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVMATLRQVVPQLSEQDAMAVMLEAHN
TGIGLVIVCDIEPAEFYCETLKSKGLTSTIEPED

>gi|352096458|ref|ZP_08957285.1| ATP-dependent Clp protease adapter protein clpS [Synechococcus sp. WH 8016]
MVDTPSRSPGGAAVLDKQTERVRKTSPRYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNT
GVGLVIVCDIEPAEFYCETLKNKGLTSTIEPED

>gi|124026645|ref|YP_001015760.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. NATL1A]
MSNIMVSSLLKSAIHLDSLIMVDSANQTDGDTAVIDREVQRVRKISPKYKVLLHNDPVNTMDYVVDTLRQ
VVPQLSEQDALNIMLETHNNGVGLVITCDLEPAEFYSESLKAKGLTSTIELES

>gi|33241103|ref|NP_876045.1| clpS gene product [Prochlorococcus marinus subsp. marinus str. CCMP1375]
MVGNPGRGPGGAAVVDKQTERVRKTSPRYKVLLHNDPVNTMDYVVTTLRQVVPQLSEQDAMAVMLETHNT
GIGLVITCDLEPAEFYSESLKGKGLTSTIEPES

>gi|33864059|ref|NP_895619.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9313]
MKLGLPTICTMGERPTYIGAVPIVLAMAVNAPSPTPGGAAVLEKQTERIRKQSPHYKVLLHNDPVNSMEY
VVVTLQQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEQES

>gi|124024066|ref|YP_001018373.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9303]
MGERPTYIGALPIVLAMAVNAPSPSPGGAAVLEKQTERIRKQSPHYKVLLHNDPVNSMEYVVVTLQQVVP
QLSEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEQES

>gi|332711797|ref|ZP_08431728.1| hypothetical protein LYNGBM3L_67610 [Lyngbya majuscula 3L]
MEYVVKTLMETVASLTQPQAVNIMMEAHQSGLALVITCAQEHAEFYCETLKNRGLTSTIEPDE

>gi|119510879|ref|ZP_01630003.1| ATP-dependent Clp protease adaptor protein ClpS [Nodularia spumigena CCY9414]
MEHVVQSLITTVPSLTQPQAVSIMMEAHTNGMALVITCAQEHAEFYCETLKSHGLSSTIEPDE

>gi|254414360|ref|ZP_05028127.1| ATP-dependent Clp protease adaptor protein ClpS [Microcoleus chthonoplastes PCC 7420]
MEYVVQALIQTVPSLTQPQAVNIMMEAHNSGIALVITCALEHAEFYCETLKNHGLTSTIEPDE

>gi|123966912|ref|YP_001011993.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9515]
MSIIKLEKGDNNNAAVLEKKTAALKNKSPKYKVLLHNDPVNSMEYITIALREVVPQLSEQDAIAIMLEAH
NNGVGLVIVCDLEPAEFYSESLKSKGISSSIEKDE

>gi|307150152|ref|YP_003885536.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7822]
MSTNVAAVVKAMATAPTVAPDKTTQVVKKTYPNYKVIVLNDDFNTFEHVAKCLMKYIPGMTSDRAWELTN
QVHFEGQAIVWVGPQEQAELYHQQLRREGLTLAPLEAA

>gi|57335897|emb|CAH25350.1| hypothetical protein [Guillardia theta]
RICACVRSAWSFPVAFPAHLHHPLLRAVCFFIKWISSILWFMMGRQVLAALALLPLAWCFQAPTSFLPGT
RGITQQTCATLRPAVLGKMQLEAPERIKIPDTFNPAEWGVGGGKGGFGDGLGGFKVPDSFNPAEMEKERQ
GGRTAVMDRPSDKTDPGKKYKVLLFNDDKNTRQYVIDTLMKYIPGMTADKAKEITVAAHNTGMAIVGVWM
YEMAEAYSDVLRSAGLRSDIDPE

>gi|170078679|ref|YP_001735317.1| putative ATP-dependent Clp protease adaptor protein [Synechococcus sp. PCC 7002]
MAPAPGILKESDRQTVRKPYPNFKVIVLNDDFNTFEHVAHCLMTYIPNMTADQAWNLTNQVHFDGQAIVW
VGPQEPAELYHQQLRREGLTMAPLEAA

>gi|357263411|gb|EHJ12427.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 0003]
MEYVVQTLMQIVPSITQPQAVDIMMEAHSNGTALVITCALEPAEFYSETLKNHGLTSTIEPDE

>gi|33862055|ref|NP_893616.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus subsp. pastoris str. CCMP1986]
MINRFSCNYNQKVMSNIKFEKGENNNAAVLEKKTAPLKNKSPKYKVLLHNDPVNSMEYVTNALREVVPQL
SEQDAISIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|186684201|ref|YP_001867397.1| ATP-dependent Clp protease adaptor [Nostoc punctiforme PCC 73102]
MVRNLSADVYGMTTAPTITPERSSQVTRKTYPNYKVIVLNDDFNTFQHVAECLMKYIPGMSGDRAWDLTN
QVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEAA

>gi|56750848|ref|YP_171549.1| clpS gene product [Synechococcus elongatus PCC 6301]
MAVETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITC
DIEPAEFYCEQLKSHGLEQQH

>gi|81299501|ref|YP_399709.1| clpS gene product [Synechococcus elongatus PCC 7942]
MAVETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITC
DIEPAEFYCEQLKSHGLSSSIEPDD

>gi|113474895|ref|YP_720956.1| clpS gene product [Trichodesmium erythraeum IMS101]
MSIETIEKPTTSTVRKTAPHYRVLLHNDDFNSMEYVVQTLMKTVPSLTQPQAVNIMMEAHSNGIALVIIC
ALEPAEFYCENLKNHGLTSTIEPDE

>gi|67924069|ref|ZP_00517517.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 8501]
MTTDVIEKPSSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVPSITQPQAVDIMMEAHSNGTALVI
TCALEPAEFYSETLKNHGLTSTIEPDE

>gi|126657545|ref|ZP_01728701.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. CCY0110]
MTTEVIEKRSSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVSGMTQPQAVDIMMEAHTNGTALVI
TCALEPAEFYCETLKNHGLTSTIEPDE

>gi|282897015|ref|ZP_06305017.1| ATP-dependent Clp protease adaptor protein ClpS [Raphidiopsis brookii D9]
MSVETIEKPSTTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVTIMMEAHSNGLALVISCAL
EHAEFYCESLNNHGLTSTIEPDD

>gi|186684027|ref|YP_001867223.1| ATP-dependent Clp protease adaptor protein ClpS [Nostoc punctiforme PCC 73102]
MSVETIQKPSTTRKLAPRYRVLLHNDDYNSMEHVVQSLIATVPSLTQPQAVSIMMEAHTNGLALVITCAL
EHAEFYCETLISHGLSSTIEPDE

>gi|284052626|ref|ZP_06382836.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira platensis str. Paraca]
MSTQTVEKTSTNRKLAPRYRVLLHNDDHNPMEYVVQVLMSTVPGLTQPQAVSIMMEAHTNGLALVITCAL
EHAEFYCETLKNHGLTSTIEPDE

>gi|334120716|ref|ZP_08494794.1| ATP-dependent Clp protease adapter protein clpS [Microcoleus vaginatus FGP-2]
MSVEIIQKASTVRKLAPRYRVLLHNDDFNPMEYVVQTLMATVPSLTQPQAVNVMMEAHTNGMGLVIVCAL
EHAEFYAETLNNHGLSSSIEPDD

>gi|75907498|ref|YP_321794.1| clpS gene product [Anabaena variabilis ATCC 29413]
MSVETIEKRSTSRKLAPRYRVLLHNDDYNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLALVITCAQ
EHAEFYCETLKDHGLSSTIEPDE

>gi|209523998|ref|ZP_03272550.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira maxima CS-328]
MALVCFGIDKFPDHCNFVNGGDGSVSTQTVEKTSTNRKLAPRYRVLLHNDDYNPMEYVVQVLMSTVPGLT
QPQAVSIMMEAHTNGLALVITCALEHAEFYCETLKNHGLTSTIEPDE

>gi|354566131|ref|ZP_08985304.1| ATP-dependent Clp protease adapter protein clpS [Fischerella sp. JSC-11]
MSVETQQKRSTSRKLAPQYRVLLHNDDYNTMEYVVQVLLTTVPSLTQPQAVSIMMEAHSNGLALVITCAQ
EPAEFYCETLKNHGLTSTIEPEE

>gi|218246012|ref|YP_002371383.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 8801]
MTTEVIEKRSTSSATVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVAGMTQPQAVDIMMEAHTNGTALVI
TCALEHAEFYCETLKNHGLTSSIEPDE

>gi|16331021|ref|NP_441749.1| ATP-dependent Clp protease adaptor protein ClpS [Synechocystis sp. PCC 6803]
MMATEVLNKPSNSTIRKHAPRYRVLLHNDDFNSMEHVVQTLIQTVAGMTQPQAVDIMMEAHFNGMSLVIT
CELEHAEFYCETLRSHGLSSTIEPDE

>gi|218438615|ref|YP_002376944.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7424]
MSTSTQVIEKSTTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGTALVI
TCTLEHAEFYCETLKNHGLTSTIEPDE

>gi|282899028|ref|ZP_06307010.1| ATP-dependent Clp protease adaptor protein ClpS [Cylindrospermopsis raciborskii CS-505]
MSVETIEKPSTTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVSIMMEAHSHGLALVISCAL
EHAEFYCESLNNYGLTSTIEPDD

>gi|17231817|ref|NP_488365.1| clpS gene product [Nostoc sp. PCC 7120]
MSVETIEKRSTSRKLAPRYRVLLHNDDHNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLALVITCAQ
EHAEFYCETLKDHGLSSTIEPDE

>gi|291571937|dbj|BAI94209.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira platensis NIES-39]
MALVCFGIDKFPYHCTFVNGGDGSVSTQTVEKTSTNRKLAPRYRVLLHNDDHNPMEYVVQVLMSTVPGLT
QPQAVSIMMEAHTNGLALVITCALEHAEFYCETLKNHGLTSTIEPDE

>gi|158338702|ref|YP_001519879.1| clpS gene product [Acaryochloris marina MBIC11017]
MSVETLEKRSTSRKLAPKYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIALVITCAF
EHAEFYCETLKMHGLTSTIEPDE

>gi|307150896|ref|YP_003886280.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7822]
MSTSTSTQVIEKSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGMAL
VITCTLEHAEFYCETLKAHGLTSTIEPDE

>gi|159029424|emb|CAO90801.1| unnamed protein product [Microcystis aeruginosa PCC 7806]
MSTEVIEKRSTATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITC
IQEHAEFYCETLKNKGLTSSIEPDE

>gi|359457944|ref|ZP_09246507.1| ATP-dependent Clp protease adaptor protein ClpS [Acaryochloris sp. CCMEE 5410]
MSVETLEKRSTGRKLAPKYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIALVITCAF
EHAEFYCETLKMHGLTSTIEPDE

>gi|254423912|ref|ZP_05037630.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7335]
MSTSISTIEKPSVSTVRKIAPRYRVLLHNDDFNSMEYVVEALIETVPSLTAPQAIDIMMQTHNTGIGLVI
VCEMEHAEFYCEGLKGKGLTSTIEPEE

>gi|298490087|ref|YP_003720264.1| ATP-dependent Clp protease adaptor protein ClpS ['Nostoc azollae' 0708]
MSVETIEKRSTTRKLAPQYRVLLHNDDYNSMEYVVQVLMTSVPSITQPQAVNIMMEAHNSGLALVITCAQ
EHAEFYCETLKGHGLSSTIEPD

>gi|220908775|ref|YP_002484086.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7425]
MAVETIEQRSTVRKLAPRYRVLLHNDDVNSMEHVVEVLLKTVPSLTQPQAVDIMMEAHVNGIALVITCAL
EHAEFYCESLKLGGLTSTIEPDE

>gi|300868553|ref|ZP_07113170.1| ATP-dependent Clp protease adaptor protein ClpS [Oscillatoria sp. PCC 6506]
MSVETIEKRSTVRKIAPRYRVLLHNDDFNSMEYVVQTLMHTVPSLTQPQAVNIMMEAHTNGLAVVIICAQ
EHAEFYSETLNNHGLISTIEPDE

>gi|148972604|ref|ZP_01811408.1| ATP-dependent Clp protease adaptor protein ClpS [Leptolyngbya valderiana BDU 20041]
MSVETIEKRSTVRKHAPRYRVLLHNDDFNTMEYVVQTLVKTVPGLTQPQAVSIMMEAHTNGMALVITCAQ
EHAEFYCETLRRHGLSSSIEPDD

>gi|22297755|ref|NP_681002.1| clpS gene product [Thermosynechococcus elongatus BP-1]
MEAWPTMSVQTIEKPATVRKLAPRYRVLLHNDNVNSMEYVVEVLLKTVPSLTQPQAVDIMMEAHLTGVAL
VITCALEHAEFYCEGLKMAGLTSTIEPTE

>gi|166367986|ref|YP_001660259.1| ATP-dependent Clp protease adaptor protein ClpS [Microcystis aeruginosa NIES-843]
MIEKRSTATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITCIQEH
AEFYCETLKNKGLTSSIEPDE

>gi|170078877|ref|YP_001735515.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7002]
MSTGVIEQRSTSTIRKPAPRYRVLLHNDDFNSMEHVVQTLMQTVAGLTQPQAVSIMMEAHTNGIALVITC
VQEHAEFYCETLKMHGLTSTIEPDE

>gi|284929541|ref|YP_003422063.1| hypothetical protein UCYN_10070 [cyanobacterium UCYN-A]
MVTDVIEKISLNTSTTKKPVPRYKVLLHNDDFNPMDYVVQILMQTISGMTRPQAAEIMMEAHISGTALVI
TCAFEPAEFYRETLKNHGLSSSIEPDE

>gi|148243279|ref|YP_001228436.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. RCC307]
MTHASETPVSSPGGGAAVMERQPETVRKPSPRYRVLLHNDPVNSMEYVVTSLREVVPSLSEQDAMAVMLE
AHNSGVGLVIVCDIEPAEFYCESLKAKGLTSTIEPEE

>gi|254430350|ref|ZP_05044053.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanobium sp. PCC 7001]
MTAAAMTTVPQATQTPSRESGAAVMEKAPERVRKPSPRYKVLLHNDPVNSMEYVVTTLRQVVPSLSEQDA
IAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPDD

>gi|72382903|ref|YP_292258.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. NATL2A]
MSNIMVNSLSKSAIHLESLIMVDSANQTDGDTAVIDREVQRVRKISPKYKVLLHNDPVNTMDYVVEILRQ
VVPQLSEQDALNIMLETHNNGVGLVITCDLEPAEFYSESLKAKGLTSTIELES

>gi|86607127|ref|YP_475890.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. JA-3-3Ab]
MATETLVKPSVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPSMLPPQATEIMLEAHNNGVAVVIVVPR
EHAEFYCEQLRQHGLTSSIEPER

>gi|317968680|ref|ZP_07970070.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CB0205]
MIRSTQAPGRESGGAAVMEKAPERVRKPSPRYKVLLHNDPVNTMEYVVSTLRQVVPSLSEQDAIAVMMEA
HNTGVGLVIVCDIEPAEFYSETLKAKGLSSTIEPED

>gi|124026645|ref|YP_001015760.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. NATL1A]
MSNIMVSSLLKSAIHLDSLIMVDSANQTDGDTAVIDREVQRVRKISPKYKVLLHNDPVNTMDYVVDTLRQ
VVPQLSEQDALNIMLETHNNGVGLVITCDLEPAEFYSESLKAKGLTSTIELES

>gi|87301880|ref|ZP_01084714.1| hypothetical protein WH5701_01105 [Synechococcus sp. WH 5701]
MSDTIRATETPTRSPGGAAVIEKEVQRVRKPSPRYRVLLHNDPVNSMEYVVTTLRQVVPSLSEQDAIAVM
LEAHNTGVGLVIVCDLEPAEFYSETLKAKGLSSTIEPES

>gi|116075699|ref|ZP_01472958.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. RS9916]
MAVNTTSPGPGGAAVLDKQTERVRKRSPRYKVLLHNDPVNSMEYVVSTLQQVVPQLSEQDAMAVMLEAHN
SGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPES

>gi|78185599|ref|YP_378033.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CC9902]
MAEETPTRSPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVMTTLRQVVPQLSEQDAMAVMLEAHN
TGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPED

>gi|78211862|ref|YP_380641.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CC9605]
MVMAVESPSQKPGGAAVLDKAPEKVRKRSPRYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEA
HNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|116072120|ref|ZP_01469388.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. BL107]
MAEETPTRSPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVMATLRQVVPQLSEQDAMAVMLEAHN
TGIGLVIVCDIEPAEFYCETLKSKGLTSTIEPED

>gi|352096458|ref|ZP_08957285.1| ATP-dependent Clp protease adapter protein clpS [Synechococcus sp. WH 8016]
MVDTPSRSPGGAAVLDKQTERVRKTSPRYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNT
GVGLVIVCDIEPAEFYCETLKNKGLTSTIEPED

>gi|260434316|ref|ZP_05788286.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 8109]
MSRSISLFPLNLKVFGSMVMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCEMLKSKGLTSSIEPEE

>gi|113954242|ref|YP_729603.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CC9311]
MVDTPSRSPGGAAVLDKQTERVRKTSPRYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNT
GIGLVIVCDIEPAEFYCETLKNKGLTSTIEPES

>gi|86608169|ref|YP_476931.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. JA-2-3B'a(2-13)]
MATETLVKPSVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPAMMPPQATEIMLEAHHNGVAVVIVVPR
EHAEFYCEQLRQHGLTSSIEPER

>gi|87125032|ref|ZP_01080879.1| hypothetical protein RS9917_03483 [Synechococcus sp. RS9917]
MHRSDLAMVGSTSSTSPGGAAVLDKQTERVRKHSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMA
VMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPET

>gi|148238705|ref|YP_001224092.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 7803]
MVMAVETPSRTPGGAAVLEKAPERVRKQSPRYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEA
HNTGVGLVIVCDLEPAEFYCETLKGKGLTSTIEPEN

>gi|161353432|ref|NP_898239.2| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 8102]
MAMAVDTPTRSPGGAAVMEKAPERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEA
HNTGVGLVIVCDLEPAEFYCETLKAKGLTSTIEPET

>gi|88807954|ref|ZP_01123465.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 7805]
MAVETPSLTPGGAAVLDKAPERVRKQSPRYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEAHN
TGVGLVIVCDLEPAEFYCETLKGKGLTSTLEPDT

>gi|318042663|ref|ZP_07974619.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. CB0101]
MPELDWMPRSTPCTAAFTATQTPGRESGGGAVMEKAPERVRKPSPRYKVLLHNDPVNTMEYVVGTLRQVV
PSLSEQDAIAVMLEAHNTGVGLVIVCDIEPAEFYSETLKAKGLTSTIEPES

>gi|33633458|emb|CAE08663.1| conserved hypothetical protein [Synechococcus sp. WH 8102]
MASAPQVRATSDCPPSTAAPTWMLLWPESRPSEQVVQRFPLDLNLPNTMAMAVDTPTRSPGGAAVMEKAP
ERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEAHNTGVGLVIVCDLEPAEFYCET
LKAKGLTSTIEPET

>gi|123966912|ref|YP_001011993.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9515]
MSIIKLEKGDNNNAAVLEKKTAALKNKSPKYKVLLHNDPVNSMEYITIALREVVPQLSEQDAIAIMLEAH
NNGVGLVIVCDLEPAEFYSESLKSKGISSSIEKDE

>gi|124024066|ref|YP_001018373.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9303]
MGERPTYIGALPIVLAMAVNAPSPSPGGAAVLEKQTERIRKQSPHYKVLLHNDPVNSMEYVVVTLQQVVP
QLSEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEQES

>gi|33864059|ref|NP_895619.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9313]
MKLGLPTICTMGERPTYIGAVPIVLAMAVNAPSPTPGGAAVLEKQTERIRKQSPHYKVLLHNDPVNSMEY
VVVTLQQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEQES

>gi|159904162|ref|YP_001551506.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9211]
MSLVDWNYLPTGIMVEATGSSPGGATVIEKQSELVRKRSPRYKVLLHNDPVNSMDYVVTTLRQVVPQLSE
QDALAVMLEAHNTGVGLVIVCDLEPAEFYSESLKAKGLSSTIEKET

>gi|78779975|ref|YP_398087.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9312]
MLSIKLEQSVSNNSAVIEKKPAELKNKSPKYRVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|33241103|ref|NP_876045.1| clpS gene product [Prochlorococcus marinus subsp. marinus str. CCMP1375]
MVGNPGRGPGGAAVVDKQTERVRKTSPRYKVLLHNDPVNTMDYVVTTLRQVVPQLSEQDAMAVMLETHNT
GIGLVITCDLEPAEFYSESLKGKGLTSTIEPES

>gi|123969234|ref|YP_001010092.1| clpS gene product [Prochlorococcus marinus str. AS9601]
MLSIKLEQSGSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|157414100|ref|YP_001484966.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9215]
MSSIKLEQRVSNSSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGIGLVIICDLEPAEFYSESLKSKGISSSIEKED

>gi|254526054|ref|ZP_05138106.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9202]
MLSIKLEQSVSNGSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGIGLVIICDLEPAEFYSESLKSKGISSSIEKED

>gi|33862055|ref|NP_893616.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus subsp. pastoris str. CCMP1986]
MINRFSCNYNQKVMSNIKFEKGENNNAAVLEKKTAPLKNKSPKYKVLLHNDPVNSMEYVTNALREVVPQL
SEQDAISIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|357263411|gb|EHJ12427.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 0003]
MEYVVQTLMQIVPSITQPQAVDIMMEAHSNGTALVITCALEPAEFYSETLKNHGLTSTIEPDE

>gi|119489795|ref|ZP_01622553.1| ATP-dependent Clp protease adaptor protein ClpS [Lyngbya sp. PCC 8106]
MEYVVQVLLQTVPSLTQPQAVSIMMEAHTNGLALVITCAQEHAEFYCETLKNNGLTSTIEPDE

>gi|254414360|ref|ZP_05028127.1| ATP-dependent Clp protease adaptor protein ClpS [Microcoleus chthonoplastes PCC 7420]
MEYVVQALIQTVPSLTQPQAVNIMMEAHNSGIALVITCALEHAEFYCETLKNHGLTSTIEPDE

>gi|121489819|emb|CAK19331.1| putative adaptor protein ClpS [Physcomitrella patens]
MAGSLRLFVSIPATARHFGINGVEKAQRVHNRVNGRYKINAASGPSQGGGVLDRPTIDKPTPGRESEFDL
KKKKKISPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLAVVIVCPQEDAEDYCMQ
LRTNGLLSSIEPASC

>gi|302761288|ref|XP_002964066.1| hypothetical protein SELMODRAFT_142341 [Selaginella moellendorffii]
MACTLTQVAHLWPSTSQVSRFNTIFAEADKCHKCFTRIIASHAVRAALPGGLGGGVLDKPAIETAPTPGR
ESEFDLRKKKKMAPPYRVILHNDNFNRREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGLSVVIVCSQEDA
EEHCTQLRANGLLSSIEPASGGSC

>gi|87303756|ref|ZP_01086507.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 5701]
MLLHNDPVNSMEYVMATLRQVVPQLSEQDAMAVMLEAHNTGIGLVIVCDIEPAEFYCETLKSKGLTSTIE
PED

>gi|168011584|ref|XP_001758483.1| predicted protein [Physcomitrella patens subsp. patens]
QGGGVLDRPTIDKPTPGRESEFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMN
EAHINGLAVVIVCPQEDAEDYCMQLRTNGLLSSIEP

>gi|37520315|ref|NP_923692.1| ATP-dependent Clp protease adaptor protein ClpS [Gloeobacter violaceus PCC 7421]
MSTETLERKSVQRKPMPLYKVLLHNDDHTPMNYVIEVLMKTIPKMQPSKARKIMLEAHNGGVAVVIVCAL
EHAEFYSESLNRHNLTSTYEPDC

>gi|168014848|ref|XP_001759963.1| predicted protein [Physcomitrella patens subsp. patens]
AAAPGQGGGVMDRPTIDKPTPGRESEFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLLKAIPGMTVDIA
VNVMNEAHINGIAVVIVCPQEDAEDYCMQLRTNGLLSSIEPD

>gi|119510879|ref|ZP_01630003.1| ATP-dependent Clp protease adaptor protein ClpS [Nodularia spumigena CCY9414]
MEHVVQSLITTVPSLTQPQAVSIMMEAHTNGMALVITCAQEHAEFYCETLKSHGLSSTIEPDE

>gi|351723283|ref|NP_001234970.1| uncharacterized protein LOC100527361 [Glycine max]
MKSAICGRILSPNHVFKPGDTHSICKGPYSNLCVPMAVLATGPGKGGGVLEKPVIEKVTPGRESEFDLKK
SRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAEDHCTQLR
GNGLLSSIEPASGGC

>gi|351721328|ref|NP_001235414.1| uncharacterized protein LOC100500511 [Glycine max]
MKSAICGRILSPNHVFKPGDTHSICKGPYSNLCVPMVVLATGPGIGGGVLEKPVIEKVTPGRESEFDLKK
SRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAEDHCMQLR
GNGLLSSIEPANGGC

>gi|18409086|ref|NP_564937.1| ATP-dependent Clp protease adaptor protein ClpS [Arabidopsis thaliana]
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRSILMTLSTSAALGKGGGVLDKPIIEKTTPGRESEF
DLRKSKKIAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAEQHC
MQLRGNGLLSSVEPDGGGC

>gi|108803856|ref|YP_643793.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
MVGSLTRDIRCSAATKTAPARKTRRAPSREPRYRVILHNDDWTPMDHVVAALMKVVPRLSLRRAVSIMLE
AHTKGQAVVTRCHRELAELYREGLKAEGLISTIEPDG

>gi|225423913|ref|XP_002281884.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS [Vitis vinifera]
MENAICGRLALSPNHVFNSKSGDKHSLLKGPCTNRSFLMAISASGPGKGGLLERPVIEKVTPGRESEFDL
RKSRKIAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAEDHCMQ
LRGNGLLSSIEPASGGC

>gi|297841589|ref|XP_002888676.1| hypothetical protein ARALYDRAFT_894639 [Arabidopsis lyrata subsp. lyrata]
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRGVLMTLSTYAALGKGGGVLDKPIIEKTTPGRESEF
DLRKSKKMAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAEQHC
MQLRGNGLLSSVEPDGGGC

>gi|255576515|ref|XP_002529149.1| ATP-dependent Clp protease adaptor protein clpS, putative [Ricinus communis]
MALSATGAGKGGGLLEKPVIEKTTPGRESEFDLRKSRKTAPPYRVILHNDNYNKREYVVQVLMKVIPGMT
LDNAVNIMQEAHYNGLSVVIICAQADAEDHCMQLRGNGLLSSIEPASGGC

>gi|223943781|gb|ACN25974.1| unknown [Zea mays]
MALSAAAPGKGGGVLDRPVEKTTPGRQSEFDVKKSRKMSPPYRVILHNDNYNRREYVVKVLMKVIPGMTV
DNAVNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNGLRSSIEPASGGC

>gi|357488429|ref|XP_003614502.1| ATP-dependent Clp protease adapter protein clpS [Medicago truncatula]
MKSAICRSMGLSPNHLFISGDRYSFCKGPYSNLCVPMAVLTKGSGKGGGILEKPVIEKATPGRESEFDLK
KSRKTAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQADAEDHCMQL
RGNGLLSSIEPAGDGC

>gi|356531226|ref|XP_003534179.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS-like [Glycine max]
MEAALCSALALSPNQVFNAANPGDKNVPLKYSKDRSVVMTVAATGILGKGGGLLERPTIETTSPGRESEF
DLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAEDHC
MQLRGNGLLSSIEPADGGGC

>gi|147805878|emb|CAN78258.1| hypothetical protein VITISV_026645 [Vitis vinifera]
METAICGRVPLSPNXFFTSKSAPGKGSGVLERPTIERIMPGRESEFDLRKSRKMSPPYRVLLHNDNYNKR
EYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQVDAEXHCMQLRGNGLLSSIEPASGGC

>gi|351724025|ref|NP_001237811.1| uncharacterized protein LOC100306117 [Glycine max]
MEAALCSALAPSPNQVFNAANPGDKNVPLKYSKDRSVVMTVAATGILGKGGGLLERPTIETTSPGRESEF
DLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAEDHC
MQLRGNGLLSSIEPADGGGC

>gi|242081547|ref|XP_002445542.1| hypothetical protein SORBIDRAFT_07g021160 [Sorghum bicolor]
MEAAVPSRVALSAASRLPNRHAVAGDRSFVYKGRCQSLAIPMALSAAAPGKGGVLDRPVEKTTPGRQSEF
DVKKSRKMSPPYRVILHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAEEHC
TSLRGNGLRSSIEPASGGC

>gi|226506038|ref|NP_001150373.1| ATP-dependent Clp protease adaptor protein ClpS containing protein [Zea mays]
MEAAVPSRVALSAASRLPNPHAVTGDRSFIYKGRCQSLAIPMALSAAAPGKGGGVLDRPVEKTTPGRQSE
FDVKKSRKMSPPYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|115476544|ref|NP_001061868.1| Os08g0432500 [Oryza sativa Japonica Group]
MEAAVPSRVALSASRLSNHHHHAVGGERYAIYRGRCPNPAIPMALAAAAAPGKGGGVLDRPIEKVTPGRQ
SEFDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIICSQSEAE
EHCTSLRGNGLRSSIEPASGGC

>gi|225455872|ref|XP_002274839.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS [Vitis vinifera]
METAICGRVPLSPNHFFTSKSGDKHSLSKQWTHRTMLMTVSAAAPGKGSGVLERPTIERIMPGRESEFDL
RKSRKMSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMSVVIICAQVDAEDHCMQ
LRGNGLLSSIEPASGGC

>gi|294460817|gb|ADE75982.1| unknown [Picea sitchensis]
MASVIYSRLILPQPQLYQQKSGEKISQSKGACMNRVFSAIRSTSPGGKGGGLLERPTIEKTTPGRESEFD
LRKSRKTSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDTAVNIMQEAHYNGLAVVIICAQVDAEEHCT
QLRGNGLLSSIEPASDGC

>gi|332711797|ref|ZP_08431728.1| hypothetical protein LYNGBM3L_67610 [Lyngbya majuscula 3L]
MEYVVKTLMETVASLTQPQAVNIMMEAHQSGLALVITCAQEHAEFYCETLKNRGLTSTIEPDE

>gi|224099343|ref|XP_002311446.1| predicted protein [Populus trichocarpa]
METAICGRIALSPNHVFNPKPGDKNSVCRGPCANRGILMAISTTCSGKGGGLLEKPVIERTTPGRESEFD
LRKSKKMAPPYRVMLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAEEHCM
QLRGNGLLSSIEPASGGC

>gi|224111728|ref|XP_002315955.1| predicted protein [Populus trichocarpa]
METAICGRIALSPNHVFNPKPGDKNSVCRGPCASRGILMSISATVSGKGGGGGGGILEKPVIERTTPGRE
SEFDLRKSKKMAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICTQADAE
EHCMQLRGNGLLSSIEPASGGC

>gi|125603506|gb|EAZ42831.1| hypothetical protein OsJ_27419 [Oryza sativa Japonica Group]
MEAAVPSRCGALREPALQPPPPRGERYAIYRGRCPNPAIPMALAAAAAPGKGGGVLDRPIEKVTPGRQSE
FDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIICSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|357147864|ref|XP_003574520.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS-like [Brachypodium distachyon]
MEAAVPSRIALSARIMNHHVVAAGGRSSIYRGRYPNIAIPIVVTAAGKGGGVLDRPAEKISPGRQSEFDV
KKSRKMSPPYRVVLHNDNENRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLAVVIVCSQSEAEEHCTS
LRGNGLRSSIEPASGGC

>gi|223948869|gb|ACN28518.1| unknown [Zea mays]
MALSAAAPGKGGGVLDRPVEKITPGRQSEFDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTV
DNALNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNGLRSSIEPASGGC

>gi|307105846|gb|EFN54094.1| hypothetical protein CHLNCDRAFT_31972 [Chlorella variabilis]
MTICVGQRLGGQAVAGKAGDKPPTRGAWLVPAGATRRSAQRRARLHVAARSAGKGGGVLDRPGVLPGQQR
GRETRRRRPPSYRVLLHNDNYNRREYVVQVLMKVVEGTTVDDAVNIMQEAHINGLAMVTQCAQDKAELYC
ESLRLNGLIATIEPAGTGGSDGTSSS

>gi|226493842|ref|NP_001148322.1| ATP-dependent Clp protease adaptor protein ClpS containing protein [Zea mays]
MMASVPSRVALSAASRLPNLHAVAGDRSFIYKRRCPSLSIPMALSAAAPGKGGGVLDRPVEKITPGRQSE
FDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALNIMQEAHVNGLSVVIVCSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|195652021|gb|ACG45478.1| ATP-dependent Clp protease adaptor protein ClpS containing protein [Zea mays]
MMASVPSRVALSAASRLPNLHAVAGDRSFIYKRRCPSLSIPMALSAAAPGKGGGVLDRPVEKITPGRQSE
FDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALSIMQEAHVNGLSVVIVCSQSEAEEH
CTSLRGNGLRSSIEPASGGC

>gi|126697028|ref|YP_001091914.1| hypothetical protein P9301_16901 [Prochlorococcus marinus str. MIT 9301]
MEYVTISLREVVPQLSEQDAIAIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|298245523|ref|ZP_06969329.1| ATP-dependent Clp protease adaptor protein ClpS [Ktedonobacter racemifer DSM 44963]
MAQRQCQPSRLEIRPEEVVRQRSSLLPLYKVILFNDDYNDMLHVVAALLETVNTLTMQEATHIMLTAHLN
GNAIVIVCPHELAEHYQERLLGYALTVTIEPE

>gi|81299287|ref|YP_399495.1| clpS gene product [Synechococcus elongatus PCC 7942]
MSPQPDESVLSILGVPRPCVKKRSRDDAFVLTVLTCSLQAIAAPATAPGTTTTRVRQPYPHFRVIVLDDD
VNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAELYHEQLRREGLTMAPLEAA

>gi|56751052|ref|YP_171753.1| clpS gene product [Synechococcus elongatus PCC 6301]
MSPQPDESVLSILGVPRPCVKKRSRNDAFVLTVLTCSLQAIAAPATAPGTTTTRVRQPYPHFRVIVLDDD
VNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAELYHEQLRREGLTMAPLEAA

>gi|218441397|ref|YP_002379726.1| ATP-dependent Clp protease adaptor [Cyanothece sp. PCC 7424]
MSTNVAAVVTAMTTAPTIAPDKTTQVVKKTYPNYKVIVLNDDFNTFQHVANCLMKYIPGMTSDRAWELTN
QVHYEGQATVWVGPQEQAELYHQQLRREGLTMAPLEAA

>gi|119510612|ref|ZP_01629742.1| ATP-dependent Clp protease adaptor protein ClpS [Nodularia spumigena CCY9414]
MVTRLSAAVYGAGTAPTVTPGKTTEVVRKTYPNYKVIVLNDDFNTFQHVSECLMKYIPGMTGDRAWDLTN
QIHYEGQAIVWVGPQEMAELYHQQLRRAGLTMAPLEAA

>gi|354566811|ref|ZP_08985982.1| ATP-dependent Clp protease adapter protein clpS [Fischerella sp. JSC-11]
MITKLSAAVYAMAATPTIAPERSTQVTRKPYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTSDRAWELTN
QVHYEGQAIVWTGPQEPAELYHQQLRRAGLTMAPLEAA

>gi|307150152|ref|YP_003885536.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7822]
MSTNVAAVVKAMATAPTVAPDKTTQVVKKTYPNYKVIVLNDDFNTFEHVAKCLMKYIPGMTSDRAWELTN
QVHFEGQAIVWVGPQEQAELYHQQLRREGLTLAPLEAA

>gi|16330271|ref|NP_440999.1| ATP-dependent Clp protease adaptor [Synechocystis sp. PCC 6803]
MISNAATSTPDRLTSTVRKTYPNFKVIVLNDDFNTFQHVSDCLLKYIPGMTGDRAWELTNQVHFDGLAIV
WVGPQEQAELYHQQLRREGLTMAPLEKA

>gi|218246561|ref|YP_002371932.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 8801]
MATAPSVAPKGSTAVVNKPYPNYKVIVLNDDFNSFEHVAKCLMTYIPGMTSDRAWELTNQVHFEGQATVW
VGPQEQAELYHQQLRREGLTMAPLEKA

>gi|75909055|ref|YP_323351.1| clpS gene product [Anabaena variabilis ATCC 29413]
MVTKLSIDVYAMSTAPTVTPERSNQTVRKSYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTN
QVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEAA

>gi|17227900|ref|NP_484448.1| clpS gene product [Nostoc sp. PCC 7120]
MVTKLSIDVYAMSTAPTVTPERSNQTVRKTYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTN
QVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEAA

>gi|209526864|ref|ZP_03275384.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira maxima CS-328]
MIASPTTTPSRSSQTVRKPYPNYKVIVLNDDFNTFQHVANCLMKYLPGMTSDQAWELTNRVHYEGQATVW
VGPLEQAELYHTQLSREGLTMAPLEKA

>gi|172038476|ref|YP_001804977.1| putative ATP-dependent Clp protease adaptor protein [Cyanothece sp. ATCC 51142]
MSKRLSTGIQGMATSTSTAPKGSTVIDRKPYPNYKVIVLNDDFNTFNHVANCLMKYIPGMSSDRAWELTE
QVHFEGLAIVWTGPQEQAELYHQQLRREGLTMAPLEEA

>gi|291567197|dbj|BAI89469.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira platensis NIES-39]
MVASPTTTPSRSSQTVRKPYPNYKVIVLNDDFNTFQHVANCLMKYLPGMTSDQAWELTNRVHYEGQATVW
VGPLEQAELYHTQLSREGLTMAPLEKA

>gi|186684201|ref|YP_001867397.1| ATP-dependent Clp protease adaptor [Nostoc punctiforme PCC 73102]
MVRNLSADVYGMTTAPTITPERSSQVTRKTYPNYKVIVLNDDFNTFQHVAECLMKYIPGMSGDRAWDLTN
QVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEAA

>gi|21542305|sp|Q8YZQ3.2|CLPS_NOSS1 RecName: Full=ATP-dependent Clp protease adapter protein ClpS
MSTAPTVTPERSNQTVRKTYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTNQVHYEGQAIVW
VGPQEPAELYHQQLRRAGLTMAPLEAA

>gi|300864591|ref|ZP_07109450.1| ATP-dependent Clp protease adaptor [Oscillatoria sp. PCC 6506]
MTSSPTIAPDRSSQVTRKPYPNYKVIVLNDDFNTFQHVSECLVKYIPGMTSDRAWKLTNQVHYEGQATVW
VGPQEQAELYHMQLSRAGLTMAPLEQA

>gi|166363445|ref|YP_001655718.1| ATP-dependent Clp protease adaptor [Microcystis aeruginosa NIES-843]
MSSAPSTTLDKSTQVVKKTYPNYKVIVLNDDFNTFDHVANCLIKYIPDMTTDRAWELTNQVHYQGQAIVW
TGPQEQAELYHQQLRREGLTMAPLEAA

>gi|67924463|ref|ZP_00517887.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 8501]
MSKRLSIGIRGMATSTSTAPKGATVVERKRYPNYKVIVLNDDFNTFDHVAKCLLKYIPGMSSDRAWELTE
QVHFEGLATVWTGPQEQAELYHQQLRREGLTMAPLEEA

>gi|126656780|ref|ZP_01727994.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. CCY0110]
MATSTSTAPKGSTVIDRKPYPNYKVIVLNDDFNTFNHVANCLMKYIPGMSSDRAWELTEQVHFEGLAIVW
TGPQEQAELYHQQLRREGLTMAPLEEA

>gi|357261617|gb|EHJ10864.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 0003]
MATSTSTAPKGATVVERKHYPNYKVIVLNDDFNTFDHVAKCLLKYIPGMSSDRAWELTEQVHFEGLATVW
TGPQEQAELYHQQLRREGLTMAPLEEA

>gi|282901708|ref|ZP_06309624.1| ATP-dependent Clp protease adaptor protein ClpS [Cylindrospermopsis raciborskii CS-505]
MKTRPSPVYAMASAPTVTPDQGTQVVRKPYPNYKVIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWELTNQ
VHYEGQAIVWVGPQEQAELYHQQLRRAGLTMAPLEAA

>gi|282895992|ref|ZP_06304023.1| ATP-dependent Clp protease adaptor protein ClpS [Raphidiopsis brookii D9]
MKTRPSPIYAMAPAPTVTPDQGTQVIRKPYPNYKIIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWELTNQ
VHYEGQAIVWVGPQEQAELYHQQLRRAGLTMAPLEAA

>gi|298491120|ref|YP_003721297.1| ATP-dependent Clp protease adaptor protein ClpS ['Nostoc azollae' 0708]
METRLAAVYYDMATAPTVTPDRVNQVTRKTYPNYKVIVLNDDFNTFQYVAECLMKYIPGMSGDLAWDLTN
QVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEGA

>gi|159031002|emb|CAO88704.1| clpS [Microcystis aeruginosa PCC 7806]
MASAPSTTLDKSTQGVKKTYPNYKVIVLNDDFNTFDHVANCLIKYIPDMTTDRAWELTNQVHYQGQAIVW
TGPQEPAELYHQQLRREGLTMAPLEAV

>gi|254412762|ref|ZP_05026535.1| ATP-dependent Clp protease adaptor protein ClpS [Microcoleus chthonoplastes PCC 7420]
MTVVISAARSATSAAPTQAPEKSRQVTRKPYPNYKVIVLDDDFNTFQHVHDCLVKYIPGMSSDYAWKLTN
QVHFEGQAIVWVGPQEQAELYHQQLSRAGLTMAPLEAA

>gi|119490026|ref|ZP_01622650.1| ATP-dependent Clp protease adaptor protein ClpS [Lyngbya sp. PCC 8106]
MTSSPTVAPSRSSQVTQQPYPNYKVIVLNDDFNTFEHVSSCLMKYIPGMNSDLAWKLTNQVHFEGQATVW
VGPLEQAELYHTQLSREGLTMAPLEKA

>gi|334119600|ref|ZP_08493685.1| ATP-dependent Clp protease adapter protein clpS [Microcoleus vaginatus FGP-2]
MTSSPTIAPVRSSQVTRKPYPNYRVIVLNDDFNTFQHVVECLTKYIPGMTSDQAWKLANQIHHEGQATVW
VGPQEQAELYHMQLSRAGLTMAPLEST

>gi|332708950|ref|ZP_08428921.1| hypothetical protein LYNGBM3L_32060 [Lyngbya majuscula 3L]
MVRSAAYKATFAAPVKAPERSGQVTRKPYPKYKVIVLDDDFNTFQHVHDCLVKYIPGMTNDHAWELTHQV
HNEGQAIVWVGPQEQAELYHQQLSRAGLTMAPLEAT

>gi|170078679|ref|YP_001735317.1| putative ATP-dependent Clp protease adaptor protein [Synechococcus sp. PCC 7002]
MAPAPGILKESDRQTVRKPYPNFKVIVLNDDFNTFEHVAHCLMTYIPNMTADQAWNLTNQVHFDGQAIVW
VGPQEPAELYHQQLRREGLTMAPLEAA

>gi|22298631|ref|NP_681878.1| clpS gene product [Thermosynechococcus elongatus BP-1]
MPSVVPQERQQVTRKHYPNYKVIVLNDDFNTFQHVAACLMKYIPNMTSDRAWELTNQVHYEGQAIVWVGP
QEQAELYHEQLLRAGLTMAPLEPE

>gi|359459224|ref|ZP_09247787.1| ATP-dependent Clp protease adaptor protein ClpS [Acaryochloris sp. CCMEE 5410]
MAITAVQTPVTRPEEKQAQKTVRKPYPNFKVIVVNDDVNTFEHVAKTLMTYIPHMTSDKAWELTNQIHFE
GQAIVWVGPQEQAELYHMQLQRAGLTMAPLEAA

>gi|86606056|ref|YP_474819.1| ATP-dependent Clp protease adaptor [Synechococcus sp. JA-3-3Ab]
MTTEAPTRPAQQSSPSRTRVRQPYPHFKVIVLDDDFNTFQHVTECLLKYIPGMTLPLARQLTVQVDAEGQ
AVVWVGPQEQAELYHQQLLREGLTMAPLEPA

>gi|113477268|ref|YP_723329.1| clpS gene product [Trichodesmium erythraeum IMS101]
MSLGISIIGIIENIAVRGGASSPTTLAPKKDSQVVNKPYPNYKVIVLNDDVNTFKHVAECLQKYIPGMTS
DRAWELTYQVHNEGQAIVWVGPLEQAELYHQQLSRAGLTMAPLEKA

>gi|158337023|ref|YP_001518198.1| clpS gene product [Acaryochloris marina MBIC11017]
MQTPVTRPEEKQAQKTVRKPYPNFKVIVVNDDVNTFEHVAKTLMTYIPHMTSDKAWELTNQIHFEGQAIV
WVGPQEQAELYHMQLQRAGLTMAPLEAA

>gi|220909224|ref|YP_002484535.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7425]
MVRPIQTSSLSPLAVATPRQSPTPVQDRQTIRQPYPHYKVIVLNDDFNTFEHVAKCLMKYIPNMTSDRAW
ELTYQVDREGQAIVWVGPQEQAELYHLQLGQAGLTMAPLELA

>gi|86610000|ref|YP_478762.1| ATP-dependent Clp protease adaptor [Synechococcus sp. JA-2-3B'a(2-13)]
MTTEAPTRPAQQFSPSRTQVRQPYPHFKVIVLDDDFNTFQHVTECLLKYIPGMTLPLARQLTVQVDAEGQ
AVVWVGPQEQAELYHQQLLREGLTMAPLEPA

>gi|87302745|ref|ZP_01085556.1| hypothetical protein WH5701_13370 [Synechococcus sp. WH 5701]
MAAPGVQTIPAGIRQRQRYPHLRVVVLDDDVNTFQHVVNCLVRYLPGMGPDRAWELAHQIDSQGSAVVWS
GPQEQAELYHQQLSQEGLTMAPLERE

>gi|284928874|ref|YP_003421396.1| hypothetical protein UCYN_02930 [cyanobacterium UCYN-A]
MFKRLSITIPETSISTNIKHSAVIDYKPYPNCKIIVLNDDFNTFDHVANCLIRYIPAMTKSHAWELTQKI
HFNGFATVWMGPLEQAELYHQQLRREGLTMAPLEGI

>gi|148242507|ref|YP_001227664.1| ATP-dependent Clp protease adaptor [Synechococcus sp. RCC307]
MTSSAPSRQTAGSTLLERAPYPNFKVVVLNDEVNTFQHVVDCLVKYIPAMDPDRAWSLAQQIDSDGQAVV
WVGPQEQAELYHMQLGAEGLTMAPLERA

>gi|87124406|ref|ZP_01080255.1| hypothetical protein RS9917_12370 [Synechococcus sp. RS9917]
MTVTPTGTATVLDRATSRSDYPQARVIVLDDDVNTFQHVVDCLCRIIPGMGSERAWDLAHRIDSEGAADV
WSGPLEQAELYHQQLSAEGLTMAPLERC

>gi|37521807|ref|NP_925184.1| ATP-dependent Clp protease adaptor [Gloeobacter violaceus PCC 7421]
MSSATVTPTKPETSVKALKPWKVIVLNDDFNTFQHVANCLVKYIPHMHPDRAWKLTQQVHSEGRAIVWVG
PLEQAELYHEQLSREGLTMAPLEQA

>gi|260434286|ref|ZP_05788256.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 8109]
MTSSSPGSSAVLERQGTTQRYPQARVIVLDDDVNTFQHVVDCLRKIIPGMSEDNAWNLANRIDGHGAAEV
WCGPLEQAELYHQQLQSEGLTMAPLERC

>gi|78212974|ref|YP_381753.1| ATP-dependent Clp protease adaptor [Synechococcus sp. CC9605]
MTSSSPGSSAVLERQGTTQRYPQARVIVLDDDVNTFQHVVDCLRKIIPGMSEDNAWNLANRIDGQGSAEV
WCGPLEQAELYHQQLQAEGLTMAPLERC

>gi|318041538|ref|ZP_07973494.1| ATP-dependent Clp protease adaptor [Synechococcus sp. CB0101]
MAQQAVRDKQRVDAPYPTGRVIVLDDDHNTFQHVVEVLVRYIPAMTSDRAWELAHQIDGQGSALVWSGPL
EQAELYHQQLGAEGLTMAPLERG

>gi|317970016|ref|ZP_07971406.1| ATP-dependent Clp protease adaptor [Synechococcus sp. CB0205]
MQPIRSISSSPGGQAVMERQRVRAPYPTGRVIVLDDDHNTFQHVVEVLVKHIPAMVSDRAWELAHQIDSQ
GSAVVWSGPLEQAELYHQLLAGEGLTMAPVERG

>gi|113955042|ref|YP_730629.1| ATP-dependent Clp protease adaptor [Synechococcus sp. CC9311]
MTMATPGTASVLQPERTTLRYPNARVIVLNDDVNTFEHVVECLCKIIPGMNSDKAWTLAHQIDGEGAAEV
WAGPLEPAELYHQQLSSEGLTMAPLERN

>gi|116074794|ref|ZP_01472055.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. RS9916]
MTGSSGAQSTLLERSRTTQGYPEARVIVLNDDVNTFQHVVDCLCKIIPGMGTERAWDLAHQVDGQGSAEV
WCGPLEQAELYHQQLTGEGLTMAPIERC

>gi|33862944|ref|NP_894504.1| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. MIT 9313]
MTFATPGTTPLLERAKQTQRYPQARVIVLNDDVNTFQHVVDCLRRIIPGMSEERAWNLAHQIDGQGSAEV
WCGPLEQAELYHQQLSGEGLTMAPLERC

>gi|352093981|ref|ZP_08955152.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 8016]
MATPGTASVLQPERTTLRYPNARVIVLNDDVNTFEHVVECLCKIIPGMNSDKAWTLAHQIDGEGSAEVWA
GPLEPAELYHQQLSSEGLTMAPLERN

>gi|124023254|ref|YP_001017561.1| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. MIT 9303]
MTFATPGSTPLLERAKQTQRYPQARVIVLNDDVNTFQHVVDCLRRIIPGMSEERAWNLAHQIDGQGSAEV
WCGPLEQAELYHQQLSGEGLTMAPLERC

>gi|33865838|ref|NP_897397.1| ATP-dependent Clp protease adaptor [Synechococcus sp. WH 8102]
MSSSSPGSASLLERQTITQRYPQARVIVLDDDVNTFQHVVDCLRKIIPGMSEEKAWSLANRIDGQGSAEV
WCGPLEQAELYHQQLAAEGLTMAPLERC

>gi|116070493|ref|ZP_01467762.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. BL107]
MTSSSPSSSTLLERQKTTQRYPEAKVIVLDDDVNTFQHVVDCLRKIIPGMDEDKAWGLAHRIDGEGSAEV
WRGPLEQAELYHQQLQTEGLTMAPLDRC

>gi|88808607|ref|ZP_01124117.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. WH 7805]
MYLLVQASCSRALMTSSSPGVSTVLERDRQALRYPQARVIVLNDDVNTFEHVVESLCRIIPGMNTDKAWA
LARRVDGEGSAEVWCGPLEQAELYHQQLGADGLTMAPIERC

>gi|78779324|ref|YP_397436.1| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. MIT 9312]
MYNSPLTVLDNKKSKVKYPEARVIVLDDSFNTFQHVANCLLIIIPGMSENRAWDLTIKVDNTGSAEVWRG
NLEQAELYHEQLVSKGLTMAPIDKT

>gi|148239546|ref|YP_001224933.1| ATP-dependent Clp protease adaptor [Synechococcus sp. WH 7803]
MTSSSPGVSTVLERDRQAQRYPQARVIVLNDDFNTFEHVVESLCRIIPGMNTEKAWSLAHRIDGEGAAEV
WCGPLEQAELYHQQLGAEGLTMAPIERC

>gi|123968534|ref|YP_001009392.1| clpS gene product [Prochlorococcus marinus str. AS9601]
MVNSLGTVLEPKKSKAKYPEARVIVLDDNFNTFQHVANCLLTIIPSMSEQRAWDLTIKVDKTGSAEVWRG
NLEQAELYHEQLFSKGLTMAPIEKT

>gi|126696337|ref|YP_001091223.1| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. MIT 9301]
MFNSLGTVLDPKKSKAKYPEARVIVLDDNFNTFQHVANCLLTIIPSMSEQRAWDLTIKVDKTGSAEVWRG
NLEQAELYHEQLFSKGLTMAPIEKT

>gi|72002284|gb|AAZ58086.1| conserved hypothetical protein [Prochlorococcus marinus str. NATL2A]
MLKDVLQLTAATAMKFSTNSTTTVLDPKTTKIKYPEARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWE
LAVEVDREGLAEVWRGPFEQAELYHQQLISKGLTMAPIEKT

>gi|78184628|ref|YP_377063.1| ATP-dependent Clp protease adaptor [Synechococcus sp. CC9902]
MTSSSPSSSTLLERQKTTQRYPEAKVIVLDDDVNTFQHVVDCLRKIIPGMDEEKAWGLAHRIDGQGSAEV
WRGPLEQAELYHLQLQTEGLTMAPLDRC

>gi|159904055|ref|YP_001551399.1| hypothetical protein P9211_15141 [Prochlorococcus marinus str. MIT 9211]
MRETKRRNQCSRRAHQKDASRNGRPLLLMMDKKIMTRHTKDFVATTAMKFSANSTTTVLDPKTTKKKYPE
ARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWVLAVEVDREGLAEVWRGPLEQAELYHQQLISKGLTMA
PIEKT

>gi|161347556|ref|YP_291789.2| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. NATL2A]
MKFSTNSTTTVLDPKTTKIKYPEARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWELAVEVDREGLAEV
WRGPFEQAELYHQQLISKGLTMAPIEKT

>gi|33241004|ref|NP_875946.1| clpS gene product [Prochlorococcus marinus subsp. marinus str. CCMP1375]
MKFSANSTTTVLDPKTTKKKYPEARIIVLDDNFNTFEHVANCLATIIPGMSEKRSWVLAVEVDREGLAEI
WRGPLEQAELYHQQLISKGLTMAPIEQT

>gi|254526218|ref|ZP_05138270.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. MIT 9202]
MFNSLSIVLDQKKSKAKYPEARVIVLDDSSNTFQHVAYCFLTIIPSMSERRAWNLTIKVDKTGSAEVWRG
NLEQAELYHEQLLSKGLTMAPIEKT

>gi|254421403|ref|ZP_05035121.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7335]
MLNDDFNTFEHVVKTLTTYIPGMNSDQAWELADQIHNEGQAIVWTGPLEQAELYHSQLIRAGLTVAPLEK
A

>gi|157413367|ref|YP_001484233.1| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. MIT 9215]
MLNSLSTVLDQKKSKAKYPEARVIVLDDSFNTFQYVANCLLTIIPSMSERRARDLTIKVDKTGSAEVWRG
NLEQAELYHEQLLSKGLTMAPIEKT

>gi|284045641|ref|YP_003395981.1| ATP-dependent Clp protease adaptor protein ClpS [Conexibacter woesei DSM 14684]
MGQTIEKQRVQGPGSGLGGNWRVIVKNDDHNTFDHVARTLARYIPGVTIAVGYDYADRIHNSGQAIVWSG
QREVAELYWEQLQGAGLTMAPLEQG

>gi|284051855|ref|ZP_06382065.1| ATP-dependent Clp protease adaptor protein ClpS [Arthrospira platensis str. Paraca]
MTSDQAWELTNRVHYEGQATVWVGPLEQAELYHTQLSREGLTMAPLEKA

>gi|367468593|ref|ZP_09468447.1| ATP-dependent Clp protease adaptor protein ClpS [Patulibacter sp. I11]
MSQTIEQTRAADPGTGLGGAWNVIVRNDDHNTFDHVATTLARVIPGVNVDAGFRLADRIHQAGLAVVWTG
HKELAEHYWEQLRDAGLTMAPLEQA

>gi|37522100|ref|NP_925477.1| hypothetical protein gll2531 [Gloeobacter violaceus PCC 7421]
MLSSAEAPSPGTVQWAPNGQKAQDRQHRVASVHVTGLAASGYLAVASYPASRQPGDVQKRLRWGAIVVSF
GYTGTQDDYPHASMERMVLAPAAVSAPPLPTKTPLDPVKTPEKTPLRWRDWVVRLFNDPVNKFEHVVESL
CKHVPGMSQDMAWSVAWQAHREGVAATYQGPREVAELVCEKLVRDGLISDCCES

>gi|159029424|emb|CAO90801.1| unnamed protein product [Microcystis aeruginosa PCC 7806]
MSTEVIEKRSTATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITC
IQEHAEFYCETLKNKGLTSSIEPDE

>gi|86608169|ref|YP_476931.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. JA-2-3B'a(2-13)]
MATETLVKPSVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPAMMPPQATEIMLEAHHNGVAVVIVVPR
EHAEFYCEQLRQHGLTSSIEPER

>gi|166367986|ref|YP_001660259.1| ATP-dependent Clp protease adaptor protein ClpS [Microcystis aeruginosa NIES-843]
MIEKRSTATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTALVITCIQEH
AEFYCETLKNKGLTSSIEPDE

>gi|67924069|ref|ZP_00517517.1| ATP-dependent Clp protease adaptor protein ClpS [Crocosphaera watsonii WH 8501]
MTTDVIEKPSSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVPSITQPQAVDIMMEAHSNGTALVI
TCALEPAEFYSETLKNHGLTSTIEPDE

>gi|218438615|ref|YP_002376944.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7424]
MSTSTQVIEKSTTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGTALVI
TCTLEHAEFYCETLKNHGLTSTIEPDE

>gi|22297755|ref|NP_681002.1| clpS gene product [Thermosynechococcus elongatus BP-1]
MEAWPTMSVQTIEKPATVRKLAPRYRVLLHNDNVNSMEYVVEVLLKTVPSLTQPQAVDIMMEAHLTGVAL
VITCALEHAEFYCEGLKMAGLTSTIEPTE

>gi|220908775|ref|YP_002484086.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7425]
MAVETIEQRSTVRKLAPRYRVLLHNDDVNSMEHVVEVLLKTVPSLTQPQAVDIMMEAHVNGIALVITCAL
EHAEFYCESLKLGGLTSTIEPDE

>gi|86607127|ref|YP_475890.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. JA-3-3Ab]
MATETLVKPSVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPSMLPPQATEIMLEAHNNGVAVVIVVPR
EHAEFYCEQLRQHGLTSSIEPER

>gi|148972604|ref|ZP_01811408.1| ATP-dependent Clp protease adaptor protein ClpS [Leptolyngbya valderiana BDU 20041]
MSVETIEKRSTVRKHAPRYRVLLHNDDFNTMEYVVQTLVKTVPGLTQPQAVSIMMEAHTNGMALVITCAQ
EHAEFYCETLRRHGLSSSIEPDD

>gi|307150896|ref|YP_003886280.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 7822]
MSTSTSTQVIEKSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGMAL
VITCTLEHAEFYCETLKAHGLTSTIEPDE

>gi|218246012|ref|YP_002371383.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. PCC 8801]
MTTEVIEKRSTSSATVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVAGMTQPQAVDIMMEAHTNGTALVI
TCALEHAEFYCETLKNHGLTSSIEPDE

>gi|170078877|ref|YP_001735515.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7002]
MSTGVIEQRSTSTIRKPAPRYRVLLHNDDFNSMEHVVQTLMQTVAGLTQPQAVSIMMEAHTNGIALVITC
VQEHAEFYCETLKMHGLTSTIEPDE

>gi|126657545|ref|ZP_01728701.1| ATP-dependent Clp protease adaptor protein ClpS [Cyanothece sp. CCY0110]
MTTEVIEKRSSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVSGMTQPQAVDIMMEAHTNGTALVI
TCALEPAEFYCETLKNHGLTSTIEPDE

>gi|113474895|ref|YP_720956.1| clpS gene product [Trichodesmium erythraeum IMS101]
MSIETIEKPTTSTVRKTAPHYRVLLHNDDFNSMEYVVQTLMKTVPSLTQPQAVNIMMEAHSNGIALVIIC
ALEPAEFYCENLKNHGLTSTIEPDE

>gi|168014848|ref|XP_001759963.1| predicted protein [Physcomitrella patens subsp. patens]
AAAPGQGGGVMDRPTIDKPTPGRESEFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLLKAIPGMTVDIA
VNVMNEAHINGIAVVIVCPQEDAEDYCMQLRTNGLLSSIEPD

>gi|16331021|ref|NP_441749.1| ATP-dependent Clp protease adaptor protein ClpS [Synechocystis sp. PCC 6803]
MMATEVLNKPSNSTIRKHAPRYRVLLHNDDFNSMEHVVQTLIQTVAGMTQPQAVDIMMEAHFNGMSLVIT
CELEHAEFYCETLRSHGLSSTIEPDE

>gi|168011584|ref|XP_001758483.1| predicted protein [Physcomitrella patens subsp. patens]
QGGGVLDRPTIDKPTPGRESEFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMN
EAHINGLAVVIVCPQEDAEDYCMQLRTNGLLSSIEP

>gi|108803856|ref|YP_643793.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
MVGSLTRDIRCSAATKTAPARKTRRAPSREPRYRVILHNDDWTPMDHVVAALMKVVPRLSLRRAVSIMLE
AHTKGQAVVTRCHRELAELYREGLKAEGLISTIEPDG

>gi|121489819|emb|CAK19331.1| putative adaptor protein ClpS [Physcomitrella patens]
MAGSLRLFVSIPATARHFGINGVEKAQRVHNRVNGRYKINAASGPSQGGGVLDRPTIDKPTPGRESEFDL
KKKKKISPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLAVVIVCPQEDAEDYCMQ
LRTNGLLSSIEPASC

>gi|254423912|ref|ZP_05037630.1| ATP-dependent Clp protease adaptor protein ClpS [Synechococcus sp. PCC 7335]
MSTSISTIEKPSVSTVRKIAPRYRVLLHNDDFNSMEYVVEALIETVPSLTAPQAIDIMMQTHNTGIGLVI
VCEMEHAEFYCEGLKGKGLTSTIEPEE

>gi|57335897|emb|CAH25350.1| hypothetical protein [Guillardia theta]
RICACVRSAWSFPVAFPAHLHHPLLRAVCFFIKWISSILWFMMGRQVLAALALLPLAWCFQAPTSFLPGT
RGITQQTCATLRPAVLGKMQLEAPERIKIPDTFNPAEWGVGGGKGGFGDGLGGFKVPDSFNPAEMEKERQ
GGRTAVMDRPSDKTDPGKKYKVLLFNDDKNTRQYVIDTLMKYIPGMTADKAKEITVAAHNTGMAIVGVWM
YEMAEAYSDVLRSAGLRSDIDPE

>gi|351724025|ref|NP_001237811.1| uncharacterized protein LOC100306117 [Glycine max]
MEAALCSALAPSPNQVFNAANPGDKNVPLKYSKDRSVVMTVAATGILGKGGGLLERPTIETTSPGRESEF
DLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAEDHC
MQLRGNGLLSSIEPADGGGC

>gi|356531226|ref|XP_003534179.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS-like [Glycine max]
MEAALCSALALSPNQVFNAANPGDKNVPLKYSKDRSVVMTVAATGILGKGGGLLERPTIETTSPGRESEF
DLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLAVVIVCAQVDAEDHC
MQLRGNGLLSSIEPADGGGC

>gi|354566131|ref|ZP_08985304.1| ATP-dependent Clp protease adapter protein clpS [Fischerella sp. JSC-11]
MSVETQQKRSTSRKLAPQYRVLLHNDDYNTMEYVVQVLLTTVPSLTQPQAVSIMMEAHSNGLALVITCAQ
EPAEFYCETLKNHGLTSTIEPEE

>gi|351723283|ref|NP_001234970.1| uncharacterized protein LOC100527361 [Glycine max]
MKSAICGRILSPNHVFKPGDTHSICKGPYSNLCVPMAVLATGPGKGGGVLEKPVIEKVTPGRESEFDLKK
SRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAEDHCTQLR
GNGLLSSIEPASGGC

>gi|255576515|ref|XP_002529149.1| ATP-dependent Clp protease adaptor protein clpS, putative [Ricinus communis]
MALSATGAGKGGGLLEKPVIEKTTPGRESEFDLRKSRKTAPPYRVILHNDNYNKREYVVQVLMKVIPGMT
LDNAVNIMQEAHYNGLSVVIICAQADAEDHCMQLRGNGLLSSIEPASGGC

>gi|351721328|ref|NP_001235414.1| uncharacterized protein LOC100500511 [Glycine max]
MKSAICGRILSPNHVFKPGDTHSICKGPYSNLCVPMVVLATGPGIGGGVLEKPVIEKVTPGRESEFDLKK
SRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICDQADAEDHCMQLR
GNGLLSSIEPANGGC

>gi|282897015|ref|ZP_06305017.1| ATP-dependent Clp protease adaptor protein ClpS [Raphidiopsis brookii D9]
MSVETIEKPSTTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVTIMMEAHSNGLALVISCAL
EHAEFYCESLNNHGLTSTIEPDD

>gi|302761288|ref|XP_002964066.1| hypothetical protein SELMODRAFT_142341 [Selaginella moellendorffii]
MACTLTQVAHLWPSTSQVSRFNTIFAEADKCHKCFTRIIASHAVRAALPGGLGGGVLDKPAIETAPTPGR
ESEFDLRKKKKMAPPYRVILHNDNFNRREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGLSVVIVCSQEDA
EEHCTQLRANGLLSSIEPASGGSC

>gi|225423913|ref|XP_002281884.1| PREDICTED: ATP-dependent Clp protease adapter protein ClpS [Vitis vinifera]
MENAICGRLALSPNHVFNSKSGDKHSLLKGPCTNRSFLMAISASGPGKGGLLERPVIEKVTPGRESEFDL
RKSRKIAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLSVVIICAQADAEDHCMQ
LRGNGLLSSIEPASGGC

>gi|284929541|ref|YP_003422063.1| hypothetical protein UCYN_10070 [cyanobacterium UCYN-A]
MVTDVIEKISLNTSTTKKPVPRYKVLLHNDDFNPMDYVVQILMQTISGMTRPQAAEIMMEAHISGTALVI
TCAFEPAEFYRETLKNHGLSSSIEPDE

