>gnl|BL_ORD_ID|414 Streptococcus_thermophilus_CNRZ1066 gi|55822408|ref|YP_140849.1| ABC transporter ATP binding protein [Streptococcus thermophilus CNRZ1066]
MFKIFKRLTAKELSMIVLAVIFVCLNVYLNLKIPDYMSDIITLLSTKGTKASDIFAWNTD
APGMRMLLMSFAGFMASVVVSFLAARTASSFTTRLRDDIFHQVLDFSDAE----------
------------------------------------------------------------
------------------------------------------------------------
------IKKFSIPSLLTRTTNDITQLQMALTMGLQ---VITQGPIMAIWAITKI------
-ADKNGNWLLALLVAVAVIAILMLFLLIMVMPKQRLIQTLTDKLNSVTRESLTGIRVVRA
YNAESYQEDKFEKANTDLTQNNLFIGRSFALLTPVMTAVSSGLTLAIYWIGAH-------
----------------LIEDVKIPTDPTKIAGAMEDKVHLFSDMVVYSS------YAMQV
VMGFMMMMVVFFLLPRAV----VAAGRINEVLDTQSSVSYPEYSSEKPKEVGTVEFED--
----------VSFRYSETSEPVLEHVSFKAKKGDTVALIGSTGSGKSTLVNLIPRFYDAT
QGTIKVDGVDVRYYDHETLHNIVGYIPQKAVLFSGDITSNMTMGTSNNSPLDDAKIWEAL
ELAQGKDFVENKEGQLKAEVAQAGSNFSGGQKQRLAIARALARKPEILIF-----DDSFS
ALDYKTDRKLRQELAEKTQDMTKLIVAQRISTIMDADQILVLDKGKVVGQGTH--EEL--
-----------------------------LANNEVYQEIAY-------------------
-------------SQLSKEELED-------------------------------------
----------------------GK
>gnl|BL_ORD_ID|1263 Streptococcus_thermophilus_CNRZ1066 gi|55823257|ref|YP_141698.1| bifunctional methionine sulfoxide reductase A/B protein [Streptococcus thermophilus CNRZ1066]
MRNIPKSVTLKAWRCKYLVKG---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------VLKMSNPNNHVIYLAGGCFW---GVEEYFSRVPGVLDAVSGYANG
SSETTRYELISQTGHAETV-------------------------QVTYDAGKVTLREILL
HFFRIINPLSKNKQGNDV---------GTQYRTGVYYTDVNDLPIIEKVFQEMSEQYGQP
LAVELLPLQHFIPAEEYHQDYLKKNPNGYCHINVNQAVNPVIDSSSYHKPSQEELKVSLS
PEAYA----------------------VTQENRTERAFTSPLWNHFEPGIYVDVVTGE--
----------PLFSSRDKFYSACGWPSFSRPI----------------------------
------------------------------------------------------------
-------------------------------------------SPEVANY-----KEDHS
---------------------HNMDRIEVRSRVGDSHLGHVFPDGPSDKGGLRYCING--
-----------------------------VATRFVPKADME-------------------
-------------KEGYAYLLDQ-------------------------------------
----------------------VD
