>Acaryochloris_marina_MBIC11017_gnl_BL_ORD_ID_3792
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------mq
tpvtr----peekqaqktvrkpypnfkvivvnddvntfehvaktlmtyiphmtsdkawel
tnqihfegqaivwvgpqeqaelyhmqlqrag------ltmapleaa-----
>Anabaena_variabilis_ATCC_29413_gnl_BL_ORD_ID_3450
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mvtklsidvyam-------------st
aptvt----p--ersnqtvrksypnykvivlnddfntfqhvaeclvkyipgmtgdlawdl
tnqvhyegqaivwvgpqepaelyhqqlrrag------ltmapleaa-----
>Nostoc_sp_PCC_7120_gnl_BL_ORD_ID_714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mvtklsidvyam-------------st
aptvt----p--ersnqtvrktypnykvivlnddfntfqhvaeclvkyipgmtgdlawdl
tnqvhyegqaivwvgpqepaelyhqqlrrag------ltmapleaa-----
>Nostoc_punctiforme_ATCC_29133_gnl_BL_ORD_ID_3650
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mvrnlsadvygm-------------tt
aptit----p--erssqvtrktypnykvivlnddfntfqhvaeclmkyipgmsgdrawdl
tnqvhyegqaivwvgpqepaelyhqqlrrag------ltmapleaa-----
>Nodularia_spumigena_CCY9414_gnl_BL_ORD_ID_1770
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mvtrlsaavyga-------------gt
aptvt----p--gkttevvrktypnykvivlnddfntfqhvseclmkyipgmtgdrawdl
tnqihyegqaivwvgpqemaelyhqqlrrag------ltmapleaa-----
>Arthrospira_platensis_NIES_39_gnl_BL_ORD_ID_1627
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------m-------------va
spttt----p--srssqtvrkpypnykvivlnddfntfqhvanclmkylpgmtsdqawel
tnrvhyegqatvwvgpleqaelyhtqlsreg------ltmapleka-----
>Lyngbya_sp_CCY_8106_gnl_BL_ORD_ID_4005
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------m-------------ts
sptva----p--srssqvtqqpypnykvivlnddfntfehvssclmkyipgmnsdlawkl
tnqvhfegqatvwvgpleqaelyhtqlsreg------ltmapleka-----
>Oscillatoria_sp_PCC_6506_gnl_BL_ORD_ID_1058
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------m-------------ts
sptia----p--drssqvtrkpypnykvivlnddfntfqhvseclvkyipgmtsdrawkl
tnqvhyegqatvwvgpqeqaelyhmqlsrag------ltmapleqa-----
>Cyanothece_PCC_7424_gnl_BL_ORD_ID_4383
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mstnvaavvtam-------------tt
aptia----p--dkttqvvkktypnykvivlnddfntfqhvanclmkyipgmtsdrawel
tnqvhyegqatvwvgpqeqaelyhqqlrreg------ltmapleaa-----
>Microcystis_aeruginosa_NIES_843_gnl_BL_ORD_ID_703
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------m-------------ss
apstt----l--dkstqvvkktypnykvivlnddfntfdhvanclikyipdmttdrawel
tnqvhyqgqaivwtgpqeqaelyhqqlrreg------ltmapleaa-----
>Cyanothece_sp_BH68_ATCC_51142_gnl_BL_ORD_ID_3651
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mskrlstgiqgm-------------at
ststa----p--kgstvidrkpypnykvivlnddfntfnhvanclmkyipgmssdrawel
teqvhfeglaivwtgpqeqaelyhqqlrreg------ltmapleea-----
>Cyanothece_sp_CCY_0110_gnl_BL_ORD_ID_1780
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------m-------------at
ststa----p--kgstvidrkpypnykvivlnddfntfnhvanclmkyipgmssdrawel
teqvhfeglaivwtgpqeqaelyhqqlrreg------ltmapleea-----
>Microcoleus_chthonoplastes_PCC_7420_gnl_BL_ORD_ID_3381
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mtvvisaarsat-------------sa
aptqa----p--eksrqvtrkpypnykvivldddfntfqhvhdclvkyipgmssdyawkl
tnqvhfegqaivwvgpqeqaelyhqqlsrag------ltmapleaa-----
>Cylindrospermopsis_raciborskii_CS_505_gnl_BL_ORD_ID_3110
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------m-ktrpspvyam-------------as
aptvt----p--dqgtqvvrkpypnykvivlnddfntfehvakslmkyipgmtteqawel
tnqvhyegqaivwvgpqeqaelyhqqlrrag------ltmapleaa-----
>Raphidiopsis_brookii_D9_gnl_BL_ORD_ID_516
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------m-ktrpspiyam-------------ap
aptvt----p--dqgtqvirkpypnykiivlnddfntfehvakslmkyipgmtteqawel
tnqvhyegqaivwvgpqeqaelyhqqlrrag------ltmapleaa-----
>Thermosynechococcus_elongatus_BP_1_gnl_BL_ORD_ID_1087
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
mpsvv----p--qerqqvtrkhypnykvivlnddfntfqhvaaclmkyipnmtsdrawel
tnqvhyegqaivwvgpqeqaelyheqllrag------ltmaplepe-----
>Synechocystis_sp_PCC_6803_gnl_BL_ORD_ID_1103
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------mi-------------sn
aatst----p--drltstvrktypnfkvivlnddfntfqhvsdcllkyipgmtgdrawel
tnqvhfdglaivwvgpqeqaelyhqqlrreg------ltmapleka-----
>Synechococcus_sp_PCC_7002_gnl_BL_ORD_ID_2207
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------m-------------ap
apgil----k--esdrqtvrkpypnfkvivlnddfntfehvahclmtyipnmtadqawnl
tnqvhfdgqaivwvgpqepaelyhqqlrreg------ltmapleaa-----
>Trichodesmium_erythraeum_IMS101_gnl_BL_ORD_ID_3325
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------ms------------------------------------
----------lgisiigiie-----------------niavrgga-------------ss
pttla----p--kkdsqvvnkpypnykvivlnddvntfkhvaeclqkyipgmtsdrawel
tyqvhnegqaivwvgpleqaelyhqqlsrag------ltmapleka-----
>ClpS2_Synechococcus_7942_ClpS2
------------------------------------------------------------
------------------------------------------------------------
-------------------------------mlpspfrpqttiasenvktaskaaqpkvn
ssmspqpdesvlsilgvprpcvkk------------------------------------
----------rsrddafvlt-----------------vltcslqa-------------ia
apata----p--gttttrvrqpyphfrvivldddvntfqhvaecllkyipgmtgdrawdl
tnqvhyegaatvwsgpqeqaelyheqlrreg------ltmapleaa-----
>Cyanothece_PCC_7425_gnl_BL_ORD_ID_3769
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------mvrpiqts-----------------slsplava-------------tp
rqspt----p--vqdrqtirqpyphykvivlnddfntfehvakclmkyipnmtsdrawel
tyqvdregqaivwvgpqeqaelyhlqlgqag------ltmaplela-----
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_2237
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------ms
satvt----p--tkpetsvkalkp-wkvivlnddfntfqhvanclvkyiphmhpdrawkl
tqqvhsegraivwvgpleqaelyheqlsreg------ltmapleqa-----
>Prochlorococcus_marinus_MIT_9313_gnl_BL_ORD_ID_672
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------fa
tpgtt----p--llerakqtqrypqarvivlnddvntfqhvvdclrriipgmseerawnl
ahqidgqgsaevwcgpleqaelyhqqlsgeg------ltmaplerc-----
>Synechococcus_sp_WH_8109_gnl_BL_ORD_ID_1922
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------ss
spgss----a--vlerqgttqrypqarvivldddvntfqhvvdclrkiipgmsednawnl
anridghgaaevwcgpleqaelyhqqlqseg------ltmaplerc-----
>Synechococcus_WH_8102_gnl_BL_ORD_ID_1299
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----s-------------ss
spgsa----s--llerqtitqrypqarvivldddvntfqhvvdclrkiipgmseekawsl
anridgqgsaevwcgpleqaelyhqqlaaeg------ltmaplerc-----
>Synechococcus_sp_CC9902_gnl_BL_ORD_ID_1044
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------ss
spsss----t--llerqkttqrypeakvivldddvntfqhvvdclrkiipgmdeekawgl
ahridgqgsaevwrgpleqaelyhlqlqteg------ltmapldrc-----
>Synechococcus_sp_RS9916_gnl_BL_ORD_ID_1876
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------gs
sgaqs----t--llersrttqgypearvivlnddvntfqhvvdclckiipgmgterawdl
ahqvdgqgsaevwcgpleqaelyhqqltgeg------ltmapierc-----
>Synechococcus_WH_7803_gnl_BL_ORD_ID_1209
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------ss
spgvs----t--vlerdrqaqrypqarvivlnddfntfehvveslcriipgmntekawsl
ahridgegaaevwcgpleqaelyhqqlgaeg------ltmapierc-----
>Synechococcus_sp_RS9917_gnl_BL_ORD_ID_1372
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------vt
ptgta----t--vldratsrsdypqarvivldddvntfqhvvdclcriipgmgserawdl
ahridsegaadvwsgpleqaelyhqqlsaeg------ltmaplerc-----
>Prochlorococcus_sp_CC9311_gnl_BL_ORD_ID_1389
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m-----t-------------ma
tpgta----s--vlqperttlrypnarvivlnddvntfehvveclckiipgmnsdkawtl
ahqidgegaaevwagplepaelyhqqlsseg------ltmaplern-----
>Synechococcus_sp_CB0205_gnl_BL_ORD_ID_2119
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------mqpirsi-------------ss
spggq----a--vmerqrvrapyptgrvivldddhntfqhvvevlvkhipamvsdrawel
ahqidsqgsavvwsgpleqaelyhqllageg------ltmapverg-----
>Synechococcus_sp_JA_2_3B_a2_13_gnl_BL_ORD_ID_2497
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------mttea-------------pt
rpaqq----f--spsrtqvrqpyphfkvivldddfntfqhvtecllkyipgmtlplarql
tvqvdaegqavvwvgpqeqaelyhqqllreg------ltmaplepa-----
>Cyanobacterium_sp_UCYN_A_gnl_BL_ORD_ID_272
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------mf-----------------krlsitip-------------et
sistn----i--khsavidykpypnckiivlnddfntfdhvancliryipamtkshawel
tqkihfngfatvwmgpleqaelyhqqlrreg------ltmaplegi-----
>Prochlorococcus_marinus_MIT_9312_gnl_BL_ORD_ID_939
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
ynspl----t--vldnkkskvkypearvivlddsfntfqhvanclliiipgmsenrawdl
tikvdntgsaevwrgnleqaelyheqlvskg------ltmapidkt-----
>Prochlorococcus_marinus_MIT_9211_gnl_BL_ORD_ID_1514
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------mretkrr
nqcsrrahqkdasrngrplllmmd------------------------------------
----------kkimtrhtkd-----------------fvattamk-------------fs
anstt----t--vldpkttkkkypeariivlddnfntfehvanclvtiipgmsekrswvl
avevdreglaevwrgpleqaelyhqqliskg------ltmapiekt-----
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_2530
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------mlssaeapspgtvqwapngqkaqdrqhrvasvhvtglaas------gylavasy
pasrqpgdvqkrlrwgaivvsfgytgtqddyphasmermvlapaa-------------vs
applptktpldpvktpektplrwrdwvvrlfndpvnkfehvveslckhvpgmsqdmawsv
awqahregvaatyqgprevaelvceklvrdg------lisdcces------
>Acaryochloris_marina_MBIC11017_gnl_BL_ORD_ID_5473
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetle-----------------k----------------------
---------------rstsrklapkyrvllhnddfnsmehvvqvliqtvpnltqpqavsv
mmeahtngialvitcafehaefycetlkmhg------lt-stiepde----
>Anabaena_variabilis_ATCC_29413_gnl_BL_ORD_ID_1891
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetie-----------------k----------------------
---------------rstsrklapryrvllhnddynsmeyvvqvlittvpsltqpqavsi
mmeahtnglalvitcaqehaefycetlkdhg------ls-stiepde----
>Nostoc_sp_PCC_7120_gnl_BL_ORD_ID_4631
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetie-----------------k----------------------
---------------rstsrklapryrvllhnddhnsmeyvvqvlittvpsltqpqavsi
mmeahtnglalvitcaqehaefycetlkdhg------ls-stiepde----
>Nodularia_spumigena_CCY9414_gnl_BL_ORD_ID_2031
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------mehvvqslittvpsltqpqavsi
mmeahtngmalvitcaqehaefycetlkshg------ls-stiepde----
>Nostoc_punctiforme_ATCC_29133_gnl_BL_ORD_ID_3476
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetiq-----------------k----------------------
---------------psttrklapryrvllhnddynsmehvvqsliatvpsltqpqavsi
mmeahtnglalvitcalehaefycetlishg------ls-stiepde----
>Arthrospira_platensis_NIES_39_gnl_BL_ORD_ID_6367
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------malvcfgi-dkfpyh------------------ctf
vnggdgs------vstqtve-----------------k----------------------
---------------tstnrklapryrvllhnddhnpmeyvvqvlmstvpgltqpqavsi
mmeahtnglalvitcalehaefycetlknhg------lt-stiepde----
>Cylindrospermopsis_raciborskii_CS_505_gnl_BL_ORD_ID_496
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetie-----------------k----------------------
---------------psttrklapryrvllhnddynsmeyvvqvllstipsltqpqavsi
mmeahshglalviscalehaefyceslnnyg------lt-stiepdd----
>Raphidiopsis_brookii_D9_gnl_BL_ORD_ID_1510
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetie-----------------k----------------------
---------------psttrklapryrvllhnddynsmeyvvqvllstipsltqpqavti
mmeahsnglalviscalehaefyceslnnhg------lt-stiepdd----
>Lyngbya_sp_CCY_8106_gnl_BL_ORD_ID_3908
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------meyvvqvllqtvpsltqpqavsi
mmeahtnglalvitcaqehaefycetlknng------lt-stiepde----
>Microcoleus_chthonoplastes_PCC_7420_gnl_BL_ORD_ID_4785
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------meyvvqaliqtvpsltqpqavni
mmeahnsgialvitcalehaefycetlknhg------lt-stiepde----
>Leptolyngbya_valderiana_BDU_20041_gnl_BL_ORD_ID_6
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetie-----------------k----------------------
---------------rstvrkhapryrvllhnddfntmeyvvqtlvktvpgltqpqavsi
mmeahtngmalvitcaqehaefycetlrrhg------ls-ssiepdd----
>Cyanothece_PCC_7425_gnl_BL_ORD_ID_3320
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mavetie-----------------q----------------------
---------------rstvrklapryrvllhnddvnsmehvvevllktvpsltqpqavdi
mmeahvngialvitcalehaefyceslklgg------lt-stiepde----
>Oscillatoria_sp_PCC_6506_gnl_BL_ORD_ID_4778
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msvetie-----------------k----------------------
---------------rstvrkiapryrvllhnddfnsmeyvvqtlmhtvpsltqpqavni
mmeahtnglavviicaqehaefysetlnnhg------li-stiepde----
>Thermosynechococcus_elongatus_BP_1_gnl_BL_ORD_ID_210
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-meawpt------msvqtie-----------------k----------------------
---------------patvrklapryrvllhndnvnsmeyvvevllktvpsltqpqavdi
mmeahltgvalvitcalehaefyceglkmag------lt-stiepte----
>Trichodesmium_erythraeum_IMS101_gnl_BL_ORD_ID_952
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------msietie-----------------kp--t------------------
---------------tstvrktaphyrvllhnddfnsmeyvvqtlmktvpsltqpqavni
mmeahsngialviicalepaefycenlknhg------lt-stiepde----
>Cyanothece_PCC_7424_gnl_BL_ORD_ID_1601
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ms------tstqvie-----------------ks--t------------------
---------------tstvrkpapryrvllhnddfnsmeyvvqtlmktvagmtqpqavni
mmeahtngtalvitctlehaefycetlknhg------lt-stiepde----
>Cyanothece_sp_BH68_ATCC_51142_gnl_BL_ORD_ID_2328
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mttevie-----------------krsss------------------
---------------tstvrkpapryrvllhnddfnsmeyvvqtlmqtvsgmtqpqavdi
mmeahtngtalvitcalepaefycetlknhg------lt-stiepde----
>Cyanothece_sp_CCY_0110_gnl_BL_ORD_ID_2487
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mttevie-----------------krsss------------------
---------------tstvrkpapryrvllhnddfnsmeyvvqtlmqtvsgmtqpqavdi
mmeahtngtalvitcalepaefycetlknhg------lt-stiepde----
>Microcystis_aeruginosa_NIES_843_gnl_BL_ORD_ID_5244
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------mie-----------------kr--s------------------
---------------tatirkpapryrvllhnddfnsmeyvvqslmqtiagmtqpqavdi
mmeahtngtalvitciqehaefycetlknkg------lt-ssiepde----
>Synechococcus_sp_PCC_7002_gnl_BL_ORD_ID_2405
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mstgvie-----------------qr--s------------------
---------------tstirkpapryrvllhnddfnsmehvvqtlmqtvagltqpqavsi
mmeahtngialvitcvqehaefycetlkmhg------lt-stiepde----
>Synechocystis_sp_PCC_6803_gnl_BL_ORD_ID_1854
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------m------matevln-----------------kp--s------------------
---------------nstirkhapryrvllhnddfnsmehvvqtliqtvagmtqpqavdi
mmeahfngmslvitcelehaefycetlrshg------ls-stiepde----
>ClpS1_Synechococcus_7942_ClpS1
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mavetiq-----------------kp--e------------------
---------------tttkrkiapryrvllhnddfnpmeyvvmvlmqtvpsltqpqavdi
mmeahtngtglvitcdiepaefyceqlkshg------le-qq----h----
>Cyanobacterium_sp_UCYN_A_gnl_BL_ORD_ID_939
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mvtdvie-----------------kisln------------------
---------------tsttkkpvprykvllhnddfnpmdyvvqilmqtisgmtrpqaaei
mmeahisgtalvitcafepaefyretlknhg------ls-ssiepde----
>Synechococcus_sp_JA_2_3B_a2_13_gnl_BL_ORD_ID_664
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------matetlv-----------------k----------------------
---------------psvtpkhmpmyrvllhnddvntmeyvvqvlvkvipammppqatei
mleahhngvavvivvprehaefyceqlrqhg------lt-ssieper----
>Prochlorococcus_marinus_MIT_9313_gnl_BL_ORD_ID_1789
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------mklglptictmgerpt------yigavpiv
lamavnapsptp-ggaavle-----------------kq---------------------
---------------terirkqsphykvllhndpvnsmeyvvvtlqqvvpqlseqdamav
mleahntgvglvivcdlepaefycetlkakg------lt-stleqes----
>Synechococcus_sp_RS9916_gnl_BL_ORD_ID_2779
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--mavnttspgp-ggaavld-----------------kq---------------------
---------------tervrkrsprykvllhndpvnsmeyvvstlqqvvpqlseqdamav
mleahnsgvglvivcdlepaefycetlkakg------lt-stlepes----
>Prochlorococcus_sp_CC9311_gnl_BL_ORD_ID_363
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---mvdtpsrsp-ggaavld-----------------kq---------------------
---------------tervrktsprykvllhndpvnsmeyvvvtlqqvvpqlseqdamav
mlethntgiglvivcdiepaefycetlknkg------lt-stiepes----
>Synechococcus_WH_7803_gnl_BL_ORD_ID_368
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
mvmavetpsrtp-ggaavle-----------------ka---------------------
---------------pervrkqsprykvllhndpvnsmeyvvstlrqvvpqlseqdamav
mleahntgvglvivcdlepaefycetlkgkg------lt-stiepen----
>Synechococcus_WH_8102_gnl_BL_ORD_ID_2141
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
mamavdtptrsp-ggaavme-----------------ka---------------------
---------------pervrkqsprykvllhndpvntmeyvvttlrqvvpqlseqdamav
mieahntgvglvivcdlepaefycetlkakg------lt-stiepet----
>Synechococcus_sp_WH_8109_gnl_BL_ORD_ID_198
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------msrsislfp------lnlkvfgs
mvmavdspsqkp-ggaavld-----------------ka---------------------
---------------pervrkrsprykvllhndpvnsmeyvvatlqqvvpqlseqdcmav
mleahntgvglvivcdiepaefycemlkskg------lt-ssiepee----
>Synechococcus_sp_CC9902_gnl_BL_ORD_ID_2014
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--maeetptrsp-ggaavld-----------------ka---------------------
---------------pervrkrsprykvllhndpvnsmeyvmttlrqvvpqlseqdamav
mleahntgvglvivcdiepaefycetlkskg------lt-ssieped----
>Synechococcus_sp_RS9917_gnl_BL_ORD_ID_1996
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------mhrsd
lamvgstsstsp-ggaavld-----------------kq---------------------
---------------tervrkhsprykvllhndpvntmeyvvttlrqvvpqlseqdamav
mleahntgvglvivcdlepaefycetlkakg------lt-stlepet----
>Synechococcus_sp_CB0205_gnl_BL_ORD_ID_783
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
mirstqapgres-ggaavme-----------------ka---------------------
---------------pervrkpsprykvllhndpvntmeyvvstlrqvvpslseqdaiav
mmeahntgvglvivcdiepaefysetlkakg------ls-stieped----
>Prochlorococcus_marinus_MIT_9312_gnl_BL_ORD_ID_1590
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-mlsikleqsvs-nnsavie-----------------kk---------------------
---------------paelknkspkyrvllhndpvnsmeyvtislrevvpqlseqdaiai
mleahntgvglvivcdlepaefyseslkskg------is-ssieked----
>Prochlorococcus_marinus_MIT_9211_gnl_BL_ORD_ID_1621
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------ms------lvdwnylp
tgimveatgssp-ggatvie-----------------kq---------------------
---------------selvrkrsprykvllhndpvnsmdyvvttlrqvvpqlseqdalav
mleahntgvglvivcdlepaefyseslkakg------ls-stieket----
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_745
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------mstetle-----------------r----------------------
---------------ksvqrkpmplykvllhnddhtpmnyvievlmktipkmqpskarki
mleahnggvavvivcalehaefyseslnrhn------lt-styepdc----
>Prunus_persica_gnl_BL_ORD_ID_10981
------------------------------------------------------------
--------------------------m-aa------------------------------
----------------------------------------------------------ic
grvalspnqgf----nlaksgdkhyfhk-qcs-srsilm------------------ta-
ss-trlg------kggglle-----------------kptie-kt---------------
tpsrd----s--efdlrksrkmsppyrvmlhndnynkreyvvqvlmkvipgmtvdiavni
mqeahhnglavvivcaqvdaedhcmqlrgng------ll-ssvepasdg-c
>Capsella_rubella_gnl_BL_ORD_ID_21193
------------------------------------------------------------
--------------------------mdtt------------------------------
----------------------------------------------------------ic
grlalapstlf----ss-ksgdkhslskgpcl-nrgvlm------------------tl-
stsaalg------kgggvld-----------------kpiie-kt---------------
tpgre----s--efdlrkskkmappyrvilhndnfnkreyvvqvlmkvipgmtvdnavni
mqeahingmavvivcaqadaeqhcmqlrgng------ll-ssvepdggg-c
>Brassica_rapa_gnl_BL_ORD_ID_16356
------------------------------------------------------------
--------------------------meta------------------------------
----------------------------------------------------------ic
grlalapttlf----ns-isgdkhsvskgpcvnnrgvli------------------tm-
st-svvg------kgggvld-----------------kpiie-kt---------------
tpgre----s--efdlrkskkmappyrvilhndnfnkreyvvqvlmkvipgmtvdnavni
mqeahingmavvivcaqadaeqhcmqlrgng------ll-ssvepdggg-c
>Prunus_persica_gnl_BL_ORD_ID_19291
------------------------------------------------------------
--------------------------meta------------------------------
----------------------------------------------------------ic
grlplspnhvf----np-kpgdrhplckgpct-nlgipm------------------av-
sa-tgpg------kggglle-----------------rpvie-kt---------------
tpard----s--efdlrksrktappyrvilhndnynkreyvvqvlmkvipgmsldnavni
mqeahhnglsiviicaqadaeehcmqlrhng------ll-ssiepasgggc
>Glycine_max_gnl_BL_ORD_ID_3555
------------------------------------------------------------
--------------------------mksa------------------------------
----------------------------------------------------------ic
gri-lspnhvf-------kpgdthsickgpys-nlcvpm------------------av-
la-tgpg------kgggvle-----------------kpvie-kv---------------
tpgre----s--efdlkksrksappyrvilhndnfnkreyvvqvlmkvipgmtldnavni
mqeahynglsvviicdqadaedhctqlrgng------ll-ssiepasgg-c
>Ricinus_communis_gnl_BL_ORD_ID_3780
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m------------------al-
sa-tgag------kggglle-----------------kpvie-kt---------------
tpgre----s--efdlrksrktappyrvilhndnynkreyvvqvlmkvipgmtldnavni
mqeahynglsvviicaqadaedhcmqlrgng------ll-ssiepasgg-c
>Carica_papaya_gnl_BL_ORD_ID_311
------------------------------------------------------------
--------------------------meta------------------------------
----------------------------------------------------------ic
grlslspstvf----np-kpgekhspckgpci-trgilm------------------al-
sa-tggg------kgggvle-----------------rpvie-kt---------------
tpgre----s--efdlrksrktappyrvilhndnynkreyvvqvlmkvipgmtldnavni
mqeahynglsvviicaqadaedhcmqlrgng------ll-ssiepasgg-c
>Populus_trichocarpa_gnl_BL_ORD_ID_43343
------------------------------------------------------------
--------------------------meta------------------------------
----------------------------------------------------------ic
grialspnhvf----np-kpgdknsvcrgpca-nrgilm------------------ai-
st-tcsg------kggglle-----------------kpvie-rt---------------
tpgre----s--efdlrkskkmappyrvmlhndnynkreyvvqvlmkvipgmtldnavni
mqeahynglsvviicaqadaeehcmqlrgng------ll-ssiepasgg-c
>Medicago_truncatula_gnl_BL_ORD_ID_34263
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------m------------------av-
lt-kgsg------kgggile-----------------kpvie-ka---------------
tpgre----s--efdlkksrktappyrvilhndnfnkreyvvqvlmkvipgmtldnavni
mqeahhngmsvviicaqadaedhcmqlrgng------ll-ssiepagdg-c
>Vitis_vinifera_gnl_BL_ORD_ID_4262
------------------------------------------------------------
--------------------------meta------------------------------
----------------------------------------------------------ic
grvplspnhff----ts-ksgdkhslsk-qwt-hrtmlm------------------tv-
sa-aapg------kgsgvle-----------------rptie-ri---------------
mpgre----s--efdlrksrkmsppyrvllhndnynkreyvvqvlmkvipgmtldnavni
mqeahhngmsvviicaqvdaedhcmqlrgng------ll-ssiepasgg-c
>Aquilegia_coerulea_gnl_BL_ORD_ID_33124
------------------------------------------------------------
--------------------------meta------------------------------
----------------------------------------------------------ic
grvslspnhvf----nnhkpgdkhaiyrgpct-nrgilm------------------ti-
sa-agpg------kggglld-----------------rptie-kt---------------
tpgre----s--gfdvrksrkmsppyrvmlhndnynkreyvvqvlmkvipgmtvdnavni
mqeahindlavviicaqadaeehctqlrgng------ll-ssiepasgg-c
>Eucalyptus_grandis_gnl_BL_ORD_ID_42553
rrvgiatiqtnsrfpkhpffrpldttkivpsdfsfppkkfspinlllssle---------
----niaeekgrererergktspgiameta------------------------------
----------------------------------------------------------ic
grvalsphhvf----s--ksgdkhyfnk-qcs-yrsslt------------------tm-
st-talg------kggglle-----------------rptie--t---------------
tpgre----s--efdvrksrktappyrvmlhndnfnkreyvvqvlmkvipgmtldnavni
mqeahynglsvviictqadaeehcmqlrgng------ll-ssiepasgg-c
>Selaginella_moellendorffii_gnl_BL_ORD_ID_14527
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------g------lgggvld-----------------kpaie-ta--------------p
tpgre----s--efdlrkkkkmappyrvilhndnfnrreyvvqvlmkvipgmtldnavni
mqeahhnglsvvivcsqedaeehctqlrang------ll-ssiepasgg--
>Glycine_max_gnl_BL_ORD_ID_17909
------------------------------------------------------------
--------------------------meaa------------------------------
----------------------------------------------------------lc
salalspnqvf----naanpgdknvplk-ysk-drsvvm------------------tv-
aatgilg------kggglle-----------------rptie-tt---------------
spgre----s--efdlrksrktsppyrvllhndnfnkreyvvqvlmkvipgmtidnavni
mqeahynglavvivcaqvdaedhcmqlrgng------ll-ssiepadgggc
>Vitis_vinifera_gnl_BL_ORD_ID_7060
------------------------------------------------------------
--------------------------mena------------------------------
----------------------------------------------------------ic
grlalspnhvf----ns-ksgdkhsllkgpct-nrsflm------------------ai-
sa-sgpg------k-gglle-----------------rpvie-kv---------------
tpgre----s--efdlrksrkiappyrvilhndnynkreyvvqvlmk-------------
-----------------adaedhcmqlrgng------ll-ssiepasgg-c
>Panucum_virgatum_gnl_BL_ORD_ID_14345
------------------------------------------------------------
--------------------------msgs------------------------------
----------------------------------------------------------sp
grcslaaagl-----grlaagdrsciykgrfq-slaipm------------------al-
sa-aapg------k-ggvld-----------------rp-ve-kt---------------
tpgrq----s--efdvkkkrkmtppyrvilhndnynrreyvvqvlmkvipgmtvdnavni
mqeahvnglsvvivcsqseaeehctslrgng------lr-ssiepasgg-c
>Setaria_italica_gnl_BL_ORD_ID_19258
------------------------------------------------------------
--------------------------meaa------------------------------
----------------------------------------------------------vp
srvalsaasrfpn--rhavagdrstiykgrcq-slaipm------------------al-
sa-aapg------k-ggvld-----------------rp-ve-kt---------------
tpgrq----s--efdvkkkrkmtppyrvilhndnynrreyvvkvlmkvipgmtvdnavni
mqeahvnglsvvivcsqseaeehctslrgng------lr-ssiepasgg-c
>Sorghum_bicolor_gnl_BL_ORD_ID_22153
------------------------------------------------------------
--------------------------meaa------------------------------
----------------------------------------------------------vp
srvalsaasrlpn--rhavagdrsfvykgrcq-slaipm------------------al-
sa-aapg------k-ggvld-----------------rp-ve-kt---------------
tpgrq----s--efdvkksrkmsppyrvilhndnynrreyvvqvlmkvipgmtvdnavni
mqeahvnglsvvivcsqseaeehctslrgng------lr-ssiepasgg-c
>Zea_mays_gnl_BL_ORD_ID_43912
------------------------------------------------------------
--------------------------meaa------------------------------
----------------------------------------------------------vp
srvalsaasrlpn--phavtgdrsfiykgrcq-slaipm------------------al-
sa-aapg------kgggvld-----------------rp-ve-kt---------------
tpgrq----s--efdvkksrkmsppyrvilhndnynrreyvvkvlmkvipgmtvdnavni
mqeahvnglsvvivcsqseaeehctslrgng------lr-ssiepasgg-c
>Oryza_sativa_gnl_BL_ORD_ID_6727
------------------------------------------------------------
--------------------------meaa------------------------------
----------------------------------------------------------vp
srvalsasrls-nhhhhavggeryaiyrgrcp-npaipm------------------ala
aa-aapg------kgggvld-----------------rp-ie-kv---------------
tpgrq----s--efdvrksrkmtppyrvllhndnynrreyvvqvlmkvipgmtvdnavni
mqeahvnglsvviicsqseaeehctslrgng------lr-ssiepasgg-c
>Brachypodium_distachyon_gnl_BL_ORD_ID_24208
------------------------------------------------------------
--------------------------meaa------------------------------
----------------------------------------------------------vp
srialsarimn----hhvvaggrssiyrgryp-niaipi------------------vv-
---taag------kgggvld-----------------rp-ae-ki---------------
spgrq----s--efdvkksrkmsppyrvvlhndnenrreyvvqvlmkvipgmtvdnavni
mqeahvnglavvivcsqseaeehctslrgng------lr-ssiepasgg-c
>Physcomitrella_patens_gnl_BL_ORD_ID_33457
mllgalektlslpag---------------------------------------------
--------------------------maas------------------------------
----------------------------------------------------------lr
lfitvppvtsh----tgikvvekvqrvcdkvn-gr---y------------------air
da-aapg------qgggvmd-----------------rptid-kp---------------
tpgre----s--efdlkkkkkmsppyrvmlhndnfnkreyvvqvllkaipgmtvdiavnv
mneahingiavvivcpqedaedycmqlrtng------ll-ssiepdt---c
>Physcomitrella_patens_gnl_BL_ORD_ID_6354
------------------------------------------------------------
--------------------------mags------------------------------
----------------------------------------------------------lr
lfvsipatarh----fgingvekaqrvhnrvn-gr---y------------------kin
aa-sgps------qgggvld-----------------rptid-kp---------------
tpgre----s--efdlkkkkkmsppyrvmlhndnfnkreyvvqvlmkaipgmtvdiavnv
mneahinglavvivcpqedaedycmqlrtng------ll-ssiepas---c
>Volvox_carteri_gnl_BL_ORD_ID_608
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------maasvlrpppvsva
---sraptaal----avlpgsaclgwrranfgtstllsq------------------ttr
tcvqmra------gvpglld-----------------sptit------------------
---se----p--qqgtdraykrppiykvflhndnynkreyvvkvllkvveeitvddavtv
mqeahetgvalvvacpqenaeryceglrlng------lt-stiepag---r
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_9005
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------maasclrpaptasa
qmmtrspvaglprpcsalqrsgct--lqgafg--tfapq------------------ttr
tfvvtwa------k-ggvmd-----------------apttt------------------
---qq----p--asgversqkrppiykvllhndnynkreyvvkvllkvveqitvddavtc
mqeahetgvalvvacpqdnaeryceglrlng------lt-stiepgg---c
>Cyanophora_paradoxa_gnl_BL_ORD_ID_27119
------------------------------------------------------------
------------------------------------------------------------
-------------------------mafcsavplragrvvgsvlqatpsacfqpaepapv
ssvssrrstffageidvgvhvdarstadsspatrrfvaa------------------tvv
pp-----------tsavvlkpapkiaktglqtdtasakpevetgg-------------dg
akske----------reneeefmgkwkvllhndeantmeyvikairtvvpnishqeavni
mleahttgv-vvivcekehaeyyceglkgyq------lw-ssieped---v
>Cyanidioschyzon_merolae_gnl_BL_ORD_ID_2238
------------------------------------------------------------
------------------------------------------------------------
----------------------------mvscvffvstfhpyslnwqprnapllrretlt
rrptpvvvqrrangaalpirtewsgwtrpesgvrrmptnmprgrsr------kpsfsptg
-------------ggattle-----------------reavrekt---------------
--------------tatkgvdpgkkyklllfndekntrervvevllkcipglskldaqsi
mqkahttgmalvgvwvfelaeaycdllrseg------lv-sdiepae----
>Cyanophora_paradoxa_gnl_BL_ORD_ID_23599
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------maafvapanpvrsqaigrcaiaspasvvfelq------------------rvf
savsipggsgglkggaavle-----------------rpsvi----------------gd
vdvta----w--atfmarrkaqapkyrvllfndpfnkrehvv------idglttadavei
mskahnegfavaavvvqevaelyveglrscg------lt-atcepde----
>Prunus_persica_gnl_BL_ORD_ID_16262
------------------------------------------------------------
-----------------------------------------------------mhqmrtl
nsawfprkqakqkemetetekgnpkktnfvisyflpfflslcvlvfpstqattrlaemnm
al-tggatttssfsltrivgfpp----ppspsrscsrilgvkegqerwr---ggng----
-mavkarfgssk-ggagvle-----------------rpkfdqsq-------------fd
patqleqggdigrlkekrgigsgdsyrvllvddvrhteklvakvvpqvvpsvtpddargl
flksrengvavvivtvkehaefysqmmirgg------lr-stiepdsnsl-
>Carica_papaya_gnl_BL_ORD_ID_24571
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
av-tgkpttsvslthlppllfsp----iprpasvvsvrgrsgtskf-ar-----------
---vnanfvpsk-ggagile-----------------rptfdqsq-------------fd
pstqvleggdvgrlknkkgvgsgdsyrvllmddirhtenlvakilpqvipsvtpndarrl
fnesrengvavvivtvkehaefysqmmirgg------lr-stiepdtnvl-
>Populus_trichocarpa_gnl_BL_ORD_ID_33308
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
alftaasttrfsstkqqsvhfns----mdgpipthstranfpqkra-ia---mstn----
-lavkasf--tk-ggtgvle-----------------rptfdqsq-------------fd
pssqaleggdigrlrdkrgvgsgdsyrvlliddarhserlvakvlpqavpsvtpddarkl
fhesrengvavvivtvkehaefysqmmvrgg------lr-siiepesntv-
>Populus_trichocarpa_gnl_BL_ORD_ID_42340
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
avltaasttwfssttqqpvqfnn----vdgsiftrnfkanfpqkra-it---mstg----
-ltvkasf--tk-ggpgvle-----------------rptfdqsq-------------fd
pssqvleggdigrlrdkrgvgsgdsyrvlliddsrhseslvakvlpravpsvtpedarkl
fhesrengvavvivtvkehaefysqmmirgg------lr-sviepdssnv-
>Oryza_sativa_gnl_BL_ORD_ID_22109
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
ai-ssraaacgalifptta-----------saapvsrsvsvdqrvs-hr---rrka----
-vavaavphas--sggalle-----------------rpafdqsq-------------ld
tlpvtqeggdtgrmrdrrgsgsgdsykvlliddarhteklvekalpqvvpsvtaeaarql
fhasrqkgaalvivavkehaefyaqmmvrqg------lr-saiepesdlas
>Setaria_italica_gnl_BL_ORD_ID_2316
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
ai-sgraaactalvfpsta--------ttttttplpstvsvnlrar-hr---kkat----
-agvvaaphasg-gggavle-----------------rpafdqsq-------------ld
tlpvtqeggdpgrlrdgrrsgsgdsykvllvddvrhtekhvekalpqvvpsitaeaarql
fhesrlkgvalvivavkehaefyaqmmvrqg------lr-saiepesdlas
>Physcomitrella_patens_gnl_BL_ORD_ID_17725
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
aa-amgsaaqvmllglqpvga------vsqaaapvcvrvavgqqrd-trgtvggsg----
-gvfqarlgggg-ggagvle-----------------rpkldqsg-------------sd
ttprteeggesgraaqrnrtgggeryrvllldherhtetyvakaltkavpnitaeqarkc
ffesrligksvvmvavkehaemhafsmaryg------lr-stiepdgsvm-
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_17107
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------mlatrckcnlpsrsf------vaparsvr
tralhvegrfgggrggnvid-----------------rpdvdvskrlggfdlsdwnipsw
daktdngnngsntdkdkksppgggnyrvllldspqhtekgvvaaitrvvpgtnpdharnc
fatskqlgmaiittalkehaelyreqlftyr------vr-talepdnstv-
>Volvox_carteri_gnl_BL_ORD_ID_2065
------------------------------------------------------------
---------------------------------------------------mekplspas
llpagsgacpetfnvvlsdwlrpiavvgfaagweswasagsagammilfccgwgiqpgyt
fgwgsvslrkqtlilfvlwrlhytklqlemamlsqrtfknlrrgsr------akvirpcg
rfalqiqarfgg-grgnvld-----------------rpdvdlskrlggfdlsdfnlggw
kpstesgrsgsgldkdkqsppgggnyrvllmdspqhsekvvvrgictvvpnadeaharnc
yhtskqlgmaiittalkehaefyrqqlytyg------cr-taiepdstva-
>Rhodopseudomonas_palustris_CGA009_gnl_BL_ORD_ID_1197
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------milvnddytprefvvsvlkgef-rmtedqatkv
mltahqrgvcvvgvftkdvaetkatratdagrakgypll-fttepee----
>Rhodopseudomonas_palustris_CGA009_gnl_BL_ORD_ID_3127
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------mlqpslshsaagqagdrinrplamagdggrsgps
tpstsv------itktkprtkrpnlyrvlilnddytpmefvvhvlekff-qmdveaatkv
mlhvhhhgigecgvftyeiaetkvtqvmdfarkhqhplq-cvmekk-----
>Escherichia_coli_UTI89_gnl_BL_ORD_ID_1000
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------mg
ktndwldfdqlaeekvrdalkppsmykvilvnddytpmefvidvlqkff-sydveratql
mlavhyqgkaicgvftaevaetkvamvnkyarenehpll-ctleka-----
>Streptomyces_avermitilis_MA_4680_gnl_BL_ORD_ID_5165
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------mgrvt
apapleiektesaeevfavpepdvpwvtivhndpvnlmsyvtyvfqtyf-gyskdkatkl
mldvhhkgravvssgtreemerdvqamhgyg------lw-atlqqdrk---
>Chlorobium_tepidum_TLS_gnl_BL_ORD_ID_2204
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------m
irltasnnpdtrteeliadvdtldawrvvlfndddhtfdevifqiikav-rctrsiaekh
twevhtrgraivyagemsncirvsaileeia------lk-teiqtg-----
