>Acaryochloris_marina_MBIC11017_gnl_BL_ORD_ID_3792
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MQTPVTRP
EEKQAQKTVRKPYPNFKVIVVNDDVNTFEHVAKTLMTYIPHMTSDKAWELTNQIHFEGQA
IVWVGPQEQAELYHMQLQRAG------LTMAPLEAA-----
>Anabaena_variabilis_ATCC_29413_gnl_BL_ORD_ID_3450
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MVTKLSIDVYAMSTAPTV
TPERSNQTVRKSYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTNQVHYEGQA
IVWVGPQEPAELYHQQLRRAG------LTMAPLEAA-----
>Nostoc_sp_PCC_7120_gnl_BL_ORD_ID_714
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MVTKLSIDVYAMSTAPTV
TPERSNQTVRKTYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWDLTNQVHYEGQA
IVWVGPQEPAELYHQQLRRAG------LTMAPLEAA-----
>Nostoc_punctiforme_ATCC_29133_gnl_BL_ORD_ID_3650
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MVRNLSADVYGMTTAPTI
TPERSSQVTRKTYPNYKVIVLNDDFNTFQHVAECLMKYIPGMSGDRAWDLTNQVHYEGQA
IVWVGPQEPAELYHQQLRRAG------LTMAPLEAA-----
>Nodularia_spumigena_CCY9414_gnl_BL_ORD_ID_1770
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MVTRLSAAVYGAGTAPTV
TPGKTTEVVRKTYPNYKVIVLNDDFNTFQHVSECLMKYIPGMTGDRAWDLTNQIHYEGQA
IVWVGPQEMAELYHQQLRRAG------LTMAPLEAA-----
>Arthrospira_platensis_NIES_39_gnl_BL_ORD_ID_1627
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MVASPTT
TPSRSSQTVRKPYPNYKVIVLNDDFNTFQHVANCLMKYLPGMTSDQAWELTNRVHYEGQA
TVWVGPLEQAELYHTQLSREG------LTMAPLEKA-----
>Lyngbya_sp_CCY_8106_gnl_BL_ORD_ID_4005
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MTSSPTV
APSRSSQVTQQPYPNYKVIVLNDDFNTFEHVSSCLMKYIPGMNSDLAWKLTNQVHFEGQA
TVWVGPLEQAELYHTQLSREG------LTMAPLEKA-----
>Oscillatoria_sp_PCC_6506_gnl_BL_ORD_ID_1058
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MTSSPTI
APDRSSQVTRKPYPNYKVIVLNDDFNTFQHVSECLVKYIPGMTSDRAWKLTNQVHYEGQA
TVWVGPQEQAELYHMQLSRAG------LTMAPLEQA-----
>Cyanothece_PCC_7424_gnl_BL_ORD_ID_4383
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MSTNVAAVVTAMTTAPTI
APDKTTQVVKKTYPNYKVIVLNDDFNTFQHVANCLMKYIPGMTSDRAWELTNQVHYEGQA
TVWVGPQEQAELYHQQLRREG------LTMAPLEAA-----
>Microcystis_aeruginosa_NIES_843_gnl_BL_ORD_ID_703
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MSSAPST
TLDKSTQVVKKTYPNYKVIVLNDDFNTFDHVANCLIKYIPDMTTDRAWELTNQVHYQGQA
IVWTGPQEQAELYHQQLRREG------LTMAPLEAA-----
>Microcoleus_chthonoplastes_PCC_7420_gnl_BL_ORD_ID_3381
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MTVVISAARSATSAAPTQ
APEKSRQVTRKPYPNYKVIVLDDDFNTFQHVHDCLVKYIPGMSSDYAWKLTNQVHFEGQA
IVWVGPQEQAELYHQQLSRAG------LTMAPLEAA-----
>Cylindrospermopsis_raciborskii_CS_505_gnl_BL_ORD_ID_3110
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------MKTRPSPVYAMASAPTV
TPDQGTQVVRKPYPNYKVIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWELTNQVHYEGQA
IVWVGPQEQAELYHQQLRRAG------LTMAPLEAA-----
>Raphidiopsis_brookii_D9_gnl_BL_ORD_ID_516
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------MKTRPSPIYAMAPAPTV
TPDQGTQVIRKPYPNYKIIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWELTNQVHYEGQA
IVWVGPQEQAELYHQQLRRAG------LTMAPLEAA-----
>Thermosynechococcus_elongatus_BP_1_gnl_BL_ORD_ID_1087
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------MPSV
VPQERQQVTRKHYPNYKVIVLNDDFNTFQHVAACLMKYIPNMTSDRAWELTNQVHYEGQA
IVWVGPQEQAELYHEQLLRAG------LTMAPLEPE-----
>Synechocystis_sp_PCC_6803_gnl_BL_ORD_ID_1103
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MISNAATS
TPDRLTSTVRKTYPNFKVIVLNDDFNTFQHVSDCLLKYIPGMTGDRAWELTNQVHFDGLA
IVWVGPQEQAELYHQQLRREG------LTMAPLEKA-----
>Cyanothece_sp_BH68_ATCC_51142_gnl_BL_ORD_ID_3651
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------MSKRLSTGIQGMATSTST
APKGSTVIDRKPYPNYKVIVLNDDFNTFNHVANCLMKYIPGMSSDRAWELTEQVHFEGLA
IVWTGPQEQAELYHQQLRREG------LTMAPLEEA-----
>Cyanothece_sp_CCY_0110_gnl_BL_ORD_ID_1780
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MATSTST
APKGSTVIDRKPYPNYKVIVLNDDFNTFNHVANCLMKYIPGMSSDRAWELTEQVHFEGLA
IVWTGPQEQAELYHQQLRREG------LTMAPLEEA-----
>Synechococcus_sp_PCC_7002_gnl_BL_ORD_ID_2207
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------MAPAPGI
LKESDRQTVRKPYPNFKVIVLNDDFNTFEHVAHCLMTYIPNMTADQAWNLTNQVHFDGQA
IVWVGPQEPAELYHQQLRREG------LTMAPLEAA-----
>Trichodesmium_erythraeum_IMS101_gnl_BL_ORD_ID_3325
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MSLGISIIGIIENIAVRGGASSPTTL
APKKDSQVVNKPYPNYKVIVLNDDVNTFKHVAECLQKYIPGMTSDRAWELTYQVHNEGQA
IVWVGPLEQAELYHQQLSRAG------LTMAPLEKA-----
>ClpS2_Synechococcus_7942_ClpS2
------------------------------------------------------------
-------------------------------------------MLPSPFRPQTTIASENV
KTASKAAQPKVNSSMSPQPDESVLSILGVPRPCVKKRSRDDAFVLTVLTCSLQAIAAPAT
APGTTTTRVRQPYPHFRVIVLDDDVNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAA
TVWSGPQEQAELYHEQLRREG------LTMAPLEAA-----
>Cyanothece_PCC_7425_gnl_BL_ORD_ID_3769
------------------------------------------------------------
-------------------------------------------M----------------
---------------------------------------VRPIQTSSLSPLAVATPRQSP
TPVQDRQTIRQPYPHYKVIVLNDDFNTFEHVAKCLMKYIPNMTSDRAWELTYQVDREGQA
IVWVGPQEQAELYHLQLGQAG------LTMAPLELA-----
>Cyanobacterium_sp_UCYN_A_gnl_BL_ORD_ID_272
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------MFKRLSITIPETSIST
NIKHSAVIDYKPYPNCKIIVLNDDFNTFDHVANCLIRYIPAMTKSHAWELTQKIHFNGFA
TVWMGPLEQAELYHQQLRREG------LTMAPLEGI-----
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_2237
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------MSSATV
TPTKPETSVKALKP-WKVIVLNDDFNTFQHVANCLVKYIPHMHPDRAWKLTQQVHSEGRA
IVWVGPLEQAELYHEQLSREG------LTMAPLEQA-----
>Synechococcus_sp_JA_2_3B_a2_13_gnl_BL_ORD_ID_2497
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------MTTEAPTRPAQ
QFSPSRTQVRQPYPHFKVIVLDDDFNTFQHVTECLLKYIPGMTLPLARQLTVQVDAEGQA
VVWVGPQEQAELYHQQLLREG------LTMAPLEPA-----
>Prochlorococcus_marinus_MIT_9313_gnl_BL_ORD_ID_672
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTFATPGT
TPLLERAKQTQRYPQARVIVLNDDVNTFQHVVDCLRRIIPGMSEERAWNLAHQIDGQGSA
EVWCGPLEQAELYHQQLSGEG------LTMAPLERC-----
>Synechococcus_sp_WH_8109_gnl_BL_ORD_ID_1922
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTSSSPGS
SAVLERQGTTQRYPQARVIVLDDDVNTFQHVVDCLRKIIPGMSEDNAWNLANRIDGHGAA
EVWCGPLEQAELYHQQLQSEG------LTMAPLERC-----
>Synechococcus_WH_8102_gnl_BL_ORD_ID_1299
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MSSSSPGS
ASLLERQTITQRYPQARVIVLDDDVNTFQHVVDCLRKIIPGMSEEKAWSLANRIDGQGSA
EVWCGPLEQAELYHQQLAAEG------LTMAPLERC-----
>Synechococcus_sp_CC9902_gnl_BL_ORD_ID_1044
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTSSSPSS
STLLERQKTTQRYPEAKVIVLDDDVNTFQHVVDCLRKIIPGMDEEKAWGLAHRIDGQGSA
EVWRGPLEQAELYHLQLQTEG------LTMAPLDRC-----
>Synechococcus_sp_RS9916_gnl_BL_ORD_ID_1876
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTGSSGAQ
STLLERSRTTQGYPEARVIVLNDDVNTFQHVVDCLCKIIPGMGTERAWDLAHQVDGQGSA
EVWCGPLEQAELYHQQLTGEG------LTMAPIERC-----
>Synechococcus_WH_7803_gnl_BL_ORD_ID_1209
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTSSSPGV
STVLERDRQAQRYPQARVIVLNDDFNTFEHVVESLCRIIPGMNTEKAWSLAHRIDGEGAA
EVWCGPLEQAELYHQQLGAEG------LTMAPIERC-----
>Prochlorococcus_sp_CC9311_gnl_BL_ORD_ID_1389
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTMATPGT
ASVLQPERTTLRYPNARVIVLNDDVNTFEHVVECLCKIIPGMNSDKAWTLAHQIDGEGAA
EVWAGPLEPAELYHQQLSSEG------LTMAPLERN-----
>Synechococcus_sp_RS9917_gnl_BL_ORD_ID_1372
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------MTVTPTGT
ATVLDRATSRSDYPQARVIVLDDDVNTFQHVVDCLCRIIPGMGSERAWDLAHRIDSEGAA
DVWSGPLEQAELYHQQLSAEG------LTMAPLERC-----
>Synechococcus_sp_CB0205_gnl_BL_ORD_ID_2119
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------MQPIRSISSSPGG
QAVMERQRVRAPYPTGRVIVLDDDHNTFQHVVEVLVKHIPAMVSDRAWELAHQIDSQGSA
VVWSGPLEQAELYHQLLAGEG------LTMAPVERG-----
>Prochlorococcus_marinus_MIT_9312_gnl_BL_ORD_ID_939
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------MYNSP
LTVLDNKKSKVKYPEARVIVLDDSFNTFQHVANCLLIIIPGMSENRAWDLTIKVDNTGSA
EVWRGNLEQAELYHEQLVSKG------LTMAPIDKT-----
>Prochlorococcus_marinus_MIT_9211_gnl_BL_ORD_ID_1514
------------------------------------------------------------
------------------------------------------------------------
-----MRETKRRNQCSRRAHQKDASRNGRPLLLMMDKKIMTRHTKDFVATTAMKFSANST
TTVLDPKTTKKKYPEARIIVLDDNFNTFEHVANCLVTIIPGMSEKRSWVLAVEVDREGLA
EVWRGPLEQAELYHQQLISKG------LTMAPIEKT-----
>Acaryochloris_marina_MBIC11017_gnl_BL_ORD_ID_5473
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETLEKR-------------------------------
------STSRKLAPKYRVLLHNDDFNSMEHVVQVLIQTVPNLTQPQAVSVMMEAHTNGIA
LVITCAFEHAEFYCETLKMHG------LT-STIEPDE----
>Anabaena_variabilis_ATCC_29413_gnl_BL_ORD_ID_1891
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIEKR-------------------------------
------STSRKLAPRYRVLLHNDDYNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLA
LVITCAQEHAEFYCETLKDHG------LS-STIEPDE----
>Nostoc_sp_PCC_7120_gnl_BL_ORD_ID_4631
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIEKR-------------------------------
------STSRKLAPRYRVLLHNDDHNSMEYVVQVLITTVPSLTQPQAVSIMMEAHTNGLA
LVITCAQEHAEFYCETLKDHG------LS-STIEPDE----
>Nodularia_spumigena_CCY9414_gnl_BL_ORD_ID_2031
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MEHVVQSLITTVPSLTQPQAVSIMMEAHTNGMA
LVITCAQEHAEFYCETLKSHG------LS-STIEPDE----
>Nostoc_punctiforme_ATCC_29133_gnl_BL_ORD_ID_3476
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIQKP-------------------------------
------STTRKLAPRYRVLLHNDDYNSMEHVVQSLIATVPSLTQPQAVSIMMEAHTNGLA
LVITCALEHAEFYCETLISHG------LS-STIEPDE----
>Cylindrospermopsis_raciborskii_CS_505_gnl_BL_ORD_ID_496
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIEKP-------------------------------
------STTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVSIMMEAHSHGLA
LVISCALEHAEFYCESLNNYG------LT-STIEPDD----
>Raphidiopsis_brookii_D9_gnl_BL_ORD_ID_1510
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIEKP-------------------------------
------STTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVTIMMEAHSNGLA
LVISCALEHAEFYCESLNNHG------LT-STIEPDD----
>Arthrospira_platensis_NIES_39_gnl_BL_ORD_ID_6367
------------------------------------------------------------
--------------------------------------------------------MALV
CFGIDKFPYHCTFVNGGDGSVSTQTVEKT-------------------------------
------STNRKLAPRYRVLLHNDDHNPMEYVVQVLMSTVPGLTQPQAVSIMMEAHTNGLA
LVITCALEHAEFYCETLKNHG------LT-STIEPDE----
>Lyngbya_sp_CCY_8106_gnl_BL_ORD_ID_3908
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MEYVVQVLLQTVPSLTQPQAVSIMMEAHTNGLA
LVITCAQEHAEFYCETLKNNG------LT-STIEPDE----
>Microcoleus_chthonoplastes_PCC_7420_gnl_BL_ORD_ID_4785
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------MEYVVQALIQTVPSLTQPQAVNIMMEAHNSGIA
LVITCALEHAEFYCETLKNHG------LT-STIEPDE----
>Leptolyngbya_valderiana_BDU_20041_gnl_BL_ORD_ID_6
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIEKR-------------------------------
------STVRKHAPRYRVLLHNDDFNTMEYVVQTLVKTVPGLTQPQAVSIMMEAHTNGMA
LVITCAQEHAEFYCETLRRHG------LS-SSIEPDD----
>Cyanothece_PCC_7425_gnl_BL_ORD_ID_3320
------------------------------------------------------------
------------------------------------------------------------
--------------------MAVETIEQR-------------------------------
------STVRKLAPRYRVLLHNDDVNSMEHVVEVLLKTVPSLTQPQAVDIMMEAHVNGIA
LVITCALEHAEFYCESLKLGG------LT-STIEPDE----
>Oscillatoria_sp_PCC_6506_gnl_BL_ORD_ID_4778
------------------------------------------------------------
------------------------------------------------------------
--------------------MSVETIEKR-------------------------------
------STVRKIAPRYRVLLHNDDFNSMEYVVQTLMHTVPSLTQPQAVNIMMEAHTNGLA
VVIICAQEHAEFYSETLNNHG------LI-STIEPDE----
>Thermosynechococcus_elongatus_BP_1_gnl_BL_ORD_ID_210
------------------------------------------------------------
------------------------------------------------------------
--------------MEAWPTMSVQTIEKP-------------------------------
------ATVRKLAPRYRVLLHNDNVNSMEYVVEVLLKTVPSLTQPQAVDIMMEAHLTGVA
LVITCALEHAEFYCEGLKMAG------LT-STIEPTE----
>Trichodesmium_erythraeum_IMS101_gnl_BL_ORD_ID_952
------------------------------------------------------------
------------------------------------------------------------
--------------------MSIETIEKP-------------------------------
----TTSTVRKTAPHYRVLLHNDDFNSMEYVVQTLMKTVPSLTQPQAVNIMMEAHSNGIA
LVIICALEPAEFYCENLKNHG------LT-STIEPDE----
>Cyanothece_PCC_7424_gnl_BL_ORD_ID_1601
------------------------------------------------------------
------------------------------------------------------------
------------------MSTSTQVIEKS-------------------------------
----TTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMKTVAGMTQPQAVNIMMEAHTNGTA
LVITCTLEHAEFYCETLKNHG------LT-STIEPDE----
>Microcystis_aeruginosa_NIES_843_gnl_BL_ORD_ID_5244
------------------------------------------------------------
------------------------------------------------------------
------------------------MIEKR-------------------------------
----STATIRKPAPRYRVLLHNDDFNSMEYVVQSLMQTIAGMTQPQAVDIMMEAHTNGTA
LVITCIQEHAEFYCETLKNKG------LT-SSIEPDE----
>Synechococcus_sp_PCC_7002_gnl_BL_ORD_ID_2405
------------------------------------------------------------
------------------------------------------------------------
--------------------MSTGVIEQR-------------------------------
----STSTIRKPAPRYRVLLHNDDFNSMEHVVQTLMQTVAGLTQPQAVSIMMEAHTNGIA
LVITCVQEHAEFYCETLKMHG------LT-STIEPDE----
>Cyanothece_sp_BH68_ATCC_51142_gnl_BL_ORD_ID_2328
------------------------------------------------------------
------------------------------------------------------------
--------------------MTTEVIEKR-------------------------------
--SSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVSGMTQPQAVDIMMEAHTNGTA
LVITCALEPAEFYCETLKNHG------LT-STIEPDE----
>Cyanothece_sp_CCY_0110_gnl_BL_ORD_ID_2487
------------------------------------------------------------
------------------------------------------------------------
--------------------MTTEVIEKR-------------------------------
--SSSTSTVRKPAPRYRVLLHNDDFNSMEYVVQTLMQTVSGMTQPQAVDIMMEAHTNGTA
LVITCALEPAEFYCETLKNHG------LT-STIEPDE----
>Cyanobacterium_sp_UCYN_A_gnl_BL_ORD_ID_939
------------------------------------------------------------
------------------------------------------------------------
--------------------MVTDVIEKI-------------------------------
--SLNTSTTKKPVPRYKVLLHNDDFNPMDYVVQILMQTISGMTRPQAAEIMMEAHISGTA
LVITCAFEPAEFYRETLKNHG------LS-SSIEPDE----
>Synechocystis_sp_PCC_6803_gnl_BL_ORD_ID_1854
------------------------------------------------------------
------------------------------------------------------------
-------------------MMATEVLNKP-------------------------------
----SNSTIRKHAPRYRVLLHNDDFNSMEHVVQTLIQTVAGMTQPQAVDIMMEAHFNGMS
LVITCELEHAEFYCETLRSHG------LS-STIEPDE----
>ClpS1_Synechococcus_7942_ClpS1
------------------------------------------------------------
------------------------------------------------------------
--------------------MAVETIQKP-------------------------------
----ETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTG
LVITCDIEPAEFYCEQLKSHG------LE-QQH--------
>Synechococcus_sp_JA_2_3B_a2_13_gnl_BL_ORD_ID_664
------------------------------------------------------------
------------------------------------------------------------
--------------------MATETLVKP-------------------------------
------SVTPKHMPMYRVLLHNDDVNTMEYVVQVLVKVIPAMMPPQATEIMLEAHHNGVA
VVIVVPREHAEFYCEQLRQHG------LT-SSIEPER----
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_745
------------------------------------------------------------
------------------------------------------------------------
--------------------MSTETLERK-------------------------------
------SVQRKPMPLYKVLLHNDDHTPMNYVIEVLMKTIPKMQPSKARKIMLEAHNGGVA
VVIVCALEHAEFYSESLNRHN------LT-STYEPDC----
>Prochlorococcus_marinus_MIT_9313_gnl_BL_ORD_ID_1789
------------------------------------------------------------
--------------------------------------------MKLGLPTICTMGERPT
YIGAVPIVLAMAVNAPSPTPGGAAVLEKQ-------------------------------
-----TERIRKQSPHYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLEAHNTGVG
LVIVCDLEPAEFYCETLKAKG------LT-STLEQES----
>Synechococcus_sp_RS9916_gnl_BL_ORD_ID_2779
------------------------------------------------------------
------------------------------------------------------------
----------MAVNTTSPGPGGAAVLDKQ-------------------------------
-----TERVRKRSPRYKVLLHNDPVNSMEYVVSTLQQVVPQLSEQDAMAVMLEAHNSGVG
LVIVCDLEPAEFYCETLKAKG------LT-STLEPES----
>Synechococcus_sp_RS9917_gnl_BL_ORD_ID_1996
------------------------------------------------------------
--------------------------------------------MHRS------------
-------DLAMVGSTSSTSPGGAAVLDKQ-------------------------------
-----TERVRKHSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMLEAHNTGVG
LVIVCDLEPAEFYCETLKAKG------LT-STLEPET----
>Prochlorococcus_sp_CC9311_gnl_BL_ORD_ID_363
------------------------------------------------------------
------------------------------------------------------------
-----------MVDTPSRSPGGAAVLDKQ-------------------------------
-----TERVRKTSPRYKVLLHNDPVNSMEYVVVTLQQVVPQLSEQDAMAVMLETHNTGIG
LVIVCDIEPAEFYCETLKNKG------LT-STIEPES----
>Synechococcus_WH_7803_gnl_BL_ORD_ID_368
------------------------------------------------------------
------------------------------------------------------------
--------MVMAVETPSRTPGGAAVLEKA-------------------------------
-----PERVRKQSPRYKVLLHNDPVNSMEYVVSTLRQVVPQLSEQDAMAVMLEAHNTGVG
LVIVCDLEPAEFYCETLKGKG------LT-STIEPEN----
>Synechococcus_WH_8102_gnl_BL_ORD_ID_2141
------------------------------------------------------------
------------------------------------------------------------
--------MAMAVDTPTRSPGGAAVMEKA-------------------------------
-----PERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQLSEQDAMAVMIEAHNTGVG
LVIVCDLEPAEFYCETLKAKG------LT-STIEPET----
>Synechococcus_sp_CC9902_gnl_BL_ORD_ID_2014
------------------------------------------------------------
------------------------------------------------------------
----------MAEETPTRSPGGAAVLDKA-------------------------------
-----PERVRKRSPRYKVLLHNDPVNSMEYVMTTLRQVVPQLSEQDAMAVMLEAHNTGVG
LVIVCDIEPAEFYCETLKSKG------LT-SSIEPED----
>Synechococcus_sp_WH_8109_gnl_BL_ORD_ID_198
------------------------------------------------------------
--------------------------------------------MSRSISLFPLNLKVFG
-------SMVMAVDSPSQKPGGAAVLDKA-------------------------------
-----PERVRKRSPRYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEAHNTGVG
LVIVCDIEPAEFYCEMLKSKG------LT-SSIEPEE----
>Synechococcus_sp_CB0205_gnl_BL_ORD_ID_783
------------------------------------------------------------
------------------------------------------------------------
--------MIRSTQAPGRESGGAAVMEKA-------------------------------
-----PERVRKPSPRYKVLLHNDPVNTMEYVVSTLRQVVPSLSEQDAIAVMMEAHNTGVG
LVIVCDIEPAEFYSETLKAKG------LS-STIEPED----
>Prochlorococcus_marinus_MIT_9211_gnl_BL_ORD_ID_1621
------------------------------------------------------------
----------------------------------------------------------MS
LVDWNYLPTGIMVEATGSSPGGATVIEKQ-------------------------------
-----SELVRKRSPRYKVLLHNDPVNSMDYVVTTLRQVVPQLSEQDALAVMLEAHNTGVG
LVIVCDLEPAEFYSESLKAKG------LS-STIEKET----
>Prochlorococcus_marinus_MIT_9312_gnl_BL_ORD_ID_1590
------------------------------------------------------------
------------------------------------------------------------
---------MLSIKLEQSVSNNSAVIEKK-------------------------------
-----PAELKNKSPKYRVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTGVG
LVIVCDLEPAEFYSESLKSKG------IS-SSIEKED----
>Prunus_persica_gnl_BL_ORD_ID_10981
------------------------------------------------------------
-------------M-AAICGRVALSPNQGF----NLAKSGDKHYFHK-QCS-SRSILMTA
-------------SST-RLGKGGGLLEKPTIEKT-------------------TPSRDS-
--EFDLRKSRKMSPPYRVMLHNDNYNKREYVVQVLMKVIPGMTVDIAVNIMQEAHHNGLA
VVIVCAQVDAEDHCMQLRGNG------LL-SSVEPASDG-C
>Capsella_rubella_gnl_BL_ORD_ID_21193
------------------------------------------------------------
-------------MDTTICGRLALAPSTLF-----SSKSGDKHSLSKGPCL-NRGVLMTL
-------------STSAALGKGGGVLDKPIIEKT-------------------TPGRES-
--EFDLRKSKKMAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGMA
VVIVCAQADAEQHCMQLRGNG------LL-SSVEPDGGG-C
>Brassica_rapa_gnl_BL_ORD_ID_16356
------------------------------------------------------------
-------------METAICGRLALAPTTLF-----NSISGDKHSVSKGPCVNNRGVLITM
-------------STS-VVGKGGGVLDKPIIEKT-------------------TPGRES-
--EFDLRKSKKMAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGMA
VVIVCAQADAEQHCMQLRGNG------LL-SSVEPDGGG-C
>Prunus_persica_gnl_BL_ORD_ID_19291
------------------------------------------------------------
-------------METAICGRLPLSPNHVF-----NPKPGDRHPLCKGPCT-NLGIPMAV
-------------SAT-GPGKGGGLLERPVIEKT-------------------TPARDS-
--EFDLRKSRKTAPPYRVILHNDNYNKREYVVQVLMKVIPGMSLDNAVNIMQEAHHNGLS
IVIICAQADAEEHCMQLRHNG------LL-SSIEPASGGGC
>Glycine_max_gnl_BL_ORD_ID_3555
------------------------------------------------------------
-------------MKSAICGRI-LSPNHVF-------KPGDTHSICKGPYS-NLCVPMAV
-------------LAT-GPGKGGGVLEKPVIEKV-------------------TPGRES-
--EFDLKKSRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLS
VVIICDQADAEDHCTQLRGNG------LL-SSIEPASGG-C
>Ricinus_communis_gnl_BL_ORD_ID_3780
------------------------------------------------------------
---------------------------------------------------------MAL
-------------SAT-GAGKGGGLLEKPVIEKT-------------------TPGRES-
--EFDLRKSRKTAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLS
VVIICAQADAEDHCMQLRGNG------LL-SSIEPASGG-C
>Carica_papaya_gnl_BL_ORD_ID_311
------------------------------------------------------------
-------------METAICGRLSLSPSTVF-----NPKPGEKHSPCKGPCI-TRGILMAL
-------------SAT-GGGKGGGVLERPVIEKT-------------------TPGRES-
--EFDLRKSRKTAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLS
VVIICAQADAEDHCMQLRGNG------LL-SSIEPASGG-C
>Populus_trichocarpa_gnl_BL_ORD_ID_43343
------------------------------------------------------------
-------------METAICGRIALSPNHVF-----NPKPGDKNSVCRGPCA-NRGILMAI
-------------STT-CSGKGGGLLEKPVIERT-------------------TPGRES-
--EFDLRKSKKMAPPYRVMLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLS
VVIICAQADAEEHCMQLRGNG------LL-SSIEPASGG-C
>Medicago_truncatula_gnl_BL_ORD_ID_34263
------------------------------------------------------------
---------------------------------------------------------MAV
-------------LTK-GSGKGGGILEKPVIEKA-------------------TPGRES-
--EFDLKKSRKTAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMS
VVIICAQADAEDHCMQLRGNG------LL-SSIEPAGDG-C
>Vitis_vinifera_gnl_BL_ORD_ID_4262
------------------------------------------------------------
-------------METAICGRVPLSPNHFF-----TSKSGDKHSLSK-QWT-HRTMLMTV
-------------SAA-APGKGSGVLERPTIERI-------------------MPGRES-
--EFDLRKSRKMSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGMS
VVIICAQVDAEDHCMQLRGNG------LL-SSIEPASGG-C
>Aquilegia_coerulea_gnl_BL_ORD_ID_33124
------------------------------------------------------------
-------------METAICGRVSLSPNHVF----NNHKPGDKHAIYRGPCT-NRGILMTI
-------------SAA-GPGKGGGLLDRPTIEKT-------------------TPGRES-
--GFDVRKSRKMSPPYRVMLHNDNYNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINDLA
VVIICAQADAEEHCTQLRGNG------LL-SSIEPASGG-C
>Eucalyptus_grandis_gnl_BL_ORD_ID_42553
RRVGIATIQTNSRFPKHPFFRPLDTTKIVPSDFSFPPKKFSPINLLLSSLENIAEEKGRE
RERERGKTSPGIAMETAICGRVALSPHHVF------SKSGDKHYFNK-QCS-YRSSLTTM
-------------STT-ALGKGGGLLERPTIE-T-------------------TPGRES-
--EFDVRKSRKTAPPYRVMLHNDNFNKREYVVQVLMKVIPGMTLDNAVNIMQEAHYNGLS
VVIICTQADAEEHCMQLRGNG------LL-SSIEPASGG-C
>Glycine_max_gnl_BL_ORD_ID_17909
------------------------------------------------------------
-------------MEAALCSALALSPNQVF----NAANPGDKNVPLK-YSK-DRSVVMTV
-------------AATGILGKGGGLLERPTIETT-------------------SPGRES-
--EFDLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVNIMQEAHYNGLA
VVIVCAQVDAEDHCMQLRGNG------LL-SSIEPADGGGC
>Selaginella_moellendorffii_gnl_BL_ORD_ID_14527
------------------------------------------------------------
------------------------------------------------------------
-------------------GLGGGVLDKPAIETAP------------------TPGRES-
--EFDLRKKKKMAPPYRVILHNDNFNRREYVVQVLMKVIPGMTLDNAVNIMQEAHHNGLS
VVIVCSQEDAEEHCTQLRANG------LL-SSIEPASGG--
>Panucum_virgatum_gnl_BL_ORD_ID_14345
------------------------------------------------------------
-------------MSGSSPGRCSLAAAGL-----GRLAAGDRSCIYKGRFQ-SLAIPMAL
-------------SAA-APGK-GGVLDRP-VEKT-------------------TPGRQS-
--EFDVKKKRKMTPPYRVILHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLS
VVIVCSQSEAEEHCTSLRGNG------LR-SSIEPASGG-C
>Setaria_italica_gnl_BL_ORD_ID_19258
------------------------------------------------------------
-------------MEAAVPSRVALSAASRFPN--RHAVAGDRSTIYKGRCQ-SLAIPMAL
-------------SAA-APGK-GGVLDRP-VEKT-------------------TPGRQS-
--EFDVKKKRKMTPPYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVNIMQEAHVNGLS
VVIVCSQSEAEEHCTSLRGNG------LR-SSIEPASGG-C
>Sorghum_bicolor_gnl_BL_ORD_ID_22153
------------------------------------------------------------
-------------MEAAVPSRVALSAASRLPN--RHAVAGDRSFVYKGRCQ-SLAIPMAL
-------------SAA-APGK-GGVLDRP-VEKT-------------------TPGRQS-
--EFDVKKSRKMSPPYRVILHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLS
VVIVCSQSEAEEHCTSLRGNG------LR-SSIEPASGG-C
>Zea_mays_gnl_BL_ORD_ID_43912
------------------------------------------------------------
-------------MEAAVPSRVALSAASRLPN--PHAVTGDRSFIYKGRCQ-SLAIPMAL
-------------SAA-APGKGGGVLDRP-VEKT-------------------TPGRQS-
--EFDVKKSRKMSPPYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVNIMQEAHVNGLS
VVIVCSQSEAEEHCTSLRGNG------LR-SSIEPASGG-C
>Oryza_sativa_gnl_BL_ORD_ID_6727
------------------------------------------------------------
-------------MEAAVPSRVALSASRLS-NHHHHAVGGERYAIYRGRCP-NPAIPMAL
------------AAAA-APGKGGGVLDRP-IEKV-------------------TPGRQS-
--EFDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLS
VVIICSQSEAEEHCTSLRGNG------LR-SSIEPASGG-C
>Brachypodium_distachyon_gnl_BL_ORD_ID_24208
------------------------------------------------------------
-------------MEAAVPSRIALSARIMN----HHVVAGGRSSIYRGRYP-NIAIPIVV
-------------TAA---GKGGGVLDRP-AEKI-------------------SPGRQS-
--EFDVKKSRKMSPPYRVVLHNDNENRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLA
VVIVCSQSEAEEHCTSLRGNG------LR-SSIEPASGG-C
>Vitis_vinifera_gnl_BL_ORD_ID_7060
------------------------------------------------------------
-------------MENAICGRLALSPNHVF-----NSKSGDKHSLLKGPCT-NRSFLMAI
-------------SAS-GPGK-GGLLERPVIEKV-------------------TPGRES-
--EFDLRKSRKIAPPYRVILHNDNYNKREYVVQVLMK-----------------------
-------ADAEDHCMQLRGNG------LL-SSIEPASGG-C
>Physcomitrella_patens_gnl_BL_ORD_ID_33457
----------------------------------------------------------ML
LGALEKTLSLPAGMAASLRLFITVPPVTSHTGIKVVEKVQRVCDKVNGRYA--------I
------------RDAA-APGQGGGVMDRPTIDKP-------------------TPGRES-
--EFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLLKAIPGMTVDIAVNVMNEAHINGIA
VVIVCPQEDAEDYCMQLRTNG------LL-SSIEPDT---C
>Physcomitrella_patens_gnl_BL_ORD_ID_6354
------------------------------------------------------------
-------------MAGSLRLFVSIPATARHFGINGVEKAQRVHNRVNGRYK--------I
------------NAAS-GPSQGGGVLDRPTIDKP-------------------TPGRES-
--EFDLKKKKKMSPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLA
VVIVCPQEDAEDYCMQLRTNG------LL-SSIEPAS---C
>Volvox_carteri_gnl_BL_ORD_ID_608
------------------------------------------------------------
-----MAASVLRPPPVSVA---SRAPTAAL----AVLPGSACLGWRRANFGTSTLLSQTT
------------RTCVQMRAGVPGLLDSPTITSE------------------------P-
--QQGTDRAYKRPPIYKVFLHNDNYNKREYVVKVLLKVVEEITVDDAVTVMQEAHETGVA
LVVACPQENAERYCEGLRLNG------LT-STIEPAG---R
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_9005
------------------------------------------------------------
-----MAASCLRPAPTASAQMMTRSPVAGLPRPCSALQRSGCT--LQGAFG--TFAPQTT
------------RTFVVTWAK-GGVMDAPTTTQQ------------------------P-
--ASGVERSQKRPPIYKVLLHNDNYNKREYVVKVLLKVVEQITVDDAVTCMQEAHETGVA
LVVACPQDNAERYCEGLRLNG------LT-STIEPGG---C
>Cyanophora_paradoxa_gnl_BL_ORD_ID_27119
--------------------------------------------MAFCSAVPLRAGRVVG
SVLQATPSACFQPAEPAPVSSVSSRRSTFFAGEIDVGVHVDARSTADSSPATRRFVAATV
VPPTSAVVLKPAPKIAKTGLQTDTASAKPEVETGGDGAK---------------------
--SKERENEEEFMGKWKVLLHNDEANTMEYVIKAIRTVVPNISHQEAVNIMLEAHTTGV-
VVIVCEKEHAEYYCEGLKGYQ------LW-SSIEPEDV---
>Cyanidioschyzon_merolae_gnl_BL_ORD_ID_2238
------------------------------------------------------MVSCVF
FVSTFHPYSLNWQPRNAPLLRRETLTRRPTPVVVQRRANGAALPIRTEWSGWTRPESGVR
RMPTNMPRGRSRKPSFSPTGGGATTLEREAVRE---------------------------
--KTTATKGVDPGKKYKLLLFNDEKNTRERVVEVLLKCIPGLSKLDAQSIMQKAHTTGMA
LVGVWVFELAEAYCDLLRSEG------LV-SDIEPAE----
>Gloeobacter_violaceus_PCC_7421_gnl_BL_ORD_ID_2530
---------------------------------------------------------MLS
SAEAPSPGTVQWAPNGQKAQDRQHRVASVHVTGLAASGYLAVASYPASRQPGDVQKRLRW
GAIVVSFGYTGTQDDYPHASMERMVLAPAAVSAPP------------------LPTKTPL
DPVKTPEKTPLRWRDWVVRLFNDPVNKFEHVVESLCKHVPGMSQDMAWSVAWQAHREGVA
ATYQGPREVAELVCEKLVRDG------LISDCCES------
>Cyanophora_paradoxa_gnl_BL_ORD_ID_23599
------------------------------------------------------------
------MAAFVAPANPVRSQAIGRCAIASPASVVFELQRVFSAVS---------------
-----------IPGGSGGLKGGAAVLERPSVIGDVDVTAW--------------------
--ATFMARRKAQAPKYRVLLFNDPFNKREHVV------IDGLTTADAVEIMSKAHNEGFA
VAAVVVQEVAELYVEGLRSCG------LT-ATCEPDE----
>Prunus_persica_gnl_BL_ORD_ID_16262
------MHQMRTLNSAWFPRKQAKQKEMETETEKGNPKKTNFVISYFLPFFLSLCVLVFP
STQATTRLAEMNMAL-TGGATTTSSFSLTRIV---GFPPPPSPSRSCSRILGVKEGQERW
RGGNGMA----VKARFGSSKGGAGVLERPKFDQSQFDPATQLEQGGDIG-----------
--RLKEKRGIGSGDSYRVLLVDDVRHTEKLVAKVVPQVVPSVTPDDARGLFLKSRENGVA
VVIVTVKEHAEFYSQMMIRGG------LR-STIEPDSNSL-
>Carica_papaya_gnl_BL_ORD_ID_24571
------------------------------------------------------------
------------MAV-TGKPTTSVSLTHLPPL---LFSPIPRPASVVS-----------V
RGRSGTSKFARVNANFVPSKGGAGILERPTFDQSQFDPSTQVLEGGDVG-----------
--RLKNKKGVGSGDSYRVLLMDDIRHTENLVAKILPQVIPSVTPNDARRLFNESRENGVA
VVIVTVKEHAEFYSQMMIRGG------LR-STIEPDTNVL-
>Populus_trichocarpa_gnl_BL_ORD_ID_33308
------------------------------------------------------------
------------MALFTAASTTRFSSTKQQSV---HFNSMDGPIPTHSTRANFPQKRAIA
MS-TNLA----VKASF--TKGGTGVLERPTFDQSQFDPSSQALEGGDIG-----------
--RLRDKRGVGSGDSYRVLLIDDARHSERLVAKVLPQAVPSVTPDDARKLFHESRENGVA
VVIVTVKEHAEFYSQMMVRGG------LR-SIIEPESNTV-
>Populus_trichocarpa_gnl_BL_ORD_ID_42340
------------------------------------------------------------
------------MAVLTAASTTWFSSTTQQPV---QFNNVDGSIFTRNFKANFPQKRAIT
MS-TGLT----VKASF--TKGGPGVLERPTFDQSQFDPSSQVLEGGDIG-----------
--RLRDKRGVGSGDSYRVLLIDDSRHSESLVAKVLPRAVPSVTPEDARKLFHESRENGVA
VVIVTVKEHAEFYSQMMIRGG------LR-SVIEPDSSNV-
>Oryza_sativa_gnl_BL_ORD_ID_22109
------------------------------------------------------------
------------MAI-SSRAAACGALIFPTTA---SAAPVSRSVSV--------DQRVSH
RRRKAVA----VAAVPHAS-SGGALLERPAFDQSQLDTLPVTQEGGDTG-----------
--RMRDRRGSGSGDSYKVLLIDDARHTEKLVEKALPQVVPSVTAEAARQLFHASRQKGAA
LVIVAVKEHAEFYAQMMVRQG------LR-SAIEPESDLAS
>Setaria_italica_gnl_BL_ORD_ID_2316
------------------------------------------------------------
------------MAI-SGRAAACTALVFPSTATTTTTTPLPSTVSV--------NLRARH
RKKATAG----VVAAPHASGGGGAVLERPAFDQSQLDTLPVTQEGGDPG-----------
--RLRDGRRSGSGDSYKVLLVDDVRHTEKHVEKALPQVVPSITAEAARQLFHESRLKGVA
LVIVAVKEHAEFYAQMMVRQG------LR-SAIEPESDLAS
>Physcomitrella_patens_gnl_BL_ORD_ID_17725
------------------------------------------------------------
------------MAA-AMGSAAQVMLLGLQPVG--AVSQAAAPVCVRVAVGQQRDTRGTV
GGSGGV-----FQARLGGGGGGAGVLERPKLDQSGSDTTPRTEEGGESG-----------
--RAAQRNRTGGGERYRVLLLDHERHTETYVAKALTKAVPNITAEQARKCFFESRLIGKS
VVMVAVKEHAEMHAFSMARYG------LR-STIEPDGSVM-
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_17107
------------------------------------------------------------
--------------------------------------------MLATRCKCNLPSRSFV
APARSVRTRALHVEGRFGGGRGGNVIDRPDVDVSKRLGGFDLSDWNIPSWDAKTDNGNNG
SNTDKDKKSPPGGGNYRVLLLDSPQHTEKGVVAAITRVVPGTNPDHARNCFATSKQLGMA
IITTALKEHAELYREQLFTYR------VR-TALEPDNSTV-
>Volvox_carteri_gnl_BL_ORD_ID_2065
----MEKPLSPASLLPAGSGACPETFNVVLSDWLRPIAVVGFAAGWESWASAGSAGAMMI
LFCCGWGIQPGYTFGWGSVSLRKQTLILFVLWRLHYTKLQLEMAMLSQRTFKNLRRGSRA
KVIRPCGRFALQIQARFGGGR-GNVLDRPDVDLSKRLGGFDLSDFNLGGWKPSTESGRSG
SGLDKDKQSPPGGGNYRVLLMDSPQHSEKVVVRGICTVVPNADEAHARNCYHTSKQLGMA
IITTALKEHAEFYRQQLYTYG------CR-TAIEPDSTVA-
>Rhodopseudomonas_palustris_CGA009_gnl_BL_ORD_ID_1197
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------MILVNDDYTPREFVVSVLKGEF-RMTEDQATKVMLTAHQRGVC
VVGVFTKDVAETKATRATDAGRAKGYPLL-FTTEPEE----
>Rhodopseudomonas_palustris_CGA009_gnl_BL_ORD_ID_3127
------------------------------------------------------------
------------------------------------------------------------
--------MLQPSLSHSAAGQAGDRINRPLAMAGD--------------GGRSGPSTPST
SVITKTKPRTKRPNLYRVLILNDDYTPMEFVVHVLEKFF-QMDVEAATKVMLHVHHHGIG
ECGVFTYEIAETKVTQVMDFARKHQHPLQ-CVMEKK-----
>Escherichia_coli_UTI89_gnl_BL_ORD_ID_1000
------------------------------------------------------------
------------------------------------------------------------
------------------MGKTNDWLDFDQLA----------------------------
--EEKVRDALKPPSMYKVILVNDDYTPMEFVIDVLQKFF-SYDVERATQLMLAVHYQGKA
ICGVFTAEVAETKVAMVNKYARENEHPLL-CTLEKA-----
>Streptomyces_avermitilis_MA_4680_gnl_BL_ORD_ID_5165
------------------------------------------------------------
------------------------------------------------------------
----------------MGRVTAPAPLEIEKTES---------------------------
--AEEVFAVPEPDVPWVTIVHNDPVNLMSYVTYVFQTYF-GYSKDKATKLMLDVHHKGRA
VVSSGTREEMERDVQAMHGYG------LW-ATLQQDRK---
>Chlorobium_tepidum_TLS_gnl_BL_ORD_ID_2204
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------MIRLTASNNPD
TRTEELIADVDTLDAWRVVLFNDDDHTFDEVIFQIIKAV-RCTRSIAEKHTWEVHTRGRA
IVYAGEMSNCIRVSAILEEIA------LK-TEIQTG-----
