>gnl|BL_ORD_ID|18720 @Nematostella_vectensis@ jgi|Nemve1|209342|fgenesh1_pg.scaffold_104000043
M---------------------------------------------------YNAENTRS
K-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------GAS----
-----------KHCAWGVCKSDSR---------------------------YPEK-----
----------------------LPEG-TNFI-----RFPKPGNVKDGMTEWEKGQ-----
----------------QILKTEKAKRW---------------LHACGRKDFSKISDIKKD
TYICTLHFMEGKGPTEDHPYPVLATLTEKEQNQRATRAKTRSRSRKRRENPIEETGASKK
HQQESSCFPVPGDPEEQSEDTSVLFESGLPGPSRASLESQDQGRTDKETQTVYCKCTLGA
KVETMIYRNRLIQEGIGLFPSEQKEVNLMSSEIIIADDKKCKYFTGLHTEQFEALFEFLG
PAKYELSYWDGPENIEKGSLARGEPQGISVKEQLFLTLLRLRRGFNIATIAHM-------
YSISNTVVRKFFVTWI----QFMFCHFKEFEHLMFPSRQALRTFLPKVFQKFKNVRCSVD
CTEF----FCQTPSNYGKQQQGNMFSSYKHHNTMKCLIAVTPNGSACFVSDLFEGSIDDV
SIFRESGILKHINP--------------GDAI-------------LVDKRFTVQDLLFNK
QATIHIP----PFLGKRD--CLTKEEELATKRIAKARIHVERFNERLKKFRLIGNIIPLN
LSSIASQLVYVSCCLVNFQPCLCK
