>gnl|BL_ORD_ID|3127 @Rhodopseudomonas_palustris_CGA009@ RPA3148 DUF174
ML----------------------QPSLSHSAAGQAGDRINRPLAMAG------------
DG-----------GRSGPSTPSTSVITKTKPRTKRPNLYRVLILNDDYTPMEFVVHVLEK
FFQ-MDVEAATKVMLHVHHHGIGECGVFTYEIAETKVTQVMDFARKHQHPLQCVMEKK
>Synechococcus_7942_ClpS2
MLPSPFRPQTTIASENVKTASKAAQPKVNSSMSPQPDESV---LSILGVPRPCVKKRSRD
DAFVLTVLTCSLQAIAAPATAPGT--TTTRVRQPYPH-FRVIVLDDDVNTFQHVAECLLK
YIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAELYHEQL-----RREGLTMAPLEAA
