>gnl|BL_ORD_ID|4892 @Branchiostoma floridae@ jgi|Brafl1|70912|fgenesh2_pg.scaffold_30000200
MM----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----WMKVCIF-------------------------------------------------
------------------------------------------------------------
--LLSSATLSHGDCGG-----TVTGAEGTISSPGYPVSYPSRMDCTWTLPSRG-GRLTLS
FTDFQLE-----RPIGMLSSRCNYDYVE--------VHEGDALVGRWCGENSPGTLT---
---FGSRTAQVHMVSDSSISRRGFRLQWSLAGVA--------------------------
-----PPCGGVMDGPY--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------G
EITSPSYPLDYPSSQ---------------------------------------------
------------------------------------------------------------
---------------------------------------------------DCTWTIAAQ
GGQIIARFLDFALETGSSCQYDYLEIIANGEAPRNPA-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------LLFLGRNAGVT---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>gnl|BL_ORD_ID|10518 @Branchiostoma floridae@ jgi|Brafl1|83753|fgenesh2_pg.scaffold_124000043
MD---------------SLGYASYETPWTVKFRSFLASFSDV------------------
------------------------------------------------------------
----------------------FSNFGTHIGESYNHDRCYRSVQMRLYTLSKRQFVLVFA
GFFMCFAVSVFIGVAGP----------------PIVTEHDVNASALQSPKVENLA-----
-------TGPFQLRTPTLSTFNQQLWLTSKIFIRNPKGDTIKSKFTMSVVVEGQ------
--VADSSVLITGERTH-----NHSRTLHCNKETCNDLVILH-------LGYLDFTTYLVR
VMFFGISDKYPVTEVGFSFKMYNPTFTQLEIWFRF----------------VFLVLTFMV
TCVFAHSLRR-FSIRDWSIEQKWMSILL--------------------------------
--------------PLLLLYNDPIFPLTF-------------------------------
------------------------------------------------------------
----------------------------------------------------LVNSWVPG
MFDAVFQASFLCALLLFWLCAYHGIRQYERRFMTFYVPKVMIVGLLWISAVTLASWQEYN
ELQDPTYQYKVD------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TVNFTILPA
EFLSFYGLLNFYLYTMAYVYSPSKNALHESHFKDNPAFSMLNDSEDEVIYGFQH------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------NMELNPFLAFVAAAGILPFFHITGLALVLICD------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>gnl|BL_ORD_ID|11271 @Ciona_intestinalis@ jgi|Cioin2|293833|estExt_fgenesh3_pg.C_chr_14p0166
MSID--------------------------------AGSHQILAKVYYSGHAFSLHLEHT
IQMEELFTMVRLNCNFPDAQVFTLKWMDDEGDPCTISSQLELSEALRLYRHNNETVLLFH
IFLGIPVEPGLLCPGEH-------------------------------------------
-----------------------------KLYRHGARRWYKLKRILRQI-----------
------------------------------------------------------------
--KKPKHPRIPIESGPILDSGDSQDSKASSDQASPNAPGFGLKDF---EMLKVIGRGSYA
KVLLVKLKSTDKMYAM---KVIKKELVTDEEDIDWVQTEKH----------VFETASNYP
FLVGL----HSCFQTPERLF---FVIEYVNGGDLMFHMQRQRKLPEEHARFYAAEIVLAL
H-------FLHEKG-------IIYRDLKLDNVLLDSDGHIKLTDYGMCKEGIRKGVNTST
FCGTPNYIAPEILRGEDYDFSVDWWALGVLMFEMMAGRSPFDIVGMTDNPEQNTEDYLFQ
VILEKVIRIPRSLSVKASS----VL---KGFLNKIPVDRLGCN-----------------
-------------HESGFQDILDHQFFRTIDWD---------------------------
------LLQSRQVVP---PYKPNIEDDLGLDNFDKQ--FTQEPV-QLTP--TEATVI---
-----------------GKIDQADFE-------GFEYI-----------------NPLLM
TSDV---AV
>gnl|BL_ORD_ID|8419 @Cladonia_grayi@ jgi|Clagr2|91120|fgenesh1_kg.11_#_26_#_isotig14289
MYA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------CLDGPIRR-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------FGGEPTLSGSS-
----------------------------RPPLIAERCLVILQGSTSSKILILACEQHLSH
LNQLTTAVVCATSDSE------------------------------VEDCQRLTRGV---
-------------------------------------------------------S
>gnl|BL_ORD_ID|8679 @Drosophila_melanogaster@ gi|21358013|ref|NP_651658.1| cleavage and polyadenylation specificity factor 100, isoform A [Drosophila melanogaster]
MTSIIKLHTISGAMDESPPCYILQIDDVRILLDCGWDEKFDANFIKELKRQVHTLDAVLL
SHPDAYHLGALPYLVGKLGLNCPIYATIPVFKMGQMFMYDLYMSHFNMGDFDLFSLDDVD
TAFEKITQLKYNQTVSLKDKGYGISITPLNAGHMIGGTIWKIVKVGEEDIVYATDFNHKK
ERHLSGCELDRLQRPSLLITDAYNAQYQQARRRARDEKLMTNILQTVRNNGNVLIAVDTA
GRVLELAHMLDQLWKNKESGLMAYSLALLNNVSYNVIEFAKSQIEWMSDKLT-KAFEGAR
NNPFQFKHIQLCHSLADVYKLPAGPKVVLASTPDLESGFT---------RDLFV------
---QWASNANNSIILTTRTSP------GTLAMEL--VENCAPG-----KQIELDVRR---
-----RVDLEGAEL--EEYLRTQGEKLNPLIVKP----------------------DVEE
ESSSESEDDIEMS------------VITGKHDIVVRPE---GRHHSGFFKSNKRHHVMFP
YH--------EEKVKCDE-------------------YGEIINLDDYRIADATGYEFVPM
EEQNKENVKKEEPGIGAEQQANGGIVDNDVQLLEKPTKLISQ-RKTIEVNAQVQRIDFEG
RSDGESMLKILSQLRPRRVI--VIHGTAEG--------------TQVVARHCEQNVGARV
----FTPQKGEIIDVTS---EIHIYQVRLTEGLVSQLQFQKGKD--AEVAWVDGRLGMRV
KAIEAPMDVTVEQDASVQEGKTLTLETLADD-EIPIHNSVLINELKLSDFKQTLMRNNIN
SEFSGGVLWCSNGTLALRRVDAGKVAMEGCLSEEYYKI----------------------
--RELLYEQYAIV
>gnl|BL_ORD_ID|1401 @Homo_sapiens@ gi|33946297|ref|NP_892021.1| zinc finger protein 326 isoform 1 [Homo sapiens]
MD----------------------------------------------------------
--------------------------------------FE--------------------
-------------------------------DDYTHSACRNTYQGFNGM-DRDYGPGSYG
GMDRDY------------------------------------------------------
-GHGSYG--------------GQRSMDSYLNQSYG-------------------------
--------------------------------------------------MDNHSGGG--
----GGSRF---------------GPYESYDSRSSLGGRD-------LYRSGYGFNE---
---------PEQSRFG------------------------------------------GS
YGGRFESSYRNSLDSFGGRNQGGSSWEAPYSRSKLRPGFMEDRGRENYSSYSSFSSPHMK
PA---P------------VGSRGRGTPAYPESTFGSRNYDAFGGPSTGRGRGRGHMGDFG
S-------IHRPGIVVDYQNKSTNVTVAAARGIKRKMM--------QPFNKPS--GTFIK
KPKLAKPMEKIS---------LSKSPTKTDPKNEEEEKRRIEARREKQRRRREKNSEKYG
DGYRMAFTCSFCKFRTFEE----------------------KDIELHLESSSHQETLDHI
QKQTKFDKV---------------------------VMEFLHECMVNKFKKTSIRKQQTN
NQTEVVKIIEKDVMEGVTVDDHM---MKVETVHCSACSVYIPALHSSVQQHLKSPDHIKG
KQAYKEQIKRESVLTATSILNNPIVKARYERFVKGENPFEIQDHSQDQQIEGDE------
EDEEKIDEPIEEEEDE-------------DEEEEAEEVGEVEE--------VEEVEEVRE
GGIEGEGNIQGVGEGGEVGVVGEVEGVGEVEEVEELEEETAKEEPADFPVEQPEEN----
-----------------------------------------
>gnl|BL_ORD_ID|1223 @Saccharomyces_cerevisae@ gi|6320546|ref|NP_010626.1| Fcf1p [Saccharomyces cerevisiae S288c]
MGKAKKTRKFGLVKRTLNTKKDQRLKKNQENIKTK-------------------EDPELT
RNIPQVSSALFFQYNQAIKPPYQVLIDTNFIN---FSIQKKVDIVRGMMDCLLAKCNPLI
TDCVMAELEKLGPKYRIALKLARDPRIKRLSCSHKGTYADDCLVHRVLQHKCYIVATND-
-----------------AGLKQRIRKIPGIPLMSVGGHAYVIEKLPDVF
>gnl|BL_ORD_ID|24784 @Takifugu_rubripes@ jgi|Takru4|739292|fgh5_pg.C_scaffold_269000014
MGNGVTAPRKWREVCEGGSAPYWLWQPQQVGLMGNQKDQFVLSHIIREFLHPDLEANFVK
RCRRRLIKSIQPVDAIVDALREVGVLNTANLEAISIHADQREKQRILVDQVLWKGNKAQD
AFFLALARSNPFVLQELDRRALKNQGFSEGSIQEDLVDFLVPDEEKWFHWVLRDHLMEGD
SNQPRTHGPLQKHFGFKQLDTITKKVLLKIVPTLSRSPKRAADAPASHLNANANARHHPA
AGTCLEKEELVTSESSSAMTTEKNL--EPEVEVSPDVFEDGDMFRLQCEHQGLFHCRLTG
LRLEGVGDVLYQLVPWDLDFLSSKGLRPAGPLFRFTLLSGRFHRLHLPHCQLLEDVAEGG
QHFLSVVHATEERVDFITPSHVTQSHVIVDVPGFSCFGLVTGRRNNSAIRGLVVLFSEIR
QHLLFVLLLPRNIFLTQVIKEWKQRIGAKYVETVPDCELIPNHTYKLSGQPVTLIQPETS
EFVNFSDYSNFLPSFQVQLPDGATSVKLQLSSPEAALPLIGWLFRSTDSVTWERVVQLRA
HTGQPEELCPAVAMEEPMHTTLILLQMLQSLESKDFLLFHYHLKLRPNPIPVSRLENADR
PRTVDLMVQQYQPEGAKQVTEEIFRMMKFEDLADQLRA
>gnl|BL_ORD_ID|6167 @Trichoplax_adhaerens@ jgi|Triad1|451|gw1.1.45.1
FDAFQQASTLTDTLDHFQRLCQELKLHNDHLRPCRHFYNQLKKKLTSWKCTALWNKYDKK
MADRAITGAKNTANTHVLIVGAGPVGLRAAIECAMLGCKVVVVEKRNHFSRNNVLHFWPF
IISDMKSLGAKTFHGRFCSGSLDHCSIRQVQLILLKIALLLGVNVFINVTFNEMRQPTDK
NLVWTADITPADHIINKYQVHALINAEGCRTRLAGFHRKEFRGKLAIAITANFINYQTKE
ESRVEEISGVAYIFNQGFFNDLRNSKGIDLENIVYYRDNTHYFVMTAKKKSLLLKGVLKA
DYSDVNKLLSTENIDQIALQNYAKQAADFSTRYQ---LPKLEFALNHYKK--PDVAVFDF
TSIYAAEH------SCRVIERKGQPLLMQLAGDGLLEPFWPTGSGCARGFLGAYDSAWMI
RGWSALISRKRADCIELIRQRESVYTLLAQTTPNNLQKNITKYSLDPNTRYCNLNIKAIP
ATVVQFLYDDGSDSTDNPSKKMSKSPSMIAGITTHELLGWCSNCTSVYKNINIVNMTTSW
KDGMAFCAIIHRFRPDLIDFDSLSPDSVEENLNLAISVSDEHLAIAPTFNPNELIELGGA
DPLSIMCFVAKLYDVFKNEKP
>gnl|BL_ORD_ID|5726 @Ustilago_maydis@ jgi|Ustma1|5727|UM05727
MVFIVKIPNRSRANTPEASNTPTNQTVSSPPQALQTAAIDIVQTTTPPSRTEAVASMDYV
AAPPTGVLPGTSSTRAVRTAASTTSAQSAAELDILLAPSVLKHRYVRGVDKSLIVERPER
IRAVLLGIATAIGKSSSEQPHDPTMALHTSQRSPSKAPSQQQNTIHLASSIDSSVARTTT
HVSCAPLPANTPSQQDQDDDLVARLSSLSVQATAAQHPTSPAQQKFRVLHSTRSLPLDPP
HPAVAFTHAHSDEVVSLLETAYGQARQKRREARTATSTCTQASDALIDASQFKPERETTP
TPASVAAGPPSQQQAASSLSPARTSHAAYLEYLCNKAPNHPPQSHRKPHQTSPSKSIPED
SETYTSSDGEGDDAMHLSEVPEHLPQGDLYLAGPSDQSGMDGGSAEAIRHAMGACCEAVD
RVVSAAASTTMASPTLSPLREIKVQDSTHLNVTESLASNDDNETAPAAKRAFVLSRPPGH
HCSGSTPQGFCWVNNAIVAAAHAYHEHSIDRVVIFDIDLHHGNGTQNLAWRINADANKHD
DQRTERIASLRVAALERARQALGSGSGRAHASRLAKVALTEHDEAEVKRQAGPRALRLFY
SSLHDIESFPCEDGDPGMIKDASTCVEGAHGQWIWNIHLDHYRTESDFRRLYDDKYKIVF
SKAARFLGATCATQQNTLVLISAGFDACAYEYPGMQRHGKHVPPSFYHMFARDAVHFADA
HADGKLVSVLEGGYSDRALCSAALAHVTGLAVRVDSAASSVVGGEAETEYWKLENLIAVE
KVAKKMAAHAAAAVSGAAPSTNTTPKRRQAELAPWLSLTSKAFAAFEQACGKGNVVPLGI
GATPSTRSSATTNTTNSPAIGAGGRVLRDRGALRTRPGAWESATSTPHARRAASPTKTAG
RKDSPIKKESPSSVTSVGGVVDASATPVMADTQRGLVDDSMSMDTDTPTKSVTSDARVRS
LRLPSPLKSIHQSN-DNRVRKSDVEADQQRQANSTDPTIAPTQVDPSVPAAPVDTNTSTF
PSA-LSTYGNAVSTDAEVAASPSIEDTINASTTLRSRTLSSAHASLVDTSFL------AH
APMHVDAADTHASSD-------SLGQLYDNGDSWIHQHSLLGGEPDAPGSPDWSAAHACV
PSTYQGEPETQAPATLGTAVTSSEFTGAAGVENQASRQHQAPVSSSSSLYPDLAS-CHLA
HPTQ
>gnl|BL_ORD_ID|44902 @Branchiostoma floridae@ jgi|Brafl1|240123|e_gw.378.8.1
------------------------------------------------------------
-------------------------------------------------------MKKTY
LM----------------VAAIDFGTT---------------------------------
-------------YSGYAFSFMS-------------------------------SPE---
------------------DIIMNKNW-GESVGFQSYKTPTSVL-----------------
-------------------------LSPEGKFVEF-------------------------
------------------------------------------------------------
--------------------------------GFKAIAKYTTLLEENEDK--------EY
F-----------------------------------------------------------
------------------------------------------------------------
------------------------FFDRFK------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------MRLHASYQDLDRNVYLTALN
GKRL-----------PATDVFSHALRYLKQHMMKEIAKVSQTIHIGDE------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------DIR---WVI---
------------TVPAIWNDAAKQFMREAAYNANIVSKTN--------------------
--------P---------------------------------------------------
-------------------------------------------QHLVIALEPESASLYCR
ELPVNQF---------MGESAD--------------------------------------
-------GNDKLNMPPGTRYMVIDCGGGTVDITTHEI--RPDNRVKEVYAA---TGGAWG
GTQVDEQFVALIELVFGKTFIDDYRSSHPSEWQSWMESFETKKRSNTS-ESGSV------
------------------NFPFNYHFDEFHRRVKGGGVKESIDNCQVDGVRFSN-GFLCL
DDEKMRDLFKEVIDNIM--NHVEKLMQEESMSNVTYVFLVGGFSESPLLQADFRKRFSNR
VRVLVPNDASLAVVKGAVKF------------------GHTPNLISERISPRTYGIKCAS
SYDS--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------DLHKGGKVVHGR----CM
N-----------------------------------------------------------
---AFHTFVEAGEPVLV-------------------------------------------
------------------------------------------------------------
--------------GTGKKHIFYALYPDQTQAGIKVYGSYDKEVHLTSAPGVQKLGVTTL
DMPD------TTGG---TDRQLEVTFLFGDTEIDVKAVDLTTRSKANVE-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--INFLHNDIRR
>gnl|BL_ORD_ID|33430 @Branchiostoma floridae@ jgi|Brafl1|131878|estExt_fgenesh2_pg.C_5990002
M-------------------------------------ARTSGWNTTAAIVTGAACALAG
AALAGYLLSGRRPKKRTKIIEMMDELQKENVHIR--------------------------
------------------------------------------------------------
------------------------------------------------------DPE---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RVEKLLCQLIQDGKSKLQIITDFDM-
------------------------------------------------------------
------------------------------------------------------------
------------------------TLSRFS------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------IN
GKRC-----------ATCHNVLENSSLVPESKKQILDELRDT------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------YYP
IE----------INAKMTIEEKIPFMMEW--------YTK--------------------
--------G---------------------------------------------------
-------------------------------------------TGVLVECGLKQSDLSLA
----------------VKESNA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------RMRDGCD
W-----------------------------------------------------------
---QFHTLHEHSVPMLIFSAGIGDILEEIIKQ----------------------------
------------------------------------------------------------
--------------------------HSQMYANMRVVSNYMDFNHDGMLVGFKGDLVHTY
NKNEGALRNSDYFT---TLKERRNIILMGDSMGDLRMADGVPNMQHILKIGFLNDNIEER
LEKYKEAYDIVLVSDDTMDVPNAIMKKIL-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------
>gnl|BL_ORD_ID|886 @Ciona_intestinalis@ jgi|Cioin2|241581|estExt_genewise1.C_chr_06q0331
MRNLSSLRCLFCAYPKNKFLSKYFSNQVHTEAEQIIKEKRVIFSGIQPTGIPHIGNYLGA
LKHWVELQNES-DDIYYSIVDLH----SLTIPKSRDFMQDSIFNITACLLACGVDPDTTV
LYQQSSVPEHTQLSWVIGCIVPVNRLKHLPQWKEKLESSIDGGGHIGRYTYPVLQTADIL
LYKATHVPAGSEDQAIHLVLTNEFAKSFNRMHGNFFPETQMISNPTFARIRDFRDPRVKM
SKSSPSINGRIELTDTDSEIRLKIKRAVTDSTSQVTYDPENRPGVSNLIQIHCGMCDITP
EKACSLACNMDTGKYKSLVADAVIEQLSPIREKYLKIRKDEVKLKMVLDHGAKRARVVAK
SNWESIRELLGINIAEIS
>gnl|BL_ORD_ID|4579 @Cladonia_grayi@ jgi|Clagr2|118970|estExt_fgenesh1_pg.C_80106
MGNDAAASVTGGDDYKGLMQQWLDTNGSSYVDFTRTCTGERGIDREEGFVSQFYSTCLEA
FQQMCRQEQQRYAPGARSYLLEEELGKLYLWGETFGPGELDKALFESEEIRDNVLDLLVN
LGELVIRELRASSTIARPGQIHQLESFIEQTRLIMSAVDGQENLDGLAGDAECLDRDDYS
DDDIDDFCEDVAFTIKCLMELGPSLEQNLASARRSDLSIFKSASVLHCPSEPAEFYVSLV
REKFRQASEGLVKRLGEANWQRHLKVRNMMEDAKNNPAKVQDTARSTFHDSGIGTSVPVR
TQYAPSHTSFRTSNTEGGPRSLRVPPTPLEAAQGKPFQCFLCGDMLSTIRTRTQWKMHVF
SDLMPYICTFDGCQHELRSFPNRSSWADHEFQDHRYNRSWLCPECPRESCSTLDWEHHLN
DVHNQKLSGPNLVAARNIFYRITPKRAEEEECPLCRVVLGEPRRAFVKHVSRHMEDIALK
ALPRNADEDSETSSVDTNHALVEDNDTSKDGFGDDNGNTVYSERDDMGDALILGSPEAER
PYVLRSVSPDDSPPAERSPTPVGMSKLKERRRRPKTRASQGDAALIGFMGGLNHPDLASK
AGEEPLPRESDESGDEDEVGSESGPDALRPLFATASHSKSDKSPREHQAGEEPLPLFNTL
HKFQPSQNSASPGHERTYQACILPVPDVVERVRSATSKRKAEDDESDMGGNEHIRAPIID
H
>gnl|BL_ORD_ID|18167 @Drosophila_melanogaster@ gi|281365428|ref|NP_001097473.2| Stromalin-2, isoform D [Drosophila melanogaster]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------MSDISFDDAVLND
SQASNQMDFEI--------------------------------REECSIAPNDEPVCVDG
TVGDATNKSLLQMILSRKRLSPTNKRNSHIESVAKYWGEFYLDSPTAALVALLQF-----
------------VVEVSGSHYQIPDDTSMP--FSYSDILSNSSSHFSNTHIYPLIRKPAD
VFVNQVGSFLNALLLVANKFRSDSYQLFLVQLTNFVMA----------------------
------------------------------------------------------------
----------------CSESNI--------------------RTFRHTATM---------
----IGLKIMTILSDLKSLDD----EIAMTVWMQMFNSMFVARSRDIVTDIRLLCISELG
QWFARYPHCHLQPTSLRIFYEALNDGS----------------GDVIQCSLDNIS-----
---------VLCRKDVLFSEIVALTSEFREILVELCLGKEDAIAEKSVQFLTHFHVLSAE
I--LTDDVCRVLEQLIMAANRGLAQAAADLFILRRNGLDGETFCQ--RVKHLLQLFIECG
HEQA--DYLVDSLIDN--------------------------------------------
--------------------CELVLDWKS-----------MIAVLLENPKSRELSDIHC-
-----SSLIAILLAGVKQATAGEIPPGRYTKDLKREPRQGAQERATKCLAPVLPELLRTY
ANRLQDIERLLELPKYFCFDYYHEQNRMGQLNELVEHFELIIFDQTSSTTVLQITVKTLE
FLNRMIPIPLTKQLLNSAVTNYKMAWHRTQDTSPSRSTHNESNRLLATLRLLTV------
--LSGHFNLSKWDLTEPLLFSLKMLLRQRRLPNGDDLPPEAFSLYLKACFCCLCWDMENL
EGTALNNVDMDEYCDVLHHNLEDYLYVTFSLVGKSNTEPLAYPCFSYTCD-LFVLHGN--
---LCGSSN-------------PSIRSVAHVPSGNELDILEGFLMEHFLELSPSDLMLET
NSDQLQRIRSILTSYLKVVCLGVVPTMRASKFYEYYVKYHAPFGDVMRCSMELALQRNPI
HFAMTMLHTCLLLYAKVFPDDTRHAAGQRALRPAEFSELMELANRLAKILISNPMEHREC
V---------------EQQRTEHSNLAHQFRVTDCENRYAMAIAFHGPARLTDLWPQICD
PPTEYLITDVLTARSDRPRLRFNEICARPLDARLHRNHRAEISPSTICWT
>gnl|BL_ORD_ID|18168 @Drosophila_melanogaster@ gi|281365426|ref|NP_612109.3| Stromalin-2, isoform C [Drosophila melanogaster]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------MSDISFDDAVLND
SQASNQMDFEI--------------------------------REECSIAPNDEPVCVDG
TVGDATNKSLLQMILSRKRLSPTNKRNSHIESVAKYWGEFYLDSPTAALVALLQF-----
------------VVEVSGSHYQIPDDTSMP--FSYSDILSNSSSHFSNTHIYPLIRKPAD
VFVNQVGSFLNALLLVANKFRSDSYQLFLVQLTNFVMA----------------------
------------------------------------------------------------
----------------CSESNI--------------------RTFRHTATM---------
----IGLKIMTILSDLKSLDD----EIAMTVWMQMFNSMFVARSRDIVTDIRLLCISELG
QWFARYPHCHLQPTSLRIFYEALNDGS----------------GDVIQCSLDNIS-----
---------VLCRKDVLFSEIVALTSEFREILVELCLGKEDAIAEKSVQFLTHFHVLSAE
I--LTDDVCRVLEQLIMAANRGLAQAAADLFILRRNGLDGETFCQ--RVKHLLQLFIECG
HEQA--DYLVDSLIDN--------------------------------------------
--------------------CELVLDWKS-----------MIAVLLENPKSRELSDIHC-
-----SSLIAILLAGVKQATAGEIPPGRYTKDLKREPRQGAQERATKCLAPVLPELLRTY
ANRLQDIERLLELPKYFCFDYYHEQNRMGQLNELVEHFELIIFDQTSSTTVLQITVKTLE
FLNRMIPIPLTKQLLNSAVTNYKMAWHRTQDTSPSRSTHNESNRLLATLRLLTV------
--LSGHFNLSKWDLTEPLLFSLKMLLRQRRLPNGDDLPPEAFSLYLKACFCCLCWDMENL
EGTALNNVDMDEYCDVLHHNLEDYLYVTFSLVGKSNTEPLAYPCFSYTCD-LFVLHGN--
---LCGSSN-------------PSIRSVAHVPSGNELDILEGFLMEHFLELSPSDLMLET
NSDQLQRIRSILTSYLKVVCLGVVPTMRASKFYEYYVKYHAPFGDVMRCSMELALQRNPI
HFAMTMLHTCLLLYAKVFPDDTRHAAGQRALRPAEFSELMELANRLAKILISNPMEHREC
VIALHRSGILFVFELAQKQPTEATKKLPFLRVLKV---FVPLLLVQDKTRILNFF-----
EPYEQLIIPTCN-RNDIAHLKEYRNALRPRKTKSY--------PQA---T
>gnl|BL_ORD_ID|3050 @Drosophila_melanogaster@ gi|18859667|ref|NP_573160.1| CG9634 [Drosophila melanogaster]
MAINQGKYKPSICAIDEV------------------------------------------
------------------------------------------------------------
-------------------------------------------DDRSFKLHNSQDEIGGK
QQLQQIEGSETAPLTTNQQKLHMDDGSHLTPKDLEAARQDALNEVAAGGAGGRTPAAITP
NSTHPSANGLRALLLPGRRSFDALMSLSRKRRILYVTTACLCALLLLIIILLLAFWPEVP
FYLRAPLCLDKECVESSRQLLLWANTSKSPCHETYEWACGNFASDYANHEYFVIKRGEWN
YETYNEYQELNELNRFIAMLPNSQEGSVESTVSSLYRS----------------------
------------------------------------------------------------
----------------CRETDVLDKSQSDLLLKRAINAVYGWQAFRDSNRLQSWEYKRVL
VVLQAKHGIFPYYRVTVENGFSNPHDYVITL-----------------------------
---------DEGELGLPDKYFYGNDAD----------------EEVVR----GYK-----
---------LLLRDFAINMGIVSREADLF----------ADDIFHYERRIVNHIEDAKAD
ANRPINKLMRLADLKIKAPSLPILESLQAIFPKTKITEDTEVLVRDPEVMHALSVLLSTS
DKKPINNFIVWSLARKMLPHLSKEYRTLAETFDHALYG------------------RTAS
YPRWLIC-------------SKVVRDWLPFAVDALQQQPPRQQFETMTSKSRGLNKTQGN
-----EELLKLM-----------------FFSLRNQLKDSLEQ--AKWLEPAARQFIQKK
LNEMR-------------LQFGIPDEVLQQPTYLAQYYNELILNNV-------FFVEHLE
WIWTFRRSQMEKKLGPLAILDVIVSEMYTRDNPQAIAYSNKLNMLLVSKVLISSNYYDYR
YPVAVNFARIGTDILEALIDNFSTFLLQFNTQSTDISDAAPEIRYAQPDVNCLAAGQPPR
LVHELNE---------LSSNALKSFHVTLS---AARTAARALSNFVNAIDAGSAIQGS--
---GIDQANTYEALGLTRRLRIPGLRSF------NENELFTLSYMQQHCSTTIAD-----
--KDYARIKPLVESQL--------------------------------------------
--AESYLFNATWQHIQFLPRSTNCAAAE--------------------------------
------------------------------------------------------------
-------------------------------------------ATCSNLL
>gnl|BL_ORD_ID|19759 @Homo_sapiens@ gi|22749527|ref|NP_689992.1| GLIPR1-like protein 1 [Homo sapiens]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------ALKNKFSCL-------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------W-ILGLCLVAT
TSSKIPSITDPHFIDNCIE----------------AHNEWR---GKVNPPAAD--MKY--
-------------MIWDKGL-AKMAKAWANQCKFEHNDCLDKSYKCYAAFEYVGENIWLG
GIKSFTPRHAITAWYN----ETQFYDFDSLSCSRVCGHYTQLVWANSFYV----------
-------------------------------------GCAVAMCPNLGGASTAIFVCN--
------YGPAGNFANMPPYVRGESCSLCSKEE---------------KCVKNLCKNPFL-
----------------------------------KPTGRAPQQTAFNPFSLGFLL-----
------------------------------------------------------------
---LRI------------------------------------------------F
>gnl|BL_ORD_ID|18720 @Nematostella_vectensis@ jgi|Nemve1|209342|fgenesh1_pg.scaffold_104000043
M---------------------------------------------------YNAENTRS
K-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------GAS----
-----------KHCAWGVCKSDSR---------------------------YPEK-----
----------------------LPEG-TNFI-----RFPKPGNVKDGMTEWEKGQ-----
----------------QILKTEKAKRW---------------LHACGRKDFSKISDIKKD
TYICTLHFMEGKGPTEDHPYPVLATLTEKEQNQRATRAKTRSRSRKRRENPIEETGASKK
HQQESSCFPVPGDPEEQSEDTSVLFESGLPGPSRASLESQDQGRTDKETQTVYCKCTLGA
KVETMIYRNRLIQEGIGLFPSEQKEVNLMSSEIIIADDKKCKYFTGLHTEQFEALFEFLG
PAKYELSYWDGPENIEKGSLARGEPQGISVKEQLFLTLLRLRRGFNIATIAHM-------
YSISNTVVRKFFVTWI----QFMFCHFKEFEHLMFPSRQALRTFLPKVFQKFKNVRCSVD
CTEF----FCQTPSNYGKQQQGNMFSSYKHHNTMKCLIAVTPNGSACFVSDLFEGSIDDV
SIFRESGILKHINP--------------GDAI-------------LVDKRFTVQDLLFNK
QATIHIP----PFLGKRD--CLTKEEELATKRIAKARIHVERFNERLKKFRLIGNIIPLN
LSSIASQLVYVSCCLVNFQPCLCK
>gnl|BL_ORD_ID|1041 @Saccharomyces_cerevisae@ gi|6320363|ref|NP_010443.1| Sac3p [Saccharomyces cerevisiae S288c]
MNTSFGSVVPSTNFNFFKGHGNNDNTSANSTVNNSNFFLNSNETKPSKNVFMVHSTSQKK
SQQPLQNLSHSPSYTENKPDKKKKYMINDAKTIQLVGPLISSPDNLGFQKRSHKARELPR
FLINQEPQLEKRAFVQDPWDKANQEKMISLEESIDDLNELYETLKKMRNTERSIMEEKGL
VDKADSAKDLYDAIVFQGTCLDMCPTFERSRRNVEYTVYSYEKNQPNDKKASRTKALKVF
ARPAAAAAPPLPSDVRPPHILVKTLDYIVDNLLTTLPESEGFLWDRMRSIRQDFTYQNYS
GPEAVDCNERIVRIHLLILHIMVKSNVEFSLQQELEQLHKSLITLSEIYDDVRSSGGTCP
NEAEFRAYALLSKIRDPQYDENIQRLPKHIFQDKLVQMALCFRRVISNSAYTERGFVKTE
NCLNFYARFFQLMQSPSLPLLMGFFLQMHLTDIRFYALRALSHTLNKKHKPIPFIYLENM
LLFNNRQEIIEFCNYYSIEIINGDAADLKTLQHYSHKLSETQPLKKTYLTCLERRLQKTT
YKGLINGGEDNLASSVYVKDPKKDRIPSIADQSFLMENFQNNYNEKLNQNSSVKPQINTS
PKRVATRPNHFPFSQESKQLPQISQSHTLSTNPL----LTPQVHGDLSEQK--------Q
QQIKTVTDGGSPFVFDQSAQNSTVEASKAHMISTTSNGAYDEKLSSEQEEMRKKEEQRIE
EEKTQL-KKKQENADKQVITEQI--ANDLVKEVVNSSVIS------IVKREFSEANYRKD
FIDTMTRELYDAFLHERLYLIY----------MDSRAELKRNS---TLKKKFFEKWQASY
SQAKKNRILEE--KKREEIKLVSHQLGVP---GFKKSTCLFRTPYKGNVNSSFMLSS-SD
KNLIFSPVND------EFNK-FATHLTKI--SKLWRPLEMQSIYYDNLTKKFPSNSLTPA
NLFIYAKDWTSLSNRWILSKFNLQTAQDSKKFSNNIISSRIICIDDEYEPS-DFSD----
-----LQLLIFNTGVTNPDIFDLEMKLKDDGEELIKLITGISLNTNICFSLLIIYWE---
SAENTLSESTIKHLLK---LNRISKNYSSVIERIDLMNLTEESPHKCLEDKLS------E
ISHSYVYKLT---ERGKYDKTL--------RQKRSLAGIHSRSTQLQTTKDIDQKMKKML
EKEKNKYQQQI----------GERNTYAHLESHIDASPRSKKRKLPILLSTSHSSQFKTP
LASRLNTSGSSTSPPLPSHLAM-KFRKNSRVT--SLHTVLPVSTPSHSNNIPAA------
---------SFSG---NNTTDIQSQQLIENQKSTSVYLNNVSERILG------NQEICQT
PINPVTPVLDGA---------DQGKEDIPDSILELKILIDSVKKK---------------
--------------------------------------------------------VNND
>gnl|BL_ORD_ID|8974 @Takifugu_rubripes@ jgi|Takru4|733980|fgh5_pg.C_scaffold_142000021
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------SNHTHWRENI
RS----------------------------------------------------------
------------------------------------------------------------
----------------------------------SEVKSRE-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
TQSHANADGQTTCPEDTC------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----HVPPLVPPSLFLFCRDAANARLNEVQPVRSR------------------------
------------------------------------------------------------
------------------------------------------------GVPN--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------LHHPNSINLVI---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------RHHTGFKNVIYTFHLSPTSFDQ
DL-----------------------------------GLTKADKVASLHPRADVCRTYPD
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>gnl|BL_ORD_ID|18438 @Takifugu_rubripes@ jgi|Takru4|710469|fgh5_pm.C_scaffold_49000035
MECEWKP-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------DEQGLQQILQLLKES----------Q
SPDTSTQ-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------RTVQQRL-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------EQLNQYP-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------DFNNYLIFVLTK--------LKSEDEPTRSLSGLILKNNVK
AHYQNFPNGVSDFIKSEC---------LQNIGDSSPLIRATVGILITTIASKGELQNWPE
LLPKLCLLLDSEDYNTCEGAFGALQKICEDSAEILDSDILDRPLNFMIPKFLQFFKHNSP
KIRSHAIACVNQFIISRTQALMLHIDPFIEASLNLFALAEDEEPEVRKNVCRALVMLLEV
RLDRLLPHMHNIIEYMLQRTQDQDENVALEACEFWLTLAEQPVCKEVLCG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----HLSKLTPVLVNGMKYSEIDIILLKGDIEEDE------------------------
------------------------------------------------------------
------------------------------------------------AIPDNEQDIRPR
FHRSRTVAQQHEGDGIEDDEDEDDELDDDDTISDWNLRKCSAAALDVLANVFRDELLLHI
LPLLKELLFHPDWVVKESGIL---------------------------------------
------------------------------------------------------------
------VLGAIAEGCMQGMIPYLPELIPHLVQCLSDKKALVRSITCWTLSRYAHWVVSQP
PDTYLKPLMTELLKRILDSNKRVQEAACSAFATLEEEACTELVPYLAFILDTLVFAFSKY
QHKNLLILYDAIGTLADSVGHHLNKPEYIQMLMPPLIQKWNQLKDEDKDLFPLLEATTAL
QSGFLPYCEPVYQRCVNLVQKTLAQAMLYQSQPDQYESPDKDFMIVALDLLSGLAEGLGG
TIEQLVACSNILTLMYQCMQDKMPEVRQSSFALLGDLTKACFQHVKPCIADFMPVLGTNL
NPELISVCNNATWAIGEISIQMGPEMQPY-------VAMVLHQLVEIINRPNTPKTLLEN
TAITIGRLGYVCPQEVAPMLQQFIRPWCSSLRNIRDNEEKDSAFRGICTMITVNPGGVVQ
DFIFFC------------------------------------DAVASWVNPKDDLRDMFY
KILHGFKNQVGDDNWRRFA-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------DQFPVPLKERLAFYGV-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>gnl|BL_ORD_ID|9425 @Trichoplax_adhaerens@ jgi|Triad1|58691|fgeneshTA2_pg.C_scaffold_8000239
M--------------KKSPSNKVFPGDALVNNYLTADKEADVHDNFRDSMTNSSLYATTT
LPSVTRNQAVFIQHGSHMQ--ALLGLKDTEKATFYYKESCNQLEVTAMKKDLGGVLIQLN
EIIGNIKQKDHHLPELLCSYFRSDLARIYKFNDILRNSNIDAVGTISEGERFHVLSLTLE
DLSKASQLLCDKYSSVCLEVKGNISHSVYSSNVTVEFEHCYRIKIEFEHYNGNPANTTDI
KMAGYIDDILHASQNIYALVEKLKGS
>gnl|BL_ORD_ID|2873 @Ustilago_maydis@ jgi|Ustma1|2874|UM02874
M----PQSALTPNTP---------------------------------------------
--------------------------------------YRACKAEDRRSGIIYLDDDEHT
HLDDVKHVG-------ARDRPS--PKRSITDDQDASTA----------------------
-----------QKRSRSGPSAAS-------------------------------------
-------------ISNVSGG------------------------LPSGSR----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------LPQ-----------------------
------------------------------------------------------------
-------------------------------------PTSSG------------------
------------------------------------------------------------
-----------------------------------SISQTPRKYPP--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------LGSSQT---------------------------APPQYDSQYDKYS--
----------------------------------------------------EDELRIDF
AAKEQILRGR--------------------------------------------------
----------LAQLQTLELGW-----------------------------HGPEAWYQKH
EAFER-----------------------------------VHEMQKKLAH----------
-----------------------------------------------IAW----------
-----------ALGAKEFGAVPAPSLTSATTPGHTAENTSRRSTPVR-------------
------------------------------------------------------------
------------------------------------------------------------
-------SLPAN--------PYSDSAVRTTSSS---------------------------
------------------------------------------------------------
-----------------------FQILGDNMVSAARKPLASPVTTSREQTP-----SSTA
SKSNSTAPLRVLRDPSH----------------------ILHASDDIVSANENSTDLPEI
VDN-------SIQHRTQADEAPSVATSAVNVDDQDGFLQGSLSADRRDQPIVNAQIYELS
DDDEDDVEAMPVEEKFKLCGPSMQEPMSKDQLRSMPHYPWTTQVGYVLKKFFKLKRFRRN
QLEAINGTLS----GRDVFVLMPTGGGKSLCYQLPACIDTDKATGVSIVISPLLSLIEDQ
VLDLVRKDVPAVKLTGDMSANDRRDAFNTARDRVGSLRLLYVTPEFIRQSNQAMELLDLL
YSQKRLARIVVDEAHCVSQWGHDFRPHYTELGALRDKYP--------QVPIMALTATANA
RVIKDVKSCLKMRNVLQLSSSFNRPNLEYQVRKKPKSKLIDEIASFILT-----SHKDEC
GIVYCFSRESCETVADDLKKHGI---------TAHHYHAKLGKDDRSKVQQRWKNGEYKV
IVAT--------------------------------------------------IAFGMG
I--DKPDVRFVIHHSLPKSLEGYY-QETGRAGRDGLDSVCILY--YSWTDVRRMENMMLS
EEKSQEAIDRSIDSLREMQRFCENEIECRRV---QVLRYFGESGFTSEQCR---------
--------STCDNCCR-------QSGAIYIQDVTELAVKAI-------KLVKAIADKGGR
WTLPHCAEVFYGHRTKKIREAGHDKLEMHGAGSEIAKVEIHRLFEHLCSEGVFKLKDVMN
RAGFNTS--YLMVGSAADKVLNGQKAIKMQVAAKVSAASSSLNNGRGQNTRKQQRQ----
--LRDEDFAEFDEDAHDISNVSLTPPSRVEPQAG-----------TTDGSLDDDNWIPEE
MFTDNFDLDADTDDDAPLAADNQAANGSR---------RVVSNAAG--------SDDSAD
DFE------IDPRSSDVNQGCYR-----ELKKLDDRL----ARQEKQSRGWLIRDDKLQE
ISVLAACSIDALSSCLRGTDGARWVQKYGSLYIEICQRFLQ----TERRAPDVGRTAATG
GTGRRSTLARNAEAEPTANTPKSSATAGLRKER-------AAPRKSALAA-AASLGQYTY
QDPDTRATRSRGSGA---------------------------------------------
-----------------------------------------------------------S
ARNASR------------------------------------------------------
------------------------------------------------------------
--------------------------ATSGNGRAAHASSNSTADS---------------
-------------------RVSATAAQA------------------------PQPLKRIT
LHRGF-------------------------------------------------------
-------------------------------------------LGGANAT----------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------PAIRPMPLASSSTPNL
PRSG--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>gnl|BL_ORD_ID|2488 @Ustilago_maydis@ jgi|Ustma1|2489|UM02489
M-----TPITTPSSTDV-------------------------------------------
------------------------------------------------------------
-----------------RKRP-----------KANSHSLI--------------------
------------------------------------------------------------
--------------------------------------------VPGNVDR---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------HAALCE-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------QLRNRQ-------------------
------------------------------------------------------------
-----------------------------------------------ITDL---------
------------------------------------------------------------
----------VDVSGSGT------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------GTRGW---------------------------------------
----------------------------------------IWGTITDIFY----------
---------------------------------------------YLFVW----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------IPRTWWYTLTSLP---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------QLVLDP
IGL---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------GSALAFAFVTTFAL------FGSLVVSA
IWRLPFVQSYWQPIS---------------------------------------------
---DRKDI----------------------------------------------------
------------------------------------------------------------
--------SLGNLAYPLIFEFDANPQNKQIRDAAFKVMSDPMQAD-----AKPSTDQERN
FDLEI-----------SKLLMMLSAL------VYERKVGAYHKAALLAQQGKKLNKQFMC
DDKVLTDAGIDIGQKVDFADSKIKRVAREWGLNYASVSELATNTSPLCGAFWHPYHNFII
LAFKGTDPVEFKEWAVDLTFNYTDGRGWLPGFTKVHAGFYKQIFPQDLNHATGAFPY-SQ
IRNAVSKIASEIRATSDS---DHVNLYVTGHSLGAGLASLFYTRAISSPKDFGQTEDGAN
QVFVRDAYCFGTPIVGDPDCISAFNQACHERDLDFPHALWRVTNRRDAVATMLPDA--GD
NNTLVHIS-------------------------PLSQLHFAHIGQEIQLDNDVGKV----
------------YTGPGTSLPVGTPVN---------------------------------
------IITHLHQGGEGPKVSLPPVFSLLEWIPVVRRLVAHTPSSYWDRL----------
-----------------------------------------------------------T
KVQAEN------------------------------------------------------
------------------------------------------------------------
--------------------------------TIEYARSH--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>gnl|BL_ORD_ID|5504 @Ciona_intestinalis@ jgi|Cioin2|259749|gw1.26.107.1
SGSTTVMLAANPKLTSIEVEAIIKQKLWENMEPLKQAFQLYDADRCTNVTKGEFRRVLEN
YCLPMTAEQFNALVVKIGTNPNGTISYLRFIDKFVPSTPILLYINSFTPTGIDTIERFLQ
QKIAANLKNVIRSFKLFDYNMDGLVQRHELRRVIENYCLKLNDSQFNKLWSRYDFQHTGA
INYRDFLRRLGVNAATAERHMRLEREKSVTDLILDRNKDKKKRKSMRSEMMKMEDVEKEF
RKKMKNNYQNIKRALMTFDISSDGFISIDDLKAVLDNFVLPTSDEIFHQLMYKFEVRGTG
KVSWEQFLSKFQDPQSNGNGQTIPIGQNHKVGCALDNSSTPDVIKKLKDHILNNFATLKQ
AFLAFDENHKGVIGRKDLRRIIETFAMKISDENFKELQVYLDPQHTGFINYHSFLQLFES
REHVTAHKWLFSTHKFNENQSPAILAWNTVEEILREKLSENYRMVADEYSALDTTGDGRI
SRTHLRRLINRYALPVSDEHFNKMWSACEGSSEGRICFARFLDNLNIDVQPGDLEGTSKR
IQEESSEREERRVILLILISSRSRINEIDKADLRHTNLLSASEVVRRLKDRMLQHDAGIR
KSFLRFSRSGKDRVTKKDLRKMLDDIGLRMEDSQFKELMKMLHVNGRGLLYSDFVESFQD
PRTDGMGKVRRQFRNHIVNPTNVRYMTAQECYDQLLERMRQNFGSVRSAFYKVDDDHDGN
LTMTEFRRLLDSFMFIITDQTFHELLRMLGLTKRSSLSYHDFLNKFEVVDKEEGHPWLNI
SPPYRYNRPRSATELAADQVHQCLCLKAEQAWSDLAKAFQNFDADGNGIIKKKELRSVLF
RFILPISHAEFNKLWSRYDEEGKGFISHQDFTRKLGVGFTTGDNLGMLEMSKNKMGFFQP
QKMFCQIKKKCEIGPQRMIPVSYRFREYYSDFDKAFRQLDKNRDGYITIADLQRVLLQLN
YFLDEKQFLDLLRRLGLPTTKSKLSYFDFLRSIDDGRASKYGRRDVIGRESVTWQSFESL
TVEKATIKLKEQVTVNYDSLNAAFRAFDRLQTGLVKVVDFRRLLDNFCFKLTDKQFRGVL
LKCRITGGSVSSNKMINWIVFLQDFSQIKDVKLKEWGDYVGKIAPPQSPHELPLVEVEER
ISEVVTARHFQISRDFADVDYAKIFVVSREDFRDILNRHVMRLTDDQFDRLWAKQAVNEF
NNIEYREFLKRYQLHKDDKVKQEGQTTQKPCDEIQPISNQISVPRPPSRLVSIMGNPRPV
TPLVNADSAEMKVKDLVYKSWQDIQRECKKLDLEGTGTVLPDEFVGILDSFGVMLPLEDA
RQLMLKY----------DLHEQ---QGRFS-----------YREFLRHFILTLKPQDEGL
LKRRKIHAAKLPVDTGSENSSFFNAMIGLRERVLLSWKEMRRSFRNLDQRAEGFVSPAVF
RQVLRQFSINLSEEDFYHLVSFYDHKMKGEIPYNDFIRAFLQ
>Synechococcus_7942_ClpS2
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLP-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
SP----------------------------------------------------------
---------------------------------------------------------FRP
Q---------------------------------------------TTIA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------SENVKTASKAAQPKVNSSMSPQPDESVLSILGVPRPC
VKKRSRDDA--FVLTVLTCSLQAIAAPATAPGTTTTRVRQPYPHFRVIVLDDDVNTFQHV
AECLLKYIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAELYHEQLRREGLTMAPLEAA-
------------------------------------------------------------
------------------------------------------
>gnl|BL_ORD_ID|4678 @Cladonia_grayi@ jgi|Clagr2|94839|fgenesh1_kg.66_#_15_#_isotig10838
MEEY--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------LRGCHEAID-
--------------------------------VLRAHLEKSLNGLRS-------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TGFEKRKAT
LKAYFGSRDADCQIQNIRRAMEGLSLC-HSSIMGQICVHSHRSIQGLTA-----------
----------------------QTNNLTLGTQDI--------------------------
------------------------------------------------------------
------------------------------------------------------------
RRDIQQLQHVNLRTLQGIQNLEAA-HEWMAAVQGVLPLEIRNLVRNAI------------
--AEELRSASQDQETLSNEALRK-------------------------------------
--------------QTLSLNPGIQN-----------------------------------
------------ALPLER----------PSTVPTSPKLEN--------------------
---------------TSNHQSSEHFQEMEDLLL---------------------------
------------------------
>gnl|BL_ORD_ID|47 @Cladonia_grayi@ jgi|Clagr2|72631|estExt_Genewise1Plus.C_10023
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------SAQADAC-----------
----------------------RKAMKGLGTDEAALIRVLTHLSP---------------
LEVPA---------IKQAFQQRHGRSL---------------------------------
----------------------------------------------------------EH
DVEKEVSGHFEMCLLSILRGPLQN-DVW----------SLNKAIHGAGTKEQLLDEVLIG
RSNADMRAIKEAYQKTYHRPLEH-----------DVRGDLS-------------------
AKTERMYEMILSATRQEESAPVLPQSVDADVTELYRATEAKVGTEQLTVCAILTNRSDGQ
IRAIAQAYEQKYRRPLEKVLVNEFAGHMEQALVQMVRCGADRTMRDAIALEDCMAGAGTK
DDLLVTRVVKIHWNPYHVHQVKAAYRQRYGRDLLHRIKGETSGDYERCLIAML-------
---------------------SPP
>gnl|BL_ORD_ID|11189 @Drosophila_melanogaster@ gi|24653390|ref|NP_524737.2| arrow [Drosophila melanogaster]
MALEPYTKSAEIEPQLCQVIDNNEDVTTKATKCTKSNSGVGWRQMLIGFLLICFGISNSW
QYKNVHMPSSSSLIASPPASAFVNTPATLLFTTRHDIQVANITRPTGGPQIDVIVRDLAE
AMAIDFYYAKNLVCWTDSGREIIECAQTNSSALQPLLRAPKQTVISTGLDKPEGLAMDWY
TDKIYWTDGEKNRIEVATLDGRYQKVLFWTDLDQPRAVAVVPARKLLIWTDWGEYPKIER
ASMDGDPLSRMTLVKEHVFWPNGLAVDLKNELIYWTDGKHHFIDVMRLDGSSRRTIVNNL
KYPFSLTFYDDRLYWTDWQRGSLNALDLQTRELKELIDTPKAPNSVRAWDPSLQPYEDNP
CAHNNGNCSHLCLLATNSQGFSCACPTGVKLISANTCANGSQEMMFIVQRTQISKISLDS
PDYTIFPLPLGKVKYAIAIDYDPVEEHIYWSDVETYTIKRAHADGTGVTDFVTSEVRHPD
GLALDWLARNLYWTDTVTDRIEVCRLDGTARKVLIYEHLEEPRAIAVAPSLGWMFWSDWN
ERKPKVERASLDGSERVVLVSENLGWPNGIALDIEAKAIYWCDGKTDKIEVANMDGSGRR
VVISDNLKHLFGLSILDDYLYWTDWQRRSIDRAHKITGNNRIVVVDQYPDLMGLKVTRLR
EVRGQNACAVRNGGCSHLCLNRPRDYVCRCAIDYELANDKRTCVVPAAFLLFSRQEHIGR
ISIEYNEGNHNDERIPFKDVRDAHALDVSVAERRIYWTDQKSKCIFRAFLNGSYVQRIVD
SGLIGPDGIAVDWLANNIYWSDAEARRIEVARLDGSSR-RVLLWKG---------VEEPR
SLVLEPRRGYMYW--------TESPTDSI--------RRAAMDGSDLQTIVAGANHAAGL
TFDQE---------------TRRLYWATQSRPAKIESADWDGKKRQILVGSDMDEPYAVS
LYQDYVYWSDWNTGDIE----------------RVHKTTGQNRSLVHSGMTYITSLLVFN
DKRQTGVNPCKVNNGGCSHLCLAQPG---------------------RRGMTCACPTHYQ
LAKDGVSCIPPRNYIIFSQ----RNCFGRLL------PNTTDCPNIPL------------
----------------PVSGKNIRA----------VDYDPITHHIYWIEGRSHSIKRSLA
NGTKVSLLANSGQPFDLAIDIIGRLLFWTCSQSNSINVTSFLGESVGVIDTGDS-EKPRN
IAVHAMKRLLFWTDVGSHQAIIRARVDGNERVELAYKLEGVTALALDQQSDMIYYAHGKR
IDAIDING-----------KNKKTLVSMHISQVINIAALG--------------------
GFVYWLDD-------------------KTGVERITVNGERRSAELQRLPQITDIRAVWTP
DPKVLRNHTCMHSRTKCSHICIASGEGIARTRDVCSCPKHLMLLEDKENCGAFPACGPDH
FTCAAPVSGISDVNKDCIPASWRCDGQKD-----------CPDKSDEVGCPTCRADQFSC
QSGECI---------------------------DKSLVCDGTTNCANGH---DEADCCKR
PGEFQCPINKLCISAALLCDGWENCADGADESSDICLQRRMAPATDKRAFMILIGATMIT
IFSIVYLLQFCRTRIGKSRTEPKDDQATDPLSPSTLSKSQRVSKIASVADAVRMSTLN--
---SRNSMN---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------SYDRNHITGAS-------SSTTN-----------------------------
-------GSSMVAYPINP------------------------------------------
------------------------------------------------------------
--------------------------------------------------PPSPATRSRR
PY--------RHYKIINQPPPPTPCSTDIC------------------------------
------------------------------------------------------------
------------------------------------------DESDSNYTSKSNS-NNSN
GGATKHSSSSAAAC----------------------------------------------
-----------------------------------LQYGYDSEPYPPPPTPRSHYHSD--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------VRIVPESSCPPSPSSRSS---------------------
------------------------------------------------------------
-------------------------------TYFSPLPPPPSPV----------------
------------------------------------------------------------
-------------------------QS----------------PSR--------------
------------------------------------------------------------
---------------------------------------------------GFT
>gnl|BL_ORD_ID|3583 @Drosophila_melanogaster@ gi|24643415|ref|NP_608360.2| CG32529, isoform A [Drosophila melanogaster]
MVSKKRSNAAERVQRSTATAAAAAAAAAAAATASSTQGKK--------------------
------RPGKQTKASGGGG-----------------------------------------
----------------DEADDKKSASKTDSAAKKPAKDPTGSSGVSTATTEGGA------
------------------------------------------------------------
------------------------------------------------------------
-----------------GNGGGKQTTSTTTSSTSSTTAPSASASASASNSLKLSPEERHE
DGKARAINKMLKSLDIKIHGFDNLLPSGEERLN---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------DGVLKSSISENVKTKSRAAAVKVISSLNPGKMPPVKRVRPSPEPVREKVAEKPA
EKVLDKEKPKAEQQITPPPAPEESPASKVPKKTVQQAKKAKVESSLVQATVLTTTSAATS
APSSA---------------STSKHTSTKNPGKKSAHSEQMPKKELSKLAKMGKPKKEAN
LVKSTARLPDSNTESVQMELEEIVSTPTVTPTPSATPTATPTPTATPTLTPTPTATRTRT
PTPTLTPTPTPTSTPSSTAIAAGQPAPPPPPPGGAPKQRPKVKYTKTSAGSKGRMQQALN
QKAPAASWSGAKDIYDFKSGSEDEEPIKMVLPSLKELREFSDEDNKPLKLFERQAEKTKV
QVQDEEEQPLVKKEEKPPSEKEVKVKSKEKEKEKEKDVDPLSNAQQSEPAAKHTTSTSTT
STTSITSVKKQAK---------RKIATPMPSSAGRKKKTVGKGKAAAAKEPPPSGSSAES
SSSEDERKLSAYSGPKRHRM---ASLNALAKVQCLYENESRTAHELGLSKATQQPPRIRT
LDGSDDDNHKDSPRHGDTDRDKGSVSPPHTSAAPPAAPIAPPKEAEPRRELRYVPGGRGV
GKHWEFDS-------------------DSETEELQLQQTLPPVKKKKLPK-------KAP
PKKVASSETDAKRKKKSVQVEESDDEEAKEKEKEKEKPKPPKQLPKKRKTAFTEELIGDY
KGILARKRMASLNASAIVAATYEVERHLDKNLASDCSSFESYDELDTMPTTTSKVTSAAA
IKTEVIHIKKEPKESKESLRERERERESERRRERDNELKDSTVGKMSSHSIIEESNDSKY
SKETKETNTDTTITTTGYRDSAASTKDAKDCSRPTSSSVVIVQDTDVTITGVYVNASNGA
AQEAYCKMQY---------------------RVQSSVTEERVLRPGSVEPPKSYTPLS--
---ALSSMLPPGASSGLSEAHSSPPLPVHAAPTGPHVLLPGEHLSAGMYHAPDLGLHTEH
ALPDHHGPPPPSYAAAAAAAAAAAAYHAHQLAPGGGGVLHMHHQHQYAAHAAHAHHYQQA
AEYHGGPPPPPHHYGGPPPQGHYGPPPGAPVPVPVAVPNTVTVPPERCDVGSPPPSYRAS
AYPPPSSVGMPPPTLGGGS-------SAFCAPSPLHHHQHQHQQPGPGVGPPHHDPSGYY
QPAGPLISPHVIAAPPPPAQVKKLQEEDGPVSAAGSPTQLQQQQAAAEAAAAAADQAAAQ
SQSQSQGQSHGHAHSHAHNPQQAQHPPQPQPYPAGAVAAAAAAAAAHQGVPYSRSMHAAQ
MHYSTGYPPNYYAPYPGEVMCYSPPTYPPYFSSKVYQPSHPAHPAAHPQGPPPPGAYRRY
PYYQHAGPPPPHELYEQQPPPPPVSSGSVSGPAQQQPPTSSPASVGAAGAGTAGAPSGSQ
LVPAHQQQHQQQHLEHYPGPPSYYAGYSPGGGASAGQCYTRGLQGPYMEYPPQCPCPMPQ
SCPKNVHTGPHIGSNIISNIDQSSSCSSSMLLSATSNSNIGGGSSSSSSSSSSTTLPACS
SATTTTTASALTTSRGPVKNVTPNNSNSSGHTSTNSCRSSNNSNNSSNSSCQTIEMTSWA
TAATNTTSTTATTATTGTQCQMLVKTELKGENPQVTKMQYEAHVMPPPTPPESYCASDEK
LLDDQEQEAELELRLRLGLGLEKSHGGQQHIEAYDLTCSTPPPVTVPQAAAVPRKARIGK
SMAREMVYAAQQQLLPEKQLKQPKEAAAKLEAEPEMPFVLKAEIKAETKIKIEHDGEAQA
STHISQLPDLKPTIKTEPEQELEQEAASVPSVAKTEPQPEVEVEREQQEPPVDEEQQPTP
GGSKQRFNLLALSSGNKKTKTNNSYKSLIKQAEPKSYLCPGRRFIRRHGRAPAKYVKRRQ
MILTQRQQQRMRLQRREQQQQRRQQREAAAEVVAGAVVTPSLAGNPIEQAGSEVSIVKDQ
APNSSATPSASPKRARPRKQEIAALHLLEGLDTTLSRGYFSDPELNHSSRKQAPTAVGGL
YAASSPLTTATDHRGKQTTAEKRSKSETKKPPSGESSESGLPCKKPRKEPAGKVKGKGKK
TTAGAAATTIASTAETQTEAVNAITASNQETNNNEYQTADLQAQKFRECPAVTDAKVAGT
ATSTSTASQQQNQQHSDEQHQFLVPSQPATASATAALAATPPPSRQGQATHTKRTRSRCK
FGNRKRQRHRPGGVSYELDVTQPPATKANVVPKWNNGWMWAGKAFQGAVFLNSDDPLVLR
TCYPAMRHVEGDIIRIRDCVLLKANEDNELPYVAKVAHLWQNPEDGEMMMSLLWYYRPEH
TDQGRQRNDCPDEVYASRHRDHNSVACVEDKCYVLTFSEYCRYRRRLRAAEEDVEDVSIV
PRRPSIATAPGFPVRTVPEHTNPELVMFCRRAYEFRTRRLLKLPHKNGLVCSSS
>gnl|BL_ORD_ID|26662 @Homo_sapiens@ gi|119395738|ref|NP_001073285.1| insulin receptor isoform Short preproprotein [Homo sapiens]
MATGGRRGAAAAPLLVAVAALLLGAAGHLYPGEVCPGMDIRNNLTRLHELENCSVIEGHL
QILLMFKTRPEDFRDLSFPKLIMITDYLLLFRVYGLESLKDLFPNLTVIRGSRLFFNYAL
VIFEMVHLKELGLYNLMNITRGSVRIEKNNELCYLATIDWSRILDSVEDNYIVLNKDDNE
ECGDICPGTAKGKTNCPATVINGQFVERCWTHSHCQKVCPTICKSHGCTAEGLCCHSECL
GNCSQPDDPTKCVACRNFYLDGRCVETCPPPYYHFQDWRCVNFSFCQDLHHKCKNSRRQG
CHQYVIHNNKCIPECPSGYTMNSSNLLCTPCLGPCPKVCHLLEGEKTIDSVTSAQELRGC
TVINGSLIINIRGGNNLAAELEANLGLIEEISGYLKIRRSYALVSLSFFRKLRLIRGETL
EIGNYSFYALDNQNLRQLWDWSKHNLTITQGKLFFHYNPKLCLSEIHKMEEVSGTKGRQE
RNDIALKTNGDQASCENELLKFSYIRTSFDKILLRWEPYWPPDFRDLLGFMLFYKEAPYQ
NVTEFDGQDACGSNSWTVVDIDPPLRSNDPKSQNHPGWLMRGLKPWTQYAIFVKTLVTFS
DERRTYGAKS--DIIYVQTDATNPSVPLDPISVSNSSSQIILKWKPPSDPNGNITHYLVF
WERQAEDSELFELDYCLKGLKLPSRTWSPPFESEDSQKHNQSEYEDSAGECCSCPKTDSQ
ILKELEESSFRKTFEDYLHNVVFVPRPSRKRRSLGDVGNVT-----------VAVPTVAA
F--PNTSSTSVPTSPEEHRPFEKV---VNKESLVISGLRHFTGYRIELQACNQDTPEERC
--SVAAYVSARTMPEAKADDIVGPVTHEIFENNVVHLMWQEPKEPNGLIVLYEVSYRRYG
DEELHLCVSRKHFALERGCRLRGLSPGNYSVRIRATSLAGNGSWTEPTYFYVTDYLDVPS
NIAKIIIGPLIFVFLFSVVIGSIYLFLRKRQPDGPLGPLYASSNPEY---LSASDVFPCS
VYVPDEWEVSREKITLLRELGQGSFGMVYEGNARDIIKGEAETRVAVKTVNESASLRERI
EFLNEASVMKGFTCHHVVRLLGVVSKGQPTLVVMELMAHGDLKSYLRSLRPEAENNPGRP
PPTLQEMIQMAAEIADGMAYLNAKKFVHRDLAARNCMVAHDFTVKIGDFGMTRDIYETDY
YRKGGKGLLPVRWMAPESLKDGVFTTSSDMWSFGVVLWEITSLAEQPYQGLSNEQVLKFV
MDGGYLDQPDNCPERVTDLMRMCWQFNPKMRPTFLEIVNLLKDDLHPSFPEVSFFHSEEN
KAPESEELEMEFEDMENVPLDRSSHCQREEAGGRDGGSSLGFKRSYEEHIPYTHMNGGKK
NGRILTLPRSNPS-----------------------------
>gnl|BL_ORD_ID|23286 @Nematostella_vectensis@ jgi|Nemve1|231988|fgsh_est.C_scaffold_13000013
MQAHLLDGDLAISHSILGHGMNAYGNDKHSHMDITSARPSSLGALAGTQPRSDTRPGHSE
GLKPPPPLIQVSPTRPLGQKSPIVETPRDQRERLPPGGVHKPEPVFGHTKASSQGQQHAV
EMESKALPMVDLTRERPGGSPIQEGMRGQSQQQHVGDLKSTGQAPSARAALKAIAMTAMA
SGKAPDEREAREREREKEHKKHEDLCIPPRHPDPKLNSYEQNEAIRKFSALPSCIPVPRE
FSPNAEYMSHHQYTAMMQLQAQAQAQALSGAHVHPQARAHAAAAVAAANYGHPMFMSGCV
PYHHLEYPVLTPVGYQQLSLQEMQQQQHNGEASSSHMKLNVPFSHLSQARPIYHSSLPST
SSSYNRVLEELSMNPRARYFAHQAAEEKLAQGHRVPSRSGDISDHELTHPFLARSSPHLR
QTHTITNVRGHSLSPGEAQKPGYSPYPEAERKRDSPSDRPRSRSPGMVYLQASRGPTRPT
SLAELQSRAAVIPEMVFPEPQRAGMSDAQRSHSRTPEPRPESRESRVIVHTDRRPDSRER
VIQHDQRAKYQESRVESQERQTMRDTRPRHPDELRPDIRHDIRVAQERREGRPDSKDATR
VMHLHEPRAGIELLHDGHRPPQSEQRADSRVDPRRIHGFPDSRSSRPGDSRMEPDIPRSS
VQVLPYPEPRPDAWIEYRTPDGRVFPGLRPEVIADSRISPYDARVKSVEQRPDPQPHRDQ
RRDVIKGIRESEHRFTDPQSFTHHDSRQDLHQGVPVADSRHRSEPQQANEVERTERPVIT
LEQERRVERIPAVPISVQTKPKKSVSDDPMLNLATLVDVAAAATKVEVARERREAEEREL
QERVERDSPVRCTAVTSTSPRYGITTGLVPKPPPLMPITGTKTSQEASPKPPAVLSITGG
TAGMPPKSPPKLVSPQESQPSRTSTSPERPPPLVTHTIPSVISSPQYSASKGTLGPPPLI
PRATASPVIQSTQMYLSQEESELPAHRNGGKEHAAKIELTETSQGHVNKKPFVEEDKNQL
GYGQSSQQNVVRNIFETVTYLGPSNFVMPGTHQGQKESSPPRSTQTLQASEGRSASGYTK
IGEPAAVIRPWRANPADKDTTCKVPTAPNPSFAEYLLGPTASRTEEVLRQVKEQQQSLKR
PHEISVPSVAVPFKKRSRLSTDPIKDEIDVSSVPVAVAEAMDRALVRPEQPVTMRRDAAH
QELERHMPDFDDEQQRQDLRRLQVSRSMNRRDVQSQDRLFQTSNLPGRDREMSNSDTESA
EETENLQEESGDEYISTAMPERQLHQVAVEENLPRFHHRHPGNLNRERNLEVVSSRVEQN
ICSTSANI---------PLHSSSVTSSAAFCSPSNTDTSRVVGRVSQAPHNSITSRINES
EV-APSTRRPERTAITSSSSEQLPSSGVTHPSAEAQGVLARLSQALDQAREMQRAAQSQP
RVSEISAAVQNTYEDNVNQDQEMQAVEANQTEQMQDENIGSQAVGNIIPDSSQGITADIA
EASGS--ENEESIERAVAGIPGRDTMSYQQDQEVDTSEALQLLSPSVQDEPSQV--IDSE
MLPSGTDTVLSSPQPSVPCSDIPLASSSSLQPAPSIADALSCM---------TSSQRVTA
QSSSSTTM---SPQPSVPNEHPAVPRRNVLSPESSDDVIQMPESSEVRADASDHSSVQSP
QPSGSRVSQPLSPSCPSTSELT-QPPSSAVEPTASQSMQPQPSFASLSVQGFQHHEAEIG
QSENVSEPST-------SYQPESAVSSHQEELEGASVERFRSLDIASP--SPSDVAAAMD
QPQTH-------------------------SPESSAKAADSSDSNIPQPMEGVLESSREA
VESSDMRDKGQYSSVSQSQEP-----NSNVSTSQADSRVTPVPSTSIEEPDSHDEQITDD
DHAVSAHINIEDD-DEDSFIPDTGDVVSPSQDHEMADSTDSEHEQQPVFPTFVGE-----
FIPSSSDRRD-----PVTSTCRHSATSSPRESIFSTREAEP--MQASEGRDEVVNEMEEE
NGNRVSEETVESSIRLENFENQLGTRDEGSSQDEESVSPAQAESDSLVV------DSSRD
EVQRKGSDSSTSEEARVDSDSEAVETVSYADRQVSSHSTVIEMVSEDLKLSSLSQPGRAD
LSTCEKPQTVFDSFTGEVGKRTSDTSTRESFRVDFASSDMVKASSES---AVNTSEAACE
FSSRSQALKIASDSST-SEPARVVSGTSIYEAEKTDSDPLTSETATAGFNMSDVEKRGSS
TSEESRYSSKSPVSEAVSSARQSTDDRSDGEIVSDEE-DVTETGQHSRPSSPHLATSTDI
PLPL-IFPISPPSPESPNQESEDDSVSPAP----PWPTSHSLNTMG------SSIFSHTL
QGSSSPS------QYSTLSLSRLANQRNTAYPFSALSLSIGSASSSARSSPVHFNLGRAQ
SPSSSSLLPRSHEPVPILKANMAESYQIAIMIFAGIGAFLLIVLLPLSFGGVEYYEMSFK
RQKSTGEVDLSKVYTSGLHLIGPDYAFKPFRADAHFETLSKITTYSTDKVEVTISCSFQY
FLKEEDLADLHAEYDIYYKPVIRTTANAAVKSRASQISVAQFIRDRDTVETALFKNLADR
LGGKCCRKNCAGDACKDCIAWSQCKRSDKGLFVEVRYFQLLAFDINEDIKSRYLRQVTEK
EQEEQANFELQEKVVRKETERQKNEILNEAAEIAQNATSIAAIITAQTEADTLVKVENAR
NPGLAEVFSALNITSEQHKASYIYLNTIRQQEKAKLSVNYDTLMAKD
>gnl|BL_ORD_ID|1292 @Saccharomyces_cerevisae@ gi|6320616|ref|NP_010696.1| Ade8p [Saccharomyces cerevisiae S288c]
MARI--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----VVLISGSG-----------------------------------------------
------------------------------SNLQALIDAQKQGQ----------------
---------------------------------------LGEDAHIVSVISSS-------
------------------------------------------------------------
---------------KKAYGLTRAA--------DNNIPTKVCSLYPYTKGIAKEDKAARA
KARSQFENDLAKLVLEEKPDVIICAGWLLILGSTFLSQLQSVPILNLHPALPGCFDGTTH
AIEMAWRKCQDENKPLTAGCMVHYVIEEVDKGEPLVVKKLEIIPGEETLEQYEQRVHDAE
HIAIVEATYKVLQQLHK-------------------------------------------
------------------------------------------------------------
-----------------------------
>gnl|BL_ORD_ID|13254 @Takifugu_rubripes@ jgi|Takru4|569775|e_gw2.59.3.1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------DIHCKADPFTGMHRQGGVNQLGGVFVNGRPLPDVVR---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------QRIVELAHQGVRPCDISRQLRV
SHGCVSK---ILGRYYETGSIKPGVIGGSKPKVATPKVVEKIADYK--------------
------------------------------------------------RQNPTMFAWEIR
------------------------------------------------------------
--------------------------------------DRLLAEGVCDNDTV--------
------------------------------------------------------------
---PSVSSINRIIRTKVQQ-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------PFHPSPDG--TSLSTPGH---------------
------------------------------------------------------------
------------------------------------------------------------
-----------------TIVPSSASPPVTSASNDPAG-----------------------
------------------SYSINGILGIPRSN----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GEKRKRDD---------------DGSDGSGPNSDSQGSV
ESLRKHLRADAFTQQQ---------------------------LEALDRVFERPSYPDVF
PTSEHIKNEQANEYTLPGLNSSLDEVKPSLSSSANPD-----------------------
-----LGPSVSQSYPV--------------------------------------------
---------------------------GRDMANTTLPGYPPHVPPTGQGSYPTSTLAGMV
PGSEFSGNPY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------SHPQYTTYNEAWRFSNPALLSSPYYY---------------
-----SAASRGSAPPTAATAYDRH------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>gnl|BL_ORD_ID|22901 @Takifugu_rubripes@ jgi|Takru4|581264|e_gw2.86.91.1
LK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------LHHRGETATSVD
YLSFLCYPMDIHCKADPFSSMHRHGGVNQLGGVFVNGRPLPDVVR---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------QRIVELAHQGVRPCDISRQLRV
SHGCVSK---ILGRYYETGSIKPGVIGGSKPKVATPKVVDKIAEYK--------------
------------------------------------------------RQNPTMFAWEIR
------------------------------------------------------------
--------------------------------------DRLLAEGVCDNDTV--------
------------------------------------------------------------
---PSVSSINRIIRTKVQQ-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------QFHPSPDGSVTPLSTPGH---------------
------------------------------------------------------------
------------------------------------------------------------
-----------------TIVPNTASPPVTSASNNPVG-----------------------
------------------SYSINGILGIPRSN----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GEKRKRDDVLWSGNHLDGRKIGHYGSDGSGPGSDSQGSV
ESLRKHLRADAFTQQQ---------------------------LEALDRVFERPSYPDVF
PTSEHVKPEQANEYSLPSLNTGLEDVKPSLSSSASSD-----------------------
-----LASSVSQSYSVVTDSHPSYPPSMCVKREPHEASFAPFTPSSVGDSALADILPHQS
SLSVDASYPAHALGHCYSQYTSQAFIAGRDMASTTLPGYPPHVPPTGQGSYPTSTLAGMV
PGGDFSGNPY--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------SHPQYTTYNEAWRFSNPALL-MPHPV---------------
-----APHLPLLPLPTTATSY--HGDQLKLQGQGFGLHIVPV------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>gnl|BL_ORD_ID|9026 @Takifugu_rubripes@ jgi|Takru4|610285|e_gw2.541.7.1
GA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------LGSFWPAQAACLPSDLQFTSDVSTLISCPA
GNLEDSLDDRIDSQPGHERSAYPGGDEREGECVDRKQKKKKKRRQKTEESFENSGSSGHF
EVQTQGENTSSTEDIYHRIGPSRDRQAGWEDQ----IGKCGGRGKRGKSRKKIP------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------EEWGMTAEPLVPTSAVASQIKEEVLLDLGRAAESPFADSN
QSPWIQEAYVEEDLLPKPLSKDLFSVTSISPLVLNS------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------ALNATAAPFT---MPSTTNSATFESMPGNSFP-----------------AD
SF----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------DLLMDSENSGLDQCNVSQEREA
KVGDMIDSGMIDSASFTQESCAQGIPEQDAFRPASPSSQGHSPEVL--------------
--------------------------------------------ASAPPISPPDTLWVVN
------------------------------------------------------------
--------------------------------------DSQLSSSTESSDLS--------
-----------------------------------------------NKK-------IHA
HPLPSGLSFDTPCPAPLRS-----------------------------------------
------------------------------------------------------------
---PKTTAQE--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------FDLKDEKKKKR----------KSSSPSLKSSTSP---------------
------------------------------------------------------------
------------------------------------------------------------
-----------------GESFTQQAPPVVSPSSQSVP-----------------------
------------------SVAFLGSGLNPSAKPFFPSFAN--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SVEEGTMVQPV--------------------------------------------
-----------------------DSAAICFVGSPKAD-----------------------
----------------SEEESPPSEPVFM-------------------------------
-----------------VHA--------QQQREVMLP-------AMSECSHLPVPTTLEL
PARSPGEN---------------DMELNQPVSTISRSGCSPNAMQRPLTVAEDQPPTPPS
CQPAGVTEVDLW------------------------------------------------
------------------------------------------------------------
-----------QDLPEPRFSTPPLSLLNASKAASSPSPLNDPVEDLKVEKELGGIGHPAP
PSSKGVSSFDISSPPSAGTDT--EEENCVHEPEFVAFHHANANSDLEA------------
--------SDLEVVTKSRVGGDSDDGLTAGSFGRWSLILIPLLCLALRKISYNKSKCE--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>gnl|BL_ORD_ID|2205 @Trichoplax_adhaerens@ jgi|Triad1|59731|fgeneshTA2_pg.C_scaffold_12000082
MGYIAILHYKYIVKSEYLRVETSPAFQSKKGYQVTNDRDGLHDNDNDNVSGNLPRLSSIG
RHSLRLSHRLKTDQESHEYQEDKSKNDFRPNNQLPTFADKLRTSPLTDLSLARNYSHLRA
LPNHDNPTLGNSADNTRNNNSSNLLRLRTQSDLGTDNKQLRRRYKPFTLSTQKHHFNDDD
NHKNLANHARSHSGSSLERLSQRRAQYRENVDLDKSAAPIASEIYLENSPSQQPYEINAD
ESIIMNGDENNKNQYQLQQHEGVVSISPSLESLTTTQDNNIQH-----------------
-----------------FDKKDPQEEIHQQHNTDTHHSKGTTEIEE------NNYQPSFK
ADPNEDANFSSVHNEGDNVSSKPTPDLESL------------VPSLLPSHQTVDSVDDPM
VPPKLPSSPPPLIPSQLVEKAEQI-------DANVANEKQDLIKANTTVNTASVRSNIGS
PLSSGSQSSSYSPFRSAVSPFSDSSQECPKLNIDKPLIQWTPSDVGNWLTSVGLDAMKRR
FTTNKIDG---KELEKMTKEKLEQIGVRYAMLRDKIMDKIMKLRSELIKNKPKPVEKSKE
EVSLVYPKPASKASEMSSISDLTKKERKPIAISPQTEIAPPLPETPPPSKAPQADMKSVP
TDLSVKRTASEQSDKSAPNQSPTSNENTSNQA--TKPN----SEYNKTLDSDNKGLSV--
-IKKPSLPESELPSSQKK---SNFKV---DDNNNTKGKDESSRRAKKTFPTIPKKVKGDD
VSQESTIHLENVILRFNNENRKDLATVAASAGAEAAAIAARRFGLFFNKVDDAKDKRHQK
RMARLSSNTQKQNQSFSSSKKDARSATTTTDNGEVAPDPVSNDYTCVSRNIAVKNPSYEV
ISSLEPDDDALRHPNATVAGQLLLIDDKYYYVPLSSPRSPHQ---LSHDPFNTNTSEDIP
VRDKVSAKSESPTVNELSKETNVESNQTLSPVPDETIDPLIKIPPKPNRYIKSMSQSNRD
SSTEPNHDIQTIEPKSHLVNDFIEKKTINNDQQSPPDLAIDLSELASQNELDKTLPSLEI
DSTNKF---------SRYSSEATRGVIPLDGIISQSISPYQQHSSDISTSELDRSDNDLL
YQQSNEPFANYFNQSLDDGINKQDSQLNEATPKLKNFNSELPLENSVIKEHPLQLSTNEA
SNCQIRNPISEQQDHKIPTIGSIYDHYQEEIESIQNEDHDKDLNLESTEVDDKLHTSMNR
KISIPIKSMNSDDVSLWLNSIGLPEIAAICEDNAINGKDIQNLGSKLFEHPELNLEERRE
VLATEIYFMNNKPDRENSELHNSLKEIAKNSNGSDKVLALAILEVMKSPPWCHGVDVDID
FNNKNILNYSNGTVTTAENNQTPFLESNDDLKHQNGGSSPYAEIGQVPTSGGIQPYNSIP
TQSEFEPKVVPSQQNIENQNNLFGSQPVQEIVNTTTISDNSATLNSSTFSTGNDSDLPSH
GVPSSPPIRSGANLPLYMQQNFGEKQDKSAKNKKKKITTRISKIFKPGTKSSNDDKKKVR
SQSQEEDNGLLRIDASILHRGQSVPGPSYKGFKVAPQINCLQVIENLLEKYEVHTDPKTY
YISQESLDQTVPAVELNFDDYPLPIQMKWPKNSKLFFELKRKLPIIKIQMQMMLNDQPSD
QLTTYEVSTSTTAKEITQQQLKSRKVDIDNLQDWCLVELTHGGNRIFDEEECLHAVHHQN
VQVLLLKRSKLRSTSSSLSSSGEDVELILSKNNDYPPANSQERPITIPVNQSNIAFIQKL
QKEMNDSPTLEKLLAEINQLRNIVTALQKRAALAIENSIISTNAKVDLENAQQIHSQELD
DKQGQIDKLKAVIALKDKEIQQLQNSNKSKGDQLTTLTGERDRALRLLQKYATGNDITER
LQGIQVQDDAANHTSLNDKNKNELIKDLQRKEREKEFLQVYVNNILSVICEEAPQLLESI
NRLQSSRL
>gnl|BL_ORD_ID|4984 @Ustilago_maydis@ jgi|Ustma1|4985|UM04985
MASTE-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------QDGGP---------PSLHISPPGTAFASGASTGVAPPP---------
VLRP-THGRARSSS----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------LV--------------------------------
------------------------------------------------------------
--------------------------------------------------SVTR------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------VEETHEEM-
------------------------------------------------------------
------------------------------------------------LDQS--------
--------AGFNAN---------------------------------------------A
DWVNYKGAWVI------HVVLIIVAKILLDVIPAMQQDTSWT-LVNLGYMTLSYIMFHYV
TGTPFESNAGAYDQLTLWEQIDEGAQYTPAKKWLTSVPIGLFLVSTHYTRYN--------
---PLLFGLNFSAL--LFVLFP---KLPILHRL-RFRFFAPPPTPSPYPSQPPTPTGTRT
PSHAA-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
F
>gnl|BL_ORD_ID|5157 @Ustilago_maydis@ jgi|Ustma1|5158|UM05158
MFGSSGFGGFGQQNNQQQQQQQQQQQQQPAGGLFGQTQQPTTPAQTGFGASTGFGSTGGF
GAAQPAAQTGGGLFGQQPSQAQNPSFGGFGASNNNASTTGAFGARPAGATGFGGFGAPAN
NTSTSSFTFGSTPNQQQQQQPAAGGFGSSTFGSTNPATGGLFGVQQQQQPAAGGFGATTG
AFGQPGAGAVPAQITQGTATVPYDPVREDLTPSEPIKDRKNWDVQQAITVMPAYGHHSIE
ELRLMDYQQGRSKGNTGPGATAAPSTGFGFGATNTSTGAFGQPQQQSTGFGATPSTGTTG
GLFGQPQQQQQPGGLFGQQNNQQQSGGLFGAKPATTGFGASTSTGGLFGQQQNQPQTASL
FGQPQQQQQPSSSFSFGSQPQQPAANTGFTFGANNNNNNNQQQNKPSFGFGASTTQPGQT
GFGFGANSNQQQSQTATGFGAGTTGTTGGFSFGQKPATGGLFGATTSQPGQTAGATSTFG
GFGANNSAATQSKPTFGFGAGGGGGFGATSAAGTGTTTAPTATGGLFGGASTTQPSTGGL
FGSTNTASGGAAGTTGGFSFGANNNQNQSGQTGSTAGFGGGLFGAKPAGQTGTQSATGGL
FGSTGTQTGQQGSTGFGAGTSTGGGLFGSTANKPATGGFSFGAGGGSSLFGSNNQQNNQQ
QGAGGLGTGFGQTQSNTSGGLFGQSNQNSSGATGGGLFGGNSSAGGSSLFGNAGTSNTAG
GLFGNSTQNSTGGNLFGGLGGGQNQQASGGLFGQSQQNQQQPGFSQNQQQQPTVQASLDS
NPYGTDSLFASNPINGTAGGSTANGASLPFNVAPKNKPPLTTPFRSSPRGANKINRLRGS
TPGASGLGSSSFVREGTPGSFREGTPGAHARFGTPGRAGSPALFKGLSDEYSQPLSSQAF
VSRPSAKRLVLDDAGENSFSVSRIGRSGSVPHFDSGSSPAVGSLGASAFRSGTVQPTSAS
RVTFSPALEQRAESVRPGGGDLSFASSLPSRRGNFLGGASSSSIMEDTPLKIVSAAAAKA
GAPRQGRDLESSFAAPTSMNAAATNGSAPSSGKVGEYYTEPSLSALRTANYNELAAVHNF
IVGRKGVGQIEFLEPVDLTSIEDLNDIVGGIVQIRLKEVVVYPEEDDYDPRNPKDGAKRN
FLPGAKAKQGTGLNVPARVSLEACWPADRATREPIKDAEHPRVKQMINKLKNKPETEFVD
FEPESGTWTFKVKHFSRYGLDDSDEDEEGADAGAGAKQAAAAAAKGSSGTSANRPASKRL
APMTMDQDGLSDDGSSDADDYDDDDAPPPLRTLDDGDMDSDDGANQAAAAAVAAAKRRQQ
RQWTPSSSVAGRERDGSATPSRAMTPVGNAAEARRVQVMQASFFGQDDSKSASAAVVPDK
PMGASLSHKRTLNLRPSVASLDKPADPQPLTAKDRKIESHPPEPRKATVQEVQQPAKKLR
KLDVAKSDAVAADGETLDAGMSLGRSFRVGWGPDGTLVHNGRIVGGGNFGSVSSSAAARM
ETDAAASANTSTLVLEKVKLFRDAETTAEEAIKAEKLLGVQLEHTNIELDDDGIPTAHTN
FATRFRHFASSFEHKDRSFEASLWRLGVALFDEIKLHIPEGAPTATADRIRSMRRKAAVS
DWLRHTVAGAVETEARSHIAASRRAALLFSLLSGNQVERAVNAALDAGDLRLATLIAQ--
AGGDEEVRAEISEQLLIWRKEGVDAHITRDHRRVYELLSGNVLVSKGTDSRTTKDPIDQV
SDLPICEGLDWKRAFGLFLWYESAYEAPLEHSFERYEAQVAPSASTNAGIAPPLPWYRES
SSVGATRLRQLLQKAGGYDRDALFELLKLYVDPTYGLEPALNACAFGASNMDARLPWHLY
NLLSRVLQRRDFGDRIELGLVDDGDDGMQDDQDSDGVMLNSQVAKSKAVQGNSARADMLA
SSYATQLELMGLWKWSAFVLLHLELGESRQAAIKALLSRNVAKLNSERGFLCERLLIPES
WLYEAKSYEARARDDRYSEYQLLLKANNWTAAHNVAVLDLAPEAIIRGDHELVSVLFSPF
YLEVSGDPADEVAGWADGAALYIDYVAASREIPGLAALLSDRATRDLALEKAERYASRLA
TLASGINSLLSLRSATASCFTSKAKAGERTLMVARTEMIAGITNLARILVNIATATAGSA
AAGVDEEAKAKLEAMGARMLSSGAVSGGKDGEQGGWDTAALEVDAVQAAADDYLNSLIGI
A
