>gi|141427971|gb|ECR75556.1| hypothetical protein GOS_3922326 [marine metagenome]
IIATQAAPQSSSAFCSTNGKRRSDRRIDRGRAGLDAKQPAAPATCARMDSSIPYPTAMPWAAAQPGSAAV
IEKAAERVRKPSPRYRVLLHNDPVNTMEYVVTTLRQVVPSLSEQDAIAVMLEAHNTGVGLVIVCDIEPAE
FYSETLKAKGLSSTIEPDS

>gi|135898707|gb|EBK56513.1| hypothetical protein GOS_8711496 [marine metagenome]
MVSSLLKSAIYLGSLIMVDSTNKTDGDTAVIDREVQRVRKISPKYKVLLHNDPVNTMDYVVESLRQVVPQ
LSEQDALNIMLETHNNGIGLVITCDLEPAEFYSESLKAKGLTSTIELES

>gi|142176669|gb|ECW16202.1| hypothetical protein GOS_2769706 [marine metagenome]
MMAALQSMHRSDLAMVGSTSSPSPGGAAVLDKQTERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQL
SEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPET

>gi|142057444|gb|ECV23196.1| hypothetical protein GOS_2939080 [marine metagenome]
MMAALHSMHRSDLAMVGSTSSPSPGGAAVLDKQTERVRKQSPRYKVLLHNDPVNTMEYVVTTLRQVVPQL
SEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKAKGLTSTLEPET

>gi|142133146|gb|ECV83258.1| hypothetical protein GOS_2827406 [marine metagenome]
MSRSLSPFPLDFKGFGSMVMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|141095155|gb|ECP59006.1| hypothetical protein GOS_5475216 [marine metagenome]
MAVASAPQVRATSDCPPSTAAPTWMLRWPESRPSEQVVHRFPLDLNQPNTMAMAVDTPTRSPGGVAVMEK
APERVRKQSPRYKVLLHNDPVNTMEYVVSTLRQVVPQLSEQDAMAVMMEAHNTGVGLVIVCDLEPAEFYC
ETLKAKGLTSTIEPES

>gi|142495294|gb|ECY49484.1| hypothetical protein GOS_2350549 [marine metagenome]
MGSPSTAASTRLMCGSRLPTEWIPGASLTICSTRPMWWEPLAAALAPPVRAISASQPSTAAPTSTRRWHG
SKRSEPSPFRFPLDFPQQRVLVMAVETPVRNPGGAAVVEKAPERVRKPSPRYKVLLHNDPVNTMEYVVST
LQQVVPQLSEQDAMAVMLEAHNTGVGLVIVCDLEPAEFYSETLKAKGLSSSIEPES

>gi|143493813|gb|EDF29313.1| hypothetical protein GOS_980729 [marine metagenome]
MASPSMAASMRLTCGSKPLKAWIPGASLTTCSTRPMWWEPLAVALAPLVRATSASRPSTAAATWMKPCAA
SALFRLPSVLRSAPAMTHASETPVRSPGGGAAVMERQPETVRKPSPRYRVLLHNDPVNSMEYVVTSLREV
VPSLSEQDAMAVMLEAHNSGVGLVIVCDIEPAEFYCESLKAKGLTSTIEPEE

>gi|136346190|gb|EBN54449.1| hypothetical protein GOS_8228726 [marine metagenome]
AATWMKPCAASALSRLPSVLRSAPAMTHASETPVRSPGGAAVMERQPETVRKPSPRYRVLLHNDPVNSME
YVVTSLRQVVPSLSEQDAMAVMLEAHNSGVGLVIVCDIEPAEFYCESLKAKGLTSTIEPEE

>gi|134979990|gb|EBE70446.1| hypothetical protein GOS_9719048 [marine metagenome]
MSRSPFALPLDFNRFGSMAMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|135027397|gb|EBF02553.1| hypothetical protein GOS_9664929 [marine metagenome]
MIRSPFALPLDFNRFGSMAMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPED

>gi|134970288|gb|EBE63870.1| hypothetical protein GOS_9729978 [marine metagenome]
MSRSPFALPLDFNRFGSMAMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPED

>gi|135008274|gb|EBE89638.1| hypothetical protein GOS_9686618 [marine metagenome]
MSCSLSPFPLNFKSFGSMVMAVDTPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQ
VVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|137021116|gb|EBR76158.1| hypothetical protein GOS_7545599 [marine metagenome]
MEGNTLLTCGSKRLKEWIHGASLITCSTKPTWWEPQAVALVLLARAISACPPSTAAAMSTKPCAASVLFR
LPSVLRSAPAMTHASETPVRSPGGAAVMERQPETVRKPSPRYRVLLHNDPVNSMEYVVTSLREVVPSLSE
QDAMAVMLEAHNSGVGLVIVCDIEPAEFYCESLKAKGLTSTIEPEE

>gi|137466260|gb|EBU25707.1| hypothetical protein GOS_7142202 [marine metagenome]
HRFGSMAMAVDSPSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMA
VMLEAHNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|144106180|gb|EDI90891.1| hypothetical protein GOS_1787846 [marine metagenome]
MVMAVDSSSQKPGGAAVLDKAPERVRKRSPRYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEA
HNTGVGLVIVCDIEPAEFYCETLKSKGLTSSIEPEN

>gi|142658060|gb|ECZ64559.1| hypothetical protein GOS_2146470 [marine metagenome]
MMINRFSCNYNQKVMSNIKFEKGENNNAAVLEKKTAPLKNKSPKYKVLLHNDPVNSMEYVTNALREVVPQ
LSEQDAISIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|138553250|gb|ECA39305.1| hypothetical protein GOS_5036795 [marine metagenome]
APERVRKRSPRYKVLLHNDPVNSMEYVVATLQQVVPQLSEQDCMAVMLEAHNTGVGLVIVCDIEPAEFYC
ETLKSKGLTSSIEPEN

>gi|143686637|gb|EDG27545.1| hypothetical protein GOS_810114 [marine metagenome]
MLSIKLEQSNNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKDD

>gi|136031255|gb|EBL44706.1| hypothetical protein GOS_8570357 [marine metagenome]
MIFRFKNLMLSIKLEQSSSNNSAVIEKKPAELKNKSPKYKVLLHNDPINSMEYVTISLREVVPQLSEQDA
ISIMLEAHNTGVGLIIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|138409194|gb|EBZ47076.1| hypothetical protein GOS_5198459 [marine metagenome]
IGNNNSALLEKQTSKLKQKSPKYKVLLHNDPVNSMEYVASTLREVVPQLSEQDAISIMLEAHNSGVGLVI
VCDLEPAEFYSESLKSKGLTSSIEKED

>gi|139872534|gb|ECI05164.1| hypothetical protein GOS_6346074 [marine metagenome]
MNYHFYQFSALFLFLLSIATPLHLAQGYSSAIGTGSFAGSRGGESRVVTASASGAPPTVRRAAVSPKMVG
GVTINKPPSKQLSPPKGQTNTRGGGGAKFRVLLFNDPVNTKEYVARMLMTKSGLTEDSAFQCMMQAHKMG
MGLIGIWLRERAEAITGELQEAGLTVTMVPEE

>gi|135982215|gb|EBL13280.1| hypothetical protein GOS_8618357 [marine metagenome]
ISNNSAVIEKQAVQLKNKSPKYKVLLHNDPINSMEYITVSLREVVPQLSEQDAIAIMLEAHNTGVGLVIV
CDLEPAEFYSESLKSKGISSSIEKDD

>gi|134332296|gb|EBA69932.1| hypothetical protein GOS_357478 [marine metagenome]
MHKINSDSIGNNNSALLEKQTSKFKQKSPKYKVLLHNDPVNSMEYVASTLREVVPQLSEQDAISIMLEAH
NSGVGLVIVCDLEPAEFYSESLKSKGLTSSIEKED

>gi|140077755|gb|ECJ39067.1| hypothetical protein GOS_4505498 [marine metagenome]
MHKINSDSIGNNNSALLEKQTSKLKQKSPKYKVLLHNDPVNSMEYVASTLREVVPQLSEQDAISIMLEAH
NSGVGLVIVCDLEPAEFYSESLKSKGLTSSIEKED

>gi|138283895|gb|EBY78998.1| hypothetical protein GOS_4425435 [marine metagenome]
TSALKSKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAISIMLEAHNTGVGLVIVCDLEPAEFYSE
SLKSKGISSSIEKED

>gi|142035659|gb|ECV04359.1| hypothetical protein GOS_2971799 [marine metagenome]
IPKNLMLSIKSEQSVSNNSAVIEKKTAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAISI
MLEAHNTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136200619|gb|EBM55729.1| hypothetical protein GOS_8390855 [marine metagenome]
MLMLSINLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAISIMLE
AHNTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143844497|gb|EDH03656.1| hypothetical protein GOS_677204 [marine metagenome]
MLSIQSANSVDNSAVLEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHN
TGVGLIIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|140011070|gb|ECI99015.1| hypothetical protein GOS_6109031 [marine metagenome]
ILKNLMQFINSEQSLSNNSAVIEMKPAELKNKSPKYKVLLHNDPINSMEYVTLALREVLPQLSEQDAIAI
MLEAHNTGVGLVIICDLEPAEFYSESLKSKGISSSIEKDD

>gi|142267621|gb|ECW84440.1| hypothetical protein GOS_2646187 [marine metagenome]
MLPVPLDSLSLRTMVMAVDTPSRSPGGAAVLDKAPEKVRKRSPRYKVLLHNDPVNSMEYVVTTLRQVVPQ
LSEQDCMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKGKGLTSTIEPEE

>gi|135018439|gb|EBE96503.1| hypothetical protein GOS_9675232 [marine metagenome]
VTFASPPSTAETMSTAPWRGSRPSDSPAVLLVPLDFLSLRTMVMAVDTPSRSPGGAAVLDKAPEKVRKRS
PRYKVLLHNDPVNSMEYVVTTLRQVVPQLSEQDCMAVMLEAHNTGVGLVIVCDLEPAEFYCETLKGKGLT
STIEPEE

>gi|141410538|gb|ECR63761.1| hypothetical protein GOS_4373743 [marine metagenome]
MKFNNSESGGNSGATLLEKKPSELKIKSPKYKVLLHNDPINSMEYVTTTLREVVPQLSEQDAIAIMLEAH
NSGVGLVIVCDLEPAEFYSESLKSKGLTSSIEKED

>gi|139226634|gb|ECE28170.1| hypothetical protein GOS_3585557 [marine metagenome]
MKVMRSIKLEQSVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAISIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143148191|gb|EDD16684.1| hypothetical protein GOS_1347778 [marine metagenome]
MKFNNSESGGNSGATLLDQKPSELKIKSPKYKVLLHNDPVNSMEYVTTTLREVVPQLSEQDAIAIMLEAH
NSGVGLVIVCDLEPAEFYSESLKSKGLTSSIEKED

>gi|140991833|gb|ECO89936.1| hypothetical protein GOS_3633248 [marine metagenome]
MQSIKLEQSVSNNSAVIEKQPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAISIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139691322|gb|ECG80526.1| hypothetical protein GOS_4286371 [marine metagenome]
ILMLSIKLGQSASNNSAVIEKNPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAVAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139168406|gb|ECD87512.1| hypothetical protein GOS_5186317 [marine metagenome]
MKFNNSESEGNSGATLLDQKPSELKIKSPKYKVLLHNDPVNSMEYVTTTLREVVPQLSEQDAIAIMLEAH
NSGVGLVIVCDLEPAEFYSESLKSKGLTSSIEKED

>gi|138586127|gb|ECA62071.1| hypothetical protein GOS_4130352 [marine metagenome]
IYNYKYNLDSKNLMPYIDLEQNISNNSAVIEKKPAELKNKSPKYKVLLHNDPINSMEYVTNSLREVVPQL
SEQDAVAIMLEAHNTGVGVVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139072666|gb|ECD22184.1| hypothetical protein GOS_4287054 [marine metagenome]
INLMLSIKLEQGVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|142035662|gb|ECV04362.1| hypothetical protein GOS_2971802 [marine metagenome]
MNLMLSIKLEQGVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139161245|gb|ECD82339.1| hypothetical protein GOS_5394798 [marine metagenome]
MNLMLSIKLGSSENNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139431309|gb|ECF06731.1| hypothetical protein GOS_4199873 [marine metagenome]
MLSINLEQSGSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|140796190|gb|ECN56858.1| hypothetical protein GOS_5394722 [marine metagenome]
IIDGVSQILKNLMLSIKLEQNVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTITLRQVVPQLS
EQDAISIMLEAHNTGIGLVIICDLEPAEFYSESLKSKGISSSIEKED

>gi|140582934|gb|ECM29217.1| hypothetical protein GOS_3495172 [marine metagenome]
INLMLLLMLEQSLNNNSVVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAMAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|142761391|gb|EDA38743.1| hypothetical protein GOS_2010648 [marine metagenome]
MLSIKLEQGINNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIERED

>gi|143564903|gb|EDF66206.1| hypothetical protein GOS_915910 [marine metagenome]
MINNLMLSTKLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTIALREVVPQLSEQDAIAI
MLEAHNTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|141268003|gb|ECQ78654.1| hypothetical protein GOS_4277373 [marine metagenome]
MSGIMLFFPWMLMLFSIFFFFKSGDSLGYTPRLSHRTRSAGVAEWNGAGISEAKVPFRDQAVPRSMRMMV
GGVTVNKPPSKQLAPPKGNTKARAGGGAKFRVLLFNDPVNTKEYVARMLMTKSGLTEDSAFQCMMQAHRL
GMGLVGIWLRERAEAITNELX

>gi|138807637|gb|ECB94976.1| hypothetical protein GOS_5841697 [marine metagenome]
ILDSKILMLSIKLEQIGSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAI
AIMLEAHNTGIGLVIICDLEPAEFYSESLKSKGISSSIEKED

>gi|143144474|gb|EDD13978.1| hypothetical protein GOS_1352462 [marine metagenome]
VGQRPFTPMPASERSKAWWPFIWKTPRSSVANSIPLASPSMAGSTLPTYGSKLRMAWTPGASLTICSIRR
MWSAPREVASAQPERVTSASRPSTAETMSTAPWRGSRPSDSPAVLPVPLDSLSLRTMVMAVDTPSRSPGG
AAVLDKAPEKVRKRSPRYKVLLHNDPVNSMEYVVTTLRQVVPQLSEQDCMAVMLEAHNTGVGLVIVCDLE
PAEFYCETLKGKGLTSTIEPEE

>gi|139765444|gb|ECH30670.1| hypothetical protein GOS_5788129 [marine metagenome]
MINNLMLSTKLEQSLSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTIALREVVPQLSEQDAIAI
MLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139351239|gb|ECE59333.1| hypothetical protein GOS_6079377 [marine metagenome]
ILKILMLSVKLEQTVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTMSLREVVPQLSEQDAIAI
MLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136928747|gb|EBR24005.1| hypothetical protein GOS_7631506 [marine metagenome]
MLVSFSSKKNLMLSIKLEQSVSDNSAVLEKKPAELKNKSPKYKVLLHNDPVNSMEYVAISLREVVPQLSE
QDAIAIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136993818|gb|EBR60725.1| hypothetical protein GOS_7570919 [marine metagenome]
MNLMRSIKLEQSANNNSAVIEKKPAELRNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|137634186|gb|EBV17040.1| hypothetical protein GOS_6945397 [marine metagenome]
MLMLSIKLEQSVSNNSAVIEKKPAEQKNKSPKYKVLLHNDPVNSMEYVTISLRAVVPQLSEQDAIAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|137802220|gb|EBW07969.1| hypothetical protein GOS_6803972 [marine metagenome]
MNLMLSIKLEQSANNSSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|140414417|gb|ECL60218.1| hypothetical protein GOS_6252558 [marine metagenome]
MNLMRSIKLEQSVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143474295|gb|EDF18150.1| hypothetical protein GOS_1000541 [marine metagenome]
MLMLPIKLEKSVSNNSAVIEKNPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143470595|gb|EDF15925.1| hypothetical protein GOS_1004498 [marine metagenome]
MKLEQSVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTG
VGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143203052|gb|EDD56049.1| hypothetical protein GOS_1283625 [marine metagenome]
MNLMLSIKLEQSANNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|142085632|gb|ECV47006.1| hypothetical protein GOS_2892776 [marine metagenome]
MLSIKLEQSVSNNSAVLEKKPAELKNKSPKYKVLLHNDPVNSMEYVAISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143594951|gb|EDF77605.1| hypothetical protein GOS_896203 [marine metagenome]
MNLMLSIKLEQSVNNNSAVIEKNPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143509188|gb|EDF37407.1| hypothetical protein GOS_966386 [marine metagenome]
MNLMLPLKLEKSVNNSVVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|137801328|gb|EBW07450.1| hypothetical protein GOS_6804807 [marine metagenome]
MNLMLSIKLEQSANNNSAVIEKQPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|142633421|gb|ECZ47209.1| hypothetical protein GOS_2177818 [marine metagenome]
MLMQSIKLEQSSSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136266737|gb|EBN00542.1| hypothetical protein GOS_8317040 [marine metagenome]
MNLMLFIRLEQSANNNSAVIEKKPAELKNKSPKYKVLLHNDPINSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIERED

>gi|137888585|gb|EBW57769.1| hypothetical protein GOS_6724887 [marine metagenome]
MLMLFIKLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLRQVVPQLSEQDAIAIMLE
AHNTGVGVVIVCDLEPAEFYSESLKSKGISSSIEKEDC

>gi|140235878|gb|ECK44917.1| hypothetical protein GOS_3814924 [marine metagenome]
MLLIKLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136222349|gb|EBM70385.1| hypothetical protein GOS_8366824 [marine metagenome]
MKLEQSLSNNSVVLEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTG
VGLVIICDLEPAEFYSESLKSKGISSSIEKED

>gi|143548771|gb|EDF57602.1| hypothetical protein GOS_931022 [marine metagenome]
MINSMISIKLEQSANNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIM
LEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143495602|gb|EDF30425.1| hypothetical protein GOS_978706 [marine metagenome]
MITSTTKTLINLMLPLKLEQSVNTNSVVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLS
EQDAITIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|135947239|gb|EBK89648.1| hypothetical protein GOS_8657330 [marine metagenome]
MNLMLSIKLEQSVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139562492|gb|ECF92324.1| hypothetical protein GOS_4305797 [marine metagenome]
ILDSKILMLSIKLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAI
AIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|140633429|gb|ECM45752.1| hypothetical protein GOS_6347623 [marine metagenome]
MLSIKLEQSANNNSAVIEKKPAELKNKSPKYKVLLHNDPINSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143229659|gb|EDD75354.1| hypothetical protein GOS_1250549 [marine metagenome]
MLMLSIKLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|138469130|gb|EBZ89054.1| hypothetical protein GOS_3554539 [marine metagenome]
ILMLSIKLEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLE
AHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136003197|gb|EBL26091.1| hypothetical protein GOS_8599675 [marine metagenome]
MIISEIKVPKDLMLSIKLEQSNNSAVIEKKPAELKNKFPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQ
DAIAIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|139090267|gb|ECD34421.1| hypothetical protein GOS_3816731 [marine metagenome]
IEKKPAELKSKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAHNTGVGLVIICDLEPAE
FYSESLKSKGITSSIEKED

>gi|137329615|gb|EBT48852.1| hypothetical protein GOS_7265402 [marine metagenome]
MMFNSLGTVLDPKKSKTKYPEARVIVLDDNFNSFKHVANCLLTIIPSMSEQRAWNLTIKVDKTGSAEVWR
GNLEQAELYHEQLFNKGLTLAPIEKA

>gi|142330875|gb|ECX31177.1| hypothetical protein GOS_2561319 [marine metagenome]
MISMIIIKLEQSVNNNSAVIEKKPAELKNRSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIML
EAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|141980339|gb|ECU59473.1| hypothetical protein GOS_3743427 [marine metagenome]
MLSIKLEQSANNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYITISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|136363635|gb|EBN66347.1| hypothetical protein GOS_8208827 [marine metagenome]
MLMQILMVSSVSKSAIPLGSLIMVDSVNQTDGDTAVIDREVQRVRKVSPKYKVLLHNDPVNTMDYVVETL
RQVVPQLSEQDALKIMLDTHNNGIGLVIVCDLEPAEFYSESLKAKGLTSTIELEN

>gi|136982813|gb|EBR54517.1| hypothetical protein GOS_7581304 [marine metagenome]
MYNYEYNLNPNKLMLSIKLEQRVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQL
SEQDAIAIMLEAHNTGIGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|143662992|gb|EDG14199.1| hypothetical protein GOS_833352 [marine metagenome]
MLSIKSEQSVSNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLSEQDAIAIMLEAH
NTGVGLVIVCDLEPAEFYSESLKAKGISSSIEKED

>gi|138176236|gb|EBY21153.1| hypothetical protein GOS_3725366 [marine metagenome]
MITSTIITLINLMLFIKLKQSVNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTISLREVVPQLS
EQDAIAIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIERED

>gi|136273532|gb|EBN05304.1| hypothetical protein GOS_8309650 [marine metagenome]
MYNYYYLNSKILMLSIKLEQSVSNNSAVIEKEPAELKNKSPKYKVLLHNDPINSMEYVTISLREVVPQLS
EQDAIAIMLEAHNTGVGLVIVCDLEPAEFYSESLKSKGISSSIEKED

>gi|141422516|gb|ECR71859.1| hypothetical protein GOS_4069344 [marine metagenome]
MMFNSLGTVLDPKKSKKKFSEARVIVLDDSFNTFQHVANCLLTIIPSMSEKMAWNLTIKVDKTGSAEVWR
GNLEQAELYHEQLFRKGLTMAPIEKT

>gi|138584717|gb|ECA61053.1| hypothetical protein GOS_4169465 [marine metagenome]
MNLMLSIKLEQSLNNNSAVIEKKPAELKNKSPKYKVLLHNDPVNSMEYVTVSLREVVPQLSEQDAISIML
EAHNTGVGVVIVCDLEPAEFYSESLKSKGISSSX

>gi|136325059|gb|EBN40122.1| hypothetical protein GOS_8252806 [marine metagenome]
MMFNSLGTVLDPKESKAKYPEARVIVLDDNFNTFQHVANCLLTIIPSMSEQRAWDLTIKVDKTGSAEVWS
GNLEQAELYHEQLFSKGLTMAPIEEK

>gi|144152522|gb|EDJ24644.1| hypothetical protein GOS_1729566 [marine metagenome]
MLPMTVTPTGTATVLDRATSRSDYPQARVIVLDDDVNTFQHVVECLCRIIPGMGSERAWDLAHRIDAEGA
ADVWSGPLEQAELYHQQLSAEGLTMAPLERC

>gi|140979955|gb|ECO81505.1| hypothetical protein GOS_3963494 [marine metagenome]
DPVNTMEYVVVTLRQVVPSLSEQDAIAVMLEAHNTGVGLVIVCDLEPAEFYSETLKAKGLSSSIEPES

>gi|134340910|gb|EBA75808.1| hypothetical protein GOS_347454 [marine metagenome]
MLPMTVTPTGTATVLNRATSRSDYPQARVIVLDDDVNTFQHVVECLCRIIPGMGSERAWDLAHRIDAEGA
ADVWSGPLEQAELYHQQLSAEGLTMAPLERC

>gi|143441881|gb|EDE97807.1| hypothetical protein GOS_1036865 [marine metagenome]
MFKSRSRHFQYFSIEEHRLNFNLFKLLKTIMFNSFGTVLDPKKSKAKYPEARVIVLDDNFNTFQHVANCL
LTIIPSMSEQKAWDLTIKVDKTGSAEVWRGNLEQAELYHEQLFSKGLTMAPIEKT

>gi|138735014|gb|ECB64729.1| hypothetical protein GOS_3556681 [marine metagenome]
MFYATNKVIEREKVKAKYPDARVIVLDDSFNTFEHVANSLLTIIPDIGEKKAWDLTIKVDKFGSAEVWRG
NLERAELYHQQLFCKGLTMAPIENI

>gi|138470274|gb|EBZ89883.1| hypothetical protein GOS_3523683 [marine metagenome]
VFKSRSRHFQYFSIEQHRSNFNLIKLLKTIMVNSLGTVLDPKISKAIYPEARVIVLDDNFNTFQHVANCL
LTIIPSISEQRAWDLTIQVDKTGSAEVWRGNLEQAELYHEQLFSKGLTMAPIEKT

>gi|136201089|gb|EBM56042.1| hypothetical protein GOS_8390309 [marine metagenome]
NSLGTVLDPKKSKIKYPEARVIVLDDNFNTFQHVANSLQTIIPSMNEQRAWDLTIKVDKTGSAEVWRGNL
EQAELYHEQLFSKGLTMAPIEKT

>gi|141135960|gb|ECP87879.1| hypothetical protein GOS_4333559 [marine metagenome]
MHSPQVACSSHARDIFNTFQLKNLGEIFNRLKKISTQMFNSLSTVLDQKKSKANYPEARVIVLDDSYNTF
QHVANCLLTIIPGMSEKKSWDLTIKVDKSGSAEVWRGNLEQAELYHEQLFSKGLTMAPIEKT

>gi|136332118|gb|EBN44857.1| hypothetical protein GOS_8244886 [marine metagenome]
MFNLIKLLKKIMFNSLDTVLDPKKSKAKYPEARVIVLDDNFNTFQHVANSLLTIIPSMSEQRAWDLTIKV
DKTGSAEVWRGNLEEAELYHEQLFSKGLTMAPIEKT

>gi|139663807|gb|ECG61455.1| hypothetical protein GOS_5037493 [marine metagenome]
IIKLLKTIMINSLGTVLDPKKSKVKYPEARVIVLDDNFNTFLHVANCLLTIIPNMSEQRAWDLTKKVDKT
GSAEVWKGNLEQAELYHEQLFRKGLTMAPIEKI

>gi|140228794|gb|ECK40048.1| hypothetical protein GOS_4007135 [marine metagenome]
IGMLSKETLTEVIKLQREALDQAEVGTPREEQKELTILDSFALIITGVRRCGKSTLLHQLIRKQKKAYYI
NLEDPRLGGFDLNDFNKIEAIMEEVYGKGGTYFFDEIQTIPQWEKYIRYLVDKKEKVVLTGSNAALLSKE
LGTKLTGRHLDYELFPFSFKEFLNLKKTE

>Populus_trichocarpa_gi|224111322|ref|XP_002315814.1| predicted protein [Populus trichocarpa]
MA-------------LFTAASTTRFSSTKQQSVHFNSIDGPIPTHSTRANFPQKRAIAMS
TNLAV-----------KA------------------------------------------
--------------------SFTKGGTGVLERPTFDQS--------------QFDPSSQA
LEGGDIGRLRDKRGVGSGDSYRVLLIDDARHSERLVAKVLPQAVPSVTPDDARKLFHESR
ENGVAVVIVTVKEHAEFYSQMMVRGGLRSIIEPESNTV-------
>Populus_trichocarpa x Populus deltoides_gi|118488912|gb|ABK96265.1| unknown [Populus trichocarpa x Populus deltoides]
MA-------------LLTAASTTWFSSTTQQPVQFNNVDGSIFTRNFKANFPQKRAITMS
TDLTV-----------KA------------------------------------------
--------------------SFTKGGPGVLERPTFDQS--------------QFDPSSQV
LEGGDIGRLRDKRGVGSGDSYRVLLIDDSRHSESLVAKVLPRAVPSVTPEDARKLFHESR
ENGVAVVIVTVKEHAEFYSQMMIRGGLRSVIEPDSSNV-------
>Populus_trichocarpa_gi|224099689|ref|XP_002311579.1| predicted protein [Populus trichocarpa]
MA-------------VLTAASTTWFSSTTQQPVQFNNVDGSIFTRNFKANFPQKRAITMS
TGLTV-----------KA------------------------------------------
--------------------SFTKGGPGVLERPTFDQS--------------QFDPSSQV
LEGGDIGRLRDKRGVGSGDSYRVLLIDDSRHSESLVAKVLPRAVPSVTPEDARKLFHESR
ENGVAVVIVTVKEHAEFYSQMMIRGGLRSVIEPDSSNV-------
>Oryza_sativa Japonica Group_gi|115440869|ref|NP_001044714.1| Os01g0833600 [Oryza sativa Japonica Group]
MAISSRAAACGALIFPTTASAAPVSRSV-------------------------------S
VDQRVSHRRRKAVAVAAV------------------------------------------
--------------------PHASSGGALLERPAFDQS--------------QLDTLPVT
QEGGDTGRMRDRRGSGSGDSYKVLLIDDARHTEKLVEKALPQVVPSVTAEAARQLFHASR
QKGAALVIVAVKEHAEFYAQMMVRQGLRSAIEPESDLAS------
>Oryza_sativa Indica Group_gi|125528275|gb|EAY76389.1| hypothetical protein OsI_04320 [Oryza sativa Indica Group]
MAISSRAAACGALIFPTTASAAPVSRSV-------------------------------S
VDQRVSHRRRKAVAVAAV------------------------------------------
--------------------PHASSGGALLERPAFDQS--------------QLDTLPVT
QEGGDTGRMRDRRGSGSGDSYKVLLIDDARHTEKLVEKALPQVVPSVTAEGARQLFHASR
QKGAALVIVAVKEHAEFYAQMMVRQGLRSAIEPESDLAS------
>Picea_sitchensis_gi|294463540|gb|ADE77299.1| unknown [Picea sitchensis]
MATPVHLTQLGMSPLIPTSTKSTQVSALGIIPSRLTFISCSSRTQLKHERFTGKIMVTSV
SGRLVGGRGPGVLERPGL------------------------------------------
--------------------GGGGGGTGVLERPGFDQS--------------QFDATPSA
EEGGEIGKVREKRGTGGGDMYKVLLLDHERHTESQVAAVLPKVVPSVTPEEARKCFHESR
QTGAGLVTVTVKEHAEFYAQMMARSGLRSTIEPDGDLV-------
>Physcomitrella_patens subsp. patens_gi|168029911|ref|XP_001767468.1| predicted protein [Physcomitrella patens subsp. patens]
------------------------------------------------------------
------------------------------------------------------------
-------------------------GAGVLERPKLDQS--------------GSDTTPRT
EEGGESGRAAQRNRTGGGERYRVLLLDHERHTETYVAKALTKAVPNITAEQARKCFFESR
LIGKSVVMVAVKEHAEMHAFSMARYGLRSTIEPDGSV--------
>Volvox_carteri f. nagariensis_gi|302829927|ref|XP_002946530.1| hypothetical protein VOLCADRAFT_115933 [Volvox carteri f. nagariensis]
MA--------------------------------------------MLSQRTFKNLRRGS
RAKVIRPCGRFALQIQA-------------------------------------------
--------------------RFGGGRGNVLDRPDVDLSKRLGGFDLSDFNLGGWKPSTES
GRSG-SGLDKDKQSPPGGGNYRVLLMDSPQHSEKVVVRGICTVVPNADEAHARNCYHTSK
QLGMAIITTALKEHAEFYRQQLYTYGCRTAIEPDSTVA-------
>Chlamydomonas_reinhardtii_gi|159489657|ref|XP_001702813.1| clp protease adaptor protein [Chlamydomonas reinhardtii]
----------------------------------------------MLATRCKCNLPSRS
FVAPARSVRTRALHVEGR------------------------------------------
--------------------FGGGRGGNVIDRPDVDVSKRLGGFDLSDWNIPSWDAKTDN
GNNG-SNTDKDKKSPPGGGNYRVLLLDSPQHTEKGVVAAITRVVPGTNPDHARNCFATSK
QLGMAIITTALKEHAELYREQLFTYRVRTALEPDNSTV-------
>Coccomyxa_subellipsoidea C-169_gi|384253485|gb|EIE26960.1| ATP-dependent Clp protease adaptor protein ClpS [Coccomyxa subellipsoidea C-169]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MVVQAITTVIPGTSPEHALNCYHTAK
KLGQAIITSCIKEHAEFYSEQLSRQGISNMIEPDTTTL-------
>Chlorella_variabilis_gi|307104985|gb|EFN53236.1| hypothetical protein CHLNCDRAFT_137134 [Chlorella variabilis]
MASHAAATIPACAGAASQRPRA--------------------------------------
-VLPAPRRRRAPLHSTFA------------------------------------------
--------------------TKDRGGGAVLDRPSFGTI--------------GPDGTPLT
DSAG-SKLDSNGGRGLGGGSWRVLLLDSDKHVEARVVDAIMAVV-GADQAHAQNVFHTAR
SIGQAIITCAPKEHAEFYAQQLWQRGCKVNMEPDSTTL-------
