>Rubrobacter_xylanophilus_DSM_9941_gi_108803856
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MVGSLTRD-I
RCSAATKTAP---ARKTRRAPSREPRYRVILHNDDWTPMDHVVAALMKVVPRLSLRRAVS
IMLEAHTKGQAVVTRCHRELAELYREGLKAEGLIST-IEPD----------G
>Anabaena_variabilis_ATCC_29413_gi_75907498
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VETIEKR--
-----------------STSRKLAPRYRVLLHNDDYNSMEYVVQVLITTVPSLTQPQAVS
IMMEAHTNGLALVITCAQEHAEFYCETLKDHGLSST-IEPD----------E
>Fischerella_sp_JSC-11_gi_354566131
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VETQQKR--
-----------------STSRKLAPQYRVLLHNDDYNTMEYVVQVLLTTVPSLTQPQAVS
IMMEAHSNGLALVITCAQEPAEFYCETLKNHGLTST-IEPE----------E
>Raphidiopsis_brookii_D9_gi_282897015
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VETIEKP--
-----------------STTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVT
IMMEAHSNGLALVISCALEHAEFYCESLNNHGLTST-IEPD----------D
>Cylindrospermopsis_raciborskii_CS-505_gi_282899028
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VETIEKP--
-----------------STTRKLAPRYRVLLHNDDYNSMEYVVQVLLSTIPSLTQPQAVS
IMMEAHSHGLALVISCALEHAEFYCESLNNYGLTST-IEPD----------D
>Nostoc_azollae_0708_gi_298490087
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VETIEKR--
-----------------STTRKLAPQYRVLLHNDDYNSMEYVVQVLMTSVPSITQPQAVN
IMMEAHNSGLALVITCAQEHAEFYCETLKGHGLSST-IEPD-----------
>Oscillatoria_sp_PCC_6506_gi_300868553
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VETIEKR--
-----------------STVRKIAPRYRVLLHNDDFNSMEYVVQTLMHTVPSLTQPQAVN
IMMEAHTNGLAVVIICAQEHAEFYSETLNNHGLIST-IEPD----------E
>Microcoleus_vaginatus_FGP-2_gi_334120716
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------VEIIQKA--
-----------------STVRKLAPRYRVLLHNDDFNPMEYVVQTLMATVPSLTQPQAVN
VMMEAHTNGMGLVIVCALEHAEFYAETLNNHGLSSS-IEPD----------D
>REF_Synechococcus_7942_ClpS1_REF
------------------------MA----------------------------------
------------------------------------------------------------
---------------------------------------------------VETIQKP--
---------------ETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVD
IMMEAHTNGTGLVITCDIEPAEFYCEQLKSHGLEQQ---------------H
>Gloeobacter_violaceus_PCC_7421_gi_37520315
------------------------MS----------------------------------
------------------------------------------------------------
---------------------------------------------------TETLERK--
-----------------SVQRKPMPLYKVLLHNDDHTPMNYVIEVLMKTIPKMQPSKARK
IMLEAHNGGVAVVIVCALEHAEFYSESLNRHNLTST-YEPD----------C
>Oryza_sativa_Japonica_Group_gi_115476544
------------------------MEAAVPSRV---------------------------
---------------------------------------------------ALS-ASRLS
NHHHHA-VGGERYAI---------YRGRCPNPAIPMALAAAA----APGKGGGVLDRP-I
EKV-TPGRQS---EFDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVN
IMQEAHVNGLSVVIICSQSEAEEHCTSLRGNGLRSS-IEPASGG-------C
>Oryza_sativa_Japonica_Group_gi_125603506
------------------------MEAAVPSRC---------------------------
-----------------------------------------------------G-ALREP
ALQPPP-PRGERYAI---------YRGRCPNPAIPMALAAAA----APGKGGGVLDRP-I
EKV-TPGRQS---EFDVRKSRKMTPPYRVLLHNDNYNRREYVVQVLMKVIPGMTVDNAVN
IMQEAHVNGLSVVIICSQSEAEEHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_195652021
------------------------MMASVPSRV---------------------------
---------------------------------------------------ALSAASRLP
N--LHA-VAGDRSFI---------YKRRCPSLSIPMAL-SAA----APGKGGGVLDRP-V
EKI-TPGRQS---EFDVKKSRKMTPPFRVILHNDNHNRREYVVQVLMKVIPGMTVDNALS
IMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNGLRSS-IEPASGG-------C
>Zea_mays_gi_226506038
------------------------MEAAVPSRV---------------------------
---------------------------------------------------ALSAASRLP
N--PHA-VTGDRSFI---------YKGRCQSLAIPMAL-SAA----APGKGGGVLDRP-V
EKT-TPGRQS---EFDVKKSRKMSPPYRVILHNDNYNRREYVVKVLMKVIPGMTVDNAVN
IMQEAHVNGLSVVIVCSQSEAEEHCTSLRGNGLRSS-IEPASGG-------C
>Brachypodium_distachyon_gi_357147864
------------------------MEAAVPSRI---------------------------
---------------------------------------------------ALS--ARIM
N--HHVVAAGGRSSI---------YRGRYPNIAIPIVVT-------AAGKGGGVLDRP-A
EKI-SPGRQS---EFDVKKSRKMSPPYRVVLHNDNENRREYVVQVLMKVIPGMTVDNAVN
IMQEAHVNGLAVVIVCSQSEAEEHCTSLRGNGLRSS-IEPASGG-------C
>Arabidopsis_thaliana_gi_145326694
------------------------METAICGRL---------------------------
---------------------------------------------------ALA-----P
SSLFNS-KSGDKHLV---------SKGPCVNRSILMTLSTSA----ALGKGGGVLDKPII
EKT-TPGRES---EFDLRKSKKIAPPYRVILHNDNFNKREYVVQVLMK------------
------------------ADAEQHCMQLRGNGLLSS-VEPDGGG-------C
>Arabidopsis_lyrata_subsp_lyrata_gi_297841589
------------------------METAICGRL---------------------------
---------------------------------------------------ALA-----P
SSLFNS-KSGDKHLV---------SKGPCVNRGVLMTLSTYA----ALGKGGGVLDKPII
EKT-TPGRES---EFDLRKSKKMAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVN
IMQEAHINGLAVVIVCAQADAEQHCMQLRGNGLLSS-VEPDGGG-------C
>REF_Arabidopsis_thaliana_ClpS_REF
------------------------METAICGRL---------------------------
---------------------------------------------------ALA-----P
SSLFNS-KSGDKHLV---------SKGPCVNRSILMTLSTSA----ALGKGGGVLDKPII
EKT-TPGRES---EFDLRKSKKIAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVN
IMQEAHINGLAVVIVCAQADAEQHCMQLRGNGLLSS-VEPDGGG-------C
>Vitis_vinifera_gi_225455872
------------------------METAICGRV---------------------------
---------------------------------------------------PLS-----P
NHFFTS-KSGDKHSL---------SK-QWTHRTMLMTVSA-A----APGKGSGVLERPTI
ERI-MPGRES---EFDLRKSRKMSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDNAVN
IMQEAHHNGMSVVIICAQVDAEDHCMQLRGNGLLSS-IEPASGG-------C
>Populus_trichocarpa_gi_224099343
------------------------METAICGRI---------------------------
---------------------------------------------------ALS-----P
NHVFNP-KPGDKNSV---------CRGPCANRGILMAIST-T----CSGKGGGLLEKPVI
ERT-TPGRES---EFDLRKSKKMAPPYRVMLHNDNYNKREYVVQVLMKVIPGMTLDNAVN
IMQEAHYNGLSVVIICAQADAEEHCMQLRGNGLLSS-IEPASGG-------C
>Populus_trichocarpa_gi_224111728
------------------------METAICGRI---------------------------
---------------------------------------------------ALS-----P
NHVFNP-KPGDKNSV---------CRGPCASRGILMSISA-TVSGKGGGGGGGILEKPVI
ERT-TPGRES---EFDLRKSKKMAPPYRVILHNDNYNKREYVVQVLMKVIPGMTLDNAVN
IMQEAHYNGLSVVIICTQADAEEHCMQLRGNGLLSS-IEPASGG-------C
>Glycine_max_gi_351723283
------------------------MKSAICGRI---------------------------
----------------------------------------------------LS-----P
NHVF---KPGDTHSI---------CKGPYSNLCVPMAVLA-T----GPGKGGGVLEKPVI
EKV-TPGRES---EFDLKKSRKSAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVN
IMQEAHYNGLSVVIICDQADAEDHCTQLRGNGLLSS-IEPASGG-------C
>Medicago_truncatula_gi_357488429
------------------------MKSAICRSM---------------------------
---------------------------------------------------GLS-----P
NHLF---ISGDRYSF---------CKGPYSNLCVPMAVLT-K----GSGKGGGILEKPVI
EKA-TPGRES---EFDLKKSRKTAPPYRVILHNDNFNKREYVVQVLMKVIPGMTLDNAVN
IMQEAHHNGMSVVIICAQADAEDHCMQLRGNGLLSS-IEPAGDG-------C
>Picea_sitchensis_gi_294460817
------------------------MASVIYSRL---------------------------
---------------------------------------------------ILP-----Q
PQLYQQ-KSGEKISQ---------SKGACMNR-VFSAIRSTS----PGGKGGGLLERPTI
EKT-TPGRES---EFDLRKSRKTSPPYRVLLHNDNYNKREYVVQVLMKVIPGMTLDTAVN
IMQEAHYNGLAVVIICAQVDAEEHCTQLRGNGLLSS-IEPASDG-------C
>Glycine_max_gi_356531226
------------------------MEAALCSAL---------------------------
---------------------------------------------------ALS-----P
NQVFNAANPGDKNVP---------LK-YSKDRSVVMTVAATG----ILGKGGGLLERPTI
ETT-SPGRES---EFDLRKSRKTSPPYRVLLHNDNFNKREYVVQVLMKVIPGMTIDNAVN
IMQEAHYNGLAVVIVCAQVDAEDHCMQLRGNGLLSS-IEPADGGG------C
>Vitis_vinifera_gi_297737852
------------------------MENAICGRL---------------------------
---------------------------------------------------ALS-----P
NHVFNS-KSGDKHSL---------LKGPCTNRSFLMAISA-S----GPGK-GGLLERPVI
EKV-TPGRES---EFDLRKSRKIAPPYRVILHNDNYNKREYVVQVLMK------------
------------------ADAEDHCMQLRGNGLLSS-IEPASGG-------C
>Physcomitrella_patens_gi_121489819
------------------------MAGSLRLFV---------------------------
---------------------------------------------------SIP-----A
TARHFGINGVEKAQR---------VHNRVNGR---YKINAAS----GPSQGGGVLDRPTI
DKP-TPGRES---EFDLKKKKKISPPYRVMLHNDNFNKREYVVQVLMKAIPGMTVDIAVN
VMNEAHINGLAVVIVCPQEDAEDYCMQLRTNGLLSS-IEPAS---------C
>Selaginella_moellendorffii_gi_302761288
------------------------MACTLTQVA---------------------------
---------------------------------------------------HLWPSTSQV
SRFNTIFAEADK------------CHKCFTRIIASHAVRAAL----PGGLGGGVLDKPAI
ETAPTPGRES---EFDLRKKKKMAPPYRVILHNDNFNRREYVVQVLMKVIPGMTLDNAVN
IMQEAHHNGLSVVIVCSQEDAEEHCTQLRANGLLSS-IEPASGGS------C
>Chlorella_variabilis_gi_307105846
------------------------MTICVGQRL---------------------------
------------------------------------------------------------
GGQAVAGKAGDKPPTRGAWLVPAGATRRSAQRRARLHVAARS-----AGKGGGVLDRP--
------GVLP-GQQRGRETRRRRPPSYRVLLHNDNYNRREYVVQVLMKVVEGTTVDDAVN
IMQEAHINGLAMVTQCAQDKAELYCESLRLNGLIAT-IEPAGTGGSDGTSSS
>Chlamydomonas_reinhardtii_gi_159467236
------------------------MM----------------------------------
------------------------------------------------------------
TRSPVAGLPRPCSALQRSGCTLQGAFGTFAPQTTRTFVVTWA--------KGGVMDAP--
----TTTQQP---ASGVERSQKRPPIYKVLLHNDNYNKREYVVKVLLKVVEQITVDDAVT
CMQEAHETGVALVVACPQDNAERYCEGLRLNGLTST-IEPGG---------C
>Volvox_carteri_f_nagariensis_gi_302834902
------------------------MAASVLRPP---------------------------
-------------------------------------------------------PVSVA
SRAPTAALAVLPGSACLGWRRANFGTSTLLSQTTRTCVQMRA-------GVPGLLDSP--
----TITSEP---QQGTDRAYKRPPIYKVFLHNDNYNKREYVVKVLLKVVEEITVDDAVT
VMQEAHETGVALVVACPQENAERYCEGLRLNGLTST-IEPAG---------R
>Ktedonobacter_racemifer_DSM_44963_gi_298245523
------------------------MAQRQCQPS---------------------------
------------------------------------------------------------
------------------------------------------------------------
----RLEIRP---EEVVRQRSSLLPLYKVILFNDDYNDMLHVVAALLETVNTLTMQEATH
IMLTAHLNGNAIVIVCPHELAEHYQERLLGYALTVT-IEPE-----------
>Guillardia_theta_gi_57335897
------------------------RICACVRSAWSFPVAFPAHLHHPLLRAVCFFIKWIS
SILWFMMGRQVLAALALLPLAWCFQAPTSFLPGTRGITQQTCATLRPAVLGKMQLEAPER
IKIPDTFNPAEWGVGGGKGGFGDGLGGFKVPDSFNPAEMEKE----RQGGRTAVMDRP--
-----------------SDKTDPGKKYKVLLFNDDKNTRQYVIDTLMKYIPGMTADKAKE
ITVAAHNTGMAIVGVWMYEMAEAYSDVLRSAGLRSD-IDPE-----------
>Oscillatoria_sp_PCC_6506_gi_300864591
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-MTSSPTIAP---DRSSQVTRKPYPNYKVIVLNDDFNTFQHVSECLVKYIPGMTSDRAWK
LTNQVHYEGQATVWVGPQEQAELYHMQLSRAGLTMAPLEQA-----------
>Microcoleus_vaginatus_FGP_2_gi_334119600
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-MTSSPTIAP---VRSSQVTRKPYPNYRVIVLNDDFNTFQHVVECLTKYIPGMTSDQAWK
LANQIHHEGQATVWVGPQEQAELYHMQLSRAGLTMAPLEST-----------
>Anabaena_variabilis_ATCC_29413_gi_75909055
------------------------------------------------------------
---------------MV----------------------------TKLS-----------
--------------------------------------------------------IDVY
AMSTAPTVTP---ERSNQTVRKSYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTGDLAWD
LTNQVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEAA-----------
>Fischerella_sp_JSC-11_gi_354566811
------------------------------------------------------------
---------------MI----------------------------TKLS-----------
--------------------------------------------------------AAVY
AMAATPTIAP---ERSTQVTRKPYPNYKVIVLNDDFNTFQHVAECLVKYIPGMTSDRAWE
LTNQVHYEGQAIVWTGPQEPAELYHQQLRRAGLTMAPLEAA-----------
>Nostoc_azollae_0708_gi_298491120
------------------------------------------------------------
---------------ME----------------------------TRLA-----------
--------------------------------------------------------AVYY
DMATAPTVTP---DRVNQVTRKTYPNYKVIVLNDDFNTFQYVAECLMKYIPGMSGDLAWD
LTNQVHYEGQAIVWVGPQEPAELYHQQLRRAGLTMAPLEGA-----------
>Raphidiopsis_brookii_D9_gi_282895992
------------------------------------------------------------
---------------MK----------------------------TR-P-----------
--------------------------------------------------------SPIY
AMAPAPTVTP---DQGTQVIRKPYPNYKIIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWE
LTNQVHYEGQAIVWVGPQEQAELYHQQLRRAGLTMAPLEAA-----------
>Cylindrospermopsis_raciborskii_CS_505_gi_282901708
------------------------------------------------------------
---------------MK----------------------------TR-P-----------
--------------------------------------------------------SPVY
AMASAPTVTP---DQGTQVVRKPYPNYKVIVLNDDFNTFEHVAKSLMKYIPGMTTEQAWE
LTNQVHYEGQAIVWVGPQEQAELYHQQLRRAGLTMAPLEAA-----------
>REF_Synechococcus_7942_ClpS2_REF
------------------------MLPSPFRPQTTIASENVKTASKAAQPKVNSSMSPQP
DESVLSILGVPRPCVKK----------------------------RSRDDA---------
--------------------------------------------------FVLTVLTCSL
QAIAAPATAP---GTTTTRVRQPYPHFRVIVLDDDVNTFQHVAECLLKYIPGMTGDRAWD
LTNQVHYEGAATVWSGPQEQAELYHEQLRREGLTMAPLEAA-----------
>Gloeobacter_violaceus_PCC_7421_gi_37521807
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--MSSATVTP---TKPETSVKALKP-WKVIVLNDDFNTFQHVANCLVKYIPHMHPDRAWK
LTQQVHSEGRAIVWVGPLEQAELYHEQLSREGLTMAPLEQA-----------
>Conexibacter_woesei_DSM_14684_gi_284045641
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MGQTIEK---QRVQGPGSGLGGNWRVIVKNDDHNTFDHVARTLARYIPGVTIAVGYD
YADRIHNSGQAIVWSGQREVAELYWEQLQGAGLTMAPLEQG-----------
>Patulibacter_sp_I11_gi_367468593
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---MSQTIEQ---TRAADPGTGLGGAWNVIVRNDDHNTFDHVATTLARVIPGVNVDAGFR
LADRIHQAGLAVVWTGHKELAEHYWEQLRDAGLTMAPLEQA-----------
>Gloeobacter_violaceus_PCC_7421_gi_37522100
------------------------------------------------------------
---------------MLSSAEAPSPGTVQWAPNGQKAQDRQHRVASVHVTGLAASGYLAV
ASYPASRQPGDVQKRLRWGAIVVSFGYTGTQDDYPHASMERM-----------VLAPAAV
SAPPLPTKTPLDPVKTPEKTPLRWRDWVVRLFNDPVNKFEHVVESLCKHVPGMSQDMAWS
VAWQAHREGVAATYQGPREVAELVCEKLVRDGLISDCCES------------
