>Rubrobacter_xylanophilus_DSM_9941_gi_108803856_ref_YP_643793.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Rubrobacter_xylanophilus_DSM_9941_
mvgsltrdirc-------------------------------------------------
------------------------------------------------------------
----------------------saatktap---------------arktrrapsrep---
---ryrvilhnddwtpmdhvvaalmkvvprlslrravsimleahtkgqavvtrchrelae
lyreglkaeglist-iepdg----------
>Trichodesmium_erythraeum_IMS101_gi_113474895_ref_YP_720956.1__clpS_gene_product__Trichodesmium_erythraeum_IMS101_
------------------------------------------------------------
------------------------------------------------------------
---------------------msietiekp-----------------ttstvrktap---
---hyrvllhnddfnsmeyvvqtlmktvpsltqpqavnimmeahsngialviicalepae
fycenlknhgltst-iepde----------
>Crocosphaera_watsonii_WH_8501_gi_67924069_ref_ZP_00517517.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_8501_
------------------------------------------------------------
------------------------------------------------------------
---------------------mttdviekp---------------ssststvrkpap---
---ryrvllhnddfnsmeyvvqtlmqtvpsitqpqavdimmeahsngtalvitcalepae
fysetlknhgltst-iepde----------
>Microcystis_aeruginosa_PCC_7806_gi_159029424_emb_CAO90801.1__unnamed_protein_product__Microcystis_aeruginosa_PCC_7806_
------------------------------------------------------------
------------------------------------------------------------
---------------------msteviekr-----------------statirkpap---
---ryrvllhnddfnsmeyvvqslmqtiagmtqpqavdimmeahtngtalvitciqehae
fycetlknkgltss-iepde----------
>Synechococcus_sp._PCC_7002_gi_170078877_ref_YP_001735515.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._PCC_7002_
------------------------------------------------------------
------------------------------------------------------------
---------------------mstgvieqr-----------------ststirkpap---
---ryrvllhnddfnsmehvvqtlmqtvagltqpqavsimmeahtngialvitcvqehae
fycetlkmhgltst-iepde----------
>Cyanothece_sp._PCC_7424_gi_218438615_ref_YP_002376944.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7424_
------------------------------------------------------------
------------------------------------------------------------
-------------------mststqvieks-----------------ttstvrkpap---
---ryrvllhnddfnsmeyvvqtlmktvagmtqpqavnimmeahtngtalvitctlehae
fycetlknhgltst-iepde----------
>Lyngbya_sp._PCC_8106_gi_119489795_ref_ZP_01622553.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Lyngbya_sp._PCC_8106_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------meyvvqvllqtvpsltqpqavsimmeahtnglalvitcaqehae
fycetlknngltst-iepde----------
>Nodularia_spumigena_CCY9414_gi_119510879_ref_ZP_01630003.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nodularia_spumigena_CCY9414_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------mehvvqslittvpsltqpqavsimmeahtngmalvitcaqehae
fycetlkshglsst-iepde----------
>Nostoc_sp._PCC_7120_gi_17231817_ref_NP_488365.1__clpS_gene_product__Nostoc_sp._PCC_7120_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekr-------------------stsrklap---
---ryrvllhnddhnsmeyvvqvlittvpsltqpqavsimmeahtnglalvitcaqehae
fycetlkdhglsst-iepde----------
>Anabaena_variabilis_ATCC_29413_gi_75907498_ref_YP_321794.1__clpS_gene_product__Anabaena_variabilis_ATCC_29413_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekr-------------------stsrklap---
---ryrvllhnddynsmeyvvqvlittvpsltqpqavsimmeahtnglalvitcaqehae
fycetlkdhglsst-iepde----------
>Fischerella_sp._JSC-11_gi_354566131_ref_ZP_08985304.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Fischerella_sp._JSC-11_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetqqkr-------------------stsrklap---
---qyrvllhnddyntmeyvvqvllttvpsltqpqavsimmeahsnglalvitcaqepae
fycetlknhgltst-iepee----------
>Arthrospira_maxima_CS-328_gi_209523998_ref_ZP_03272550.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_maxima_CS-328_
----------------------------------------malvcfgidkfpdhcnfvn-
------------------------------------------------------------
----------------ggdgsvstqtvekt-------------------stnrklap---
---ryrvllhnddynpmeyvvqvlmstvpgltqpqavsimmeahtnglalvitcalehae
fycetlknhgltst-iepde----------
>Microcoleus_chthonoplastes_PCC_7420_gi_254414360_ref_ZP_05028127.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Microcoleus_chthonoplastes_PCC_7420_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------meyvvqaliqtvpsltqpqavnimmeahnsgialvitcalehae
fycetlknhgltst-iepde----------
>Nostoc_punctiforme_PCC_73102_gi_186684027_ref_YP_001867223.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nostoc_punctiforme_PCC_73102_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiqkp-------------------sttrklap---
---ryrvllhnddynsmehvvqsliatvpsltqpqavsimmeahtnglalvitcalehae
fycetlishglsst-iepde----------
>Raphidiopsis_brookii_D9_gi_282897015_ref_ZP_06305017.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Raphidiopsis_brookii_D9_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekp-------------------sttrklap---
---ryrvllhnddynsmeyvvqvllstipsltqpqavtimmeahsnglalviscalehae
fyceslnnhgltst-iepdd----------
>Cylindrospermopsis_raciborskii_CS-505_gi_282899028_ref_ZP_06307010.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cylindrospermopsis_raciborskii_CS-505_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekp-------------------sttrklap---
---ryrvllhnddynsmeyvvqvllstipsltqpqavsimmeahshglalviscalehae
fyceslnnygltst-iepdd----------
>Acaryochloris_sp._CCMEE_5410_gi_359457944_ref_ZP_09246507.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Acaryochloris_sp._CCMEE_5410_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetlekr-------------------stgrklap---
---kyrvllhnddfnsmehvvqvliqtvpnltqpqavsvmmeahtngialvitcafehae
fycetlkmhgltst-iepde----------
>Leptolyngbya_valderiana_BDU_20041_gi_148972604_ref_ZP_01811408.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Leptolyngbya_valderiana_BDU_20041_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekr-------------------stvrkhap---
---ryrvllhnddfntmeyvvqtlvktvpgltqpqavsimmeahtngmalvitcaqehae
fycetlrrhglsss-iepdd----------
>Nostoc_azollae_0708_gi_298490087_ref_YP_003720264.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nostoc_azollae_0708_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekr-------------------sttrklap---
---qyrvllhnddynsmeyvvqvlmtsvpsitqpqavnimmeahnsglalvitcaqehae
fycetlkghglsst-iepd-----------
>Cyanothece_sp._PCC_7425_gi_220908775_ref_YP_002484086.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7425_
------------------------------------------------------------
------------------------------------------------------------
---------------------mavetieqr-------------------stvrklap---
---ryrvllhnddvnsmehvvevllktvpsltqpqavdimmeahvngialvitcalehae
fyceslklggltst-iepde----------
>Lyngbya_majuscula_3L_gi_332711797_ref_ZP_08431728.1__hypothetical_protein_LYNGBM3L_67610__Lyngbya_majuscula_3L_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------meyvvktlmetvasltqpqavnimmeahqsglalvitcaqehae
fycetlknrgltst-iepde----------
>Oscillatoria_sp._PCC_6506_gi_300868553_ref_ZP_07113170.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Oscillatoria_sp._PCC_6506_
------------------------------------------------------------
------------------------------------------------------------
---------------------msvetiekr-------------------stvrkiap---
---ryrvllhnddfnsmeyvvqtlmhtvpsltqpqavnimmeahtnglavviicaqehae
fysetlnnhglist-iepde----------
>Microcoleus_vaginatus_FGP-2_gi_334120716_ref_ZP_08494794.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Microcoleus_vaginatus_FGP-2_
------------------------------------------------------------
------------------------------------------------------------
---------------------msveiiqka-------------------stvrklap---
---ryrvllhnddfnpmeyvvqtlmatvpsltqpqavnvmmeahtngmglvivcalehae
fyaetlnnhglsss-iepdd----------
>Thermosynechococcus_elongatus_BP-1_gi_22297755_ref_NP_681002.1__clpS_gene_product__Thermosynechococcus_elongatus_BP-1_
----------------------------------------------------------m-
------------------------------------------------------------
----------------eawptmsvqtiekp-------------------atvrklap---
---ryrvllhndnvnsmeyvvevllktvpsltqpqavdimmeahltgvalvitcalehae
fyceglkmagltst-iepte----------
>Synechococcus_elongatus_PCC_6301_gi_56750848_ref_YP_171549.1__clpS_gene_product__Synechococcus_elongatus_PCC_6301_
------------------------------------------------------------
------------------------------------------------------------
---------------------mavetiqkp-----------------etttkrkiap---
---ryrvllhnddfnpmeyvvmvlmqtvpsltqpqavdimmeahtngtglvitcdiepae
fyceqlkshgleqq-----h----------
>Synechococcus_sp._JA-2-3Ba_2-13__gi_86608169_ref_YP_476931.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._JA-2-3Ba_2-13__
------------------------------------------------------------
------------------------------------------------------------
---------------------matetlvkp-------------------svtpkhmp---
---myrvllhnddvntmeyvvqvlvkvipammppqateimleahhngvavvivvprehae
fyceqlrqhgltss-ieper----------
>Synechococcus_sp._WH_8109_gi_260434316_ref_ZP_05788286.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_8109_
----------------------------------msrsislfplnlkvfgsmvmavdsp-
------------------------------------------------------------
----------------sqkp-ggaavldka------------------pervrkrsp---
---rykvllhndpvnsmeyvvatlqqvvpqlseqdcmavmleahntgvglvivcdiepae
fycemlkskgltss-iepee----------
>Cyanobium_sp._PCC_7001_gi_254430350_ref_ZP_05044053.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanobium_sp._PCC_7001_
-------------------------------------------mtaaamttvpqatqtp-
------------------------------------------------------------
----------------sre--sgaavmeka------------------pervrkpsp---
---rykvllhndpvnsmeyvvttlrqvvpslseqdaiavmleahntgvglvivcdlepae
fycetlkakgltst-lepdd----------
>Prochlorococcus_marinus_subsp._pastoris_str._CCMP1986_gi_33862055_ref_NP_893616.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_subsp._pastoris_str._CCMP1986_
---------------------------------------minrfscnynqkvmsnikfe-
------------------------------------------------------------
----------------kgen-nnaavlekk------------------taplknksp---
---kykvllhndpvnsmeyvtnalrevvpqlseqdaisimleahntgvglvivcdlepae
fyseslkskgisss-ieked----------
>Prochlorococcus_marinus_str._MIT_9211_gi_159904162_ref_YP_001551506.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9211_
-----------------------------------------mslvdwnylptgimveat-
------------------------------------------------------------
----------------gssp-ggatviekq------------------selvrkrsp---
---rykvllhndpvnsmdyvvttlrqvvpqlseqdalavmleahntgvglvivcdlepae
fyseslkakglsst-ieket----------
>Prochlorococcus_marinus_str._NATL2A_gi_72382903_ref_YP_292258.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._NATL2A_
----------------------------------msnimvnslsksaihleslimvdsa-
------------------------------------------------------------
----------------nqtd-gdtavidre------------------vqrvrkisp---
---kykvllhndpvntmdyvveilrqvvpqlseqdalnimlethnngvglvitcdlepae
fyseslkakgltst-ieles----------
>Gloeobacter_violaceus_PCC_7421_gi_37520315_ref_NP_923692.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Gloeobacter_violaceus_PCC_7421_
------------------------------------------------------------
------------------------------------------------------------
---------------------mstetlerk-------------------svqrkpmp---
---lykvllhnddhtpmnyvievlmktipkmqpskarkimleahnggvavvivcalehae
fyseslnrhnltst-yepdc----------
>Oryza_sativa_Japonica_Group_gi_115476544_ref_NP_001061868.1__Os08g0432500__Oryza_sativa_Japonica_Group_
meaavpsrvals-asrlsnhhhha-vgger----------yaiyrgrcpnpaipmalaa-
------------------------------------------------------------
----------------aaapgkgggvldrp-iekv-tpgrqs---efdvrksrkmtp---
---pyrvllhndnynrreyvvqvlmkvipgmtvdnavnimqeahvnglsvviicsqseae
ehctslrgnglrss-iepasgg-------c
>Zea_mays_gi_195652021_gb_ACG45478.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS_containing_protein__Zea_mays_
mmasvpsrvalsaasrlpn--lha-vagdr----------sfiykrrcpslsipmal-s-
------------------------------------------------------------
----------------aaapgkgggvldrp-veki-tpgrqs---efdvkksrkmtp---
---pfrvilhndnhnrreyvvqvlmkvipgmtvdnalsimqeahvnglsvvivcsqseae
ehctslrgnglrss-iepasgg-------c
>Zea_mays_gi_226506038_ref_NP_001150373.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS_containing_protein__Zea_mays_
meaavpsrvalsaasrlpn--pha-vtgdr----------sfiykgrcqslaipmal-s-
------------------------------------------------------------
----------------aaapgkgggvldrp-vekt-tpgrqs---efdvkksrkmsp---
---pyrvilhndnynrreyvvkvlmkvipgmtvdnavnimqeahvnglsvvivcsqseae
ehctslrgnglrss-iepasgg-------c
>Oryza_sativa_Japonica_Group_gi_125603506_gb_EAZ42831.1__hypothetical_protein_OsJ_27419__Oryza_sativa_Japonica_Group_
meaavpsrcg---alrepalqppp-prger----------yaiyrgrcpnpaipmalaa-
------------------------------------------------------------
----------------aaapgkgggvldrp-iekv-tpgrqs---efdvrksrkmtp---
---pyrvllhndnynrreyvvqvlmkvipgmtvdnavnimqeahvnglsvviicsqseae
ehctslrgnglrss-iepasgg-------c
>Brachypodium_distachyon_gi_357147864_ref_XP_003574520.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS-like__Brachypodium_distachyon_
meaavpsrials--arimn-hhvv-aaggr----------ssiyrgrypniaipivv---
------------------------------------------------------------
-----------------taagkgggvldrp-aeki-spgrqs---efdvkksrkmsp---
---pyrvvlhndnenrreyvvqvlmkvipgmtvdnavnimqeahvnglavvivcsqseae
ehctslrgnglrss-iepasgg-------c
>Arabidopsis_thaliana_gi_145326694_ref_NP_001077794.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arabidopsis_thaliana_
metaicgrlala-----psslfns-ksgdk----------hlvskgpcvnrsilmtlst-
------------------------------------------------------------
----------------saalgkgggvldkpiiekt-tpgres---efdlrkskkiap---
---pyrvilhndnfnkreyvvqvlmk------------------------------adae
qhcmqlrgngllss-vepdggg-------c
>Arabidopsis_lyrata_subsp._lyrata_gi_297841589_ref_XP_002888676.1__hypothetical_protein_ARALYDRAFT_894639__Arabidopsis_lyrata_subsp._lyrata_
metaicgrlala-----psslfns-ksgdk----------hlvskgpcvnrgvlmtlst-
------------------------------------------------------------
----------------yaalgkgggvldkpiiekt-tpgres---efdlrkskkmap---
---pyrvilhndnfnkreyvvqvlmkvipgmtvdnavnimqeahinglavvivcaqadae
qhcmqlrgngllss-vepdggg-------c
>Vitis_vinifera_gi_225455872_ref_XP_002274839.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS__Vitis_vinifera_
metaicgrvpls-----pnhffts-ksgdk----------hslsk-qwthrtmlmtvsa-
------------------------------------------------------------
-----------------aapgkgsgvlerptieri-mpgres---efdlrksrkmsp---
---pyrvllhndnynkreyvvqvlmkvipgmtldnavnimqeahhngmsvviicaqvdae
dhcmqlrgngllss-iepasgg-------c
>Populus_trichocarpa_gi_224099343_ref_XP_002311446.1__predicted_protein__Populus_trichocarpa_
metaicgrials-----pnhvfnp-kpgdk----------nsvcrgpcanrgilmaist-
------------------------------------------------------------
-----------------tcsgkgggllekpviert-tpgres---efdlrkskkmap---
---pyrvmlhndnynkreyvvqvlmkvipgmtldnavnimqeahynglsvviicaqadae
ehcmqlrgngllss-iepasgg-------c
>Populus_trichocarpa_gi_224111728_ref_XP_002315955.1__predicted_protein__Populus_trichocarpa_
metaicgrials-----pnhvfnp-kpgdk----------nsvcrgpcasrgilmsisat
vs----------------------------------------------------------
----------------gkgggggggilekpviert-tpgres---efdlrkskkmap---
---pyrvilhndnynkreyvvqvlmkvipgmtldnavnimqeahynglsvviictqadae
ehcmqlrgngllss-iepasgg-------c
>Ricinus_communis_gi_255576515_ref_XP_002529149.1__ATP-dependent_Clp_protease_adaptor_protein_clpS__putative__Ricinus_communis_
------------------------------------------------------malsa-
------------------------------------------------------------
-----------------tgagkgggllekpviekt-tpgres---efdlrksrktap---
---pyrvilhndnynkreyvvqvlmkvipgmtldnavnimqeahynglsvviicaqadae
dhcmqlrgngllss-iepasgg-------c
>Glycine_max_gi_351723283_ref_NP_001234970.1__uncharacterized_protein_LOC100527361__Glycine_max_
mksaicgri-ls-----pnhvf---kpgdt----------hsickgpysnlcvpmavla-
------------------------------------------------------------
-----------------tgpgkgggvlekpviekv-tpgres---efdlkksrksap---
---pyrvilhndnfnkreyvvqvlmkvipgmtldnavnimqeahynglsvviicdqadae
dhctqlrgngllss-iepasgg-------c
>Vitis_vinifera_gi_297737852_emb_CBI27053.3__unnamed_protein_product__Vitis_vinifera_
menaicgrlals-----pnhvfns-ksgdk----------hsllkgpctnrsflmaisa-
------------------------------------------------------------
-----------------sgpgk-ggllerpviekv-tpgres---efdlrksrkiap---
---pyrvilhndnynkreyvvqvlmk------------------------------adae
dhcmqlrgngllss-iepasgg-------c
>Medicago_truncatula_gi_357488429_ref_XP_003614502.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Medicago_truncatula_
mksaicrsmgls-----pnhlf---isgdr----------ysfckgpysnlcvpmavlt-
------------------------------------------------------------
-----------------kgsgkgggilekpvieka-tpgres---efdlkksrktap---
---pyrvilhndnfnkreyvvqvlmkvipgmtldnavnimqeahhngmsvviicaqadae
dhcmqlrgngllss-iepagdg-------c
>Picea_sitchensis_gi_294460817_gb_ADE75982.1__unknown__Picea_sitchensis_
masviysrlilp-----qpqlyqq-ksgek----------isqskgacmnrvfsairst-
------------------------------------------------------------
-----------------spggkgggllerptiekt-tpgres---efdlrksrktsp---
---pyrvllhndnynkreyvvqvlmkvipgmtldtavnimqeahynglavviicaqvdae
ehctqlrgngllss-iepasdg-------c
>Glycine_max_gi_356531226_ref_XP_003534179.1__PREDICTED__ATP-dependent_Clp_protease_adapter_protein_ClpS-like__Glycine_max_
meaalcsalals-----pnqvfnaanpgdk-----------nvplkyskdrsvvmtvaa-
------------------------------------------------------------
----------------tgilgkgggllerptiett-spgres---efdlrksrktsp---
---pyrvllhndnfnkreyvvqvlmkvipgmtidnavnimqeahynglavvivcaqvdae
dhcmqlrgngllss-iepadggg------c
>Physcomitrella_patens_gi_121489819_emb_CAK19331.1__putative_adaptor_protein_ClpS__Physcomitrella_patens_
magslrlfvsipatarh--------fging----------vekaqrvhnrvngrykina-
------------------------------------------------------------
----------------asgpsqgggvldrptidkp-tpgres---efdlkkkkkisp---
---pyrvmlhndnfnkreyvvqvlmkaipgmtvdiavnvmneahinglavvivcpqedae
dycmqlrtngllss-iepas---------c
>Physcomitrella_patens_subsp._patens_gi_168014848_ref_XP_001759963.1__predicted_protein__Physcomitrella_patens_subsp._patens_
------------------------------------------------------------
------------------------------------------------------------
----------------aaapgqgggvmdrptidkp-tpgres---efdlkkkkkmsp---
---pyrvmlhndnfnkreyvvqvllkaipgmtvdiavnvmneahingiavvivcpqedae
dycmqlrtngllss-iepd-----------
>Selaginella_moellendorffii_gi_302761288_ref_XP_002964066.1__hypothetical_protein_SELMODRAFT_142341__Selaginella_moellendorffii_
mactltqvahlwpstsqvsrfntifaeadk-------------chkcftriiashavra-
------------------------------------------------------------
----------------alpgglgggvldkpaietaptpgres---efdlrkkkkmap---
---pyrvilhndnfnrreyvvqvlmkvipgmtldnavnimqeahhnglsvvivcsqedae
ehctqlrangllss-iepasggs------c
>Chlorella_variabilis_gi_307105846_gb_EFN54094.1__hypothetical_protein_CHLNCDRAFT_31972__Chlorella_variabilis_
mticvgqrlggqavagkagdkpptrgawlvpagatrrsaqrrarlhva------------
------------------------------------------------------------
----------------arsagkgggvldrp----gvlpgq-----qrgretrrrrpp---
---syrvllhndnynrreyvvqvlmkvvegttvddavnimqeahinglamvtqcaqdkae
lyceslrlngliat-iepagtggsdgtsss
>Chlamydomonas_reinhardtii_gi_159467236_ref_XP_001691804.1__clp_protease_adaptor_protein__Chlamydomonas_reinhardtii_
m------------mtrspvaglprpcsalqrsgct--lqgafg--tfapqttrtfvvtw-
------------------------------------------------------------
----------------ak-----ggvmdap------tttqqp---asgversqkrpp---
---iykvllhndnynkreyvvkvllkvveqitvddavtcmqeahetgvalvvacpqdnae
ryceglrlngltst-iepgg---------c
>Volvox_carteri_f._nagariensis_gi_302834902_ref_XP_002949013.1__hypothetical_protein_VOLCADRAFT_73976__Volvox_carteri_f._nagariensis_
maasvlrpppvsvasraptaal----avlpgsaclgwrranfgtstllsqttrtcvqmr-
------------------------------------------------------------
----------------ag----vpglldsp------titsep---qqgtdraykrpp---
---iykvflhndnynkreyvvkvllkvveeitvddavtvmqeahetgvalvvacpqenae
ryceglrlngltst-iepag---------r
>Ktedonobacter_racemifer_DSM_44963_gi_298245523_ref_ZP_06969329.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Ktedonobacter_racemifer_DSM_44963_
m-----------------------------------------------------------
------------------------------------------------------------
----------------aqrqcqpsrleirp---------------eevvrqrssllp---
---lykvilfnddyndmlhvvaalletvntltmqeathimltahlngnaivivcphelae
hyqerllgyaltvt-iepe-----------
>Guillardia_theta_gi_57335897_emb_CAH25350.1__hypothetical_protein__Guillardia_theta_
ricacvrsawsfpvafpahlhhpllravcffikwissilwfmmgrqvlaalallplawcf
qaptsflpgtrgitqqtcatlrpavlgkmqleaperikipdtfnpaewgvgggkggfgdg
lggfkvpdsfnpaemekerqggrtavmdrp-------------------sdktdpgk---
---kykvllfnddkntrqyvidtlmkyipgmtadkakeitvaahntgmaivgvwmyemae
aysdvlrsaglrsd-idpe-----------
>Trichodesmium_erythraeum_IMS101_gi_113477268_ref_YP_723329.1__clpS_gene_product__Trichodesmium_erythraeum_IMS101_
mslgisii----------------------------------------------------
------------------------------------------------------------
----------------------giieniavrggasspttlap---kkdsqvvnkpyp---
---nykvivlnddvntfkhvaeclqkyipgmtsdraweltyqvhnegqaivwvgpleqae
lyhqqlsragltmapleka-----------
>Lyngbya_sp._PCC_8106_gi_119490026_ref_ZP_01622650.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Lyngbya_sp._PCC_8106_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mtssptvap---srssqvtqqpyp---
---nykvivlnddfntfehvssclmkyipgmnsdlawkltnqvhfegqatvwvgpleqae
lyhtqlsregltmapleka-----------
>Oscillatoria_sp._PCC_6506_gi_300864591_ref_ZP_07109450.1__ATP-dependent_Clp_protease_adaptor__Oscillatoria_sp._PCC_6506_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mtssptiap---drssqvtrkpyp---
---nykvivlnddfntfqhvseclvkyipgmtsdrawkltnqvhyegqatvwvgpqeqae
lyhmqlsragltmapleqa-----------
>Microcoleus_vaginatus_FGP-2_gi_334119600_ref_ZP_08493685.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Microcoleus_vaginatus_FGP-2_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mtssptiap---vrssqvtrkpyp---
---nyrvivlnddfntfqhvvecltkyipgmtsdqawklanqihhegqatvwvgpqeqae
lyhmqlsragltmaplest-----------
>Arthrospira_maxima_CS-328_gi_209526864_ref_ZP_03275384.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_maxima_CS-328_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------miasptttp---srssqtvrkpyp---
---nykvivlnddfntfqhvanclmkylpgmtsdqaweltnrvhyegqatvwvgpleqae
lyhtqlsregltmapleka-----------
>Arthrospira_platensis_NIES-39_gi_291567197_dbj_BAI89469.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_platensis_NIES-39_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mvasptttp---srssqtvrkpyp---
---nykvivlnddfntfqhvanclmkylpgmtsdqaweltnrvhyegqatvwvgpleqae
lyhtqlsregltmapleka-----------
>Arthrospira_platensis_str._Paraca_gi_284051855_ref_ZP_06382065.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Arthrospira_platensis_str._Paraca_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------mtsdqaweltnrvhyegqatvwvgpleqae
lyhtqlsregltmapleka-----------
>Nodularia_spumigena_CCY9414_gi_119510612_ref_ZP_01629742.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nodularia_spumigena_CCY9414_
mvtrls------------------------------------------------------
------------------------------------------------------------
----------------------------aavygagtaptvtp---gkttevvrktyp---
---nykvivlnddfntfqhvseclmkyipgmtgdrawdltnqihyegqaivwvgpqemae
lyhqqlrragltmapleaa-----------
>Nostoc_sp._PCC_7120_gi_17227900_ref_NP_484448.1__clpS_gene_product__Nostoc_sp._PCC_7120_
mvtkls------------------------------------------------------
------------------------------------------------------------
----------------------------idvyamstaptvtp---ersnqtvrktyp---
---nykvivlnddfntfqhvaeclvkyipgmtgdlawdltnqvhyegqaivwvgpqepae
lyhqqlrragltmapleaa-----------
>Anabaena_variabilis_ATCC_29413_gi_75909055_ref_YP_323351.1__clpS_gene_product__Anabaena_variabilis_ATCC_29413_
mvtkls------------------------------------------------------
------------------------------------------------------------
----------------------------idvyamstaptvtp---ersnqtvrksyp---
---nykvivlnddfntfqhvaeclvkyipgmtgdlawdltnqvhyegqaivwvgpqepae
lyhqqlrragltmapleaa-----------
>Nostoc_punctiforme_PCC_73102_gi_186684201_ref_YP_001867397.1__ATP-dependent_Clp_protease_adaptor__Nostoc_punctiforme_PCC_73102_
mvrnls------------------------------------------------------
------------------------------------------------------------
----------------------------advygmttaptitp---erssqvtrktyp---
---nykvivlnddfntfqhvaeclmkyipgmsgdrawdltnqvhyegqaivwvgpqepae
lyhqqlrragltmapleaa-----------
>Nostoc_azollae_0708_gi_298491120_ref_YP_003721297.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Nostoc_azollae_0708_
metrla------------------------------------------------------
------------------------------------------------------------
----------------------------avyydmataptvtp---drvnqvtrktyp---
---nykvivlnddfntfqyvaeclmkyipgmsgdlawdltnqvhyegqaivwvgpqepae
lyhqqlrragltmaplega-----------
>Fischerella_sp._JSC-11_gi_354566811_ref_ZP_08985982.1__ATP-dependent_Clp_protease_adapter_protein_clpS__Fischerella_sp._JSC-11_
mitkls------------------------------------------------------
------------------------------------------------------------
----------------------------aavyamaatptiap---erstqvtrkpyp---
---nykvivlnddfntfqhvaeclvkyipgmtsdraweltnqvhyegqaivwtgpqepae
lyhqqlrragltmapleaa-----------
>Cyanothece_sp._CCY0110_gi_126656780_ref_ZP_01727994.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._CCY0110_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------matststap---kgstvidrkpyp---
---nykvivlnddfntfnhvanclmkyipgmssdrawelteqvhfeglaivwtgpqeqae
lyhqqlrregltmapleea-----------
>Cyanothece_sp._ATCC_51142_gi_172038476_ref_YP_001804977.1__putative_ATP-dependent_Clp_protease_adaptor_protein__Cyanothece_sp._ATCC_51142_
mskrls------------------------------------------------------
------------------------------------------------------------
----------------------------tgiqgmatststap---kgstvidrkpyp---
---nykvivlnddfntfnhvanclmkyipgmssdrawelteqvhfeglaivwtgpqeqae
lyhqqlrregltmapleea-----------
>Crocosphaera_watsonii_WH_0003_gi_357261617_gb_EHJ10864.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_0003_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------matststap---kgatvverkhyp---
---nykvivlnddfntfdhvakcllkyipgmssdrawelteqvhfeglatvwtgpqeqae
lyhqqlrregltmapleea-----------
>Crocosphaera_watsonii_WH_8501_gi_67924463_ref_ZP_00517887.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Crocosphaera_watsonii_WH_8501_
mskrls------------------------------------------------------
------------------------------------------------------------
----------------------------igirgmatststap---kgatvverkryp---
---nykvivlnddfntfdhvakcllkyipgmssdrawelteqvhfeglatvwtgpqeqae
lyhqqlrregltmapleea-----------
>Microcystis_aeruginosa_PCC_7806_gi_159031002_emb_CAO88704.1__clpS__Microcystis_aeruginosa_PCC_7806_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------masapsttl---dkstqgvkktyp---
---nykvivlnddfntfdhvanclikyipdmttdraweltnqvhyqgqaivwtgpqepae
lyhqqlrregltmapleav-----------
>Cyanothece_sp._PCC_8801_gi_218246561_ref_YP_002371932.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_8801_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------matapsvap---kgstavvnkpyp---
---nykvivlnddfnsfehvakclmtyipgmtsdraweltnqvhfegqatvwvgpqeqae
lyhqqlrregltmapleka-----------
>Cyanothece_sp._PCC_7424_gi_218441397_ref_YP_002379726.1__ATP-dependent_Clp_protease_adaptor__Cyanothece_sp._PCC_7424_
mstnva------------------------------------------------------
------------------------------------------------------------
----------------------------avvtamttaptiap---dkttqvvkktyp---
---nykvivlnddfntfqhvanclmkyipgmtsdraweltnqvhyegqatvwvgpqeqae
lyhqqlrregltmapleaa-----------
>Cyanothece_sp._PCC_7822_gi_307150152_ref_YP_003885536.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7822_
mstnva------------------------------------------------------
------------------------------------------------------------
----------------------------avvkamataptvap---dkttqvvkktyp---
---nykvivlnddfntfehvakclmkyipgmtsdraweltnqvhfegqaivwvgpqeqae
lyhqqlrregltlapleaa-----------
>Microcoleus_chthonoplastes_PCC_7420_gi_254412762_ref_ZP_05026535.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Microcoleus_chthonoplastes_PCC_7420_
mtvvis------------------------------------------------------
------------------------------------------------------------
----------------------------aarsatsaaptqap---eksrqvtrkpyp---
---nykvivldddfntfqhvhdclvkyipgmssdyawkltnqvhfegqaivwvgpqeqae
lyhqqlsragltmapleaa-----------
>Lyngbya_majuscula_3L_gi_332708950_ref_ZP_08428921.1__hypothetical_protein_LYNGBM3L_32060__Lyngbya_majuscula_3L_
--mvrs------------------------------------------------------
------------------------------------------------------------
----------------------------aaykatfaapvkap---ersgqvtrkpyp---
---kykvivldddfntfqhvhdclvkyipgmtndhawelthqvhnegqaivwvgpqeqae
lyhqqlsragltmapleat-----------
>Raphidiopsis_brookii_D9_gi_282895992_ref_ZP_06304023.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Raphidiopsis_brookii_D9_
m-ktrp------------------------------------------------------
------------------------------------------------------------
----------------------------spiyamapaptvtp---dqgtqvirkpyp---
---nykiivlnddfntfehvakslmkyipgmtteqaweltnqvhyegqaivwvgpqeqae
lyhqqlrragltmapleaa-----------
>Cylindrospermopsis_raciborskii_CS-505_gi_282901708_ref_ZP_06309624.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cylindrospermopsis_raciborskii_CS-505_
m-ktrp------------------------------------------------------
------------------------------------------------------------
----------------------------spvyamasaptvtp---dqgtqvvrkpyp---
---nykvivlnddfntfehvakslmkyipgmtteqaweltnqvhyegqaivwvgpqeqae
lyhqqlrragltmapleaa-----------
>Thermosynechococcus_elongatus_BP-1_gi_22298631_ref_NP_681878.1__clpS_gene_product__Thermosynechococcus_elongatus_BP-1_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------mpsvvp---qerqqvtrkhyp---
---nykvivlnddfntfqhvaaclmkyipnmtsdraweltnqvhyegqaivwvgpqeqae
lyheqllragltmaplepe-----------
>Synechocystis_sp._PCC_6803_gi_16330271_ref_NP_440999.1__ATP-dependent_Clp_protease_adaptor__Synechocystis_sp._PCC_6803_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------misnaatstp---drltstvrktyp---
---nfkvivlnddfntfqhvsdcllkyipgmtgdraweltnqvhfdglaivwvgpqeqae
lyhqqlrregltmapleka-----------
>Synechococcus_sp._PCC_7002_gi_170078679_ref_YP_001735317.1__putative_ATP-dependent_Clp_protease_adaptor_protein__Synechococcus_sp._PCC_7002_
------------------------------------------------------------
------------------------------------------------------------
---------------------------------mapapgilk---esdrqtvrkpyp---
---nfkvivlnddfntfehvahclmtyipnmtadqawnltnqvhfdgqaivwvgpqepae
lyhqqlrregltmapleaa-----------
>Synechococcus_sp._PCC_7335_gi_254421403_ref_ZP_05035121.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._PCC_7335_
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------mlnddfntfehvvktlttyipgmnsdqaweladqihnegqaivwtgpleqae
lyhsqliragltvapleka-----------
>Acaryochloris_sp._CCMEE_5410_gi_359459224_ref_ZP_09247787.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Acaryochloris_sp._CCMEE_5410_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------maitavqtpvtrp-eekqaqktvrkpyp---
---nfkvivvnddvntfehvaktlmtyiphmtsdkaweltnqihfegqaivwvgpqeqae
lyhmqlqragltmapleaa-----------
>Synechococcus_elongatus_PCC_6301_gi_56751052_ref_YP_171753.1__clpS_gene_product__Synechococcus_elongatus_PCC_6301_
mspqpdesvlsilgvprpcvkkrsrnda--------------------------------
------------------------------------------------------------
----------------------fvltvltcslqaiaapatap---gttttrvrqpyp---
---hfrvivldddvntfqhvaecllkyipgmtgdrawdltnqvhyegaatvwsgpqeqae
lyheqlrregltmapleaa-----------
>Synechococcus_elongatus_PCC_7942_gi_81299287_ref_YP_399495.1__clpS_gene_product__Synechococcus_elongatus_PCC_7942_
mspqpdesvlsilgvprpcvkkrsrdda--------------------------------
------------------------------------------------------------
----------------------fvltvltcslqaiaapatap---gttttrvrqpyp---
---hfrvivldddvntfqhvaecllkyipgmtgdrawdltnqvhyegaatvwsgpqeqae
lyheqlrregltmapleaa-----------
>Cyanothece_sp._PCC_7425_gi_220909224_ref_YP_002484535.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Cyanothece_sp._PCC_7425_
mvrpiqts----------------------------------------------------
------------------------------------------------------------
----------------------------slsplavatprqsp-tpvqdrqtirqpyp---
---hykvivlnddfntfehvakclmkyipnmtsdraweltyqvdregqaivwvgpqeqae
lyhlqlgqagltmaplela-----------
>Gloeobacter_violaceus_PCC_7421_gi_37521807_ref_NP_925184.1__ATP-dependent_Clp_protease_adaptor__Gloeobacter_violaceus_PCC_7421_
------------------------------------------------------------
------------------------------------------------------------
----------------------------------mssatvtp---tkpetsvkalkp---
----wkvivlnddfntfqhvanclvkyiphmhpdrawkltqqvhsegraivwvgpleqae
lyheqlsregltmapleqa-----------
>Synechococcus_sp._JA-3-3Ab_gi_86606056_ref_YP_474819.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._JA-3-3Ab_
m-----------------------------------------------------------
------------------------------------------------------------
------------------------------tteaptrpaqqs---spsrtrvrqpyp---
---hfkvivldddfntfqhvtecllkyipgmtlplarqltvqvdaegqavvwvgpqeqae
lyhqqllregltmaplepa-----------
>Synechococcus_sp._JA-2-3Ba_2-13__gi_86610000_ref_YP_478762.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._JA-2-3Ba_2-13__
m-----------------------------------------------------------
------------------------------------------------------------
------------------------------tteaptrpaqqf---spsrtqvrqpyp---
---hfkvivldddfntfqhvtecllkyipgmtlplarqltvqvdaegqavvwvgpqeqae
lyhqqllregltmaplepa-----------
>Synechococcus_sp._CC9311_gi_113955042_ref_YP_730629.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CC9311_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------mtmatpgtas---vlqperttlryp---
---narvivlnddvntfehvveclckiipgmnsdkawtlahqidgegaaevwagplepae
lyhqqlssegltmaplern-----------
>Synechococcus_sp._WH_8102_gi_33865838_ref_NP_897397.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._WH_8102_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------msssspgsas---llerqtitqryp---
---qarvivldddvntfqhvvdclrkiipgmseekawslanridgqgsaevwcgpleqae
lyhqqlaaegltmaplerc-----------
>Prochlorococcus_marinus_str._MIT_9303_gi_124023254_ref_YP_001017561.1__ATP-dependent_Clp_protease_adaptor__Prochlorococcus_marinus_str._MIT_9303_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------mtfatpgstp---llerakqtqryp---
---qarvivlnddvntfqhvvdclrriipgmseerawnlahqidgqgsaevwcgpleqae
lyhqqlsgegltmaplerc-----------
>Synechococcus_sp._RS9916_gi_116074794_ref_ZP_01472055.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._RS9916_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------mtgssgaqst---llersrttqgyp---
---earvivlnddvntfqhvvdclckiipgmgterawdlahqvdgqgsaevwcgpleqae
lyhqqltgegltmapierc-----------
>Synechococcus_sp._WH_7805_gi_88808607_ref_ZP_01124117.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Synechococcus_sp._WH_7805_
myllvqascsral-----------------------------------------------
------------------------------------------------------------
--------------------------------mtssspgvst---vlerdrqalryp---
---qarvivlnddvntfehvveslcriipgmntdkawalarrvdgegsaevwcgpleqae
lyhqqlgadgltmapierc-----------
>Synechococcus_sp._RS9917_gi_87124406_ref_ZP_01080255.1__hypothetical_protein_RS9917_12370__Synechococcus_sp._RS9917_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------mtvtptgtat---vldratsrsdyp---
---qarvivldddvntfqhvvdclcriipgmgserawdlahridsegaadvwsgpleqae
lyhqqlsaegltmaplerc-----------
>Synechococcus_sp._RCC307_gi_148242507_ref_YP_001227664.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._RCC307_
------------------------------------------------------------
------------------------------------------------------------
--------------------------------mtssapsrqt---agstllerapyp---
---nfkvvvlndevntfqhvvdclvkyipamdpdrawslaqqidsdgqavvwvgpqeqae
lyhmqlgaegltmaplera-----------
>Synechococcus_sp._WH_5701_gi_87302745_ref_ZP_01085556.1__hypothetical_protein_WH5701_13370__Synechococcus_sp._WH_5701_
------------------------------------------------------------
------------------------------------------------------------
----------------------------------maapgvqt---ipagirqrqryp---
---hlrvvvldddvntfqhvvnclvrylpgmgpdrawelahqidsqgsavvwsgpqeqae
lyhqqlsqegltmaplere-----------
>Synechococcus_sp._CB0205_gi_317970016_ref_ZP_07971406.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CB0205_
m-----------------------------------------------------------
------------------------------------------------------------
----------------------------qpirsissspggqa---vmerqrvrapyp---
---tgrvivldddhntfqhvvevlvkhipamvsdrawelahqidsqgsavvwsgpleqae
lyhqllagegltmapverg-----------
>Synechococcus_sp._CB0101_gi_318041538_ref_ZP_07973494.1__ATP-dependent_Clp_protease_adaptor__Synechococcus_sp._CB0101_
m-----------------------------------------------------------
------------------------------------------------------------
--------------------------------------aqqa---vrdkqrvdapyp---
---tgrvivldddhntfqhvvevlvryipamtsdrawelahqidgqgsalvwsgpleqae
lyhqqlgaegltmaplerg-----------
>Prochlorococcus_marinus_str._MIT_9202_gi_254526218_ref_ZP_05138270.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Prochlorococcus_marinus_str._MIT_9202_
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------mfnslsi---vldqkkskakyp---
---earvivlddssntfqhvaycfltiipsmserrawnltikvdktgsaevwrgnleqae
lyheqllskgltmapiekt-----------
>Prochlorococcus_marinus_str._MIT_9211_gi_159904055_ref_YP_001551399.1__hypothetical_protein_P9211_15141__Prochlorococcus_marinus_str._MIT_9211_
----------------------------mretkrrnqcsrrahqkdasrngrplllmmd-
------------------------------------------------------------
----------------kkimtrhtkdfvattamkfsansttt---vldpkttkkkyp---
---eariivlddnfntfehvanclvtiipgmsekrswvlavevdreglaevwrgpleqae
lyhqqliskgltmapiekt-----------
>cyanobacterium_UCYN-A_gi_284928874_ref_YP_003421396.1__hypothetical_protein_UCYN_02930__cyanobacterium_UCYN-A_
mfkrl-------------------------------------------------------
------------------------------------------------------------
-----------------------------sitipetsistni---khsavidykpyp---
---nckiivlnddfntfdhvancliryipamtkshaweltqkihfngfatvwmgpleqae
lyhqqlrregltmaplegi-----------
>Conexibacter_woesei_DSM_14684_gi_284045641_ref_YP_003395981.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Conexibacter_woesei_DSM_14684_
m-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------gqtiekqrvqgpgsg
lggnwrvivknddhntfdhvartlaryipgvtiavgydyadrihnsgqaivwsgqrevae
lyweqlqgagltmapleqg-----------
>Patulibacter_sp._I11_gi_367468593_ref_ZP_09468447.1__ATP-dependent_Clp_protease_adaptor_protein_ClpS__Patulibacter_sp._I11_
m-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------------sqtieqtraadpgtg
lggawnvivrnddhntfdhvattlarvipgvnvdagfrladrihqaglavvwtghkelae
hyweqlrdagltmapleqa-----------
>Gloeobacter_violaceus_PCC_7421_gi_37522100_ref_NP_925477.1__hypothetical_protein_gll2531__Gloeobacter_violaceus_PCC_7421_
mlssaeapspgtvqwapngqkaqdrqhrvasvhvtglaasgylavasypasrqpgdvqkr
lrwgaivvsfgytgtqdd------------------------------------------
----------------yphasmermvlapaavsapplptktpldpvktpektplrwr---
---dwvvrlfndpvnkfehvveslckhvpgmsqdmawsvawqahregvaatyqgprevae
lvceklvrdglisdcces------------
>Arabidopsis_thaliana_ClpS_REF
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRSILMTLSTSAALGKGGGVLDKPIIEKTTPGRESEFDLRKSKKIAPPYRVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIMQEAHINGLAVVIVCAQADAEQHCMQLRGNGLLSSVEPDGGGC
>Synechococcus_7942_ClpS1_REF
MAVETIQKPETTTKRKIAPRYRVLLHNDDFNPMEYVVMVLMQTVPSLTQPQAVDIMMEAHTNGTGLVITCDIEPAEFYCEQLKSHGLEQQH
>Synechococcus_7942_ClpS2_REF
MLPSPFRPQTTIASENVKTASKAAQPKVNSSMSPQPDESVLSILGVPRPCVKKRSRDDAFVLTVLTCSLQAIAAPATAPGTTTTRVRQPYPHFRVIVLDDDVNTFQHVAECLLKYIPGMTGDRAWDLTNQVHYEGAATVWSGPQEQAELYHEQLRREGLTMAPLEAA
