>gnl|BL_ORD_ID|1599 @Cyanobium_sp_PCC_7001@ 647589884 CPCC7001_240 ATP-dependent Clp protease adaptor protein ClpS [Cyanobium sp. PCC 7001]
MTAAAMTTV---------------------------------------------------
--------------------------------------------PQATQTPSRESGAAVM
EKAPERV--RKPSPRYKV-LLHN--------DPVNSM-----------------EYVVTT
LRQVVPSLSEQDAIAVMLEAH-------------NTGVGLVIVCDL--EP---AEFYCET
LKAKGLTSTLEPDD
>gnl|BL_ORD_ID|804 @Cyanobium_sp_PCC_7001@ 647589066 CPCC7001_441 GTP cyclohydrolase I [Cyanobium sp. PCC 7001]
MTSTLPSSFSAKGSAPAATPLPVSLRIRDRLEKAGVSFFANDNIADHLLDGELDQLEIEV
AGKVRELLRSLVIDIDNDHNTEETAERVARMYLHEVFKGRYHEQPKIASFPNVKKLDEIY
TVGPISV--RSACSHHLVPILGNCWIGIKPGDQVIGLSKFSRVADWVFSRPHIQEEAVMI
LADEIERLCKPQGLAILVKAQHYCMKWRGVKEPQTSMVNSIVRGDFRHDPSLKAEFFELV
KQQEALLST-----
