>gnl|BL_ORD_ID|1886 @Prochlorococcus_marinus_NATL2A@ gi|72382903|ref|YP_292258.1| ATP-dependent Clp protease adaptor protein ClpS [Prochlorococcus marinus str. NATL2A]
MSNI--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MVNSLSKSAI
HL----------------------------------------------------------
------------------------------------------------------------
---ESLIMVDSANQTDGDTAV---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------IDR-------------------------------------------
----------EVQRVRKISPKYKVL-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------LHNDPVNTMDYVVEILRQVVPQLSEQDALNIMLETHNNG-----------
-----------------------------------------------------VGLVITC
D-------LEPAEFYS--------------------------------------------
---------ESLKAKGLTSTIELE------------------------------------
------------------------------------------------------------
-S
>gnl|BL_ORD_ID|1348 @Prochlorococcus_marinus_NATL2A@ gi|161347556|ref|YP_291789.2| ATP-dependent Clp protease adaptor [Prochlorococcus marinus str. NATL2A]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------KFSTNSTTTV---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------LDP-------------------------------------------
----------KTTKIK--YPEARII-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------VLDDNFNTFEHVANCLVTIIPGMSEKRSWELAVEVDREG-----------
-----------------------------------------------------LAEVWRG
P-------FEQAELYH--------------------------------------------
---------QQLISKGLTMAPIEK------------------------------------
------------------------------------------------------------
-T
>gnl|BL_ORD_ID|952 @Prochlorococcus_marinus_NATL2A@ gi|72382171|ref|YP_291526.1| hydrogenobyrinic acid a,c-diamide cobaltochelatase [Prochlorococcus marinus str. NATL2A]
MHRIASLPGNDPQEEITFIEQPNAPVIFLTSATSDITCLSSVLKQPKNKKWRNKIRALPI
AYLSSNASIDHYISNTCNTAEIVIVRFLGSRSYWSYGFEQLSLWQLEKPNRQLIVVSGIE
STANDLKDISSIKKVQVDFIQLLLNEGGLKNYNYLLKVLDNLKSLEEIKVERDLIEYHDD
LVKWKWIDNDYPKIAIFLYKSLLQSGNTELADSIVEISKRHQINAKIVWITSFKSKDIQK
EIINLLDNEKIEAIITTTSFSSVEYKNDNIKNSLWDTLDVPVYQLLISSSTVNEWKKSTV
GLNPIDLSIQVVLPEVDGRICTVPIAFKNLSYIDNELSISVYKTEPYGKHIEWCINYIKN
LVYLRKSSNFNKKIAVVIANYPVKDSRIANGVGLDTPESLMYLLRWLKDEGYYLGDSTLP
RTSKELINKLITYRTNSEETISNEPQSYLSLVDYLYHWNKMESNAKEKLIKRWGEPNFSK
QLEESGFPINGFTLGNITVLVQASRGFESDNLSDLHSPDLPPTHKYIAQYFWLTHSFKAN
AIIHLGKHGSVEWLPGKGVGLSSNCFPFIICPPVPNIYPFIVNDPGEGSQAKRRTHAIII
DHLTPPLSHAGSYNELIEIENLIDEYYESKLINDNRNELLEKKIIELLIKNSWPSIDPNI
IKDDMKKINIQEIIDTAESYLCELKQSQIRTGLHIFGVNLSMDKLIELTLAISNVPTGNI
AGLSQCLAEDLGFTIDPWRDEESLDLTQIDINLFKKYTSINARKVGQLIDWFNEIGMYII
EFHCIHILNLETTVKNKIELDSKLLKYLDIENPNIFINHLITNILPRLLKSSKTEKTNLL
KALEGKRIASGPSGAPTRGKLEVLPTGKNFFSVDIRAIPTETAWDLGKRSAEKLVDLYLQ
ENGEHLLHLAISIWGTSTMRNGGEDICQLFALMGLMPIWDGTLRRVVDVEVIPMSVLNRP
RVDVTLRISGLFRDAFPQIIELIRRGQNLIGNLNEPNAINPLAESYRNGKTDSRIYGSAP
GSYGAGLQEIINNGSWDHQSELANAFIEWSKWRYEGSNNIVKDKKGLEYNLSKVKVVLHS
QDNREHDILDSDDYYQFQGGLISAVKKTSGNNPQAYFADNSRYQRPRIHKLSKEIDKVVR
SRLLNPKWLEGMKQHGYKGAFEMSASLDYLFSFDATTNLVPNWCYESIANNWLVDEKTRK
FIIDNNPWALRDIAERLLEASNRKLWTDATNEEIASIKSALSDIDSKIEKFNSNRRNNKS
AS
