>gnl|BL_ORD_ID|210 @Thermosynechococcus_elongatus_BP_1@ 637312816 tll0211 ATP-dependent Clp protease adaptor protein ClpS [Thermosynechococcus elongatus BP-1]
MEAWPTM-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------SVQTIEKPATV-
-RKLA-------------------------------------------------------
------------------------------------------------------------
--------------------------PRYRVLLHNDNVNSMEYV----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------VEVLLKTVPSL-----------TQP-------Q
AVD---------------------------------------------------IMMEAH
LTGVALVITCALEHA---------------------------------------------
------------------EFYCEGLKMAGLTSTIEPTE
>gnl|BL_ORD_ID|1087 @Thermosynechococcus_elongatus_BP_1@ 637313706 tsr1087 ATP-dependent Clp protease adaptor protein ClpS [Thermosynechococcus elongatus BP-1]
MP----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------SVVPQERQQVT-
-RKHY-------------------------------------------------------
------------------------------------------------------------
--------------------------PNYKVIVLNDDFNTFQHV----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------AACLMKYIPNM-----------TSD-------R
AWE---------------------------------------------------LTNQVH
YEGQAIVWVGPQEQA---------------------------------------------
------------------ELYHEQLLRAGLTMAPLEPE
>gnl|BL_ORD_ID|632 @Thermosynechococcus_elongatus_BP_1@ 637313248 tll0634 GDP-mannose 4,6-dehydratase [Thermosynechococcus elongatus BP-1]
MGDRKRA-----------------------------------------------------
-------------------------------------------------LITGITGQDGS
YLSELLLEKGYEVHGIIRRTSTFNTDRIDHIYVDPHQEGATLRLHYGDLTD---------
------------------------------GSTLRRIIELSQPDEIYNLGAQSHVRVSFD
APQYTVDTVAMGTLR-------LLEAIREYQERTGKQVKFYQAGSSEMFGLVQEVPQRET
TPFYPR-------SPYACAKVYAHWQTVNYREAYNLFAC----NGILFNHESPRRGETFV
TRKITRAVARIV---AGQQNKLYLGNLDAKRDWGYAKDYVRAMWLMLQQEQ---------
------------------------------------------------------------
--------------------------PDDYVVATGETHSVREFL----------------
----------ELAFGYVDLNWEDYVEFDPRYLRPTEVDLLLGDPTK--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------AKTVLGWQPSV-----------TFP-------E
LVA---------------------------------------------------LMVEAD
LHAVGIQGTTPKTTS---------------------------------------------
------------------DTVLDLIAQRQLISKA---D
>gnl|BL_ORD_ID|1196 @Thermosynechococcus_elongatus_BP_1@ 637313817 tlr1197 permease protein of oligopeptide ABC transporter [Thermosynechococcus elongatus BP-1]
MSRLRALQGYLLLRLLLA------------------------------------------
---------------------------------------PLMLWTIVTVVFLLLRATPGD
PVDAILGPRAPAAVKEALREQLGLAQPLWQQYLN--------------------------
-------------YLGQLLRFDLGTSLTSQGEAVTRIIAKHFPATAELGLVSLAIALGLG
VLIGSLAAVKSGTAWDIAGRLFGIITYALPLFWFGMLLQLLFAVNLRWLPLGSRYPITET
PPQGPT---GLYMLDALLNGNLHQLGTAFTYLLLPAITLAIVLSGIFERIVRVNLKQTLV
ADYVEAARARGI------------------------------------------------
------------------------------------------------------------
--------------------------PEHRILIHHALKNALIPV----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------ITVLGFTLASLLGGAVLTEVTFSWPGLGQRLYE
AIT---------------------------------------------------LRDYPT
VQGIVVFFAVIVVAA---------------------------------------------
------------------SILIDVLNA---WIDPRIHY
>gnl|BL_ORD_ID|111 @Thermosynechococcus_elongatus_BP_1@ 637312714 tlr0112 hypothetical protein [Thermosynechococcus elongatus BP-1]
MRTL--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----TVAAIQAQLTDDVETNILHLSDLVRQAHQRGAQLIVL-------------------
----PELFEGHYFCKEEREIHFQRAHPVKKHPTIAHFEALARELEVVIPVSFFEKAGTVY
YNSVAMIDAGGVNLGVYRKSHIPDGPGYEEKFYFRPGN---------TGFRVWRTRYGRI
GVGICWDQWFPEAARVMTLMGAEVLVYPTAIGSEPHDPTLDTKD----------------
--------------------------PWQRVMVGHAVANV--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------IPVVAANRVGNEGGQVFYGSSFIANPRGDLVAE
ADR---------------------------------------------------SQEAVL
VHKFDLGEIERLRAAYGFFRDRRP------------------------------------
------------------GLYKALLTADGVI-------
