>Synechococcus_7942_ClpS2
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------LPSPFRPQT----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------TIAS--------------------------
------------------------------------------------------------
-----------------------------------------------------ENVKTAS
KAAQ----------PKVNSSMSPQPDESVLSILGVPRPC--------------------V
KKRSRDDAFVLTVLTCSL---------------------QAIAAPATA--PGTTTTRVRQ
PYPHFRVIV----LDDDVN--TFQHVAEC-------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------LLKY----
-IPGMTGDRAWDLTNQVH------------------------------------------
-------------------------------------------------YEGAATVWSGP
QEQAELYHEQLRREGL--------------------------------------------
-----TMAPLEAA
>Synechococcus_7942_ClpS2
ML----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------PSP------------------------------------
---------FRPQ-----------------------------------------------
-----TTIASENVKTASK-----------------AAQPKVNSSMSPQPDESVLSI----
------------------------------------------------------------
-----------------------LGVPRPCVKKRSRDDAFVL------------------
-----TVLTCSLQAIAAPATAPGTTTTRVRQPYPHFRVI---------------------
-------------------VLDDDVNTFQHVAECLLKYIPGMT-GDRAWDLTNQVHYEGA
ATV-------WSGPQEQAELYHEQLRREGLT-------------------MAPLEA----
------------------------------------------------------------
----------------------------------A
>gnl|BL_ORD_ID|2964 @Anaeromyxobacter_dehalogenans_2CP_1@ gi|220918088|ref|YP_002493392.1| response regulator receiver protein [Anaeromyxobacter dehalogenans 2CP-1]
M-----------------------------------------------------------
----------------TGP--------------RVLVVDDNDALRENVAECLEGEGYAVD
LAGGGAAALELLEHEPLPAVIILDLMMPGMDGGALAAAIRADPRWAGIRLVITTGLSVSR
VRELPVDAVLMKPFGVDELL-AVLKRVG--------A
>gnl|BL_ORD_ID|167 @Aquifex_aeolicus_VF5@ gi|15605776|ref|NP_213153.1| polynucleotide phosphorylase/polyadenylase [Aquifex aeolicus VF5]
MSVEEKARIGNSEEPIIIETGKYAKLTDGSVVVRQGGTAVLVTAVMSDEPITDVDFTPLA
VDYRERASAYGRIPGGFTKREGKPTDREILVSRVIDRPIRPLFPEGFFHDVIITALTLSA
DDKYDPDVLAITGASAALHISRIPFEGPIAGVRVCRVNGEFVANPTYEQRKEADLDIVMA
GTKDAIVMVEGGGKEIPEEVLADALFFGLDAIKEVIEAQERLREKVGKPKFEYQKVELPE
DILKALEEECTPKILEAFNIKDKKERYSTLDKIVEEFIEAHQIPEELHFAVKYFYKKLES
RLMREKVLKEGVRIDGRKPNEIRPIWIEVHPFERPHGNAIFTRGQTQAYVTVTLGTPDEA
LIIETIAEGEVFKRFMLHYSMPPFSVGEAKPWGPPRRREIGHGALAERAIEPLLPPEEEY
PFIIRVVSDILESNGSTSMATVCGASLALFDAGVPMKDNKHVAGIAMGLILEKDRYVILS
DILGDEDHLGDMDFKVAGTKDGITSVQMDIKVKGITKEIMLDALKQAREGRLYILEKMYE
AIPEPRKEPHPYTPKVEVVDVPEEKAPLIIGPGGSTVKKIYDETGVKVWVGEQGKVYLFV
FPGGDVEKAKQMIQDIVREVEVGAVYKGTITRVEPYGVFVELWPGKIGLLHVSKMAEPVR
SATEKYKVGEEIIVKVLDLDELGRPRFTTIGIEDVGTEKKEVKPKVGDVYEGKVVRVEPY
GAFIEYAPGKVGLLHVSKMKERVKDARQKYKVGDVVKVKVVEIDEQGRPKFTDDV
>gnl|BL_ORD_ID|16002 Arabidopsis_thaliana AT1G68660.1|PACid:19653949
M-----------------------------------------------------------
----ETAICGRLALAPSSLFN---------------------------------------
-------SKSGDKHLVS----KGPCVNRS------ILMTLSTSAALGKGGGVLDKPIIEK
TTPGRESEFDLRKSKKIAPPY----RVILHNDNFNKREYVVQVLMKVIPGMTVDNAVNIM
--QEAHINGLAVV--------------------------------------------IVC
AQ----------------------------------------------------------
---------------------------------------ADAEQHCM-------------
------------------------------------------------------------
------------------------------------QLRGNG------------------
----------------------------------------LLSSVEPDGGG---------
------------------------------------------------------------
-------------------C
>gnl|BL_ORD_ID|19875 Arabidopsis_thaliana AT1G02270.1|PACid:19657822
M-----------------------------------------------------------
------QSHQNRSRLSLILRSRFIPSFSSPLSLFVVLAAVPLPIYFSGLLSGRNNKPLSV
MRLNSNLASSMVESNIS-------CTTFN------ILAPIYKRV--DQKNHSTRESDFRT
LWLARN-QRILDLLLHQRSSVICLQEVWVGNEELVNMYHHQLS--------SSGYTIYQL
ARTNSRGDGLLTA--------IHKDHFKVVNYRELLFNDFGDRVAQLLHVKTVIPFPLNG
KQDVQQEVIIVNTHLLFPHDSSLSIVRLHQVYKILEYLEAYQKENKLNHMPIILCGDWNG
SKR--------------------GHVYKFLRSQGFISSYDDAHQYTDSDA---HRWVSHR
NHRGNICGVDFIWLCNPSDSRKPLRTSWVEAVFSIIKYQLHKASIAEDDAFTFLGAKNHS
DSLTYSDFCLALQKVNLTGIPHGLSFEETKELWVRADLDGNGVFDYEELKKIWNMTMVNQ
P---------GNCKESVMESKKEEGEDE---AIGLKVNKAILFPQEAEKGLWPENYNISD
HACLT------------------VQFSPVKML----------------------------
---C---------------S
>gnl|BL_ORD_ID|417 @Bdellovibrio_bacteriovorus_HD100@ gi|42522068|ref|NP_967448.1| hypothetical protein Bd0460 [Bdellovibrio bacteriovorus HD100]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------DFNSIGYFQFD---------------
-----NLIQTRTPFLLLILDNVDLNDWYK---------------------SVTKMHLDN-
---ISLPSTPEGALEAVKGKNLPPHFAVVV----LDRDENTAPKVAAML----------E
QAGFINSFYVKG------------------------------------------------
-----------------------------------------------------------G
LEGLLIERQQ--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|3358 @Bdellovibrio_bacteriovorus_HD100@ gi|42525007|ref|NP_970387.1| hypothetical protein Bd3668 [Bdellovibrio bacteriovorus HD100]
MNMNEFNIAAQDFLQRVFNKLDAQNIQLDKHWFIDHLCY---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------RVSSLESYHTLKAQFADFAELLIE---------------
-----SDVNGRPIATYKFAEPIRFRDWSIQV-----------------------------
---VELPAPKPGK-TTIEG---FEHFEVVADVG-FDEIKDRYPQAAF------------S
ESGLKKDFNPELEISLDELAIKFHPLSLESVIRLEKNEAVYAAVKKS-------------
-----------------------------------------------------------G
VLKSLKEHQPLLVGTYPLGMNVSGSDVDVLINVPDLMTAEDLLQKLFST-----------
------------FENFTIESHMQSASVTASFDFQGVPFEVFAQVKDSAKQNGNLHFLAEE
RLLHVGGSSLGEKILALRKAGDKTEPAFAKALGLSGNPYAELLRLQKLCESELRQLLK--
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|2667 @Bordetella_petrii_DSM_12804@ gi|163856974|ref|YP_001631272.1| clpS gene product [Bordetella petrii DSM 12804]
MSS---------------------------------------------------------
------------------------TLDTQHDVAVEKAPARTA-----PPPMYQVVLLNDD
YTPMEFVVKVLQKFFGK-------------------------------------------
-----------------------------------------NQEDATRIMLQVHHEGRG-
------------------------------------------------------------
------------------------------------------------------------
TCGVYPRDVAATR-------IAQVAQYARARQHPLQCVMEPV
>gnl|BL_ORD_ID|3525 @Bordetella_petrii_DSM_12804@ gi|163857834|ref|YP_001632132.1| unnamed protein product [Bordetella petrii DSM 12804]
MRRAN-LPAAAALCGALLAAAPNAGG---QPVLDDGMTPAQARARLGLLGLARQI-----
---------VLPREKD--------LRDVRVDIIVPTGPA--------PAGGWPVLYLLDG
NATLQALAEAGTRQPAVLVGI------GYDIDARLDVEARAWDYTPR--------PPHGS
PAGGRDPRQASRRNGGADAWLDLIEQRVKPLA---------RAAAPIDTGRQTLYGHSYG
GLFVLHALRTRPQAFQRY-----------VAASPSLWWHAPYMAERLRDLDAAGCCAATP
RQLYLWVGDAERPRREHAG-------ARPQVSSADANARALAAELAGKAGLEV-------
HYRSFP-----GLGHGA---MLPVSAREAARIAAQ------R
>gnl|BL_ORD_ID|810 @Borrelia_garinii_PBi@ gi|51598977|ref|YP_073165.1| hypothetical protein BG0747 [Borrelia garinii PBi]
MKHMKTFVIIGLSNLGIHLLEDLSRLDCQIIIIDTSKELIEEYDVISTESFVVEQFTKNA
LKRIIPVDTDAVVIDFDDDLGKSALVTHYCNLLGLKEICVKTENRDDAEILKTLGATKII
FPSKDAARRLTPLLVSPNLSTYNIIGYDIIVAETVIPREYVGKTLFEADLRRECGITVIA
VRNLSNSRYEFVDGDYFFLKDDKIVICGKPDSIENFTNNKDLIKDLISVSKEDENLNKDA
EKKSRFLGIFNFMKIFQKDRKDN
>Synechococcus_7942_ClpS2
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------LPSP--FRPQTTIASENVKTASKAAQPKVNSSMSPQPDE-------
-------SVLSILGVPRPCVKKRSRDDAFVLTVLTCSLQAI----AAPATAPGTTT----
---TRVRQPYPHFRVI-------------------VLDDDVNTFQHVAECLLKYIPGM-T
GDRAWDLTNQ--VHYEGAATV-----------W-------SGPQEQAELYHEQLRREGLT
MAPLEAA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------
>gnl|BL_ORD_ID|1190 @Candidatus_Solibacter_usitatus_Ellin6076@ gi|116620336|ref|YP_822492.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------RRHA
AQMANP---------------------------------------------------AIA
PDTEILERERE-------------------------------------------------
-------QHVPLYRVVL-----------------------------LDDND-HTYDYVIE
ML--------QKIFIFTLDQAYRHAEEVDRAGRTVLI-----------------------
---------------------------------TCELREAEYARDQIQ------------
------------------------------------------------------------
----------------------------------------------------AYGPDWRL
PRSKGSMSAVVEPAQ---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>gnl|BL_ORD_ID|2890 @Candidatus_Solibacter_usitatus_Ellin6076@ gi|116622036|ref|YP_824192.1| unnamed protein product [Candidatus Solibacter usitatus Ellin6076]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-ADLDDLLDQDAPVSSPADSDFAWPANP--------------------------------
-----------------------------------------------------TVLGTRV
KRLDGP---------------------------------------------------DKV
TGRAKYT---------------------------------------------FDIARPRM
LYARIVRSPYPHARVVS-----------------------------VDLSVANRMPGVKA
SLV-------------SKDPAGQNNRVMFQGDEVAAVAADTEEHAIDAARA-IKVEYEIQ
PHVTIEEKALAGTAPQVFTGGNV-------------------------------------
------------------------------------------------------------
--------------------------------------------------------RAGQ
PQQSGDIAAGFQAAA--VPNLSLTHKIESGSLDHLGRPRRLSVPKKMVAPNTRSN-----
----------------------APTSRRYSLPPVCIPNVSSISAAVR-------------
------------------------------------------KRMVWLFCWTARVARKIG
TKRSWPNGTPNSGCPVTCSTNLPFRRS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>gnl|BL_ORD_ID|419 @Chlamydia_trachomatis_434_Bu@ gi|166154393|ref|YP_001654511.1| pyrG gene product [Chlamydia trachomatis 434/Bu]
M-----------------------------------------------------------
------------------------------------------------------------
------------------SFKSIFLTG------GVVSSLGKGLTAASLALLLERQDLKVA
MLKLDP------------------------------------------------------
---------------------YLNVDPGTMNP---YEHGEVYVTDDGVETDLDLGHYHRF
SSVQLSKYSIATSGQIYTKVLTKERNGEFLGSTVQVIPHVTNEIINVIQSCADHHKPDIL
IV----------------------------------------------------------
-------------EIGGTIGDIESLPFLEAVRQFRCEHPQDCLSIHMTYVPYLRAAKEIK
TKPTQHSVQNLRSIGISPDVILC-------------------------------------
---------------------------------------RSEAPLSTEVKRKISLFCNVP
EHAVFNAIDLERSIYEM--------------------------------PLLLAKENISD
FLLNKLGFSPKPLDLSDWQDLVEALCDKERQHVRIGLVGKYLEHKDAYKSVFEALFHASV
PANCSLELVPIAPESEDLLEQLSQCDGCLIPGGFGTRSWEGKISAARYCREQNIPCFGIC
LGMQALVVEYARNVLDKPLANSMEMNPETPDPVVCMMEGQDSVVKGGTMRLGAYPCRIAP
GSLASAAYKTDLVQERHRHRYEVNPSYIERLEEHGLKIAGVCPLGELCEIVEIPNHRWML
---------GVQFHPEFLSKLAKPHPLFIEFIRAAKA-----------------------
----------------------------------------------------YSLEKANH
EHR
>gnl|BL_ORD_ID|767 @Chlamydophila_abortus_S26_3@ gi|62185415|ref|YP_220200.1| unnamed protein product [Chlamydophila abortus S26/3]
MGNIESTTFRLYAEVIVNSNINQVLDYGLPHHLEHITKGTGVSVSLRGAKKYGIVHQIKT
QTECKRVLPVLGVIDSGIILPQDLLELMFWMSQYYFAPLGRTLRLVLPGISSSIIQPKQQ
YRVLLKQSKAKTKEIILAIQKESPAQAATLKTLLSCSSPPGLSELMDKAKVSQSPIHSLE
KLGAIEIASAADLEIQEDRLTFFLPEAHVLHPQQQDAVDKISSSLSSGKFQTHLIFGVTG
SGKTEVYFQAIREARKLGKSAILLVPEIALTIQTVTLFKAHFGKEVGILHHKLNDSDRNK
TWRDASNGNIHIVIGPRSALFCPLQNLGLIIVDEEHDPAYKQSESHPCYHARDVAVMRGK
LANATVILGSATPSLESYANALSGKYILSELSSRAASAYPAKISLIDMNMEREKTKTKTL
FSQAALNSIEKRLAVGEQVLVFFNRRGYHTNVSCSSCKHTLKCAHCDMVLTFHKYANVLL
CHLCNSSPKNPQTSCPKCHGTMTLQYRGSGTEKIEKVLHNIFPQVRTIRIDSDTTKFKGS
HESLLKQFATGKADILIGTQMIAKGMHFPAVTLAIILNGDSGLYIPDFRASEQVFQLITQ
VTGRSGRSHLPGEVLIQSFLPDHSTIRCAIRQDYRAFYHQEIPGRELCSYPPFVRLVRCI
FIGKCPNLTRKEAQRIHSILKEKLDTHTQLMQITPCGHFKIKDVFRYQFLIKSKQVLPVN
KKLHEALLTAKLSPKVKFMIDVDPTTTFF
>gnl|BL_ORD_ID|2204 @Chlorobium_tepidum_TLS@ CT2237 hypothetical protein
M-----------------------------------------------------------
------------------------------------------------------------
IRLTAS----------------------------------NNPDTRTEE-------LIAD
VDTLDAWR----------------------------------------------------
--VVLFND-----------------------------------------------DDHTF
DE----------------------------------------------------------
------------------------------------------------------------
---------------------------VIFQIIKAV------------RCTRSIAEKHTW
EVHTRGRAIVYAGEMSNCIRVSAILEEIALKTEIQT------------------------
-----------------------------G-
>gnl|BL_ORD_ID|1148 @Chlorobium_tepidum_TLS@ CT1164 tRNA (guanine-N1)-methyltransferase
M----------------RIE--------------------------IISVIPDFFASPLE
KG---------------------------LLGIARRKGLAEIHVHNLHDYGLGKYQQVDD
APFGGG----------------------------------AGMVIRPEP-------VFAC
IEKLQAER--------------------------------------------------SY
DEVIFMTP-----------------------------------------------DGQAF
DQKRANRLSRKGNLIILCGHYKAIDERIRRTLVTMELSVGDVVLSGGEI-----------
------------------------------------------------------------
-----------------------PALMVMDAVLRLI-----------PGVLGDGESALTD
SFQNELLDCAWYTR---PAEFRGMKVPDVLLSGHHE-----KIELWRQENARERTLER--
---------------RPEMLGKESE---KE-
>gnl|BL_ORD_ID|143 @Chloroflexus_aurantiacus_J_10_fl@ gi|163845747|ref|YP_001633791.1| hypothetical protein Caur_0148 [Chloroflexus aurantiacus J-10-fl]
MI----------------------------------------------------------
------------------------------------------------------------
-----FIVVKKAGMSDWADRQLFEYAFLQGIPMVIFTNGQEWSFYLTNAQGSYDERRVYK
LDLLESDIEESIYRLERYLQYDWVCSGEALE-----ATLSDYQNVARTREIEAALPKAWK
SLL----------------------------------------------------EEPDS
LLLELLADKVEDLCGYKPDLDVCSRFITTVMRNHVDVPPQYPTLPRTR------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------NPL------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------PAER
IETDD-----------RVRA-----GSECFIMFEGKTYKPG-----------SAIRTMLK
LFQR----------------------LAEADPGFLDRFAA--------------------
---------------MKHGSKRKYIARNRLELYPDRP---DLA-----------------
------------------------------------------------------------
-------KQCSVEIIPGWWMGKNFSKR---------------------------------
-------------------------------DIKHIIEM------ALGIISPTLRAK---
------------------------IQYEL
>gnl|BL_ORD_ID|3762 @Chloroflexus_aurantiacus_J_10_fl@ gi|163849366|ref|YP_001637410.1| glycosyl transferase family protein [Chloroflexus aurantiacus J-10-fl]
MW----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------LTLLWVVIGLGLA----GSFLGQWQRM-------RQIPRLTS
PCL-----------------------------------------------------PPDP
PLISILIPARNEERGIGR--------------CVQGALA---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------QRY------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------PHIEV
IVVDDGSTDRTPAILADLAA-----TDARLRIITGKPLPPGWVGKCHACQQA--------
--------------------------SSAASGEWL-------LFLDADTAPAPDLAAALL
CHALTTN-----------GDMVTIFPFLELKTWSERLILPPFVALIVSIFPFERLAKPDV
RPEEVLANGQCIFVRRAAYEAIGGHGAVRAEVLEDVRLGQRLRAAGFTVRGAI-----GM
EYLAVRMYTNAAEVIEGLMKNASAGSRSGGWRSLMGMTLLLAQAYGPLLLMIGGWFTGGW
AGSLVLLVGMVSWLVGLLFWGTLYQRFYRLNPLHAVLW-------PVGLLMYLLIAGYGI
LRVRLGQGVVWKG-----------RRYAG
>gnl|BL_ORD_ID|1360 @Clostridium_tetani_E88@ gi|28211194|ref|NP_782138.1| sensor kinase dpiB [Clostridium tetani E88]
MKEKLRKKITLRIKVTLYVFIILVMVISIIGYLSFKEMRELIEKERSKEALRLAQTLAMT
DEIKRNLNKKDSLALQYYVERVRLKTNVTFIVVIDMEGTRYSHPIEENIGKMIKGGDHIE
VINSGQSYVSESVGTLGLSIRGFAPVYKDGEQIGAVSVGILKGNVNLEVYNKLSKFIPFI
LVGLITGILGAYLLAHSIKNSIYGLEPKEIALLLSLKEAILESVEDGIIAVDKSGNILNY
NKSAENLLGISKRDLGK--SVLNYMPDESILEVLNTKKPLINVENKIN--VG--------
--------TTLMCNYNILE----------------------------------DRDKNFM
GLVIT------------------FED------LTSIKELAEEL-----------------
TG---VKKILWSLRAQNHEFMNKLHTISGLIQIEEYDMVVDYICELAYKRGGISYLINEN
IKIIPLQGLLLAKYNKCEEEKISFIIKESTFLERLPNKMNSEEICSVVGNLVDNSMEAVE
VDGTGKIEIEIRNNDKELFLMVKDNGGGIPKEIEEKIFLKEKSTKLGNRGLGMYIVKNII
EDKFGEIQFTSNKSGTTWFINIPMKGNSMYDKGNDN
>gnl|BL_ORD_ID|2232 @Clostridium_tetani_E88@ gi|28212066|ref|NP_783010.1| anaerobic sulfite reductase subunit C [Clostridium tetani E88]
MD---------------------------INTKALKKNAFRVTKERGKTAARVRVPGGYL
DAKYLSL-----------------------------------------------------
-------------------LQNIAETYGNGKLHITIRQG-------FEIPGIPMKYIPEV
NKALQPIIEGLEINQENPNKGYSASGTRNV-----------------------SACIGNN
VCPFANYNTAKFAK--KIEKAIFPNDYHVKIALTGCPNDCIKARMQDFGIIGMTEPQYDA
YRCIGCQACVNVCKKKSTGALSFENYKVVRDHSKCIGCGECINKCPTSAWSRSEEKY--F
KLVIMGRTGKKNPRIARDFITWIDEDSIVKIILNTYDYIDEYIDRNAPGGKEHIGYIVDR
TGYQEFKK--WALK----------------------------------------------
-----------------------------------------------------------D
IELSPKAKVE--HN------------------------------I---------------
---------------------------------NWY
>gnl|BL_ORD_ID|1028 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637456|ref|YP_677663.1| hypothetical protein CHU_1046 [Cytophaga hutchinsonii ATCC 33406]
MI----------------------------------------------------------
-----------------------------------------RIQSHSFP-----------
------------------------------------------------------------
-------------------------------------FQQEED-----------------
-------------------------------V------------------ALMEE---VQ
TSDMN-----------------------DLVVYNDDVNTFEHV----IQVLMS-VCGHSP
E-------QAEQCTLLIHYKGKCTVKMGSLNELKPMRQGICDKGIS--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------AEIL---
>gnl|BL_ORD_ID|1524 @Cytophaga_hutchinsonii_ATCC_33406@ gi|110637952|ref|YP_678159.1| hypothetical protein CHU_1548 [Cytophaga hutchinsonii ATCC 33406]
ML------------------------TGITTRVKVL------------------------
-----------------------------------------------FLLTVL-------
--------------TGATALW-----------------TLLSKGASGKPEYT--------
-----------DFIKIDTADIVK------------VTFTSHKETHYVAPK-TSSLWYIDS
KYDVRRDIITTMKLGLARMDV-------KMPVASEIKEE---IKKRLFADGVHVQ---VL
TEEGE--------------------KEFWVLTNDNDNNSSYFISSSAADPYIIYVPGFTG
DLTDLFKLKASDWRNKALFRNA----PGGIEELSVSYQSSPKDGFTIKKVLNRYEVVDMS
QVDSTRL---------------YTYLGLYQRINVEN-YLVDKQKDSVEYLLKSQQPEVLL
TVTDIDKSR-------SKTIQIYKA-----------------------------LPGTKL
LY-------------------------ARV---VDNGE----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------LVTLNPE----------------------
---------------------------------------------------------VFF
RLLVR----------------------------KQWFMDK
>gnl|BL_ORD_ID|367 @Dehalococcoides_ethenogenes_195@ gi|57234832|ref|YP_181123.1| 30S ribosomal protein S2 [Dehalococcoides ethenogenes 195]
M------PTTNIKELLEAGAHFGHQ---TSRWHPRMKKYIFT----------KRN-----
-------------------------------GIHIIDLEKTVVML---------------
-DKACNYINQVVSEGGKVLFVGTKKQAQEILAEEAKRCGMYFINQRWTGGILTNFHSIQS
RIDYLVRLEDQQARGDFNRLPKKEAQKLAEEIARLNRTMGGFKEMTRLPDVIFVVDPTKE
KIAMAEAKRMGVPLVAMVDTNCNPDEVDYPIPSNDDAMRAIKLICSKMADSVIEAQNALK
VTEVETTGEAQAETAG
>gnl|BL_ORD_ID|3040 @Deinococcus_radiodurans_R1@ gi|15807907|ref|NP_285566.1| flavohemoprotein [Deinococcus radiodurans R1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------LTPEQKAIVKATVPALEAHGETITRTF
YASMFAAHPELLNIFNPANQQTGKQARSLAASV-LAYAAHIDHPEALGGMVGRIAHKHVS
LEVLPEHYPIVGQYLLGAIAGVLGDA---AKPEILDAWAAAYGELADLM----IGIEKGM
YDAGAGQPGGWRDFRPFRVAR---------------KVAESRVITSFV-LEPV-----GG
GALPAYQPGQYLSLKVKVPGQE-----------------------RWQIRQYSLSDAPSP
DHYRISVKREGGGL-------------------VSEYLHGAVQEGDELLVHVPAGDFV--
LQQSERPVVLISAGVGIT---PMLAMVQTL------------------------------
---------------------------------------------AQAGSQRPVTFI---
------------------------------------------------------------
----------HAAQNGSVHAFRDDVARLTHEYPHF----RKVVFYDEAGPDDQLGTHHDV
AGRL-------------------SLDAVRGALPAG---EAEFYYCGPAGFAG-AVEAILD
--------------DLQVPAERRFT-----------------------------------
----------------------------------------------ETFG----------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------PS
QSFAPVILG
>gnl|BL_ORD_ID|819 @Deinococcus_radiodurans_R1@ gi|15805680|ref|NP_294376.1| hypothetical protein DR_0653 [Deinococcus radiodurans R1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------PTLETARLVLLPLSRAV----
LERRSEDDSFT-----LALPWPGEEAPQDV------------------------------
---------------------------------------------HFPAEWPG-------
------------------------------------------------------------
-----------------------------DPLPLFPLWLAALIG------DEKEGSFVAV
TREDRTAV---------------GLLGSKGSVSVGGELEIGYGFIPSAWNQGYATEAVHA
LTVHLLGQPRVQTVTAQTALGNRAS-----------------------------------
------------------------------------------ERVLEKIG----------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------FARTDRRWDDEEG
ALTLWAVGG
>gnl|BL_ORD_ID|3478 @Delftia_acidovorans_SPH_1@ gi|160898929|ref|YP_001564511.1| formate dehydrogenase subunit alpha [Delftia acidovorans SPH-1]
MTNHWVDIKNADVILIMGGNAAEAHPCGFKWVTEAKEHNGAHFMVVDPRFNRSASVADFY
APIRSGSDIVFLGGVINYLLTNDKIHHEYVRNYTDFSYIVKEEFAFDEGIFSGYDPQTRK
YDKSSWDYELDADGYVKVDASLQHPRC----------------------VYQWLKRHYAS
YTPEKVE---------SACGTPKEKFLHVC---EKLASTAVPGRVATILYALGWTQHTTG
AQILRTGAMVQLLLG-------------NIGVAGGGMNALRGHSNIQGLTDLGILSASLP
GYLTLPNEGEQDYQKYIDARTPKAMRPGQMNYWSNTPKFHVSLMKAWWGPAATAENNWAF
NYLPKLDRQYDMLQVFDLMAQGKINGYIAQGFNPLAAL---ANSNNVREGLKKLKFLVIM
DPLVTETSEFWQNHGEFNDVDPASIQTEVFRLPTTCFAEEDGAVVSSSRVLQWHWKAAEP
PGEAKTDIAIMSALHLRLKQAYEKDGGKFPEPITKLWWPYAHADHPTSEEIAKEYNGRAL
VDLFDPKDPTKLIRKAGEQLAGFGEMRDDGTTMGGCWIWAGCWTSSGNQMARRDNSDPTG
IGNTLNWAWAWPANRRVLYNRASCDRNGQPFDPKRTLIRWNGKAWGGADVPDMGPTMPPE
TTDPFIMNPEGVARFFARKGMNEGPFPTHYEAFDNPLGYNPMYPDNKLAVINPATRIFDS
VKDSAGSPSEFPHVGTTYRLTEHFHYWTKHVQLNNIVQPEQFVEIG-----EALAKELGI
ETGQHVKVSSKRGFVKAAAVVTKRIKPMKIDGKTIHHVGVPIHWGFSSTGRKGYMANNLT
ASVGDGNSLTPESKTFLVKVEKV
>gnl|BL_ORD_ID|1295 @Desulfovibrio_vulgaris_DP4@ gi|120602197|ref|YP_966597.1| response regulator receiver modulated CheB methylesterase [Desulfovibrio vulgaris DP4]
MISVVVVDDSAFMRKALSTM------------LEKDP--EIRVVATARDGEEGLQVIRQH
NP-----DVVTLDIEMP-----RMDGLTTLRHIMMEMPRPVLMVSSLTTEGAEATLKALE
LGAVDFIP-------KQLSKVSLDIVRIENDLREKVKEVSKRRMLRTPRPVRPAPTASAP
AQTAQVASAAPATAPSRPAMPATRASRPVRDVVAIGVSTGGPPAVQKVLSQLPADFPASI
LIAQHMPAAFTGPFAKRLDGVCAISVKEAESGEKLKPGTAYIAPGGKHL--------RVE
QRVSHMEVVVTTDPAEALYKPSANVLMESVGQSMGRRALGVILTGMGSDGME--------
------------------------------GMKVLKQKGGRSIAQSDATCVVYGMPKAIV
DAGLADEIVDIDDM----------------------------------------------
-----AAAIMNGLYK---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>gnl|BL_ORD_ID|2025 @Desulfovibrio_vulgaris_DP4@ gi|120602927|ref|YP_967327.1| hypothetical protein Dvul_1883 [Desulfovibrio vulgaris DP4]
MKHF----------------------------LHKTPVQGEHVIYFLYHNEEAPMPVQWT
DPLELLGDISRLDLDAS-----QMDEL---RAIIAEEVR---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--AEGAETVWNGRAF---------------------------------------------
------------------------------------------------------------
-----------------------------------RKNIIHSFGHVM-------------
--
>gnl|BL_ORD_ID|617 @Ehrlichia_canis_Jake@ gi|73667251|ref|YP_303267.1| carbamoyl phosphate synthase large subunit [Ehrlichia canis str. Jake]
MPKRTDIESIL-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------VIGAGPIV--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------IGQACEF---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---DYSGTQAC------------------------------------------------K
VLKQEGYRIILINSNPATIMTDPEIANSTYIEPITPSIIE-----KIIIK-------EKP
SAILPTVGGQTALNVAIKLCEQGILEKHNVKLIGATKEAIQKAEDRNLFRQAMDKIGVKY
PKSIIIKSVDEIKHALEYIGLPAIIRPSF--TLGGIGGGISYNKE-------EFQKNVM-
-YGLSISPISEVQVDESIIGWKEFEMEVMRDNKDNCIVVCSIENLDPMGVHTGDSITVAP
ALTLRDTEYQKMRDIS----------------FSILRE--IGVDTGGSNVQFAVNPKND-
-------EDLLVIEMNPRVSRSSALASKATGY-------------------PIAKVAAKL
AIGYSLDEIQND-------------CTKAIPASFEP---------------SIDYIVTKI
PRF--NFDKFRGAE------------KELSTSMKSVGEVMAIGRSFPE-SLQKALCSLES
GYS-GLDEHFDKNIEKDQLYNALVKLSPDRIFIIADALRHNISIEEINKITGYDPWFLIQ
IKNIIQFEQQIKNHGLPKEAEGLLLLKKMGFSDARLAHLSNNTIEYV--ENLRRSLLINP
VYKHIDTCA---------------GEFKTNASYMYSCYEGDTVNPPECESVVTDNKKVII
LGSGPNRIGQGIEFDYTCVHAAHTIRQMGYESIMINCNPETVSTDYDISDKLYFSPLTRE
SVLDII-----FKEKETNSLLGVIVQFGGQTPLKLAKVLQEKNINILGTSFDSIDLAENR
MKFQQLLTQLNLKQPPNVTCNSINEVYECVQSLAFPILARPSYVLGGQSMSIIRDSNALS
NYLTIHKNIFDNGSLL------LDQFLTNAVE-----------VDVDAICDGESVYITGI
MEHIEE-AGIHSGDSACSLPAYTLTSEITDTIAEYTKKIALALQVIGFINIQYAIQDGEI
YI----------LEVNPRASRTVPFIAKATGIPI-------AKIATKILLGEKLPTILER
KLNYIAVKEAVFSFSRFPNIDVLL----GPEMKSTGEVMGIDKSFEIAFAKAQMAAGYEL
-PTQGTAFISVKNSDKPLIVQTAQILQDIGFTIF----STKGTSTYLNEAGITTQQVNKV
REGRPHILDLLQDDKIN------LVINTSEC-IKSFSESSSIRKTALVKK-------IPY
---STTIPGAKALASAI-KTLKKQGIQVEPMQEYTKE-----------------------
------------------------------------------------------------
-----------------------------------------------
>gnl|BL_ORD_ID|2943 Escherichia_coli_UTI89 gi|91211873|ref|YP_541859.1| hypothetical protein UTI89_C2868 [Escherichia coli UTI89]
MRDYSAKTLPDCSIHCHKSFNSVCLVNIEGTMTPVKVWQERVEIPTYETGPQDIHPMFLE
NRVYQGSSGAVYPYGVTDTLSEQKTLKSWQAVWLENDYIKVMILPELGGRVHRAWDKVKQ
RDFVYHNEVIKPALVGLLGPWISGGIEFNWPQHHRP-----------TTFMPV-------
----------DFTLEAHDDGAQTVWVG---ETEPMHGLQVMTGFTLRPDRAALEIASRVY
NGNATPRHFLWWANPAVKGGEGHQSVFPPDVTAVFDHGKRAVSAFPIATGTYYKVDYSAG
VDISRYKNVPVPTSYMAEKSQYDFVGAWCHDEDGGLLHVANHHIAPGKKQWSWGHSEFGQ
AWDKSLTDNNGPYIELMTGIFADNQPDFTWLDAYEEKRFEQYFLPYHSLGMVQNASRDAV
IKLQRSERGIEWGLYAISPLNGYRLAIREIGKCNALLDDAVALTPATAIQGVLHGINPER
LTIELSDADGNIVLSYHEHQSQALPLPDVAKAPLAAQDITSTDEAWFIGQHLEQYHHASR
SPFDYYLRGVALDPLDYRCNLALAMLEYNRADFPQAVAYATQALKRAHALNKNPQCGQAS
LIRASAYERQGQYQQAEEDFWRAVWSGNSKAGGYYGLARLAARNGNFDAGLDFCQQSLRA
CPTNQEVLCLHNLLLVLSGRQDNARLQREKLLRDYPLNATLWWLNWFDGRSESALVQWRG
LCQGRDVNALMTAGQLINWGMPALAADMLNALDCQRTLPLYLQASLLPKAERGELVVKAI
DAFPQFVRFPNTLEEVAALESIEECWFARHLLACFYYNKRSYGKAIALWQRCVEMSPEFA
DGWRGLAIHAWNKQHDYELAARYLDNAYQLAPQDARLLFERDLLDKLSGVTPEKRLARLE
NNLEIALKRDDMTAELLNLWHLTGQADKAADILATRKFHPWEGGEGKVTSQFILNQLLRA
WQHLDAREPQQASELLHAALHYPENLSEGRLPGQTDNDIWFWQAVCANAQGDETEAMRCL
RLAATGDRTINIHSYYNDQPVDYLFWQGMALRLLGEQHTAQQLFSEMKQWAKEMAKTSIE
ADFFAVSQPDLLSLYSDLQQQHKEKCLMVAMLAAAGLGEVAHYESARAELMAINPAWPKA
ALFTTVMPFIFSYVH
>gnl|BL_ORD_ID|1468 @Fervidobacterium_nodosum_Rt17_B1@ gi|154250174|ref|YP_001410999.1| alanyl-tRNA synthetase [Fervidobacterium nodosum Rt17-B1]
MKFMTSDEIREAYLSFFEKKGHKRLPSASLIPDDPQLMFTVAGMVPFKPIFWGKVDPVYP
RVTTCQKCVRTNDIENVGRTPRHHTFFEMLGNFS------FGDYFKQEAIEWAWEFVTKV
LEMPEEKLWVSVYEYDDEAYEIWRKLGVPERKIVRMSKEDNFWGPAGPTGPCGPCSEIFY
DTGVEVPVPEGQDPTPANTDGRYIEIWNLVFTEFYQDEEGNLHPLPRKNIDTGAGLERIS
AMMQGVYWNFDTDLFKPIIESIENVLKVSYKSDKVKDVSIRVIADHV----RSVTFMIAD
GVLPSNEGRGYVLRRVLRRALRHGVLLGAKE----PFLYKIVDSVVQKMGKIYPEIVEKQ
SFVENIVKSEELKFINNLSRGLEIVQKIVTTSGKISAEDAFKLYDTYGFPIDILRDIATE
N-GYELDEKGFEKYLEEQRERSRKAQGEVEFAQKTGYENLGIETVFVGYDTLVSESSVLK
IRVNGEFVEKA---EGNDLECELIL--DITPFYAEKGGQVADTGVIKSQDGLFTVEYVYS
PVEGIIVHRGKLNGKISVNEKVQSQVDEIKRKSTMR---NHTATHILHSALRKVLGSHVR
QAGSLVEPTRLR----FDFTHYQALTKD-EITKIENIVNEVILKAIPVVTEI--------
------------KSYDEAVKEG-----AMALFEEKYGDFVRVVKVSDFSEELCGGTHVK-
---------NTGEIGLFKIVSESAVSAGVRRIEAITGLNSLEYLRTDEELFEKLKLLLEA
PKSEIVEKI---------QKILEEKKNLEKEIQEIKRKLINPEEIAKKVKEYNNIKYVVS
VLEDVEPDILKDLIDNISDRIKGIVL---------------LISKMSDKII--VTVKVPK
ELTQDYNAGNIAKLVSKVLGGGGGGSPTFAQAGGKLIEKIDEATELFEKIIRKEVQ
>gnl|BL_ORD_ID|367 @Fervidobacterium_nodosum_Rt17_B1@ gi|154249073|ref|YP_001409898.1| flagellar biosynthesis protein FlhA [Fervidobacterium nodosum Rt17-B1]
MK--------------------ADIAVALLIVSIIFLM-----IIPI-PNFL--LD----
-------------------------FFQLL-NISISLVLLFSTMYIKNTLELA-------
-SFPTLLLIITIFRL---------ALNVASTRAILLQ---------------GP------
-----------------KFGGKVI----LTFGNFV-------------------------
-----VGGNYVVGIVVFLILVIIQFIVITRGSERIAEVAARFTLDAMPGKQMSVDADLNA
GLITEEEARRR-REQIRREADFYGAMDGASKFVRGDAIASIIITIVNSLGGIIIGILMHK
MGIGDAAQKFLLYTVGD---------------GLVSQLPALMVSTATG--IIVSRSAAED
NLGMEL---------------IKELAGEKKVIILTG-------SVIMFLGVVTPLPTLTS
LLIGGLFLAVGLLIRGKELEQPQIVGAGTAPGMVQGPAPSVPAGPI-----LSTPEEVSE
VIQSDTVEINIGYGLLPLADLSQGG-DMLERLTMIR---RQLA----------------Q
ELGLVLSPIRVRDSVILKPNEYAIFIRGAEVSRYELVPNRLLAINPGFVTERIAGIEVKE
PAFGLQAFWIDESKKDEAIQKGFTVVDAPTVFATHVTEILR-----KYAPELLGNREFQL
LVDGLRNKFDKLVDDVFNVIKPSAVKRVLQEL-----LREGVSIRNLPYIFE--LILDNA
DKARDVETLVEYVRRGLKRQIASKLLAMDKQIHAIALDSELEQTLTESISESEEGKYI--
---SINPQIMRELIEKISIELEALMRKGYIPILVVSGTIRPYISRMVVRFIPGVTIISFE
EIPEDINLS-------------------------------------IEGVVR---L
>gnl|BL_ORD_ID|3483 @Flavobacterium_johnsoniae_UW101@ gi|146301250|ref|YP_001195841.1| unnamed protein product [Flavobacterium johnsoniae UW101]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------STKEKVRE---------------------------
-------------KVREKEAAVF-------------------------------------
------------------------------------------------------------
--------------------------------------------------NNEIIMYNDD
VNTFDHVIDTLMR-----------------------------------------------
------------------------------------------------------------
-------------------VCDHTAEQAEQCSLIVHYNGKCTVKTGPIEKLKPQCTQLLE
AG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------LSA---EIV-----------------------------------
-------
>gnl|BL_ORD_ID|2463 @Flavobacterium_johnsoniae_UW101@ gi|146300230|ref|YP_001194821.1| unnamed protein product [Flavobacterium johnsoniae UW101]
MKDEEDDNIIPNDDENNQDENLMDDNQDGDDEDIINVDAKHFEGQHFYENQEEEGEDVIT
KVTGMYKDWFLDYASYVILERAVPAIEDGFKPVQRRIMHSLKELDDGRYNKVANVVGHTM
QYHPHGDASIGDAMVQIGQKDLLIDCQGNWGNILTGDGAAAPRYIEARLSKFALEVLYSP
KITEWGLSYDGRKAEPINLPVKFPMLLAQGAEGIAVGLSTKVLPHNFNELIDASIKILKG
KPFTLYPDFMTQGIADVSNYNDGMRGGRVRVRAKIS-QLDKNTLVITQIPFSTNTSSLID
SILKANDKGKIKIKKIEDNTAADVEILIHLFPGVSPDKTIDALFAFTACETSVAPLGCVI
EDNKPLFIGVSQMLKISTHRTVDLLRQELEIQLEELKNKWHFSTLEKIFIREEMYIDFKL
YGDRESLYKYLYDRFEPFKKSFVREINDDDLQRLTQIPMIRITRFDSDKADDLIAKLEDE
MKEVEHNLEHLTDFAIAYFTKLKEKYGKGRERQTELRVFDNVEATKVVLRNTKLYVNREE
GFVGTSLKKDEYVGDCSDIDDVIVFLRDGTLMITKVDAKTFIGKDIIHVAVFDKNDKRTI
YNMMYRDGKSGPSYIKRFNVTGVTRDKAYDLTNGTNGSQVVYFSHNPNGEAEVVTILLRQ
VGTIKKLKFDIDFAKLAIKGRGSKGNLVTKYPIKKIELKEKGISTLLPRKVWFDDTVKRL
NVDARGELLGEFKPTDKILIINQSGKLKVIIPELSTHFDEDMIVLEKWKPKKPISAIYYD
GEKERYFLKRFLVENEGKEESFITDHPNSQLEIVSTDYRPVAQLVFAKVKGVQKDDLHID
VEDFIAVKGFKALGNQLTTDKLKQVNLLDPLPYEEPIEEIPEKPEISEDDPVETELDDDG
QIGLVLE
>gnl|BL_ORD_ID|2506 @Frankia_alni_ACN14a@ gi|111222013|ref|YP_712807.1| unnamed protein product [Frankia alni ACN14a]
M----EEWVHRDE--------------TVRAGTLLISGNA---------LLRDGLARMIE
SADYAFV--------AATVDDGHILPALGEGIANVQVTIVDASGPFETDVTRVDQAIAAY
PHSRVLVLGRDSN--MSTAQAFLR-----RGASAYLPIATRRDHLLATVWL--LLNDQDS
KVVILPRDDEGEAL--PGVREVLSKREMEVIEIVAEAATNMQIARRLGITE---------
---DTVKRHVSNILMKLGAVSRLDAVKKAGIPLGITSSAVSSPRRPGAAHPNNDS-----
----------------------------------------------------------RP
A--------------------
>gnl|BL_ORD_ID|5629 @Frankia_alni_ACN14a@ gi|111225139|ref|YP_715933.1| rpsB gene product [Frankia alni ACN14a]
MKQLLESGVHFGHQTKRWNPKMKRYIFTERNGIYIID-------------LQQTLS-YID
RA-YDFV--------KETVAHGGT------------------------------------
------VLFIGTK--KQAQEAIEE-----QAARVGMPYVKER-------WLGGMLTNFST
VYKRLQRLKELEEIEVTGGTEVRTKKEQLVL-----TREKAKLERTLGGIRDMSRVPSAV
WVVDTKKEHIA-----------VGEARKLGIPVVAILDTNCDPDEVDYPIPGNDDAIRSA
ALLTRVVADAVADGLMARAGASKAADAKPEQSAGEEPLAEWEQALLRGEGTAPAASEEQP
AEEPAPAAAEAQTDAAVGTAV
>gnl|BL_ORD_ID|3246 @Geobacter_metallireducens_GS_15@ gi|78224460|ref|YP_386207.1| unnamed protein product [Geobacter metallireducens GS-15]
M-----------------------------------------------------------
------------------------------------------------------------
--------------------------LPN-------------------------------
------------------------------------------------------------
QERKLRVLVVDDSSFMRMVIRSVLEKD---------------------------------
--------------------------------------PAIEVIAVAMDGVEGVEKALA-
------------------------------------------------------------
---------------------------------------------LRPD-----------
--------------------------------LITMDIEMPRLDGI-------SALKEIM
----------AKAPTRVLMVSTLTCEGAKATFDALDAGAIDYIPKNVTDSIDAQKAFKEE
LLRKVKGSGISILGR----PLVSPSPRLVVPPR---------PVI--IPRPAGQRYQYVG
IGASTGGPVAVQEVLGRIPGNFPHGIVVAIHMPKAFTGPYAERLNTKCSLQVKEAKAGDI
VQPGVVL-----------VTPGGMHTAL----------VRQGSTVAIRTIATAEYPQYIY
IPSVDHMLTTFADACNGSLLGVILTGMGADGFKGMKHLKTKGGGTI--------------
-------------------VQDEATSTI--------------------------------
-------YGMPRA-----------------CIEGGVADTV--------------------
--------------------------LPLTQIGTEITKIAG-------------------
----------------------------
>gnl|BL_ORD_ID|3310 @Geobacter_metallireducens_GS_15@ gi|78224524|ref|YP_386271.1| unnamed protein product [Geobacter metallireducens GS-15]
M-----------------------------------------------------------
------------------------------------------------------------
----------------ELLRAFLDVLFPPLCHLCKAPVPGAGP-----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------LHLCDACLGAMTPITSPLCPVCGVPHRTEGGIDHLCGSCM-
------------------------------------------------------------
---------------------------------------------LTP------------
----------------------------------------PPFDGVRGALLFDGPLQELI
HRHKYGHKVHLRRPLALLAIRHLTPFVQSVAPDVI-------IPVPLHRSRLRERGFNQA
VLVG------AVLSREWRLPLLRHTLRRVR------------PTVAQVTLSARERRANVR
GAFAVSGPAGIAG-----------------------------------------------
----------------------------------------------------------RR
VLLMDDVVTTGSTVAECARV----------------------------------------
-------------------LKDAGASAV--------------------------------
------------------------------------------------------------
----------------------FVITVALAPPGR--------------------------
----------------------------
>gnl|BL_ORD_ID|508 @Heliobacterium_modesticaldum_Ice1@ gi|167628387|ref|YP_001678886.1| unnamed protein product [Heliobacterium modesticaldum Ice1]
MRK---------------------------------------------------------
----------------------------------------------------------MF
GPTITLGVEIASTAVRMVEVSRRNQRFAIVAALKQPFSPPAGEINSDAYYQALEAAIEKC
LAGLRKKAKRAVLAF-----PSRHLI----------------------------------
------------------------------------------------------------
--------------------------SRQIRMPHMPDDEMRASLRWELE-----------
-------------------------KYV---PLSADDYVYDYLHQGVIDVEGDRMAQLLL
VALPKEEVLRHHACLKRV------GLTVTAVEISSFALSRLLNVMREKDLRTYGCLDM--
-------GYDRSTLTVFREGKVQ--------------------------------FIRFI
QMG--------AARLEESLAQTFPVE--------TIRLRLAEAAVTTEATATYEGAPAAE
EAAVTETAVAEAPEAYGAAAQM------QFLLQSFFADLIVEVRRSLDFYNLQYRDDNFS
HLVLCGGLSRLRGIDAYFTQEFKLPVSVVDMQTSLVAQIKPACLEQLTPDMAVVTGLALR
SAEED
>gnl|BL_ORD_ID|2588 @Heliobacterium_modesticaldum_Ice1@ gi|167630727|ref|YP_001681226.1| unnamed protein product [Heliobacterium modesticaldum Ice1]
MTKASSIKTAPRAGFSPGGGPPMGMPVQKAKNVKDTLRRLAAYLRPHRLSLFTVLVTALL
STVFSIVSPKLLGNATTRLFAGLMMRYQGSPDAAIDFPYIAKILLVLAGLYGFSALFGYV
QQYVMAGVAQKTVFALRQDVNEKLSRLPLRYFDSKPHGETLSRVVNDVDNISNTLSQSLT
QLITNVVTIVGIIVMMLVISPGMTLILLVTLPLSAFVIKSIASRSQSHFINQQKTLGELN
SHIEEMYTAHPVVKAYGQEASSIAKFSAINEQLYDVSWRAQFISGIIMPLMMFINNIGYV
LVCVVGGVMVTKRAIEIGDVQAFIQYARQFAHPITQTANIANVIQSTIASAERVFELLDE
AEEADIAAVPAFRPLGDVAFEAVSFRYKSDEPLIEDMSIHVKAGQTVAIVGPTGAGKTTL
INL-----------LMRFYEVDCGRITIDGVDIRHL-----------RRSDLRRCFGMVL
QDTWLFHGTIRENIAYGREGATE------------------EEIVHAAKAAKADRFIRTL
PDGYATVLDEEASNISQGQKQLLTIARALLADPAILILDEATSSVDTRTEALIQKAMGRL
MQGRTSFVIAHRLSTIREADLILVMDHGKVIEQGNHADLLAKGGFYAELYHSQFREG---
-----------------------------------------------------------G
LPQAV
>gnl|BL_ORD_ID|262 @Herpetosiphon_aurantiacus_DSM_785@ gi|159896796|ref|YP_001543043.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
MGLVESIMNFSEGRRTEVVHAIRDAITAVAGVQLLDVQSDADHNRTVISFAGEAEAVGEA
AFQATRTAQGLINLDTHRGEHPRIGATDVLPFVPLGQTTMKQCVALARKVGKRIGDELGI
AV-YLYEEAATRPERQNLADVRKGEYEAWRKAIGVDPAREPDFGPAVATPAGATVVGARQ
PLIAYNIY--------LNTTDVEIA--------------KKIA--KSIRYLGGGLRYVKA
LGLLVDGRAQISMNLVN--FRGTPI-------HRVQELV--------RAEAMRYGVTITE
GEVIGLVPQDALVDAAEHYLQLNRFRRDQVLESKLAAPSAGDDWLPTNTFQAFAAGTPTP
GGGSAAALAGALAGSLGQMVANLTVSRKKYAAVKPS--MQAALERLSEATTSLGKLALSD
SAAFNAISVTRKLPEEQADRAQQLAAAIVHACEVPLQVAQQAASLF---------DDLYL
LATQGNVNARTDAQVGGYLAYAAVNGAGLNV----LVNLGDLSDAQLREQFSAAVAKLRQ
QAEQGLQKLTTL
>gnl|BL_ORD_ID|4320 @Herpetosiphon_aurantiacus_DSM_785@ gi|159900854|ref|YP_001547101.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
MQL--------------------------------------NGERQIRIV----VADDHA
VVRA--------GISTALSDLPNVEIVAEVGDGP------GVLAALDLR-----PDALVI
DV--------SMP----------------------------------QFEPLQTIRQIRM
HYPQLKIL-----VVSAYDDDVYVQGLLQAGVDGYQLKDQPLA--DIR------LALQRV
---LAGER-WVCTPLLSKLMRGVPVVETGLTPRQRELLWCLQQGDDNHAIARRIGLSVKT
VENH-----------------LTRLYRQIGVQSRLEA-----------------------
---------------------------VHYAAQHPQLPMMPTSNQVIAPSQALSVLIVDD
NLRYRQ-HVSRMISKMQPNCAVVEAA---HQTEAMAAISQRSPDLALVDVVLGDEDGISC
AAQIKQQSPKTRVLLVSAYPDREFHRRGLAVGAVALLDKKDLDAAALRLLLEDV------
------------
>gnl|BL_ORD_ID|2166 @Herpetosiphon_aurantiacus_DSM_785@ gi|159898700|ref|YP_001544947.1| unnamed protein product [Herpetosiphon aurantiacus DSM 785]
MDR-----------------------------------------KQFLKLLGTSVATGFL
VRSF----------------------------EP------KQAAAMGLTALQFSGTTLAD
WKTVLGDGLWTAP------------------------NQVPVNNADIQTDQTSTKSILRA
NISQRGVMAHNITYKSLIDQDLFEY--------------IHTTSYEFR------LPYIPQ
---TNSG----IQNAQT--FEGGFFIWDG------------------SQTQLDYGCAFQW
V--------------------LNPWMSTFGTVYSWSSDGATQGWIPCGFLQP--------
------------------------------------------------------------
----------------DTNWHQYQMMVDYHNQTCRLTIDQTSIPIC--------------
--------------------FTATPKVGWGTETAARFQTEIISIWPGNTSIAPSHAVEIR
NWNWNLQPYT--
>gnl|BL_ORD_ID|2044 @Legionella_pneumophila_2300_99_Alcoy@ gi|296107542|ref|YP_003619243.1| methoxymalonyl CoA synthase [Legionella pneumophila 2300/99 Alcoy]
MPDDISRKQFSIGDLYFTNELEVSGLIYEIFYQKSYLSDFLTLSPGAVVFDVGANIGVFS
LFVLKQCHYDTEIYSFEPVPATFKC------LKKNLARFKHNVHVYNAGIGNVPKDCSID
FTLFGESSVTATYKPTDKIISNYQPLLNYETLLKLSSFQNKPLYYQLKYLPFLRNYLIKK
NYKHQTLETKVRCHLTALGRFIENNQITRIDLLKIDVEGAELDVINSIKPEQFSLIKQLS
IEVHDIDNRVEKLVSYLQKQGYITYVDRNPIFAELGFNHHMIYAKLPEPAIITLSEEPNN
PENYIEARQYFYGLLAGGVRIKLLESMFDLDLFRLFTGKPYLLENDIIKRLELKPVRAKK
WLHLLCCEDFLKKIMVGSQVGYQLAKSQLMLGEGYWGFKQYYDFYWQRMANEKLSNILRF
TDPKFNVSWPPKTAEEANFLETWMTKTATP------------LIQTLLACLDLNQYRSIL
DVGGGDGTIAC-ALAQAYPH---LKITVYNLPESAKIAQKNIDAMGLQKRISVFSGDFIN
D-------------------EQFPAGFDLILFVRVLWDWDNSRKRKLLNMAYHALKRKGH
VAICEGFKELCYDLCLTWEYSYIFADGFDAEVFKTSDEYKIMLQQIGFTPIPIKSISPSE
PVPGTVVLAEK
>gnl|BL_ORD_ID|1440 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116331240|ref|YP_800958.1| hypothetical protein LBJ_1643 [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M-----------------------------------------------------------
------------ASTQTPDLDEITSTKSTGGPWRVVLWDDNEHTYEYVIEMLVE-ICMMT
VEKAFLHAVQVDQEKRTIVFSGEFE-----------------------HAEHVQERI---
----------LTYGADPRMSNSKGSMSATLEK----------------------------
-----------------------------------------------------
>gnl|BL_ORD_ID|1353 @Leptospira_borgpetersenii_serovar_Hardjo_bovis_JB197@ gi|116331153|ref|YP_800871.1| short-chain dehydrogenase [Leptospira borgpetersenii serovar Hardjo-bovis JB197]
M---------------------AKKIVVVGASSGIGKELAILLLEQGHTVTLVARRDK--
-------ELKAIAAPFNSPGKTN-----------AFVIKQDVTNFDQVDSAFQKAVKSMK
G------VDEIYYASGIMYDVKPDEFDVTKDIAMLNTNLLGCVAWLNLAAVLFQKQKSGK
IIGISSIAGDRGRRGNPVYNTSKAGMNTYLEALRNRLSTLGVQVLTVKPGFIDTAMTRGM
KGLFWLISAKEAATIIVKAADSGKECVYVPARWGLVGLIIRLIPSFLFKRLSI
>Synechococcus_7942_ClpS2
------------------------------------------------------------
--MLPSPFRPQTTIASENVKTASKAAQP--KVNSSMSPQPDESVLSILGVPRPCVKKRSR
DDAFVLTVLTCSLQAIAAPATAPGTTTTR-------------------VRQPYPHFRVIV
LDDDVNTFQHVAECLLKYIPGMT----GDRAWDLTNQVHYEGAATVWSGPQEQAELYHEQ
LRREGLTMAPLEAA
>Synechococcus_7942_ClpS2
MLPSPFRPQTTIASENVKTASKAAQPKVNSSMSPQPDESVLSILGVPRPCVKKRSRDDAF
VLTVLTCSLQAIAAPATAPGTTTTRVRQPYPHFRVIVLDDDVNTFQHVAEC---------
----------------------------------------------------------LL
KYIPGMTGDRAWD-------LTNQVHYEG--------------AATVWS---GPQ-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------EQAELY-----------------------------------------
-------------HEQLRREGLTMAPLEAA------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------
>gnl|BL_ORD_ID|1887 @Neisseria_gonorrhoeae_FA_1090@ gi|59802361|ref|YP_209073.1| hypothetical protein NGO2054 [Neisseria gonorrhoeae FA 1090]
M-----------------------------------------------------------
------------------------------------------------------------
-------------RKTFLILTVSAALLSGCAWETYQDGNGKTAVRQKYPAGTPVYYQDGS
YSKNMNYNQYRPE-RRAVLPDQTGNNA-DEEHRQH-------WQKPKFQNR---------
----------
>gnl|BL_ORD_ID|1818 @Neisseria_gonorrhoeae_FA_1090@ gi|59802292|ref|YP_209004.1| hypothetical protein NGO1984 [Neisseria gonorrhoeae FA 1090]
MPSEPPSDGIARHPKSTIKMAKKPNKPFRLTPKLLIRAVLLICITAIGALAVGIVSTFNP
NGDKTLQTEPQHTDSPRETEFWLPNGAVGQDAAQPEHHHAASSEPAQPDGTEESGSGLPS
PAAPKKNRVKPRPSDAARAADSLTGT--GTQAENTLKETPVLPTNAPHPEPRKETPEKQA
QPKETPKEKETPK-ENHTKPDTPKNTP-AKPHKEILDNLF--------------------
----------
>gnl|BL_ORD_ID|42 @Pelodictyon_phaeoclathratiforme_BU_1@ gi|194335225|ref|YP_002017019.1| ATP-dependent Clp protease adaptor protein ClpS [Pelodictyon phaeoclathratiforme BU-1]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MNSSLANRWTASLTTPVTK-----QREQ
GSGPDLLDAY-----------RVVLFNDE-------------------------------
-----------------------------------------------------------E
HTFEEVIEQI--------------------------------------------------
------------------------------------------------------------
------------------------------------------IK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------AVRC----------------SRQKAEKHT--WEVHTRGRSIV-----
------------------------------------------------------------
------------FAGAMLLC----------------------------------------
------------------------------------------------------LRVSSI
LEEIALKTEI--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------QTS
>gnl|BL_ORD_ID|358 @Petrotoga_mobilis_SJ95@ gi|160901850|ref|YP_001567431.1| SsrA-binding protein [Petrotoga mobilis SJ95]
M--------TTLARN------------------------------------KKATHDYEI
I--------ETFEAGISLLGTEVKSSKAGKINFK--------DSFCKIEKGEL-------
------ILYNVHISPYSGASIFNHDPERPRKLLLHKKEIRRLQSKVQQEGLTMIPLEIYT
NNKGLIKVKIALAKGLKKYDKREKIAEKEYERRIRKQQKYENI
>gnl|BL_ORD_ID|986 @Pseudomonas_stutzeri_A1501@ gi|146281384|ref|YP_001171537.1| Co2+ ABC transporter periplasmic protein [Pseudomonas stutzeri A1501]
M--KPVIKWTTLA------------LAVCLPLSAQAHRAWMLPSATVLS-GEEPWITVDA
AVSNDLFYFEHVPMRLKGIGEAAQAPAGGPPGMRRPVPELQIIAPDGSNVSAQNGSIGRY
RSTFDVQLSQKGTYKLAVANNGLFASWKENGQPRRWMGTAESFTKDVPAKAEGLKVSQTS
NRMEVFVTSGAPSTEVLAPTGQGLELKPVTHPNDLFAGEAADFVFLLDGKPAADVEISVI
PGGNRYRDELGEIKAKTDKDGKVSITWPEAGMYWMEAELTTDKGVSKPATERRASYSATL
EVLAP
>gnl|BL_ORD_ID|3613 @Rhodopirellula_baltica_SH_1@ gi|32474280|ref|NP_867274.1| GTP-binding translation elongation factor-like protein [Rhodopirellula baltica SH 1]
M------------GFRL------------------------------------------K
RLSIESCPLSSTASPSQDAGTDTSSNTAVRDEIRNVVIIAHVDHGKT--TLVDCLLRQSG
QYRDAELKGERILD-SNDIEKERGITILSKNIAVHYRGVKINLIDTPGHADFGGEVERVV
QMADGALVLVDA------AEGPMPQTRFVLEKALQAGVKPIVVVNKVDRPDGRPPEALDE
ALELLADLGGEEQLDSAAYVFASAKEGYATDDPAKPTEDMRPLLDLLVDHLPGPTVDT--
-KSDFQMMVTTLDWSEYVGRIAVGRVNAGTIQTGQAVDVHTIDSSGNPIVRKIKASGLYV
FDKLGRVPAESAGAGDLIA-LEGLDDVEIG-DTITAPETGKALPRLK------VDEPTLE
MVFSVN--------SSPLAGREGKYVTTRQIKARLEKELERNVALRVSMIEGTEAYAV--
AGRGVLHLAVLIETMRREGYELSVGKPRVVFKEIDGK---KHEPFETLRVEV-------P
--TEVMGPVMELVGLRRGQLEEMKQRGEYSLLRFIVPSRGL--------------IGLRT
RLLNATRGTAIIHHRFESYRMVEGDVPRRANGVLISMVGGKTMPFALFALQDRAELFVPP
STEVYEGMIVGENARENDMTVNPCREKKLTNMRASGSDENVILKPPRDMSLEAALEYIED
DELVEVTPESIRLRKILLKESDRRRQGRNG
>gnl|BL_ORD_ID|4766 @Rhodopirellula_baltica_SH_1@ gi|32475433|ref|NP_868427.1| peptidase [Rhodopirellula baltica SH 1]
M------------TQRI------------------------------------------E
RLVQ------SIAD--------------------------SDQPMDAILICSEVNVRYL-
----SGFTGDSTWLL---VRPDGKATLLS-------------------------------
----------DRRYETQIAE----------------------------------------
-------------------------ECPALESAIRPPSQT--LVALLAEYLADSSLKTIG
FEADHVQVSTMHQWKEQIESVEWTQT-SGLVETLRSIKDADELATIRRAISIAERSFLSV
TNKLTPRMTELQIAHELEATMRSLGASGVAFDVIAGAEPSGALPHYHPRNIALADCRTLL
IDWGARVDGYCSDLTRTLHKADVRSATADRFEAAYQAVLESQEAAISAIRDGVEAIEVDR
AARQVLQNAGLGDAFK---------------------HGLGH----SFGLEIHEDPRMGP
MSTDVL---------REG-----------------------MVLTVEPGVYFEGEFGIR-
---------------------IEDDILVTADGFE--------------------------
-----------------RLSTLP-----------KGLD---------DCRLVV-------
------------------------------
>gnl|BL_ORD_ID|3127 @Rhodopseudomonas_palustris_CGA009@ RPA3148 DUF174
ML----------------------QPSLSHSAAGQAGDRINRPLAMAG------------
DG-----------GRSGPSTPSTSVITKTKPRTKRPNLYRVLILNDDYTPMEFVVHVLEK
FFQ-MDVEAATKVMLHVHHHGIGECGVFTYEIAETKVTQVMDFARKHQHPLQCVMEKK
>gnl|BL_ORD_ID|1668 @Rhodospirillum_rubrum_ATCC_11170@ gi|83592962|ref|YP_426714.1| hypothetical protein Rru_A1627 [Rhodospirillum rubrum ATCC 11170]
MTT---------------------------------------------------------
-----VKKRIMSLPPLSKALAGVTLVL----GLGILG-ASPALA----LGLDQAR-----
----------SAGQVCEGADGLLKAVTPTP------------------------------
------------------------------------------------------------
-------------------------------------EVKALVDSTNSQRLRLYQEA---
-----------------------------------------------ARKEGVTLLEMQA
VSGVK------------------------------------LRERHGSCR----------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>gnl|BL_ORD_ID|3836 @Roseiflexus_castenholzii_DSM_13941@ gi|156743865|ref|YP_001433994.1| hypothetical protein Rcas_3943 [Roseiflexus castenholzii DSM 13941]
M--KPFDSALKSNVLRSGGATTRYAVIPALLAVGWLAAIAVFGSSDVLVWALSSAGRLAL
PAGAALALWIVPGMALISLLWRDHTLSVIERIGVAWGIGAALPPILLLLADLLDLPWNRL
TTIM-YVVLAVSVWLFAVW--RNTKASERAPQRDPANGRIAQGYIVPLM-----------
-IGLVALALIARLYTTREMLVGSNVDSYHHTLIVQLLVERQGLFQSWEPYAPLATLTYHY
GF----HANAAFVSWLTGIPATRAVVEVGQIMNA-----ATLLTVFALTVRLTGSVIAGV
WAALIVGFYN--TLPAFLTFWG--------RNPFVTSHVILGAVLIV---WIAAIESPRH
NWRLLALAGIVSAGLSLSHY--QTTILAAPMILVSLLTLRLHASPGMMLATLGHAATIG-
------------AVALLLTLPWLLHVSSGYL-----DRNVVHAMRPEAAAGQILAAAV--
----------PALAPLYLKGPVIAAALIGLALAARRRSWHALLPAGWVLAALATAMPHLL
GLPGIGVVQGDVAAMILYLMATPLAGVTLASIGEVLERVAPRLAIIPIATAIILVSAWGV
GWQRDLVPAYMRMVTPADMQAMEWVRANTPPAARFIVNSHPIYGGDMIVGTDAGWWLPFF
AGRQTNVPPMTYGSELSVDPQYALDINALARDLRRRPLTDGRPVVIDLTLPETIDRLRSA
GYTFVYSGAQSIAGPGGIPAPDRIDTARLRTSPHFRLVYDRDGVEIFELVTQ
>gnl|BL_ORD_ID|1115 @Roseiflexus_castenholzii_DSM_13941@ gi|156741144|ref|YP_001431273.1| glycosyl transferase family protein [Roseiflexus castenholzii DSM 13941]
M--QAY------------------------------------------------------
---------------------------------------------LEGLAPVFDI---RL
IDVWPWLPLALFSALLAFWYIQDVIATLRAPHLNPHPDLPDTGPLVTVI---IPARNEAA
RIGACLEGLARQSYRSFEVIVVDDDSSDGTADVVRRFAAR----------LPALTILSSK
GL----PHHWAGKCWACWQGANRARGDWFLFLDADVAPQPELLAALVERATAGRDMITLV
PLIHLTSFAERLVLPPFIGLISMIYPFDRVNDPSSPLAFAIGQCIMVRRDVYAAVDGHR-
-----AVRGSVLEDMDLARLVKQSGYALDAAIAPDLLDVRMYNGWETLTEGLKKNAVAGY
RSGGVRSGLMGMRLGLMAIMPWNMLIAGQALPLIGGDPALAQALMLAGAALLIISALCWG
AVVRYRFRISPLWGTLYGPGTAVYFALAAQALFQIR------------------------
-------------------------------------------------------SGKGV
EWKGRMFP----------------------------------------------------
------------------------------------------------------------
---------------------------------------------------R
>gnl|BL_ORD_ID|999 @Rubrobacter_xylanophilus_DSM_9941@ gi|108803856|ref|YP_643793.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
-------------------------------------------------------VGSLT
RDIRCSAATKTAPAR---------------------------------------------
------------------------------------------------------------
KTRRAPSREPRYRV-------------ILHNDDWTPMDHVVAAL----------------
---------MKVVPRLSLRRAVSIMLEAHTKGQ------AVVTRCHRE--------LAEL
YREGLKAEG-----------LISTIEP---------------------------------
---------------------------------DG
>gnl|BL_ORD_ID|2018 @Rubrobacter_xylanophilus_DSM_9941@ gi|108804875|ref|YP_644812.1| ATP-dependent Clp protease adaptor protein ClpS [Rubrobacter xylanophilus DSM 9941]
M-----------------------------------------------------------
------------------------------------------------------------
-------GAATRPKR---------------------------------------------
------------------------------------------------------------
RSREKSGGLPPYNV-------------VLLDDDDHSYEYVIFML----------------
---------RKLF-GYPVRKGYELAREVDTTGR------AVVATTHLE--------EAEL
KRDQIQSFGPDPLIPRCKGSMRAVVEP---------------------------------
--------------------------------APG
>gnl|BL_ORD_ID|564 Streptococcus_thermophilus_CNRZ1066 gi|55822558|ref|YP_140999.1| DNA topoisomerase IV subunit B [Streptococcus thermophilus CNRZ1066]
MAKKEINVNNYNDDAIQVLEGLDAVRKRPGMYIGSTDGTGLHHLVWEIVDNAVDEALSGF
GDVIAVTLNKDGSVSVSDSGRGMPTGMHAMGKPTVEVIFTVLHAGGKFGQGGYKTSGGLH
GVGSSVVNALSSWLEVEITRDGSVYRQRFENGGHPVTGLEKIGKEPKSKTGTKVTFMPDA
SIFSTTDFKF---NTISERLKESAFLLKNVTMTLTDLRG--------EEEVREEFHYENG
V---------------QDFVSYLNEDKETLTPVIYIDGDQQDFH--LELALQYNDGYS-D
NILSFVNNVRTKDGGTH----------ETGFKSAITKAFNDYARKTGLLKEKDKNLEGSD
YREGLSAVISLLVPEEHLQFEGQTKDKLGSPLARPIVDGIVSEYLTYFLM---------E
NGDLASNLVRKAIKARDAREAARKARDASRNGKKNKKDKGLLSGKLTPAQSKNAKKNELY
LVEGDSAGGSAK------QGRDRKFQAILPLRGKVLNTEKAKMADILKNEEINTMIYTIG
AGVGADFNLDDINYDKIIIMTDADTDGAHIQTLLLTFFYRYMRPLVET-----GHVYIAL
PPLYKMSKGKGKKEVVEYAWTDGELEELRQKFGR------GALLQRYKGLGEMNADQLWE
TTMNPETRTLIRVTIDDLARAERRVSVLMGDKAAPRRQWIEDNVKFTLE-ETTAF
>gnl|BL_ORD_ID|351 Streptococcus_thermophilus_CNRZ1066 gi|55822345|ref|YP_140786.1| late competence protein required for DNA uptake [Streptococcus thermophilus CNRZ1066]
MIPKE--------------------------YYG--------------------------
------------------------------------------------------------
------------------------------------------------------------
RLFTKEQLPV---DYLSEAVKLESMI--KVDKKLRCKRC--------YSRIEEDWQLPNG
QYYCRACIVFGRNQEGKELYYFPSEKSEVDFPVLKWSGKLTPYQ--NEVSEKLLKTYK-N
QKHSLVHAV-TGAGKTEMIYNIVAYVLENKNRVVIASPRVDVCRELFLRMQKD-------
----FTCSISLL--------HADSEPYDGSPLVIATTHQLLKFYHSFDLIIVDEVDAFPF
VGNVMLNHAVKQAKTETGRYIYLTA-----------------TSTLALEEQVRLGAIEKY
HLASRFHGNPLVLPRFFWQGRLQKSLTSEKLPRPLIHQIKKQ-----RKSNFPLLIFFPN
IALGEKFSITLKKYLPTENIAFVSSKSEERSTIVEKFRKKELSILVTTTILERGVTFPQV
DVFVCMAN--------HYLYTSSSLIQIGGRVGRSPERPTGKLYFFHEGLSK--------
----------------SMLQCREEINAM--------------NKKGGFENEVSTM
>gnl|BL_ORD_ID|5165 Streptomyces_avermitilis_MA_4680 gi|29831702|ref|NP_826336.1| ATP-dependent Clp protease adaptor protein ClpS [Streptomyces avermitilis MA-4680]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GRVTAPAPLE--------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------IEKTESAEEVFAV-PEPDV
PW----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------VTIV----------HNDPVNLMS-----
YVTYVFQ-----TYF-GYSKDKATKLMLDVHHKGRAVVSSGTR-----------------
-------EEMERDVQAMHGYG-LWATLQQD-----------------RK
>gnl|BL_ORD_ID|7507 Streptomyces_avermitilis_MA_4680 gi|29834043|ref|NP_828677.1| ABC transporter ATP-binding protein [Streptomyces avermitilis MA-4680]
MRGHS----RMKTPSGHGAAPDGTGAAD-----EAAARTLLR---SAARHSRSRCVALCL
TTAAASG----------------ASLLLPAALGRALDLLLTRPGDAAGTHWVLWCTGLVL
LIALLDACHT----VLAGTTDARATAWLRQRLVGHVLAVGPRAGERFG-----PGELVAR
L------VGN-----AAQAGTAPATAATLLAA-----LAGPVGAVVALGLIDPLL-----
------------AAVFLGGAPVLTLLLRAFARDSSQCVARYQDVQGRIAGALAEAIGGAR
TIAAGGTADKEVARILRPLPELSREGRRMWRVQGRAAAQAVAVA-PLLQL-------GVV
AVGGVLLVHHRLSVGELLAASRYA-VLATGVGVLVGQLSGLIRARAAARRLGEVLTEPAP
VYGTRQLPPGEG-----RLELRSVTV-RRGGRTVLDGVDLVVPAGRTVAV----------
--VGRSGSGKSLLAALAGRLADPDDGHVLLDGV--PLRDLDRTALRRAVGHAFERPALLG
DTIEDTIAFGIP------------------------SPPPDRVRQAAATARADSFVRRLP
DGYATPCAEA--PLSGGECQRLGLARAFAHDSRLLV----------LDDALSSLDTVTER
HITEALL-----RHTPGSSRLIIAHRVSTAARADAVVWLAAGR-----------------
-------VRAVGTH----------AELWRSAAYREVFGSSGTERNGGAG
>gnl|BL_ORD_ID|1307 @Sulfurimonas_denitrificans_DSM_1251@ gi|78777510|ref|YP_393825.1| CRP/FNR family transcriptional regulator [Sulfurimonas denitrificans DSM 1251]
M-----------------------------------------------------------
------------------------RI-----HLKNTLL------FQNVDEDTIKKIESFT
TDHKVSKDNIVFYEGDEPKYLYLLVKGVIKLYKTSSSHKEIVLKYFHENELIGEVANFEN
IPYPATAKAYSDVEFLKVDFEKLKEVIFLNPSLAFNIQTSLIKKIKNLENIISTNLVLDS
KERVAKYIYSHSDDFFETKNIEIAEILGVSPETLSRILKFFKDNGIINIKKKYIDKETLS
NYF
>gnl|BL_ORD_ID|1360 @Syntrophomonas_wolfei_Goettingen@ gi|28211194|ref|NP_782138.1| sensor kinase dpiB [Clostridium tetani E88]
MKEKLRKKITLRIKVTLYVFIILVMVISIIGYLSFKEMRELIEKERSKEALRLAQTLAMT
DEIKRNLNKKDSLALQYYVERVRLKTNVTFIVVIDMEGTRYSHPIEENIGKMIKGGDHIE
VINSGQSYVSESVGTLGLSIRGFAPVYKDGEQIGAVSVGILKGNVNLEVYNKLSKFIPFI
LVGLITGILGAYLLAHSIKNSIYGLEPKEIALLLSLKEAILESVEDGIIAVDKSGNILNY
NKSAENLLGISKRDLGK--SVLNYMPDESILEVLNTKKPLINVENKIN--VG--------
--------TTLMCNYNILE----------------------------------DRDKNFM
GLVIT------------------FED------LTSIKELAEEL-----------------
TG---VKKILWSLRAQNHEFMNKLHTISGLIQIEEYDMVVDYICELAYKRGGISYLINEN
IKIIPLQGLLLAKYNKCEEEKISFIIKESTFLERLPNKMNSEEICSVVGNLVDNSMEAVE
VDGTGKIEIEIRNNDKELFLMVKDNGGGIPKEIEEKIFLKEKSTKLGNRGLGMYIVKNII
EDKFGEIQFTSNKSGTTWFINIPMKGNSMYDKGNDN
>gnl|BL_ORD_ID|2232 @Syntrophomonas_wolfei_Goettingen@ gi|28212066|ref|NP_783010.1| anaerobic sulfite reductase subunit C [Clostridium tetani E88]
MD---------------------------INTKALKKNAFRVTKERGKTAARVRVPGGYL
DAKYLSL-----------------------------------------------------
-------------------LQNIAETYGNGKLHITIRQG-------FEIPGIPMKYIPEV
NKALQPIIEGLEINQENPNKGYSASGTRNV-----------------------SACIGNN
VCPFANYNTAKFAK--KIEKAIFPNDYHVKIALTGCPNDCIKARMQDFGIIGMTEPQYDA
YRCIGCQACVNVCKKKSTGALSFENYKVVRDHSKCIGCGECINKCPTSAWSRSEEKY--F
KLVIMGRTGKKNPRIARDFITWIDEDSIVKIILNTYDYIDEYIDRNAPGGKEHIGYIVDR
TGYQEFKK--WALK----------------------------------------------
-----------------------------------------------------------D
IELSPKAKVE--HN------------------------------I---------------
---------------------------------NWY
>gnl|BL_ORD_ID|1524 @Thermosipho_melanesiensis_BI429@ gi|150021438|ref|YP_001306792.1| deoxyribonuclease V [Thermosipho melanesiensis BI429]
MEY--------KKLHSW--------KLIPEKA----------------------------
--------------IELQKLLSKKLTFKPLSKEINLVAGVDLSFVKDYGLAVIVILDKNM
ELIKVYHHIEKITFPYIPGLLAFREGPIFLKAWKKVNHNV-DVVFFDGHGISHPRSMGIA
SHMGLWIEQPTIGIAKKILFGNYVEPENKKFSF-TYITYKNQKIGIVLRSRENVKPIFIS
PGNLITLDESLELTKQFITKYKLPEPTRLAHKYSQLLKKQFNE-----------------
------------------------------------------------------------
---------------------------------------------------ELQ
>gnl|BL_ORD_ID|477 @Thermosipho_melanesiensis_BI429@ gi|150020391|ref|YP_001305745.1| stage II sporulation E family protein [Thermosipho melanesiensis BI429]
MITCEINYAFKNKGGEWVCGDSINIKRNEEKCVVSVSDGLGSGVKANILSTL--------
--TSTMSTTMVFNNVSIEEVFSSILSTLPTCKVRRISYSTLATCLIDYKKKRCTIFEYEF
PLIFYFKNDDLIPLKKVKKSVSNKYLYV-----SEMDINVGDSIFLMTDGISQA-GMG--
--------------SEKFPFG--FGEENIRFELRNLIKNKVEHVNIVEHMIKLAKKLDKG
TKGDDALIAGLKIREKRILTIMVG-PPEQEEKDKEVVEKLINSKGKKVICGGTTGQIVER
VTGKKIDIDVRSISKISPPVGYMEGIDLVTEGIITLTQVFRYYENQIEEMGVGAKKIIDL
LDWADVINFLVGRAINPAHQNPLFTHDISLKFRLIHDIAKILEEKGKIINIEYF
>gnl|BL_ORD_ID|86 @Thermotoga_maritima_MSB8@ gi|15642862|ref|NP_227903.1| hypothetical protein TM0087 [Thermotoga maritima MSB8]
MKRKPAVAG---------------------------------------------------
-LFYPSRRDELIEQIRMCFLDKR-----IGPGK---LPGPVETKLQNPIGLVSPHAG---
--------YIYSGPVAAWGFLEAVKFGEPSVVVI------IGPNH---TGLGRPVGVWPE
GE--------------------------WETPL--GTVP---VNERA-----VEIVLSNS
RYAEEDFMS------HIREHSIEVQIPFLQFVFGEVSIVPIC----LMDQSPAVAEDLAS
-----ALAKLVAEFPGVLIIASTDLN-------------HYEDQRTTLRKDSYIIEAIEG
MDPSLLYEYLVREDISMCGYGGVATLLNMDFENVRILKHATSGDVSGDTLEVVGYLSAIL
F
>gnl|BL_ORD_ID|416 @Thermotoga_maritima_MSB8@ gi|15643189|ref|NP_228233.1| glycerol dehydrogenase [Thermotoga maritima MSB8]
MITTTIFPGRYVQGAGAINILEEELSRFGERAFVVIDDFVDKNVLGENFFSSFTKVRVNK
QIFGGECSDEEIERLSGLVEEETDVVVGIGGGKTLDTAKAVAYKLKKPVVIVPTIASTDA
PCSALSVIYTPNGEFKRYLFLPR----NPDVVLVDTEIVAKAPARFLVAGMGDALATWFE
AESCKQKYAPNMTGRLGSMTAYALARLCYETLLEYGVLAKRSVEEKSVTPALEKIVEANT
LLSGLGFESGGLAAAHAIHNGLTVLENTHKYLHGEKVAIGVLASLFLTDKPRKMIEEVYS
FCEEVGLPTTLAEI-GLDGVSDEDLMKVAEKACDKNETIHNEPQPVTSKDVFFALKAADR
YGR-------MRKNLT--------------------------------------------
-
>gnl|BL_ORD_ID|1525 @Treponema_denticola_ATCC_35405@ gi|42527045|ref|NP_972143.1| polyprenyl synthetase [Treponema denticola ATCC 35405]
MIYCEKMMELKNRLEHIEKTLDCFLPEKINSSWISQSFGELAYSLPDSFFLNIINPVRDL
VKRGGKRWRPLLCVLSCELAEGDPEKAYPLTPLIE----FCHTASLVHDDIEDKSDTRRG
APAAHIKYGLDTALNSASWLYFEALNPLINYEVSESVRA---VIYSLYSQNLRRLHLGQS
MDIGWHSNSDIIPSVDEYITMISLKTGSLAKLAGELGFIAAGKPINEVLEYGKLMTDMGI
GFQILDDVKNITEGNAGKRRGDDIVEGKKSLPLIFYTEENPEGVEKIKLLFKQAAKEGIE
SPAVEASISAICSSKAVKRAEDYGKKIVEASLIKLQNNYKQNEAKELIFDLFNTILR
>gnl|BL_ORD_ID|195 @Treponema_pallidum_DAL_1@ gi|378974829|ref|YP_005223437.1| rpsC gene product [Treponema pallidum subsp. pallidum DAL-1]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------GQKVSPIGLRLGI---------
------------------------------------------------------------
------------------------------------------------------------
------------------NKVWSSRWYAGPREYAALLHEDLRIRSMIRSFPECKNADIAE
VEIV------------------------------RHPQRVTVVMH---------------
------------------------------------------------------------
--------------TARPGVVIGAKGVNIEKIGAEVQKRLNKKVQIKVKEIKRMELNAYL
VAQNVARQLTARVSFRKCLRQACAGTMKSGAQGVKIRVSGRLGGAEMSRTEEIKEGRTPL
HTLRADIDYGFAEAHTTY------GSIGV----KVWLYSGMMYGNECRKDVGSLLRRSRR
ESGQKSDELVRDERTHAERG
>gnl|BL_ORD_ID|13 @Treponema_pallidum_DAL_1@ gi|378974647|ref|YP_005223255.1| greA gene product [Treponema pallidum subsp. pallidum DAL-1]
MSEHIEHDVREMLNEEKWTRATLTAYSAEKFKELDRIIAEAKRQSILDVLKGICDEHLAH
SKNSIIALYISGIISLSKQLLDDSCLVTLLTIFGDNHKNQIVEHLCTRVLEYGESKLALR
ALGECYKTSGNEQLYDVWERLVRIDYEEAEITRVLADKYEQEGNKEKATEFYKKALYRFI
ARRQNAAIKEVWTKLVALIPDDVEFFYREQKKISEKLGEGRGSVLMQDVYVYYKENEDWT
TCINILKHILEHDEKDVWARKEIIENFRCKYRGHSQLEEYLKISNISQSWRNVFEAINDF
EKHISFDEGSFVFHRTWGVGRIAKVCNDELLIDFAKRRAHTMLLKMAISALQTLGKEHIW
VLKSVLKRQDLAAKIRQDPEWALKVIITSFDNNCNLKKVKQELVPSLLSVGEWTSWSTKA
RKILKESTGFAANPSNIDFYTVRSCPVSLEEKLAVEFKAQKN--FFARIDILNTFMDKAD
TDSDAFREMFDYFNTFLRAFSVVDGNVIAAYLVVTRVSTVL-PHLNACRP----------
-HGFADLYAHIADPRLVYTEIKDKGLKWEFVNS---------------------------
------------V--KNFVSNWS-------DEYVKLFPEVLSLEILRALMEEGYKEKALR
VVEACFEYYADNRAAVIWLFKTVRDEPWFQELRITAEQRIIVLIHIVDITYREIANRRNT
TENRKLNKQALSVLFGNDHLLEHFMLSHDVGTTTRLYTLISDIQGLDPKLKVHLRNKIIE
KYKDFKFFDTEERVVSGRGLVVTAKMLNAKK--KELQDLLDVRIPENSREIGRA------
---------LELGDLRENAEYKAAREEQTRLNNMVTRLQEEIERAQVFDPTTVVAGRVSF
GTVISLKNHTSGEDETYTILGPWESAPER----GIISYMSPLGSNLLNRKTGEQLAFTVG
EHEKVYEIL----SISAAEI
