>gnl|BL_ORD_ID|351 Streptococcus_thermophilus_CNRZ1066 gi|55822345|ref|YP_140786.1| late competence protein required for DNA uptake [Streptococcus thermophilus CNRZ1066]
MIPKE--------------------------YYG--------------------------
------------------------------------------------------------
------------------------------------------------------------
RLFTKEQLPV---DYLSEAVKLESMI--KVDKKLRCKRC--------YSRIEEDWQLPNG
QYYCRACIVFGRNQEGKELYYFPSEKSEVDFPVLKWSGKLTPYQ--NEVSEKLLKTYK-N
QKHSLVHAV-TGAGKTEMIYNIVAYVLENKNRVVIASPRVDVCRELFLRMQKD-------
----FTCSISLL--------HADSEPYDGSPLVIATTHQLLKFYHSFDLIIVDEVDAFPF
VGNVMLNHAVKQAKTETGRYIYLTA-----------------TSTLALEEQVRLGAIEKY
HLASRFHGNPLVLPRFFWQGRLQKSLTSEKLPRPLIHQIKKQ-----RKSNFPLLIFFPN
IALGEKFSITLKKYLPTENIAFVSSKSEERSTIVEKFRKKELSILVTTTILERGVTFPQV
DVFVCMAN--------HYLYTSSSLIQIGGRVGRSPERPTGKLYFFHEGLSK--------
----------------SMLQCREEINAM--------------NKKGGFENEVSTM
