>gnl|BL_ORD_ID|16002 Arabidopsis_thaliana AT1G68660.1|PACid:19653949
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRSILMTLSTSAALGKGGGVLDKPIIE
KTTPGRESEFDLRKSKKIAPPYRVILHNDNFNKR-EYVVQVLMKVIPGMTVDNAVNIMQE
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------HINGLAVVIVCAQADAEQHC--------MQLRGNGLLSSVEPD
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------GGGC
>gnl|BL_ORD_ID|16003 Arabidopsis_thaliana AT1G68660.2|PACid:19653950
METAICGRLALAPSSLFNSKSGDKHLVSKGPCVNRSILMTLSTSAALGKGGGVLDKPIIE
KTTPGRESEFDLRKSKKIAPPYRVILHNDNFNKR-EYVVQVLMK----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------ADAEQHC--------MQLRGNGLLSSVEPD
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------GGGC
>Synechococcus_7942_ClpS1
MAVE------------------------------------------------TIQKP--E
TTT-----------KRKIAPRYRVLLHNDDFNPM-EYVVMVLMQTVPSLTQPQAVDIMME
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------HTNGTGLVITCDIEPAEFYC--------EQLKSHGLEQQH---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|13955 Arabidopsis_thaliana AT1G15790.2|PACid:19651902
MDTT-------------------GDWRTQFPSASRSRIVNKIMETQLKQL--PFIRP--E
GTNE----------LRKIAVRFEEKLFNNASNQT-EYLRQICMKMLNMETKSQNAAGSSS
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----DDNTPPLVPEPSVPNNEPAVNTGDWRTQQPQDS--------RQKNINALLDTLKKI
--VPHSGKEGIDELMRI-------------------AVSLEELIFNSAINQEDYLGKISL
KMRTM-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|13954 Arabidopsis_thaliana AT1G15790.1|PACid:19651901
MDTT-------------------GDWRTQFPSASRSRIVNKIMETQLKQL--PFIRP--E
GTNE----------LRKIAVRFEEKLFNNASNQT-EYLRQICMKMLNMETKSQNAAGSSS
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----DDNTPPLVPEPSVPNNEPAVNTGDWRTQQPQDS--------RQKNINALLDTLKKI
--VPHSGKEGIDELMRI-------------------AVSLEELIFNSAINQEDYLGKISL
KMRTM-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------
>gnl|BL_ORD_ID|19853 Arabidopsis_thaliana AT1G26540.1|PACid:19657800
MELQ-------------------------TMKITKDCVVEVSSEEEGFEG--AWFRAVLE
ENPGNSS-------RRKLRVRYSTLLDMDGSSPLIEHIEQRFIRPVPPE-ENQQKDVVLE
EGLLVDADHKDGWWTGVVVKKMEDDNYLVYFDLPPDIIQFERKQLRTHLIWTGGTWIQPE
IEESNKSMFSPGTMVEVFSAKEAVWSPAMVVKETDVDDKKKFIVKDCNRYLSCNGDEARP
TNIVNSRRVRPIPPPSSVDKYALLESVETFSGLGWHKGQVRKILSENRYTVRLEATQQES
TIRHSDLRPFMVWEDGVWYNDLKQKPIKETPPTILKRKPMRSCSAAKSMTPTSATKHLRS
FLNSKEISETPTKAKFVSATRELGKNKADAVMNDKTHLLITPQETSIAPVITVTPLKQQD
AETEGKKSPKKTPEPVKHQNGLENSSTQHEMPEEENSNEKSRKRKREQNQNSNLNETDET
CNVSKAGVNGTSDTIRVDDVDDQPLSSWINIPTVLSSDQSSNVVDNSAADVEETQAKGAL
TIEPFTKNLPFWKTYEMEKGYKTVPQNPHFSPLLEFKEDIREWSAVGMMVSFYGLLEEVK
KLQLDVSSSKLGSLSTCFAELEKHGFDIATPQSRINKVLSLQVGRAKKVEERKCLEKRIE
AEEIEMQKFEHEMVEVERKMLELKRRAEVAKEKKEAADKMIVEMKSSAETIDQEIANVEL
EFITSVLAPW
