>gnl|BL_ORD_ID|6354 @Physcomitrella_patens@_Pp1s32_331V6.1|PACid:18042888
---------------MAGSLRLFVSIP---------ATARHFGINGVEKAQRVHNRVNGR
YKINAASGPSQGGGVLDRPTIDKP----TP-----GRESEFDLKKKKKMSPPYRVMLHND
NFNKREYVVQVLMKAIPGMTVDIAVNVMNEAHINGLAVVIVCPQEDAEDYCMQLRTNGLL
SSIEPASC--
>gnl|BL_ORD_ID|33457 @Physcomitrella_patens@_Pp1s40_52V6.1|PACid:18069994
MLLGALEKTLSLPAGMAASLRLFITVP---------PVTSHTGIKVVEKVQRVCDKVNGR
YAIRDAAAPGQGGGVMDRPTIDKP----TP-----GRESEFDLKKKKKMSPPYRVMLHND
NFNKREYVVQVLLKAIPGMTVDIAVNVMNEAHINGIAVVIVCPQEDAEDYCMQLRTNGLL
SSIEPDTC--
>gnl|BL_ORD_ID|17725 @Physcomitrella_patens@_Pp1s93_152V6.1|PACid:18054260
---------MAAAMGSAAQVMLLGLQPVGAVSQAAAPVCVRVAVGQQRDTRGTVGGSGGV
FQAR-LGGGGGGAGVLERPKLDQSGSDTTPRTEEGGESGRAAQRNRTGGGERYRVLLLDH
ERHTETYVAKALTKAVPNITAEQARKCFFESRLIGKSVVMVAVKEHAEMHAFSMARYGLR
STIEPDGSVM
