>gnl|BL_ORD_ID|10981 @Prunus_persica@_ppa012720m|PACid:17651436
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------AAICGRVA
LSPNQGFNLAKSGDKH---------------------YFHK-QCSSRS------------
--ILM------------------TASSTRLGK---GGGLLEKPTIEKTTP--SR------
---DSEFD-------LRKSRKMS-------------------------------------
--------------------------P---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----PY------RVMLHNDN---------YNKREYVVQVLMKVIPGMTVDIAVNIMQE--
-----------------------AHH-----NGLAVVI----------------------
-------------------------VCAQVDAED-----------------------HCM
Q----------------------------LRGNGLL------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------SSVEPASDG-C-
------------------------
>gnl|BL_ORD_ID|19291 @Prunus_persica@_ppa012655m|PACid:17659851
ME----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------TAICGRLP
LSPNHVFN-PKPGDRH---------------------PLCKGPCTNLG------------
--IPM------------------AVSATGPGK---GGGLLERPVIEKTTP--AR------
---DSEFD-------LRKSRKTA-------------------------------------
--------------------------P---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----PY------RVILHNDN---------YNKREYVVQVLMKVIPGMSLDNAVNIMQE--
-----------------------AHH-----NGLSIVI----------------------
-------------------------ICAQADAEE-----------------------HCM
Q----------------------------LRHNGLL------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------SSIEPASGGGC-
------------------------
>Synechococcus_7942_ClpS1
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AVET-----------IQKP--ETTT-----------
------------------KRKIA-------------------------------------
--------------------------P---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----RY------RVLLHNDD---------FNPMEYVVMVLMQTVPSLTQPQAVDIMME--
-----------------------AHT-----NGTGLVI----------------------
-------------------------TCDIEPAEF-----------------------YCE
Q----------------------------LKSHGLE------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------QQ--------H-
------------------------
>gnl|BL_ORD_ID|16262 @Prunus_persica@_ppa010524m|PACid:17656792
MH----------------------------------------------------------
------------------------------------------------------------
------------------------------------QMRTLNSAWFPRKQAKQKEMETET
EKGN----PKKTNFVISYFLPFFLSLCVLVFPSTQATTRLAE--MNMALTGGATTTSSFS
LTRIVGFPPPPSPSRSCSRI----------------LGVKEGQERWRG------------
--GNG------------------MAVKARFGSSKGGAGVLERPKFDQSQF--DP------
---ATQLEQGGDIGRLKEKRGIG-------------------------------------
--------------------------SGD-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----SY------RVLLVDDV---------RHTEKLVAKVVPQVVPSVTPDDARGLFLK--
-----------------------SRE-----NGVAVVI----------------------
-------------------------VTVKEHAEF-----------------------YSQ
M----------------------------MIRGGLR------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------STIEPDSNS-L-
------------------------
>gnl|BL_ORD_ID|5038 @Prunus_persica@_ppa000731m|PACid:17645398
MATGSNIDMLSTLDNNLQRPNGNLEDALQSELELILREQRNQHAIHRERDLNIYRSGSAP
PTVEGSLTAVGSLFGNSDFRDVTSRISNNNGVLSEDEIRSHPTYLSYYYSHDNINPRLPP
PLLSREDWRIAQRFQVGGSSFEGVGDWRKKKLVDDGDSLSLFSAQLGLSVQKAENDLMEL
RNGNGSNLPKQT--------------------SSEWLDRGSDGLIGLSTSGLGARRKSFA
DILQEGLDPPASLTRPSSRIAFSDIMDSTGMADARAVGLCNGVESAEGLHNGAASCGLVG
VQSHG------------------TAASHSFASAVGPS--LSRSRTPEQLFGRSP------
---SAGLPPVGSRVFPVEKKNVA-------------------------------------
--------------------------GPDMPKDNSSGMNDLDISANLSGLSLSKGRSVDE
DSRIQSQL----HLDLDKQRDFLFNMPNGHNQRLQQQLIEKSNAESFSLASNYPHLAKQN
GIMTNRNTSDGQANFGRR-----TSASFYSKGSSSGFGTLEGSNVHYQDAN--TPGMEFH
GHSGAYPVNPKLNMTINNHLDAAALPGSGDGHSMNRLGNKVGSGLHSSVMDPSYIQFLQR
ADYATRNVNSPSGYPPSKNHFGTLHGDLEGLQKAYLEALLAQQKQQYELSLLGKSGGFNH
GYYGNPSYGLGMTYPGNQMANSVHPSVGSSSPMFQNEKIERFNSMLRSSMGGSVSSWQSE
IGNDLEGRHASSLLDEFKNNKNKSFELADIVDHVVEFSTDQYGSRFIQQKLETATVEEKM
KIFPETIPHARTLMTDVFGNYVIQKFFEHGTESQRKELSSQLTGHVLPLSLQMYGCRVIQ
KALEVVDVDQQTQMVAELDGSVMKCVRDQNGNHVIQKCIECVPQDQIQFIITSFYGQVVT
LSTHPYGCRVIQRVLEHCDD---------SNTQQIIMDEIMQSVCILAQDQYGNYVIQHV
LEHGKPHERSEIIHKLAGQIVKMSQQ-----KFASNVVEKCLTFGSPEERQFLVNEMLGS
TDENEPLQAMMKDPFGNYVVQKVLETCDDQSLELILSRIKVHLTALKKYTYGKHIVSRVE
K----------------------------LITTGER------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------RIGMSASHS-S-
------------------------
>gnl|BL_ORD_ID|9819 @Prunus_persica@_ppa001201m|PACid:17650263
MANGTDSEEFVVMSKVRTGLKREFAFALKAQAEV--------------------------
-------------------SGSLGRTRGSNSLNENGKRLKKATTNEVQKDAGDEKLTSGD
DILAGGEMVEGDNVKVMEDLDETMSEEDAKSDVVDLISDDEPKTHVDDSVLSERVYEDEL
KNGE-----------------------VEMAVDDEPQTGCIGDSVNEDEAQEEQLKKSGP
EKPLVDEELPEMIESGGDKVEGEVIEKPERRFTRSALKPKAGKVNH--------------
--LPG------------------KSDSQQLNSEMQKSPFVSKSKLEMKMPKMVRKFVKLK
DFLDTGILEGQPVKYLRKVRGAGDTWLMGVITGSSILCHCDSCQGTEVVTPAVFELHAGS
SNKRPPDYIYLENGNTLRDVMTVCQNSPLGILEEAVRLAVGCSSINKCTICLNCKESIHG
EGTRSAVLLCISCMELKKSGEATPAVGANHSDDSPKPVTVPNCPDTALKCSS--SESKSQ
GRVTRKDLRLHKLVFEEDVLPDGTEVAYYSHGEKMLVGYKKGPGISCSCCNDVVSASQFE
AHAG-----------FASRRKPYLFIYTSNGVSLHELALSLSRNRKSST---------KK
NDDLCSMCRDGGDLLCCDNCPRAFHKECLSLPSVPEGTWYCKQCQSMFERE---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------KFVEHNANAVAAGRVAGVDPIEQITNRCIRIVTTFEEKFGGCALCR--
-----------------------GHEFSGSDFGPGTVI----------------------
-------------------------LCDQCEKEF-----------------------HVG
C----------------------------LKDNGIEDLKEIPKGKWFCCPDCHRVHSALQ
KLVVHGGQKLPDSLLNVVRKKHNEK--------------GTEFGANLDIKWRVLNGKTST
DDESLQLLSKALAIFHDRFAPIVDPTSRLDFIKEMLYGGTIQTQEFGGMYCAIITVNQLV
VSAGMFRIYGAEVAELPLVATSADYQGQGYFQTLFSCIERFLAFLNVKSLVVPAADEAES
IWKKRFGLEKLTQNEVPITGKVTK
>gnl|BL_ORD_ID|21128 @Prunus_persica@_ppa019752m|PACid:17661717
MG----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------K
RNGFVVASEKGT---------------------AEETTECCDIGLGLMM---QKTHQSFP
RKKMMMMMPHHHDHHEQTLL-------------------------SSGGSFGGEGCGVFE
HSASGPLFCNTSNPVTSCISDIYNAVGSDFGSLVPKS--LQQPYSDHSLS--FSPSVGGM
VNVNVRLPFTPAQREELERQTMIYRYLMSSAPVP--------------------------
--------------------------PHLLVPIAKNPSNVAHLYPNLVRGSLELGFSSNS
DPEPWRCK----RTDGKKWRCSRDVAP---DQKYCERHAHKSRPRSRKPVESNPNFINNN
TTTTTRMRSPRS------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------NFVKNNNS---------NQPTPFSTNMVSPTVPSHAQPRSMGWFMN--
-----------------------GETPTAPTAGGS-------------------------
---NQEWEQMMQFKLGLKSCYTKCNTDVDVSKQQNESSFNLYRE-------------YTG
ESQGLQTQRPSHDQYGLLLSPKLAHLEGALNSNQTQQTRHFIDAWSTTTERDSSIGEIGN
RGYVSSNQKLPFSSLTLSMSRGNETNEETDNTQMGLGILGSERENVGDLKSQWMNPLSCM
SSPPGGPLAEALCLGIA-------------------------------------------
------------------------------------------------SSTRATSSNGC-
-----------ISGSTSSGDGVYT
