>gnl|BL_ORD_ID|983 @Glycine_max@_01g21500.1|PACid:16244177
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------KSAICGRI-LSPNHVF---KPGDTHSICKGPYS--
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------NLCV
PMVVLATG-PGIGGGVLEKPVIEKVTPGRESEFDLKKSRKSAPPYRVI--------LHND
NFNKRE------------------------------------------------------
------------------------------------------YVVQVLMKV---------
-----------------------------------------IPGMTL--DNAVNIMQEAH
YNGL----------------SVVIICDQADAEDH-CMQLRGN------------------
---------GLLSSIEPANGG-C-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>gnl|BL_ORD_ID|39798 @Glycine_max@_14g17880.1|PACid:16295663
M----------------------------------YEPKNILITGAAGFIASHVTTRLID
SYPSYKIVALDKVDYCSTFKNLQSCA----------------------------------
------------------SSPNFKFIKGDIATADIVNHILIEEEIDTIMHFAAQTHVDNS
FGNSMEFTYNNIYGTHVLL---------------EACRVTNCVKRFIHVSTDEVYGETDL
EA-----------------DIGNHEASQLL------PTNPYSATKAGAEMLVMAYHRSYG
LPI---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------ITSRGNNVYGPNQYPEKLVPKFILLAMKGEKLPIHGD
GSNVRS-------------YLHCEDVAEAFDVILHKGEIGQV------------------
------------------------------YNIGTKKERSVLDVAEDICKL-FKLNPKDV
IEFVQDRPFNDKRYFLDDQKLKQLGWEERTPWEEGLKMTIDWYIKNP--DWWGDVSTALN
PHPR-------------FSAINLSDEAQWSFQYGYSRLARSY------------TEVGRK
NSGLKFLIYGRTGWIGGLLGKLCEEERIDWEYGRGRLEDRKSLMEDMRRVMPTHVLSAAG
VTGRPNVDWCESHKVETIRTNVVGTLTLADVCKE--------------------------
---------------------------------------HGLYMMNFATGCIFEYDKEHP
LGSGIGFKEEDKPNFIGSFYSKTKAMVEDLLKNYDNVCTLRVRMPISSDLSNPRNFITKI
SRYNKVVNIPNSMTVL---------------------DELLPISIEMAKRNLKGIWNFTN
PGVISHNQILELFRDYIDPKFKWENFDLGEQAKVIVAPRSNNEMDASKLKNEFPDLLSIR
DSIIKFVFEPNKKT
