>gnl|BL_ORD_ID|33457 @Physcomitrella_patens@_Pp1s40_52V6.1|PACid:18069994
MLL--GALEKTLSLP------AGMAASLRLFITVPPVTSHTGIKVVEKVQRVCDKVNGR-
---------YAIRDAAAPGQGGGVMDRPTIDKP----TP-----GRESEFDLKKKKKMSP
PY----RVMLHNDNFNKREYVVQV--------------------------LLKAI-PGMT
VDIAVNVMNEAH----INGIAVVIVCPQEDAEDY-CMQ----------------------
---------------------------LRTNGL-LSSIEPDTC-----------------
------------
>gnl|BL_ORD_ID|6354 @Physcomitrella_patens@_Pp1s32_331V6.1|PACid:18042888
-----------------------MAGSLRLFVSIPATARHFGINGVEKAQRVHNRVNGR-
---------YKINAASGPSQGGGVLDRPTIDKP----TP-----GRESEFDLKKKKKMSP
PY----RVMLHNDNFNKREYVVQV--------------------------LMKAI-PGMT
VDIAVNVMNEAH----INGLAVVIVCPQEDAEDY-CMQ----------------------
---------------------------LRTNGL-LSSIEPASC-----------------
------------
>gnl|BL_ORD_ID|17725 @Physcomitrella_patens@_Pp1s93_152V6.1|PACid:18054260
MAAAMGSAAQVMLLGLQPVGAVSQAAAPVCVRVAVGQQRDTRGTVG-----------GSG
GVFQAR--------LGGGGGGAGVLERPKLDQSGSDTTPRTEEGGESGRAAQRNRTGGGE
RY----RVLLLDHERHTETYVAKA--------------------------LTKAV-PNIT
AEQARKCFFESR----LIGKSVVMVAVKEHAEMH-AFS----------------------
---------------------------MARYGL-RSTIEPDGSV----------------
-----------M
