>gnl|BL_ORD_ID|14345 @Panucum_virgatum@_Pavirv00052963m|PACid:23770213
M------------------------------SGSSPGRCSLAAAGLGRLAAGDRS-----
--CIYKGRFQSLAIPMALSAAAPGKGGVLDRPVEKTTPGRQSEFDVKKKRKMTPPYRVIL
HNDNYNRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGN
GLRSSIEPASGGC
>gnl|BL_ORD_ID|29957 @Panucum_virgatum@_Pavirv00058735m|PACid:23785993
----------------------------------------------------DRS-----
--CIYKGRCQSLAIPMALSAAAPGKGGVLDRPVEKTTPGRQSEFDVKKKRKMTPPYRVIL
HNDNHSRREYVVQVLMKVIPGMTVDNAVNIMQEAHVNGLSVVIVCSQSEAEEHCTSLRGN
GLRSSIEPASGGC
