>gnl|BL_ORD_ID|12940 @Thellungiella_halophila@_Thhalv10019264m|PACid:20192486
METAICGRLALAPS-------TLFNSKSGDKHSISKGPC-----LNR-------------
------------------------------------------------------------
GLL---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------MAMSTSA-------------------------------
---------------MGKGGGVLDKPIIEK-----------------------TTPGRES
EFDLRKSKKMAPPYRVILHNDNFNKREYVVQ-VLMKVIPGMTVDNAVNIMQEAHINGLAV
VIVCAQADAEQHCMQLRG--------------------NGL-LSSVEPDGGGC-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>gnl|BL_ORD_ID|24997 @Thellungiella_halophila@_Thhalv10013136m|PACid:20204672
M--------------------------------------------NE-------------
------------------------------------------------------------
SFS---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GTPRSMI-------------------------------
---------------LHRNR--MKRGALRRRARDISVVLVVLVCATVV---IWTWDRTPT
SAFLP----PESHFLKLETEEKV---ERIPT-ALNTFVTKDSYSSATPFVNKEESEENLT
DNRDTEEEGKRVKE----------VTVGEKNQGKTLTTEENRLEPVEREVTVSEPNYRRT
PTSEEKKLEQVKHEVAIGETEA---TKKTHIKETNSNPESKSLATDEERTLPA-------
-------KEDDGSTSTPRNTNQACNYAKGKWVV-----DNHRPLYSGSQCKQWLASMWAC
RLMQRTDFAFERLRWQPKDCS----MEDFEGSKFLRRMRNKTLAFVGDSLGRQQFQS---
-----MMCMITGGKERLDVRDVGPEFGFITPEGRARPGGWAYRFPETNTTVLYHWSSTLC
DIEPLNISDPATEHAMHLDRPPAFLRKYLHKISVLVMNTGHHWNRGKLNGNRWVMHVNG-
------------------------------------------------------------
------------------------------------------------------------
---------VPNTNKKLAALGNAKNFTIHSTVSWVSSQLPLHPGLKAFYRSLSPRHFVGG
EWNTGGSCNNTTPMSIGKEVLQEESSDFSAGHAVKGTGVKLLDITALSHIRDEGHISRFS
ISASRGVQDCLHWCLPGVPDTWNEILLAMM
